# ORNJ Phase 1–3: Real-Data Clinical/Dosimetric Models + Public CT Imaging Workflow

**Authors:** Seher Siddiqui and Arnav Jain · B.Tech AI · NMIMS MPSTME

## Data integrity: real data 

This notebook uses two independent real datasets:
1. **ORN outcomes cohort** — the supplied MD Anderson / Figshare table (1,129 patients, 198 ORN events): clinical covariates, dose-volume histogram (DVH) summaries, event times, survival and ORN grade.
2. **Public head-and-neck CT cohort** — TCIA HNSCC-3DCT-RT, a real longitudinal CT + RTSTRUCT/RTDOSE dataset (31 participants; pre-, mid- and post-treatment CT). The full imaging archive is about 14 GB and may require restricted-access agreement / TCIA Data Retriever. See [TCIA collection page](https://www.cancerimagingarchive.net/collection/hnscc-3dct-rt/) and dataset DOI [10.7937/K9/TCIA.2018.13upr2xf](https://doi.org/10.7937/K9/TCIA.2018.13upr2xf).

## 0. Setup and reproducible data loading

In [1]:
import os, sys, warnings, math, random, gzip, base64, io, glob
import numpy as np, pandas as pd
import plotly.express as px, plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy import stats
from sklearn.model_selection import RepeatedStratifiedKFold, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, HistGradientBoostingClassifier
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import (roc_auc_score, average_precision_score, f1_score, brier_score_loss,
    roc_curve, precision_recall_curve, confusion_matrix, balanced_accuracy_score, precision_score, recall_score)
from sklearn.calibration import calibration_curve
from sklearn.inspection import permutation_importance
warnings.filterwarnings("ignore")
SEED=42
np.random.seed(SEED); random.seed(SEED)
DATA_B64_GZIP='H4sIAD5C3moC/7S9X49l15Hd+U6A36FgwICNuU7v/38e1Wy4bWBGFtyahvtpQEs13URLpEBSGuvbz47fin3OuZm3SGZm6UE3U8WqzHv32Tt2xIq1Vvzjj3/+/V8//Le/v/3Dx29///H726/+5ePtv//l4/df/+EPH3748/d/+eYvX//hxR98+PGbP66/9j9+/eGHH7/+8c8/3H67/v+HH7/78PEvH7/9kf/wD99//fuPH/7Db3/4+pv/ePvHP373b998+y/7b+//+5uvf/dv/+mfP379/Q+333z/8T/9j99++P365+vHf/zfP37/9e9+/Oa7b9eP/vCPP3693tSv/etX//rxj9/9+K/rDf3pr7fffPfDj9/96cP6l3/54enD33/8f7/59psfv/nLx/Unt//6m3/6z7+J7cP/8U8fb7/98x+/+/7DD9/8+PHDv3z/3Z//dPu/vv7299/8rz98/PCX7/7w5/Xe/8Pvfvcfb/9U/+Gvt3+KgVe+T3yf+D7zfeb7wveF7yvfV75vfN/4vvN95/th3/99eKr//vb3cf0vrf/l9T/+f7AX+y7Zd8m+y/Zdtu+KfVfsu2rfVfuu2XfNvuv2Xbfvhn037Ltp302+6/Yy7GXysn7/l1+k9eH/8PFWxy3cYuxPwb+W9fXX6wF+f7M/+W25/Xr9/+8+3K33n1jv/2et7v/97b99+93/9+3tv6+N8eGrr//yzY9/XT8lP5V8iyE8hXCb4WmO24hPo9xa5zU95Xmr5WmkW+lPLd7K+q/zlsdTKLdcn1K85Wjf16ccb/yUZy/2I6q9hn5r8alle43j1sJTzLc6+cfjqTV7Tf1W1y8Ot1qfZrzV8JSK/cqZbrnZG8rZ/lWaTzPc0lqJdkvpqZRbHE99fY5uPyFW+68xPY26PtlTSbf1g+etP9W0XkK6tae63sVTDl9+UY6lXR+tPrW1juvLdWHj7bfJFvar77793Z+//35t99cs8ChPtd3meMrlNtNTCrcxWeRu72E0e2Pr7/R2G/kpxFuf9jn6+tzJ1qBUW96yHsHTaJ9a3l5sSWez19xtYdcTWq/rl9nyRlvSycKG9YPaUyz2o+0XFFuSmp/aek18z6NZyx7XOqyHUu2ph2Frsv5tSbawedpvXI9g/ddY7DF1/tHTXI/zKeVbfurptn7c/PKLoeVduyfeYi5PyXduXV//y3ff/3GtcGfvriWOr9y7Y9jmWEekz9vsT73fZrbFW8scqu3lzAKvtVhLu7ZU5yHY0jZbhfU3M+95LU59vLSRfRLtH6zlnLx2lrZ0W1rt2fVh19LWwg8d7NzOAgdbYFvstROzLe16ymtp1zMtk+Vkt66ljcmWdp2PtbSxs8fXvq723NcurtF28XpE0z7F4OysTf3lF1OL222PlsbalnYubLZF/u1a1fSrFyt7xt3L0n73p3/9+vu/fvu/bU+t57/WdP3qtY7r1I9qb2msN1NtHdcuaI0PGOxNrqPZ10Zlx61DGect5XW67CDW9TGfLHA9W9r1XIa9rsOxXteHbtV+Riu2hOv3Ny1zYNdm26OFXbh+9goH6yesCLR+2/rNudlzXEu4lm0drJzsKdt7Gbe0dvDaqet3dXtHk9CQM0EhWChYP/6prkfw1NaPempr6dcv+/KLWG//5eMfbW2brefaRLbEnMZyjQvx7XGhEaPWxpxre+rtrH24ticbtleiQLFN3bM9gJ7suK3NO+KtDV+e9V/XmVrfR4tqL5d4xcX1e1Z8bZnFzR6J15Fdr4mA0SNhI587vBKVJzs8VdvhmcdQdWzaDh56JMN2+Frotdy2S9cWtIsgWdiJ9rS4UoI9bd77etNjLXDzuLD+0i2tv7LW07+87z5be3NdEn6dree2flHnwa81WxvVNxnvbn2KFSbs/Sc7PWsVS7FIUIjD6xOtUPqJgLuCRuMo2CpySQbixGAtC+F4rYoFYq1osrVc53St5ToLay3Xqq8YsLZlXscl2gYOXKTrgCcO07rP7F4udv2uGJCJAes3DlvObseq8Ta4Ty10rAtiXWfRY0KzG2w978CXMyY0YkL+qX37IDT8n4SF//xf//qnI0SsnTjDw/V530u1W27FUrbherE/K7aLisXoYn9WbBdl+zOekIU5O/LE+/ViByGH/ZLs7yXbfMn+crIfn+xfJPvLyf5ysp/HTvWXlXCFHQDs93BzBf96DbBvja9r8dYDmsU+8jrk6xOszbji3tp6nUvAroJqx3HFtLWFVkyzTRLsYa9rYZ2ltTGSRatqH6q9PPvVLu0VTNuwXbCeuu3FtM9ytU2kpG7dTSvqrDC+/mZRMI32Ay1crl04bT3XfR0J5rYLs91l63UFnLUv1y3mt9K6ebo9rmaPq9gby7Zfsz2BZD9rBbAVWteK+8quTxrtF7DAk5RrZwTDN2m8/bdvf/9nqooPK/v/cG7ZX7hLVyq7lnKlCOszzmqhYUXWdRqLsshkUbYpgMZjB/2yrbrun8hTWkfZLuxkTylw81hqOrhzOp++2kKnYoFhLesKOinaU10Br7HEa7ktfQ220Cv423KvGNZsSdeir4Qjkn2tZ15Y+sbSr0cVOQyTHNJCb1c6U2wHt73OlZxr5ZXBv44Hye0rM69oSc9KZC3DqvY+10Vmr1QOg5R7XWdrS63rbB2vtehruVcgtuy02b5em6+Rrn9ixS2wZs9DGomTlQ58n5tv5saZtsDazqtq6MIqFmQbF9bkdE2qGPs+86+4llbwX9u4cG2tp9Ts5rAtUezeiOQLdsdxPUZ73Lad1tqOvbbDdm1VcLAff39/rR2c/u79cZYHrfqMqmtluWtNrYyotvrrSa/kYO0Sv1YK+zLZXlkbfK24XRyRt/6pLDeQTazoZ9ksC5i48dcj8Dw2kzSTeK1F6+SbmbtyLXghi1hhq3Gfra3hwatYrmpvZdixWGFrFQ3rZyYSy0SMsgAQyXKtMLCfv97uCnbDVt+iylpuv9MqAWNd5FarTaJaun3l8SCHHYxfs+DXnJc7xUJFs1ARlHJpYbql5+t8rg80qHxW7Frn2XZFtacw2UaERN0rDzd0ozRbh2KtbySLGkThQC6wAuNKb1fEXL9q5QhrNdcdf/zCQRprVUGxJ2GRK1kYWf9qhZFVBUceviXc0QLFukY9UpM3rpVVBhEsXETCxTqu9uDXEVylxPqvqiUEMQSHGAJFhYfluAu19NUvisv//PGH6wKvirePYydP+wCT+nPVayt2TC77FUfWB1h3YiJdXX9eSVcLZVDWTu6WaEUOZLFS9Fzl9cjWP+wc3fVqPypYIG7kWlayqJ7r9gxmIjxQDNvez5ZjrD2+gsfa4ytAW1bIXTHAINY+XE9l7foMiLCeTaU6X79rPaFMCBlHmF5Hb9ibtNKX28Wy47JW+rgAC/vZM4t0l1gQmMtnyNLIKFfYaJwYu63JSVfwWMFuFdCREnmdrFEsPqz0ee2ozm5pAD0rUNrGJwNIAhaUcV2WfIWADgizXoP++bCFt+J5eMy3Oq/awlspQsocVcKQFFux0bxstoKZm6Ly6yxBB5PJ4A+Nm3dQJNsucGTHClIKFLtWuGktPqzVzneVXAx+DQYL1Tt2xMTODoTrc2f/bPCw/2bvaW2PSfRYl+sqHdfnLHzC9c7W7g28+5XSFoowC5PBgqKFQ0pQi9IkWbZ2nFm7gy4rzK26Xu0uJFtolFtrVe1GLKR6nIYVstfWq5QjBi4QoFfQyNyRlthFCyOVargQQCo5xnqikc8RCSkEuMFxsCAHbAUGF8lGiCir8FnLu8uN9acccKuW63Urlx2Xwy/JkR9s4dntU37uQoOUItonBPDyy7H3XSeonP5bv3z5xVoeFrCQBffsSdp6aucSVs/S3nyzZdstK+ImbjYd/5UoDk5ZZ4es/KkEQKQGsjKBWAf5qi6XFUaUxb9MIxpxUohGo6pem3L9iMaWcixBiRjVxjrS9suKJWWFY5KHw3GNg73Ch6GexFVLnfn7a+Oux5VIb9bGXUFk5Q72KAsFEaFk2BXTLSnWVbr+xVpjh88ba2tv0L/2F+laeOMSW7I7L3fbOjRrpdf5m4Dfg9W16JAcvKncwmu9K5D2urrtMuceiHbCenywyOs6W++6sbwrTLTi8TQPB28MXiBla0rZol1nBjFOSylWRKhgaIbiZxD9aA/FU43mGU4WEFFt8defWw0TbNktWeOiXIlFJFJMkjXLmtZ2WuucPYeIXGjeplhfrzdb8838P3/JSv/6u+siT2qcvciEy0lysAqOSLXrGSmJQqJUziqzKLBUw1ayIZLLFcvA1u4us7XdV6htBNzANWaY2bQ/10FSMbGW0TJf+hOZ8iaTw2YurUQubBgSQX499rV7A7vXCj+SnCS0h2w3ktjHBmiq2tpztVRV2lm1uZa4XCDfpCixfkK/XGa5vqn0uKxzDOqiHLt57d2VPNhCZztaq6azgoHUy0BtsmNbhsLHEuaqhL5YDGHt+Bv3Cz1I0bTE05Y40XUyELJ4ZWcwRaOOy3azFtLWFTjslWvI+lCBKpzA0ccG0SYL3e1RWWU3uWWzLfRkoSeVtN14yX5yjA6zrxVet59FjaOAJm6AAfPlWZH3jsBsC8kCV8LFWpBJKjBovHRiX6M/ZknQgQ+SXiQlEEAWcderL4MGzZvG71mLuj76el3xsIEcNZbQ+higoZVEpRMWAteAVXIdZJKwk8GTLPGiqrNuHGhnIqWxQAHMsd5GUteCSjHS5wMt6Zwf+0NDpdcae3uo256tChi1X6GgsnH29KvXB4zGXXHWzmsJ1zKvi39SGq1nmQHZbZmL5ZSVD1WoPlY8XAu/Pk63rAzc8GUeYiktCNsEC47AFEWYL0E+U2lYG6NxXHgG9mvobVpS2Kk0CqgZV0AmicxEjczft8jCXWj3b+d4VdszCdgpCsCK3u00aMDOgcW7L7+oXtc16jrr1K71tCfbX3Qy4pvDBQf8DBfrk89mcXYlxeszD+78de3ZhTdpDtDDimCRwhAFi7Oj7cQGO+CXYBEIOPzkxpFu5A6W9IJgDtqUViZkSoZdqxX27+RhDtpE67Fn8oVMq9BWNtPATtRwWt9Jrc36WvigAbZWeXDS7KMm3jn9DNvdba3zzjGspls/1SKyNaYvgbnUo8/5zqIug1E0S8hXwFibaPCBreFDorXutXUxdQ6jlZ/FTty0u5BGF3dcsHPwCTjIaghhaKBLlaquAAWvjZpVT2RCQ99bNBOHCQcZ1D0BJSUQvkTOYTVHoc1DaNCiNtBNu24KeGeyB9VtFxfLLwpnAeCD6rke9ZyVSHfZ3CXLsNP6+vr5ilWEa6oxQFkLWXQkc2Yr2l3AnbiqrQ5doYF2r6yuE6ybcqVq/XHLnGe+vwG77sELSGFhpHtjbpKVZz0LevgR6N5OCknOei6xewd2XRDr75fOM2pASoX2XKIDC7aSCb+ZvDBR7vsNGC1ZiTS1Bemun76W+miCWhC3J1MEVFwgobT7dL8QEvqJXV24mS3bmKw1PWdba6s0HUE2TgqgzUruCvVwAsY5LhqDZexxfGJjTzpzhXS50fEU96QAPASW1MgO0/6kAMDbMgavUgoNqBU9q9gowyLKigRrSRubP5LzrZ9v2KYyz2mbfO3atcjdgEJ75gAgXAeAGmvnrNU+8Xo2th2om87JuITqt/RF7jOOni+h2lYcus0kd7IuP3iDUW9IP6xJSV9qZfxr/6y3uz7m+vgJPkCkqBvPMDgliWSxBqFmUDkle2zy9c9b8670esyNDLgqeEXaYN3WqkAhyACydhsq1NAMWz8zE5UTN5mVGpU1V0+HpoqVK81+l6Gh4HGGt0UQ5fU+FK2zllhF9/PM7peCFvcYp0ptA4WHfbq1lSOlthWmhZYtPd1KNzdbs4YKASi5cQCtbrXmmMXxl/ncBE4bFIHrsDfA0woZx9gm4kzBLbGAQE1eshO3orK6ugkbYPuZ/2rhqpE2Z1vVoEyOSlt9QINKulN+ivINMM2alNs1WiN1HPfgpf9MnXKfM/9Uy+kZcBwD/YgJzayLoDSdSzPByxOMsEY7MfGsgyVAgUvE8KsL6PIiLlQYF+tVF14AflR/XsBzIXQOiuMkZIICo/Pkhmo7OqaWpZHVRahyhkxUP/mR3jNsLD//liCCdFAk0nOlErHfZPfoWsx5uezYqJZCWCV7BxV7EfJ3743AncptLWGMXtcXC65Jb4gOe8lvwNocR2j2cxPNjUhdewA3dt9x7m0RfDmq5Sn2RlhC3pjQukSztm7KCzWPeCVxt8JhDogvYP+3QAYwCkBeZ7+FTzZGf8n5/xn6SbSPtNKD9WYGgMpQL2LYsV7Rd+1dpW+GLkSaodxAazer56CIpnP1E30kFqgRV8VmMa5aoCUqHiWtT+MNVsh9MAxr9o5/o89RBAwJKh6XGmQSbwvJW6dJ2yiQLX/M9iBaOx6EfceFO1e10bzaMIyFaETDzhYgH739tDOGd+/XRu/txINWEjlpDA9az6M4t8pWuzhCaXGQ2yIHh7JGolVgn+BRuA0EbJV3XSQpaBSTwJFp4NXuRUiN3rcI9JYb5Z3hFmpLbIAqEoxXECjAVJn2RQZPybRAkwIHNA0DqyanxECgasmxQVHAQW0Tgw1+N5qbVR2RKPHOBv9QJ3bnCYnK2WAKrgMBFCKvGfTJFa+VGhS5lrRnz+pZ25c5mbp7jTShsSV9O6vbHzZ0rOMBaSoRoBud/EYnvwEpV1rTKi87a64+uFrT2s5BPRdQTfVcBnjm2o9rE9SwW9DB4tMEnVg/XHcZUTd7nDC09FH4/eqNpUaFADYBDC0X65YyrHWdMK/Xekd6/X06WbhTY1jSWixFnWBgEVCxAB422yKwWUI9MjID26AEeMHBGe60PVp3MDmL8QoiVMAtEvfihH45AZMDcUrZcYYxlykyCtnxoDRc2V/mBGZYjEaFoXKeZA0Gv2gbW66y9shaaGcD6paLYgTF+9Zz/dmK7qd3dG2XHf15vkzg5YdBGiZqoyxoVL0NAkWDWujsVvjWDbZqo5Jr8IeOMmXQqha3205HtMTioBfqYUVAvAAXZkDyEtWrQDUIYKgDIKpxmiKxy6q7tjt3FqMNtDHcgtLlbIuGnwc4f5bkGuAGNWEU9EDWJ+pAP+s6XHHPKudkAbpqb4vkCppRSWMtzeSdfeI6FPWyEznK3GtDOG/c+3V6LBFDqEHXnuIGiQ8PGaPomqRzIiywQ4wbEOOM5ay+RwHrJjeG9Eo2DCCkNqm1GdZb+/KLfmQa1qtaO7oqf7N+632EfgPRtRBTJ3nwUAZAIK4UZqV4ozzSVUvV2+WZreStvQQfo9638+82sW1BKImGF+ddr1FJNcrAJp1Cs8ezlq1SMHZo2ZHOhyF6gFCJxUtk4bE7CO+ktr7bXlTlw2KaM1yRFXReoGpbxMgrNPeTrmKkl8SCxvWp+4sULr2yhJsNJQGsxlm88160EOKk73RKXX0DFSlELflXJx+GmwGD1jCvcEqfc99hQyjsNnAj40eA1TT+naF4pGqJrkcgb6hw1QqVeCv7wab9SGkNWD+ftpOhamUDlhm0h95tJGmbaswY1mJP0NmDNa2lzUdtbLiaEONOclLumUD51UncFYmo5GiSZwRyZGrYTr/B+O8FGhDkNkszyOMbEERjOxwPJNO9MEgoK+s/kAjqYcu3IR8Wcu98xSYgrmS+F9FCt2IJfjd2qnQjXUxIFzy2DGZR1fyiB2j7G3HNWmhLUoDXAUsQ8LDzVUoZdr+e0VrmLTxKz/jF8cEOfgUn5YJFVEvDLLRX29SmHwFmHEDDjYre0tZup1Utu8ZW6QbpmIaCBM4eBwjNy8gb86YNgvJWmiHiV64wEGnxJwEP0AMDmVijX9cAHla2nEFUHc6Z9nuta0dR3YRgB1gIBI/C7g59Y8ZJ/dGBmMMW3p4KxIp+Td5S1DYupCLpJUfzrZuYRsDkp06AwkPctU7sQPhi+THLXbnDE9BPo8nWin/iSD+faA3p6o77Y9l1JDPmjBv/MdlBUECuypLpm3XQf49P5MfrXdgNBmnT2ojVIlkh/yiAk/48KPQzyVkis0zg/BFsn+SBT1RFjrVNv/b0WuR+Uc/lShIRgaXKfYIc36DuQjo1WL0BC35w3KwtGi2D6HCMJxxjA9eAYu3wJo+tZXgPpCQxel8yKjoleORYW3XH+rTiYhkV14niOpBHqPaztaXctNwBdnGl3B3kDhPW1+Q5T1STa78KOo7T/uYAjLf1JG3hdrkrp+taWcfRKpmDMUfA3sUSfN59flN4MFTNlImTYoMrxrDKCYYJ+bU3T0mt0KKtYYg3CZl6vZF2wxRF+qHGK6PrarSdlQsP1rTULYhpkHWQClTQHJ1RY8YQP6ySZvdn6KO5eJ/JAN8B30CpBpEmcYMmrhMh55GdE0XjJiMepJhoP/sW0CkGO+nVkIHngpl3NPknNOqzlB6s+VqYCZLTVQzRyWxIByoYUilOb0g01KxBQwey2ZInyWQuQaLDejUNxlaIFVLowHJ7aaDNS6jw5t708tkWnd8ppmumy5HgcReEDQrRlScv8rPdedydYoVGigtTLbEvrJRrQH0GBnz5xQgXDlZR087ltpfd/D9fy8C8bOfEhTaV2BRbhEGkHFQIPThA3pBa6kMF+mCTj2BRWBGEtbY9+ymWW4drZKkaKZnzZFHA1OriggIAMWlT2SWHSi4j1MrkLUcmLszPEGz0zQltXRIKKj681pRcBvYnoQfup3Q8EF3X5920YnLikInGhfQ631EJyzvQihhoL186SBWdaD/5bitUDILKkDZ4eOKVlL5Bfw+kTZ2IaDHVNVj5wCsqZOKZTkaWZWnAZU4Rorfj0BwdDFfkKVmX+Hm47LmULXsurmOoMAaswOSNZYhFYgYk+IqWbJBET/HpCSUhqrewlnsjb4SM6Vw3w2+uVKwjw3grQYhu0DPUQV27YGveFTepWIoUYXAxcvFmThaDBRA3gK1Ymmxh864RvbbI2aMjhkzSDc+1VVQTPSqHSN0RAzb5PlNUZ8H3BPcMCH+IoNbqHWG6Qio1DQMsx0QFGcHHI09EgHFsXsTMvlY7XxQgVVVeUr9ur3U6e6PvY1dMOAmVLVgocjNL4LghlVpie0WoO04pTNLj9fozzRARwg0o5sLrRIu1UQoAYOEoFRKHTMqQ0OwqcYjVO2+6xoJMAcg7iA6ZxqgdQ0p7+SKAcwJtCg+c1lcw3ZK6tm3VIuPMlaN9fqv8ZnsBUbxqZf/dr7/+4VjTD+v/nJndh998/f3X3/In//jNt3/+4eMP/w75QbgI9UCajYQ+bREGnIgBqXggV+oo5TrYe5fYFiG0ljcTBKZ0pJe+dAQFHez2SFSZeasd6Hw2QHtLrisRhvQli5AYzpRQ7hUdaFqEBIszxW9vnQtRaifRvZGOlM0ZmhI4mUgO9G+98fUQ2pHxGadzqO4WynokI+Gggr+xYhmYE0yaTJP276Q7OrkBB8DMQK8o1K4TTzo1hKGIZGZi99gJaIre9RmxZVK113hKFyQIMVHPQCIBv6phJ2ErOTYLkdy4qtiofhDtyoj2970jSy+2UIcXspdM11c+GQkJsfpngNAkoQWkBgbRGIdCmhOFLERfngGf7wvcd62pivwmo3LqiG1sieR7gADdLinYVSb9EvMQS4mIohE8Ph14/l7myOYt00WCbTqcn8XOJX3PkvFTq+SjBQj7ay1kYatOcqIOujQI55PNqxp9Qmru5Nvr5CU4vQl8NVKXR5qtUhRRp63sZ62zJ9dKR4wxdiNBtx7ByYl7naLskbhhXvMRlTSkvZN3PkAdBr0UWyvVaRFGFBdUrs48y+q4xocdVwHN0kqi68+C0/vJ6xzE9kl2sYJVIXAVBDmlbikODSkR6NS4qRQ2CS6GBW/ceDJIcuK2tcKGjLoi+kVlIDpfmUClX34xT5w5uULSChiQpWel4q/e2qSqMDbPIgZii0UJ1L+dvrDEjf7RQNITjfBEWRGFdND1yKK2pOt+NlxDIFs8Q68IyxLtZZLsjHa4ip7BiRlgS4XfOUmvC5RZSdkt+Q5uUdFJsiciyo6IMoEqJenIaFJ1Er0iSSrdV8knDVOaZ44N0pGCl+XhUdIX/obXZcfS5EK5LZTwA4gPyu2gjxLjxpCpgjI90USxJ7pK5KqLFJjpmewMwrzXlrRF7awNApZwULWviNdTfiDs+0AlOZU+UfsEwklEIhCArDvKyYwuOHBHyvnCGM6gDR7HJYUHYo/wuyJ6WSQo64Gky50ZkxO57G66mAmkzSB/c8nDPrwIVzv8ZgCpkrYRjjASkizZASTpbyWWEDullsedFvEQp+fYgetASpMBOFII2eIuVEK2ZYxgLh6sd/RI5eQnVQQQo530W6lOOpoRg/cAaSXuijijRBj+UVLmo2lgW//UURLHvT2b7KJ9oBB+r261EVYimkNIKFXsE6PEK7+NntUGezbuExLazyTfhYo0A+dnssaEP8F6SAa/0N1Gsi5eluEDOhjZXjY6i/kBlQFZPF1YWCZORDKuvWRFtR7uJfZfSzkoSbakuwNA13vV1ZaQsLsu9+O7JSb54odzUfRk28IDJUSCsLQWesCrHWzhHtzuJ9DeHzgKqP5xR4HnoUK8UW7ZSsp3dHI7fJiGSN59n9hgjUKmguJVnkOlW1WTO0tZ4gZPvPBeC/lqUX+BSzBTJCbevbcvMOWyHgHs1ABw0lYJOetFaJkQuNtzF2H6WfAur17vC2wNovOYL0CaOnlXg+M5oGqaAoVVipQYDcgiIzGzm2xs6mHaCtVA1zyF/S85tB2aa4ei2MnyOt2nDt+oC2yEvdPg8zT4Ik6+hXttSivCjQRHnXcQuNElnkiU9xWpRIcDPNkRM59ypAoUmFdBM9sBkRB8KNr1ZYeLty32JTIn4bo7+Rssb6N4HKIpdStqIolKp4RcSzLYYG5NEh3yz82znNzUK9jCwLXU1gksLGDx/uFkkUV8Uj2pAzD4iYnOYadwiix4IcHJYLITiXiAAiKSf6GGjNQ55qCF11aWeA2IR0Rr13mBiE2JAtNYCz0u5bu3CswH61zoWT6T61MLLvEbWNkYaglRNNIbjSKFExVhiHHtFTVlf9YtqsrQgc3mqigQZHmMZDz0EozZCJcH2pLgTcwXKFGATJxGi1I9H0E677viwhbNh+NUOsymCNJhLetmyDTIG5ZURMROBqHtlb2wb99IkaE1McV8AN8xxuigLxC3iQ6KU9t77KshkYhoAxzhApo/AFJfZhcURQ3KjaunFIQlqchORprzZJVGEZDGxXQnn0SjJu/O6v6UBTWX1zXkGJZXyGQPdLrpAnXvAGN7wExAN2Wl9u6DG9AqUXbML1oDrxfz3JnCFTUFGm4XIiMpZIIkN/QfgwbpRI2e2XFC5QsNggIy2ZWVZLld3ns0hMvdh2htouwpUHPETBo8qAxTtMHfs19KjzHjlCHKXCb3yOzNRCsnVQ8GUXccSXGH6m6+jLik0p5DjMVNrfPQki3ylS7TRSM36eJdlvx5IkTlwha0YZGNi6ORAYeNPhJZ5a7XfrnfVrKVdD4AtVlitROH1+4cJIUl7oRWLBzCqgUm1E4NYuGABRPkn5VRr99IvoVNCUqNefO77EqjCBehJ7SDez5tbfNFJxwPCocVh3fqv/C5QvBGOAcQuhL4OL1B5PUqNHBkY3IEsb9McIbHhTzCLRljvg8VhexMDcNEITJgwVUB0rSjGpY2tFETTgsYvtkPt8pf3xmAATGK3SvvrIm1iSHRNUtRsE21wsHkt2R5ZDIdW9xDg2ZRej1rkXDt60t0I77e5bQVZzcPev5dlKLmmVHCSyVxQgPZZhWmQIYJi8rAB7VT8svAW5yjITOdVrZxLEekFqfUzrrZMpI90W2wmJA8vz1BIRxNMwWd1S7kz2YDHXaLCjkrSHYH/xMAakcR/j8A1PozW9l2mDVA78JJoFxDQj7A5tfaGxauZoOJYB5FBH0F2eSA6pmi90sNHwOyqcASHZl+IN8xONp3Z3+wslHt1+pP0f2EovM9MwlVVruFVp91yBBeZAhvB0F5sr6VerDI8wIyVwWOSOCdXdpVzpuQLGPnQ6h030MjRPJm1j6xxR2XZqyus+Bfx+fzdRkqSZ/XGGIkufeIDGXB7o1PATPC0re4xYmC1/lY8sp80fPGdMQuseKWfF38N3m6QDYKKte00Ajos4zCAVqtaB/udVpgm+WDcpTtUWVSA5l7JUDs1B2sC1x6CnVD6qqw7+GCVadZOV0FPTAW+fLCuuw9phhy57734SveP4l0vANJW8hOmvF+LBVKIulIYvpUF4+zXSxrlmVpoCIpIjKR7UUCUqYrW8jXWtumhzLFUK+Ji864j+BPtp6ye2JvZniJGXeHzMnLyeGPnHchN1BObtRHPgKisNJpRONpuskYw9WJPm3rsvSCs/g37RU2OTXe7Xta/XJUHWyhTrNIeHLlM9TgG7LBLsxThqXOuLuTtjXWRYxqGZ00YIdGr7ASrq1IlwiITNhAKurCmlzfqfMwsdwpfTsdSR+BJjhDccukGYnWp8vlwfdOR3sqnsQVP5HURIvg8UCjLZUCV9CXi33GeB9HrGc1047mSt/xHJnJkPsx4mtJcgrS4YSKPKF5TcGNwI1O7WDaeMY+AGVucyfLgPltbAdbRZvhZgSHBUwFmMrd7Tsz7YMMDVQwt7OWaAGk6TpbmRF0aBGR2ybitZwI6Inuejbt6JDLsq1zOiw0+JhVXp/X5A6IQ/3CN63z9ObwDuHG9Ol25gfpbsdTs0dnbRV0NyP49ZWgyrmZLPdsfmBd3ViZ1rYL9tx2fLJapF1SAaVq9UEAcidpoo3OLQJHEJ6xPsikIVkaOjxKMr3cRGPxKFYmtjsBLFzTGRJNFpeZ2mpPgku+eGh0IUUGsrw7i76DjNS4PE2kULZZstEc2qlbd1NwJFofNZER5LGtNrPQYiBoGZXU+5U2KilP5VhduaxHiKM5eregkn4XkrwiN3WMoZ1Pg3+7NdIme1ltWK5vY44dfJqK0cjcO0BOUjCqIhoRjm0Xh9dEgzGWK7dUwy4ealLejMtF6SDORa4WMcwyY7i7/SznAIFJF6PSswgAuXNuIJfuvbTm6V4DdBD0FTgSMNuIuwveHLJQpi2j91K2BhMC2JEJapKJMu2JKUykMVVIShPWAqItZQTxwjiL+FTTfSemq/cRsBCfzyEC5UVecm+9s7KSV5Yud1ZotOUm225Ka4XNQ08+QmUENydzyQ/XWoSVX6RPeVmHy01NcHQjiT7uvo7ewpmqLKy623bHqf+1F1aRoslpQJGClKihopehq4hqjSzEZIzN43JiLzd10ODgJTrgU64DbORtHzXpxg52crrPsd/bQLE1TlcTqYHwr3MHRqz9DEkafnMlnP7FTBF9InBK5QYgbKY9iM0mCJLYGGDJ8GFcukb3gt+lsMo5iPKVPlSBjl4IUoUMrlAQFZC2zCnK3CUZQ5gc3UuqYM5TlG0I26LbN7gDK14ltpepw1O4CLvNFri7PXC973x/Sm38s9bLI7xM6KzAJkPSKJc2nb4hbm3bupUcXC6SiR2drrFlKiKVplMMlCk+gzojSIJCd0GsSXyGPQLpMKWnCNTnEV/MWHcfTC06DB7cEA2HhBzcCFiEXpHk1dQeGMKIZdDl7E7EjdrWtLMNcY4pHi3Ba0LXX+i539wOFBftWOJ2YcusYzpFIWf5Ko3WrIRu7F4p13riJmyb/xXTPbjfmf9zCK5EupthewTH7eQTth12dC/KAvTa5FQEZUDwYWXzyhq0920AEz3hKAQQAQjrpCYVVd2TDCF+2bZzxBSt2DqfjqBUt3NPIYn3spXyDqadpJkvqvN2VI8VrTdH3LqBsMIs5QNal5qlwdOrsheH6pyid17LsdZGsAMJ6dkT6gZ5+mhudYYWdZlkbv/gyW6fmAP2chKpXfQhxADXqQC1MUJByAzJioR4uYXKBCUqCWmbTcOVH8VMj6lcpMZJ+YbhKc9Ngst72ihSy9M4m2RvzkEnYI/urxFbjqJ2ILywMpwAXSjhUvqkfRSqgQbP97gQR3s+0qwLOZ1+DVQux9p95paMFm2eEb6CFQ/5Sif2KBtn225eMkWhSSgnzUbdicBX5mjWG6fZGlO9mtxO1xPOctWypCN6vHJcCTH3cgUiFUoAepZgJk8YOh2NXt0c0lNU+LqecwAuDIkiQ3km1UyesXRsfTpZVeMvN7h8lUy2ooAv1cUVE6mK4Xrb4q/IopKkWQbtsW3zxOHliSfQ6iR07KJELZIbGtDHjHu0STZML7WDg27VVnMgur1M5t5Ya6ftAzGI+UKWsNOONAIHBZpkOplkKuP2YV7D3INyDoZU90DsJvxCthp4HLq5H5W8VNsFpxer9uQZRVevQJhJsv8qOxAnh6TD3HoJHoIbroLwJXLHBIYUBdmQjqPGHyI+44FELpcPEmMpcpvj8ns+rITS75MR+WcUhfUK4VE7S66yAoYGagTYAmZZAE16UL0NAD6zLECBEuTiSUnYTRyZn/naRvEsgO3EuahUKyICNBi/qboWxtWHZbtDtD1SCiFGo0njPrjQByrWX4dZXVf7FeCjtF06AblMWXabd6+9ZyNH2DIfoBFwhjepytNlRFTMB4nrdVff3XyYdtAvwJ9H8XFnGUukIdNmzeTrdtsVAA4ZfNbiojW5HQqqjEkdxEuWMbjzSjpvvp5Oan+QeW7wiTON4Qyt+no3AO04XEPb6Jw0QDtLsiWNJvMzpvTuf8U98TCrhV3CYUZVDw6YheOcLg5zRWQMS9Wv6P/PUcwf7eZrBdgfELtsqAZ8l4lYYpK+DZT1dv1hxjEx4EhKANTiis7dCOKyXWDQBOFz9A3IAe2cK9pOw/eITUSZW3CYvAKXM0cExkvQHItm9NCjkVO54nomECU6NUPjY+aWwhHT4tjzkaIgRVvp0xE0SH4MNl2uaw2F43OIgxp2k5NNO0n+B/LOUdybTt60hRGaSXJVqhK35sGb17CjwrzB9oCrEQ7cufnMEjmPh7qpWRj5F7SEJbuUvJSdkolGgK/Ygc/Vsul7ImSrsZUBtiKMT9RcUVIQskWNlLNCkv4BRKOYN3JkScV0h0pNs0nPGgD5Fbfgo8FdRMEJRWvC7JsCs+hHD/KBzhJ43gGBK20WwBR91TKmkGWp97Lm7nA/uhD+eNpviIA30D1HlFkpbKpG8ebslK0B5eAgBWmX/lbgyWtISUINJ2w/UW0biwC/CrErGblAfwje8/rEttIneKTRqRqOaF9/WgH+Ov+C7BLkoUldedcT0fnjWfA+9VpKbnSt2QUVGKdAGk/Zp2Y8MpHJ3Gnz4vJVpKuHAdro2iYRi+Y5JnH91Epn28ep4lfr9LhhkaXIjBH1jBzeIwwRChmZVupdlH54APZjUqCxYvJ1CGXX8JKarnGD8V7vGV4yKEZB3YKmzPJu4ArE9DoCzGV4idvq2zoSLjVtL9vuEdsKhnTZI8zwb2RmC7yLkh74FcWDgZE2Ow5kEPYyNlfnYEWNUyQg9Ov8FzkEj3QHJb+P4jnl0PbimtPEX2q6ihrQa9u2lSK7QSTpaWvuPh3BiGN2Kn45qo/A3u+SCWILIysYVSKTu9C9IdJu+m0XZp+bTGiOcmWbO1SAUmd0dbk4bhHRz6kLGRUS6A5L9iC5p6YBCgJPJMjjUn8cbnRUzi+wzr97u+11uSodJuj9jBu9R/vek8/JEgJXBI+r6G9uHKpBkvZQnrnm9+AZhZCHgcpHDhstbEsCefmNPRwZ/k1FMS7Bg5ojkwaYdD+BtvZsJ5Wgw+UopOkt+ltMvPUoi0168hFSYMTYijGrttLz6g7splJWYJ/5xC6kv3qr98YVHDpqvgQOF5jPU/C/LuTJnb3ZBMfLiR3UMYK3aMibycyUf15KEanoNRFNasxIUjyRWA262hoYXoAqAl3WrpGG2E8V6dnQXnYeSsAJJPdThSJJhUaWGu8gbN1a33tCJhzSI4v3ZQS1tdR7/FHK98O57qxY3zeAPWom3pw+hz2w1E3yV5hJmWU391B5dJOmDjKoLqMvt23pnxwTPtIe/LAFgiNvkyjYQgcaNMKJCSmSyIMup9OqdcqoAGQoc9MWUNLMsxc+lHCli8F9fBIONRHcQ01VGmCVIRCxxGPOhsQUN5iUZg53EEDrMQbi1eDQkAYtMZOAVt8EhVNi3KU1GH5jJyTTSQFds2xJXwn04X4L7xkb6qRO/B5CcQOZBheoIqdwR4ftuDHgwBS0lRZy4RF5J5Uuf0ZcfnSfugzcwC9K35xfuUHIexh5g6ZmoYSTMx38o3KasFrM3rPCZz9Z4kasepMPq8hbE/BnVk+GJzvVqEeaco0h1uBKGiz9AKjtaMUkDS5VuqOHCZqUCG2r+Q6lq08GB+iM7bRUHBcWuDwAJf4M2uZAFQXDVnWsNEU0Ethlm5d5MpWrr/bjzkhYQBs2aCm1r66TAvIQKWBovsZ6YHeoZnn7/JIBMKD2/2CXDWBwAyuQUioIy8U5AOJUitlGBzRQDxSaQZUrvcCJ6s9i8XWQnxx/SnVYqNPEaLClG2z6Bt27QTSo0wfZNjSWEZC4YCzVkOgkLL06FWA7JvYkjMjkmT2P7I4z1o6h0RBcikPHnXtuuuMfz6e8hI7fFoVn9LmqBpnxZicXgY+IgRg6QGsGCcfQZAHRRjmsHWix5Aej0Q67yrkHG2VHduS22tOeJ0wufDippuJ+znqYjdykTp9+UDVVOJymSdrOkXitcrwySW3S4rX4Lgp+RTxoNk1IFU0/GUu7NEGKlKrl3sKkhbcMiLnrggATTLwZhhRC1T2QDBnTjJK+jzFVlXR1XcNxSOUyOL1himrr1fCSGDecJ12RMvW6EczoY48SarLBnZbi6YdWsDiZsm8o7jrgJbRmD4KC+1gHiEimLEtOgGOGDb0UD8CJsbuWamZDN/c8qXo/Tyq92w974jYxuTsmkW5wiQ8USoMre1A+DEoOTaTrKk7IvYoUUu3BsPbdXqr9YgdMWTz7bi9RPXpjaYDaye21+Yi0kt3huILeV0x/atlzbcnlajiNHzKJQ5GdA3xPwywsqO9JBOXQuVoGUcOlY3qK+a7cLIFs7wjEHUhmos718X5cBxNqyWQZhwxvuYQHaegg7A7qtYFiplfX3CTRqtI9auwza9PWRG77o3wxx+7zDNOJ7w3eI3J6BTN9Yo8IkAX6RgYNnc3nALkJFYSWAuMgTdeh9ODkrM5BoppcQckWemcT0jsUbzOVO1bnSTd845XXLlW1l9PowyaHcCa3dmjcWS6DgFHc4h5XOd1CoVfnjgy3lTo70+0gMEPF7NDUNPOvTR9/kIcjQpY00BcdUv12zxcLXLLC2mc64ZnGS2YeZia+HETaDKUoU/UN6r1wiBOhyMjeFA2QLXa+8C1idj5zvp/FnN7JIBpQPByb5wNPKieDMtVdEjUC7X9DpD7ADzU1srXtAye/ZKhuXurFctc9BX3vyftNWuV5zCNGuVTpm1YI5YXJnnKIK7CgfdgOozJzcwC7aaDZZbSlm9URm+sxfQl0DwYUTo0sd1WGcY6S0hRmn0MX1UXOz/1Y3wxnUt9O+PMTksikEBsAwgNayyBKjuxzQzNew63ukcpktBVRdO7eeDfERY5ZUgNnBDOqDpM2Osuu3K6TIfa+W9dwrFrbDH4ZmlAuzrFN2gl8x1UpN7Bc9yVJUMug0xGJEIor0gzocCJeiBS+5+8URKtV89tneTCwIL/d2iiFi7iHkqQjYU0UI4nIXJAiN7pvqW2pKEBsIjWVjY2PE471pWC1u5Nr6NvqeU/giBhvBVrYkwkcEdeAQSHYuebiOKlxynGinAzqdr6FD+r0RPX0iBYp+NCeirOwmewEPLqQ0VmWUec1alQVfDEJFHlO1Prq7VDcI/qQWUh17z7F6NeetL2yUi19j0XVdCJJfOwkor6N8zoXAuC9Cy5gLPGx6F0VYNjtOpQSFcmpT5kSFA+rqsBULnQWfQoElVIWDFi2h+g4Z6SJtz6BIdJ0GkPsF2FrUeho4UCYLXBosde/v5hk1Pey4sx8Yyh1I1pW7qTK8XR7GyVWXIRVjuzR57kXeMIyvM800LwEpF9/VwImetyTMNHSyQxImKMN7AKyRqTJPZeo3XF4lG900W9te2aMljM4YwWetyUk8mqmM2C9MQI5gAdPgn8jbaaWON71mnxs5bPple2ddsONPuMcProyB8+dNQZDdlwZ56yEs6f6ZAc9R46QAeEpg/OIx6k9K03kWklKVvHx6/D75AsahrssFJDtDEqRg1M1NUFOBMeCT84sLrD1Kbs8lsiI7QOa7+zXGjf0FuXvxyUYj/Fj3cLGHicjAD85QyuVB/Y5b74BY+yaqaV4AfV0Mhldqku5T1ToklUDlCFspeBnjmHeFq9lpECXpJT7VZ5Ei5y3jqT4zdmKt+nK3PYlCrnZdWmF+zYDhWYUIZn+7DHCQJNXG2RCjSKTAmpg0VOka2APFHhE9maZLWymHszciM0vwKQhMm4JFcfdjOz4bnZnLxfm/WDkLXKnGV0NOOv2LofhM2Q+oBjQ3YVF91idPnpLXsRZ4mzJAcdFFDhghYbmdLyenGM0qEzGOB9NxwWww9PI9fQCHAL02kaj5WGON+Khkx1wO1vxUeWavBKleQbPHiq/kxUrxxAZCPghssjlroVq/c43NKUe9VI5zXM6kFS1tORWck5JdCMGvIeGoi5JuEvLJ3Yf8dTktz7SA0qAGFkJbtBI2/ATkK/CxqyIoBx/J/HLcLpydW24ZpKGfGpGpBtu9GoyVAvpxxNjAuU7XVWZMPadrR1xeLUserLatrV7uHoOJ7crT/cOXPVgIb6Sgw+deuJ+LRTUUUkgmkN7V0mWBi22GbYFO6hzJC2duns0NOIZlyiTZleNqhEvK7oVjnEK2gYveIiF7LEgOnGxMEJJ/8Xq7VUP1QNVywhOrIjYN0Sge+C8IctsZnMYh1m6fXhcNk4m7nkyIndKqeOD1C7Ss/hOr8qBEMnRfAY8dd3XlFqVKaAFzUsezjAclFfy/mEwGX2+cNj3Pu+UzMOrdmvONEB47INepk9KGcPl4Bk8ySeCbg/npNEUalG3rcEOvtC9n35xouZpjLD5LMEAg9AvFN8KR3Wwu0MbztNyTbz9ms9HF9CswtPnjJI70uAr2EKpYaLobINvChzb4JzBQREeWaDQtuNFfNFYHfUcbSsXVhk/FTrcmWHlWYl5vNjtjD0NLHpnULNTGtzwibNljheoTj5ceftwETNkwB9xCIvZvTgmTZTGXB+WuhykOArBItpQTJ9AnN8qpxS959LHTigaNNin70nCwSutTBmbYVKmsr04k/vAx+zzXOhIPeiddLlqDTe2bKiwG6KURliu0LgrJ6tg+ZLp5GWodpkwkYNXIGls/RMXQkKjLRg/IQzyMRIbBcjptARVk3VkKeRtvetlgp3trxvb7CJEgz5AYP7VG1soHR97p8EBlh1Shph8GONKMGxrsyEGdIlOPtzh87XpVPj6yYlfOXoT4SBxylm/pBOPrnOPnqOEr9NdzKIo+vKwFEKtsY10r1TGhLiHrOEPXdK+GJN0DT7utZZ7npJ1UPqmaxk/3Ed+1ceb+W1kLfmGvJ6O9XMvdAL1Uo+XsE3HMEdjBJu4VX0b4+L39/yFa5WJYmNfsM9f2qMXWz/natm2pRy4Qb29Mr/DeLedmQzOyRqP2ZUOweEvHoi5tj3p1B2t6tx95EzVBYiE/6EwNV9GPmS3ER/ZB2Ef8wCbzBqKF36N1mdFE1RRsFSYzBUfCOOZqxsG52JAeilq0GUqfNLJIYF90A3sY73MTVUji6ORh/bgnjzuMon08op789Qp2c6ecpxMPtyCN037ng5e6bi34Rlbkr+BbMXhCJKIuBdzeIbATekUlKXl3eUTH0Wztrj0fWBB9sExXdbWfY8eJGfOmLmKCp23QYTbjlB0DxXd0gqR8Mjut8tnCroQKhdrwkiQeo470QC1s5y+v+DaW6ZCXI2vodE8g+EA4sd0IzmRrAZrJCf3pqEOjXKk7p4mYG5EwzRU46V4wPdlbjIuuuEOFNnRpTTCUgNPaMWHriWBQuFkBAx6jHlst/HovOTCAIvAoDWZuDd5YGykIzKeOzK0LhZPn2WArdJvGnqxB54Ihxu+3ONOOZIvevY35m9CLGBCTADVrtl71cnBdfhws0LCkBETZQ66BIhRVGP3cCvPxzprfHyb20Sx7oF+anPRyKrs5srd41OcoWO4pFv+5pAvcnEBVKV612SQIrsLetZFg28xF5G8Wm7bpoVR54/5CXZPCr7Yk07cS24467tfl7m+fwpEhiF/Z+cO/VsNmQkkOfDGHaoC1ZaTbTpPJMpwR+5uqXyylrZsd2tuDjP9ikraCp5wjz/AA3HTHDhxTuniaBSakCW6DcnEVqpK+3Q4ONDHTRD8In1C77aqU0U1ibmRrXW5SCaTC/raHVCU34ksTzm2nj7tw63DJ5DXYCbtIPXsYDJNwgNNqELZlbp7/Nm4VxEe0rP0WAa0dZzDkkQnkr1Lja5OrWObihM2etoulBKUcDGUumcJRWdPl+CuaYVdb0zzgpmUfJRE7ewOHwpkmXLGoMeNbdQxYIZipMtDZzskXvVQ78I+AyweDbE755nAo231rPTGVqg35mxU2oVFE8KHa/g5n9CkwrjHMGI5MYxO6T4JT5Pg3Oj9j7TTZ/KQOp2wIWJGLFvrRKumSM8Le1kzsQ5vgYC5gTgwKBdBROCaUaYIXLbYIxRjj5CRtK/K0+/Ocbm8dRpjFC578T/LsLnGtmjg887oY0YLQkorRTSZBKlRye5UGD8xER6DrGP+tUB7px/K5nbsWZebTSte1iByj7BNcItT5TK0lyjnLyjMFW5BwnTHpkfsta8A4RVErqAkkYFtADoyOZQNsYujXxC4FMLT/joeGKC9Dn+LgSRg8i5mdq6LlXrBzZ8kA8vkqeqldkyY43BblKrhJW1+ashAknYn7yEDh5b0GIk2XPOoyKvR7lIxtLjhe41KA+LJXAhHTienHMH3vXhZFzVQj/fc5VOLWqUfJqvI+I6xPJpeJxMX+/pi975nLA8YxKSFM5Fwapf25g4JoThC43bA0edlNEVgZu/ZW0YQQwvqzmmrdU+9VRxXiuNQt1Eids1OGR2wLsgQCplD4UYokOctDsVzMEzhXitlj8ngiSXNtKT1G9ueTB42P7kyMwGPAAPghm3fGa5M5eG9kTEeGoy8zciMJoNZqorCxZTLqMuN7vKsPokv00FKZLW+UYosVQ22gSBwr6w+XMzSqYlUuPBQAHwWomeGpXqyIMmIZllOCkv58iQMAgJzLdMx9hY91eE42TAW7pQkESci+a9XShI6T5kpjMbIKdZLnfFiq1pFJIrS7t2pdD6DEbANcB1SjEBuKeGsrDM24hqtLYqLM9SKO1jU4vdNU3lqduqCCp7fd6CYlaWv8VT+Tpxtx1FxBwea50XZUMsmfkvhm1wjNZGQaBJn5L7rYTO5BDFXGbwnSKiGIltDRfLIDNfFQsbMFzVq9ATOvsaXCsk3F9szXkcMtG1lFkA3Gk2pZPHDO/YyhISGEaqXXwkmQKyaqT3jC9dlevkN1XlrTsCo0YcSyDW8BYfXgiQPtFpF60yoQiTLSe2cj9E0egeOXEeKGsKesz1c5tAQAGtCrrqp6bYr1AmPy9a5XAY5eMVnd/IF3Pxce1rUzbK1s1lDfmmjdXgAlbKq7zRC9udYY6F6L6qpZ/+UUEdX4KTx2tqes4PNZcGiIGs2ZdkUDjkVNqWDTSTvgGNC2R2kGjcWZJQ4cAwpK8cxJsbUZW4cHvYshGGZ8ax3fgxFpIuS7mG58KaxrY8gTvjFk40lR1tJylzvrGipsaGQu2UtLmH5p4j3lwkOSCdrcuTJcF9RvjXEpbhqWqVNYWOO6DMDMlLLhFOB9b369ukUCqHJoLvASJoykZz0gkBChbp463luD/zGTAgic7u4S8bhDZFeqUWeRYs3yvo0Gtw1ZhScTgHgAI6w7Qnn5mEHH1UW2XGBIGEjLnVn45N6P5Jrz/mTf0i74HKl7cnkzICoOOMUMKoCoabQVinBZ2lP4XJsePVlYjs9zLrmq5LPWXMkure8MRHEv7G+DvesoNBKfnEnUY2u5ovz6sTc6jtzuHY3jYvm2eQ60tDniSh3wq4cQAJdw53QTSntEt3POSagL+WZSlUeWlLBc3o71e6BG1WZYgf3gKry6dIgCcTZFXtTnwDPuO/CkLQiNjhqiZKc3lnqRjJIWrJM8uFZbqoLw/4q8CdX3x6uqCsvPu2vz3Dm9zhe43yYLn45ET+RToNL0j4bODR90riVuORxDhJoQAFgR0RhF2EJ9BcrPeJpAqxxrLX45CgnJYJW1elZhbierrOOu5Utz22YpJmVsgrlML7WFEswpkQV6GMVh6MUzGOtY7vmw7kw5CLt8SRYTFqMuoX95ZzJ+r4NHWMRf+9A42DjD8pA8fDDRoHt0pccepOyXasofT8Zk2wQmsMXF4a4cA/c4nLdXWxsIt16UnJf1Spy2WLkvDEO87a7oHeSsc3IMiFmp+foBq4yqJUPX2dSQeCoJZgv4rxoyHMi5dfGCNnW2iFmKEN5uI7SILB3z+c6o0e/V7h3RqDNbX04iifK8kEe8ZzIPOR33DcBRd7LutWLRlakc7FbO0dxVaj5kTZBgbIlkqfMcwZgR0w7raMVU7CKKyhwMuljFul7D4YZhOncTpPJyvyGwSiu0LeZmcRTIsgEnJjtRrbFzoeTu/VaikjMRaYeL0dAvLEcjJfVPkP2il6TDz7BLkd1DkUObqHuJuma26lEjzsvFnnT9Hkv6Uma6yzxQz5NuApNrI5uuB+wUfEbOBCUQ99WDaQMhRZUxvnNR69176FUzTciQDfeniYVREgM4i+X5O4cXiVqWnwKV+OcWJ36Uutd5R3eNaZyRE8+Oq2TIR12cVfJrhMOlbI2nz3UOLcpb5IDVswaJKLoEZ/X3n1LduRrHZ1NWg5YOTmHSSVeD672LYSfsrm+bZydqU4G6AMZxQ2HdWT8jOQXoVhQcefi8moFnNbE88mOPmfFAC9X71HV8pxg9B4DVbwuL7EaGLQxbCNi3JCPceVx78jmGumC7CrLeJBdHIEtm6xWtgiiU1d3IIqDZaTsb2qA9kG9hYHeGDhXQbXcQwC8tQJRFS4295KEa1eyD+yKoHkyaVYOWAE/RGoe9E4mr0Fzk+DUKVaPY7rzvd3ky1EQd7X3azY0Z3CigBqwvmUm5vYqwBi5OVSuuRYBiV2YPiBK2h0KgyTl8wuzLbZ1A8evUJmjnD5ZT/kODYqZAmanPLpriMZx+SZHjgfevgEqpKJVldpP3iKARiYRhbhL9Q6QiyZFHH3e6WA334lM9qgNi+c/idW9jsScHA7t8sTQ0OwEtAGbIDEAPg+/p/x0UzHm6n7LWYYT5blSeLuIS8fuXiPF83C3UaUFXmkeHdoSDe3JtNATE7Q17yG07S6OgcRh96mpc6qj9PzNSouKK0HckxHYcIzAasSm0n2t8jHPJGuoQ9CXfG0B1i22fLPZCztwDhenJZING3sgD6xBpSAZf3Vv6ajbj/5aZm+F4b4eVZL+/Gz6XIEcV8KpSY30pbJULHHjcclH9o3NKhS2n+kIZHrhGV3sMTU7YhgXkzuG+Ow1keOoOCNm8BHDKOEpllXDKzEqmS1zvvLEnfEZLbpcyAPxM80Otk7KCH8DHhd2fY2NPvZwXySvULgKQ8DGYTNWD68xe1L5GBFG8/bC8ioPuF2HJA6cUC8Mp2fPlsvAuW3YoK/5J63hXjf4RQSu2lyu4NazEu9r6ibtN8fL0IElXE9ScrVOcjZwFNHt+WCpUE9BZIUZO5EDDTG0SCmqHNnoSSW4FyFvYFCBHppTHO5G3ofb7Ee07PIMjVFJg4kmuCMlhcooc+KhdTfErliyFp+pVU0z7l+vqFx5pwi7D1UNn3ubonfPp21b2dtPtm3t2HT5buedZvm8aCOeTMPxKZJhvX8pvNgqtsvoPno8Mk6+qhVO3+/XceofnPqCVmh2z8X6wZGlJurDVWEBLUPkGo/I6CJMd1lpBXSS8VMGyp2eRzyuLxpEjahb0UzX5sMxotx5kUI1NKhF4C7MlURREbi+oqZ9Fp8rmNimiUQxFdeLSMRp9hCaPGo3BSFadiOGCKX1rjbje2pOUZGd4f2WfVv3f0A6mNxXAybIwPRz0A0a9Isd5CxecwSSthTdT0+BI/ZPMWwPurH8Y+UIN6dPcGlwUNydVyQwkhbvY29PlkzMaKQRTTwuKsqgwoSMWNMWE+VJ7E6NHIoIaWzEWAaKhtwbUyjFcYfS240uw7Jx7YLE9w70a0Avk1R0Epsme1I6py6qiVpyyalTcgCqtIklXq5cxWjvc5ID5EmjPaQL7gNHcy+AQ5RDWk07rmLzX5lxXZm9V4MPqdREs8pAjCzCJ3YBTaEZqmyngxAgKIjhXUmLsWQ1vg01oGQ4otGyzvNune392Ca+CxntZ1tNP72Xk0CyhwPaqUkncKBQ4wOrqZRcIzslpTLDqlD5RaQbUVnABamv8gqZJ5tWrKFKf2/2PQQcaKLBj2hgHQ3JmqqQQ4GsEcUJZE44slLhGLaNGcNrE4PlHHUD8U+cIOclyua3MzIgHUNdGADl7dP2cJjfK7VkHW4gaIukkJ2ap3Z3yxLJKQ3ftZoIlCBrJXp0sWm8eSifFCr0rWhMrtGbxIwCzJNkikMfRJ5D4h8leIJq9GeJz+luTB0dja4epzovUdGl6MhTTDLdVnfaHhv1Nw0XODPrMdnCOgkgkz5Y8n47Joh+phFbffrs2tr2pSc7w61zKkTqJOUpDJfUt1QSN6ZCvp5pQSX4gdFHAl8m5hRwCJ8lld2m5HBFlW1AED037yHiO4gIQk3FNZMVkLPQXCyAZkXlL3G3sD+9X118oIBqC2VwxisDwhLjIrKB83XmRZcf9bqeLt5wb0ww7uB5IsG9xTqfdyYPFwEeUZpbikPXp1fvEsW+h5zBMUyAt0OWwPE0y5kyy2GR+9W3k5JOavYgu1SEqRpTpwXXhShRQ6aWrkx2qCx7x408Qjic05VRBVmEV/HVx7X06cPtYvKGn7ZFYrXvGqgUcUDU+eIiWd9XdsSAY4WPyZHeSbQ44vCg5u9iwsMOr9FHf+i+Ed26Jwk8f9JmK8StDwnuzznjFithwFOxfKzw6QokwCJOGGCl2Z5ioVU1HkNWk4KJJTirpxpYSJGM4HNzDUmMPqMbN8lE0WyrvB2VkTUYSg1lFrDjbnBweMPYuN6vyhFS08mOmaSgg7u6Y79Y9y5JYQ9Zij7ChToKMoNyi2fKkXxsVThGDvhE9zwtbTNX2IClu74xAw/PcfZDE32mokuC1EJaCkn58txQT9tGkuWE4QcW60VNx+QKTsMuDY1I86DBCdqgz2Q020vYeCfvm86Na9U3vlYlDezQhYpT5Cv908NMPWtU36FHlAcbVcoUYLC1kZ3pFT373PJMyOjVNZdtOjt5sOej3GXheWo/57Bn6CAcLNHjb4yb300fNkHUcCoG/N0UvSppXNPz2M9J2GZPzpZNORx0ALtYuzf0LPH7KYj4dfSsfpkF7F7VaGcGl33r3jrOzfHEXL20moxjixo1U4RZhUcjsKnCjpwsymGczEyuAM7Xl8Uf4Mhsp2tZyj7c8uhHK+EZlJ1NZrP4R8Z+DvKcffsEyGJEuhGaja5n5xAasSXleEQMOuluP3uGi/JuY61Rr/M8J28DDGjCxZncQAM4fWzjsZp9yEehM5RpuNtNU3yECtSAe85F20yA7cOXyTPcniudEUXOnUERm7Z4x5tn0NiT3aJGY8fk85L8cO3pffKOM8l79ry5qN8RfdzoQTBieI5586V8Eg6pawMDaq9YcXonJjRJFOZ0KniR+SFJxkAosj5Cnz4ZvDSXltfmFIgGDVs29625gqu46dPZLjVZFazRY0qcipzED6ykF5ZGIK6q7FvXRu470VktlIOdm7Hjh1E1FiPsFd5WgQkmgIye5MxgKIEgeWOf8w/XW7ZF3lJqqpLRnaTcX8zOecsFOOP9RpYZkW1eWYsio5Rqo0xvvvfmc8OMDljljPNpChwpVkVFUGFAeB2C0qDCzXT3vbl1JzSgS7sMCO8XhkU+8Xi9kwFtOkBBSPl0GHGiDcPCGzho5LpOO3+2+GHlyZ57UXBJFUurznvG4Tub0VOzsUh9zKul7EENcvGmrVhpW2o0QtIgyeE+8VAtLVygNLtvQ4e7kU45uWDkMJ1tbFNHKvAE92Ynlm9VRrMMY5BhV9EQybEdwAkECW5Tovka2SaxO6od6SipDDR2Dvm9GOBZFqq2xHsyrWVxRQB9eYjPf/VmdlaSMvaYGY4Up+EQ0PCznozmy2R0hYApGloGhMyIcRMM99x9iHF11tCFWpHPiZKB7KJpomTY3nzRldUjbsl/9ZSmYxAnroHq7yFNLFqSyOlK3Ix57AcCYyR1nxyYVXmD5Cdickc/2Ykeli+XcHG6sCzEwfr19WoOkI7K5FevzZkRBlh7lCFwUX227mrfQ5V0or9yF+TcaRtFzvKU2GU+mvmU0PcmeRnNPYxTAyEFd6raAfA4IWV2d8m7oc/Y6oPgqbkcTaOzgjNLNfRZztDyXDdYhgdF1iI6hcGJjCFKe3BAZQgRQie7uI19dPTt2pEs/93bqSsXlSQUTd/EwX13C+hCUhwlcy1ISDrjrcKRWAzd1rR22rPsQhyjTkYx6uZyDpeSzO0L7jMaqk//ndBZNO4i1a2B6hAOhN5DvUvD05ss8oHaCbtyi9XtQ3xmeBUN6zalLTOBdTrGCMCoMO3XizECsb43kYsasv3CVlKjMRJlSgjbZZlmfIeMLVMhdyCE+OTKxOJ2ePSVykmAGwT7Ws46ZRJPpFLtUqnOvf7FUf7CDVrBOgNU8gQlTqQizbwo0AE6yFGgRBXnU8TeQl49yKsDxCzBzw06v0z7guUZe7AAli1ZUlTzDr6nV5R31YB3azySr+5kFeR/P3hP7mQNubZLM82qe6uKfCsDzAmZvJ+1HE+SYWKnT9kIAPRrLJ3MX3zqZNuxS/O4dv9KwzQapX/Q/Gfw0wxfYKJWE1+gwxgqaJOljJOr9aAKLFTaRfkGQaTcucRpJG0M5V7hIJzurah+E0+aJz/Ju3wPk88OaKQa0jfoyw2AtWMGZdc0OSjMo30KOdJwDLVfhB8J2RgXx5GafAKVzxdArd4YsKXhq2aUqFZLdceZirak8mQd6RdLHPaGgngsTuRkknXGldaQZ+vUCHTeUxxaeSagbA+0Zz+RdvzMOmsAoshuwyc1dNkqR8eaB02jQV4wQIn7cI16oJJWdo0Rfq4P6u3WtkkyY6camPbh9SLT0HR5Cr2fMx0yStepoUZcn1NcLtY20DRTDm6lqRhdNP8TtV9XS9VIx5Dh3NnFDAOnFdt7jEMxTGOqKOnh+YSB+B4HneIQaGQ4UcArIGNlPeWjg7BhoGivuNam6WSCDhpbunP3+idlUCLT1e6+F8d8ztF3PKDrXEHr5VHpLrjd9awpuXLea+/iEzHUX1CvVbP6pEmL2Mp10UPMrROyUKGFYvecRZlVBdoS96MAjLBaml+I5QG75bUia56q/GcnEO7Q9QQg1qUlne5PNYtfMUfoxQh6HmyfB+Uf3hiVQ3I0pzXoNMyzm1rlnCz+MX3EyAyXSYIhAnSUyHrP70zTCz/xbGp1sEg2w7G4V0sFm7ViGhktu9f+ndQM9RyyzHRlKYDt5n+NbORnuAJkxBMR2CRbGoBwA3h+YORysASyQGds8EfYNyD+QiVqaOPD7p9mSmVNehHG3LY/eNpFodgDigr8iVTwjT0e2x6sIxe+4d5T6rbKrEyuz7Y92ddp7sngpizjBccyY9Xjf6Har14lwFaj31QIPAjDr+VhNCQJ7qiVMQriMnD/LNo+nXu4J1e0a3LvBNkRajaaD4P9xC3X1SU5OqvkEMes+3Ixf9NtpmFIWs+uOy3vdhSpeO2uqJfpcCLiKkMbwTnGuOFQ9vCrfT0tylKiilJUDxoG0EXMrmDP43na9voAfKW+TaQ3yhI0tTtgfhrBDzWZWJp8Ud+se1xdLjnFNys6gVAJXm7feNmmohDJQU+9u0bim5Hv2VGWfRYohAaIJNlKy5QXwlAc7u2VZAZARJDtTYOfy/y6NoDmb+wQsA06mHtUqN1v29uecXBZOoVcnunX44sJv6+jHbcrZg8/YIJWTLbXgCLbBTVigVC46NNwL25ZHZiDuIar1kfMbnkgl4tJda0+OM4nqdO1qBiRHArJQX7rXajL4PuCPl1jOQJdKHVINFI5M8/TETkoDBX3oUQ7slUfHxeZK2O7w1Z6G9szfTYKrbDm2vMxL+kdk82euXPOY2LDnqgzy8WDqDEJmKgxGUoxVfWKIJdt6Y27bMtzDyeDRofhWodO2PBh7uIYYWjTxP6RyAwIotKv8eGHxfe9AOb1NgrJseuvAGaLxpDI+kl34LhMHqVEjcABh0a4Jltqj8iWQRNDbzrIL4gubx7zO/4WjGMsWWQ/QFEFsA8dnLa8yDG4mw1e4mEuyZC3cbCV7b/Wg6Bf2j1buRyk5Eeuk5aRrRC14+5zV/X8brLQDK5YMpI+kLAclHT0Nduj9D3SEc+1SjBQN2HuICcX/keGkc1LXqULst/V0DfR4juJa0fmUSkKAilrlTcyrsgdgmYHJW5lDxOmyXF4wxqKemdXiKuGSUnkOV2RHTCsDJt3gy9buVZtmnsa53ORxztQCPVBL627vj2GaHmbFQAjT3t1muEgW+rVK9bWvUef5RbRnR9Vn6MQ4A8VLCKhMQ3xol5CjmfMAPkiC+Ogy9TYoJWpvrU5PyAWd7aoPKQil/zNGpIUxHC45nJIzfat8iBTpB0y5zWw0+C1PX3BmjfISfSlvrummPRvJ2bzE1HoFLZAK3zwX4U8dNTMHfZ/JeoW8uBMFy666xi1ZnnmWZipMht9/ZbO+031ctrmvF7tdmchd5Rg0i/Nfs6OtfWDjlCKm/AWXE7lxRKbC6qSVIFoCQ1zx9zdFNz2vIDh1m1qS+s1sUWm7Zpu7kRXH85HzgqvpGFpANJp7S2brLLLC5JxA3GA5jNGrhoZ5jQG0UM0CyBJmXmr9zwhJR0uIt1q9Jy3FX4D998KhQAgL8OhBCDfEDoOXVTs0TTOoZxZHoXhdGLp7ZSPtng6ZUViWiZX6Eh2m6wWbbH7JUGz9rsVcOnqsGDJ37u0H1Nio02p8Nl7cL4DMyymZlMM972r0XmVsoifxZtJPtvpsQ8LB7+LRpFPK3SNjAz08ALEOcmVKpmAsuEE9NtYYNnzZgDgJoodwxgSdbPU2qqbJxTMiH+MG95UV67Bw4BuOHAWSu3ke2Po3QjIo1170Lm9MzILjrrwCjNpMM1+mw60z7hUnQmnAzkj57Hn221bnLw9k4YPKusnrxBn2cyrJs2JzhkIxj5iq26oh9Kg0L31rczI1Ex/0Tax2h5Q3OSdJarm7HtyS9nYxMUALuDX4zIGGeprqIgt9jHWwoJEyR6ZLwtd3m3iNMq14iD9n5DQJizLgd/sILvsyf3EEq2FjFI3CFuhzq/PKW97SwtzbFIoSI/bt7GOVAkwaWv0WahNQul43mu1ba8F6gvrG2NxW9P2hKy+A8Ju3ibsnxONu1hc8xTY2I0eKY4blsTt6QsSR8/g/aULWbbusZLxHay3flnmtvumExevSdo52BqN41pRb5XkLL+BfFMzARrdXkNg7gdddKCe06CFRlLmWq3lpK8IsghpNzbgHVT86qXCLixi0UwAVRTECB9DW5zGKWGOxpaX4A0+b+oBX0VySeA6w45toe9tyU5vlvyMwPIeo+SB3ZVROIkasfhAkaEwlp1FlckD8kF7y34UC9I8AwHG/BTGJkRt9O0eOx3/rTLMUoHW3EfABbr0aEvYTiFthwxoEyePU3MgcDcdYUv+AS+S+JpCsMGq8KuWwsdNh6zb0csh3I2MtbAgYfvhmnSkYxbOW5GK7rndwFlhfc5JxjZhwDu/Hoi4F3eATd01tnluu21woVBUAbw0NGx0+yLs/IpnciSrk7JfBG9FlQiDNoC2Swky5Jk8N/ewXebSxT3LCd/eRNyY1bNNsesTo/wiIu2YPCgH9oZ5aAPH79EWPiP1hNwufaX4TlcFGx11Z8tiAw6JhGMPna/AYcqq5FrV6T9OTYiGZSGMBX9+SdHLPSakUYlBZuqQLbL0N9lH3LuDU3K1v2SCsgMRG9mSC+hJCaZVYl8mmdRIvZ+ctltla3kMjGs+xEfjciZsTs17MgsJcVn2hAaQ4+bjq+9MkuOnkYqfRo4VACdVmZuSKXjCXOmIccR+6xAOHTku3sKotEJqdQ7cJ5DjGU9+feonciwMPo6zJ9fnVvB1h/nkR6v+XEe1l+jGqmKpIFFZ7REhb1Sh6jUnppIN6SGhyspviIxjrbIt7bjs4ibj3hbu93B8OZfhNeNZxj2JRcV1wk2hUA5GxuL0erZJzZ1CRuBksoOWmSbAfkr2BFnF/cwANHu9YMnFJz552zn4jNmRzsZHTc4EO5sg42xBexYuCiMEhAlXTm4K4v9PjdYiyTAjXSpc7AxTn1f1QnSfm/jQZO/tHr61X0MFpJWE8XcqPtypFzf1F1FVJvFTA8MIdZQnqKLjo2V27275mmo6WTw1TRV2RB9eV9fgkwJK20gyCEbh17s8Uo1lbuGsPJ7zn+DNJTm9oxJWAh1xIov0xiJdsW11aE57acRrMncZBTc+3zrLgozhYObWRBYXGFtdkytJenAG4IQpommoQjSczZ63577rnZ5pRXwkJczuTI+/sLWTNinp20ib/pZ9wm9up4KhhudTfTOMwsA6R3KMIFonMdqUvdiIOBtILBxOCBgJlHDsktMeeVHDtRE940ts7q0kTgHmTqhv25UaNkVkPLVlcVgxyJ/G2cXR64Uetjs/atBE1jck4rtSsTJeZFSAtZ5SPg3CKBdS0MDZqZVTyjeO3rWk0yTpbts7nETf2rbDUR0oojexJ3a3wAGIMyTFR9MaLT1bxNgDLxhYPSxQGMFwPe18qf+cVP+rtybLYsfSzJlE4IkH2GhORBMRQoBOpNvQoV2V5p5vCZWUTJGKE8DHs5HVmjfLo2pgUIPkoiFoV7wVmULi1Ji2Qo8moXX55I1Fuqzqw5IO4NHUvcnYKPo1ej3RkpH9RYXwQXtm2xhWcqYVUmyV64WPHIM7c5qU6GXX9G3jfeHzTiLYRCI2NDxboENxtX6XtR1FVaORGdKe+gOPqKu7VPojJyEChEhY5dKYFpFKCUSBfiJT9YBvXx/bbVYTDtG1Z6DnrDRtboq/3NxIi0fZ7kEMl41FbiZk8bjLIl+3rqQ8Q/ZkgGb5hYHnNzgY+TIQ/OcIbr+s1TRxRjvTjA7qHMO2XgdaG+RWA1FZ575qkoTK4Q02WoJ8evhgol5v6RhyH5kRZpGeGqFz38nLwULHPCfpmCi3+C2Z1bItpwRVoSMzjV3VYpU5O3VKGJtRi81Xzg64TAZMJtCMsZ1nke4MGTcd4wKa+zAE/9pfMlne4X+6biAXSBZH9jM4aGM8juROUi1phmmHfWUqjuY89kqXKjHAuNEgUlUyTq838TfpmSQ0OfOwiqSN15i10GSoDAhaUaP5VIs9SSCBnpXh7IpMln34OslQe6BKlW2hwnO0wGz+PiJg0JnCB8NGg6cxL9v66ugbX0xGfQ9Tltvjgjiz3h3cWWyhAbtl0sAL3dlm0hs5CxxsPmf3BMpdJsp3TRRhRXWclr5TuBF96k5xOA6Le9EQE4GLyFHkXrDFZAF6QOHyzYJlEfZNoP0atnN5cVeDQqE9SORsWyGNsY8xZMi5JweUzdsM/rU+MHx7Y7pBa25Szs3iTm8T0xYjC3dPwVLZHLXDGlqck+CDRnBOiXKyf45mVMyAB1jIpMengmPm3WolTa90Bh27YLp9IaYKcnWfp+1bL0/khOeThkY09GRTQ+00KBxYjihhpC7aAzJ6M9XlulttiT2hM646SIC+tBc5c3xbCXionizb2WNxNIxorZ17uSCbGxCjRvXZGJ6FYGys0dspf6oCVOM0kFUot9DYwyhDIo3LEWgU3bWryn1juEBNBM5IdVdklkPBXbk7E4Gl1T1NrnguJN5hoFFiKRr2hUxZs/4AIybTnsgAdbNogYtGzt4v8JvnzarkB38tMrQK7TMwLUSUoWsXxd4BmeSQyhMACESjl1LVGAqJkfQdqmyYoeOYzYwARVZxYWfk8oY7/LZEESt3/m7nSIAsH3VHkGO8tp/iJ4ed/gxMwQXkBCB4rccg5A45fkDD6FALO9TCjpdxB1eXx49dPp/EgfbUTR8Qi8KgSq8LihwENEhZ2rftMelvZea85hsdjOI8HFGtsDsOB5FOA19T+CqK9MJzM6RZ4kH5H9lLo6nOFj1syUqUXtoQ5MZAq1MxXT/b0HoetLMD6HZM1MUD+lIH3G7q12uuHTSVROYVu+c+DK236QAWUU/TkPsi+pjSp4kOosJXuhmayFCQKBWecyF6e8t/eIMp6NcjXpvD/cUPE4sJQNF0vVYqj+LTRD0xs0Tf1bzJ5+Gk2a8eQ8NvNWObXRKIo/H0yg7fowEiw40XBhV1o+sUgdYyisWGM5taPyV7IZBoG2umtkBeyDxiTt0rIjnbUudYj6TvGW+aIyty2542Fmg2NdKFkXyouxHXBrcaPTzj1VFIp+5WLNL01uGm7ony8Bi6HppP2GMwuCZYErNXqLL1ntdJexbI+brytUNF1uvhof72tkgsl8EAxtzW1RD2NBz5mnaHIGt228jIJ691j94GS4/uokRZHU9KkaRiA8OhRtZmTTacxNpwG60xfPxvZYEqYogCJ9bHA1B6Fu5VtxXfgyJF6Q5jpxLw6KKEhBqKEw636SmeAB1289vL26y+NrcyDf712Sytd6n1Ims7aUZPXIYHVdtoblYfikPHXY4QCUUFOVclC/ZaILg/ZnZhtY+gUalXKPUGpgBtnKXHCB6aGsHKafe0ldy5V6aHcu5FE13jVqhCqh2sf1JaN7bcF16GJW5kxFZcKqMIbvfPdBrr79gy5+MyVN/ajZDNHu8X0Dd/hk7PtpzcbS6vkTQWOudg2QdjVgYHbVDCiUzQh4/5DWDi/ROiMYjirfhc9V72jHXSXw02rMxjd+6LYL667U95la1hOkSpAlOKP+QIa8O9kOq+HsnpYlIabDZ8TvSGVWqXYWZ1yyHvvSvvPpspfacpPfEBMYMy1nMAaqboWWvNPpklJ58Hn/k7eSOIBnna4oQHE4h88iZaCFeFRdc5iMbRyh6UTOFWkz+2FlwKX/BiyTzsrLg7icHVKUOFCj7As2lxg20KgUkUHh8Fx8g9ZhsysmzYCp+m9OVBCb0hTo8U4e3LXK6UrXQRjcma09p7mqQsD1GuFo15zd2hl0ATPmMmIQMlyAFpnEgynZVKuzsKmp6bNCev4OBDzGba+nXaBRX/9UITpEBTKcGXXb2ZcExYYEywjzskA03V3VnFr20QO5lKBb+2gRez1nee9MVzDXM5ejl8/a31B2yocxpcpSvSsZzNGOGUsJlbxR0Rii4k8R9wApuwPQMXs6n5jiXeN19Lm0abfLx4Snus7/Bx7O2Q5zXny+kXTVVuGvDApTviOQ08ylSENnav3kj1qVu0ThLjJtWi5rqUST6ZDlV0PpzpdfO59X8sz5f5XTdfKD5IckLVamInV4qS7BqdhvFmFf+EDlrursh3yJ4elNT2lnPdD5RUY6VnR4d63DRPYfnVkWaJnESrHbT8StqGvnRwPZGcbug7ZSmEYLvwNgbz64xiocnZ/J0IDYPyXNMyNWu2MojRdnM83Tk13/KGSrtd8ubxGdZZvjFHNzWpNxIB7oEkx/bvt3DJTJTKoLCedpwgLgiA19C13J55iMhpSHq0tKc6VZ9EO6j1Zt99rYG1LI3aknzWt6wKZzzDg1zgCvqbSgafuiN/h0OZyIczbjdwp6c5CIcRhtnO5hgvO3rKCNUO9+fL5PrVrOUSp8kygrZ13NZtWCrU4lSqjIhwqtaqbh8hVPde4NvpVxw4pxtnUNt2DFLz2AJ/yXSDH5wUNx28Oqw6qleImeQ3YxOSi9eDScB2dkwwST823B8na/zFdfAFRGab8ptjuk6ICx47QnkQon/RXfjPH3+4a/S1eyB50hxJtFVj2PoyaGtD05mQejaq2ypb6OF1cOCqt/vq3qa9w8nqINMdDmanydQgER4twNi3s292H4AmDERe4cM1/tK3VPIIaeJLd88yR/IJ2xpykuFHZu6NymVoJHjZiZp6a30WW2NP6myv04MXHX++HLX+avkpxaxsvVv2oeZTH0XW24wlHRqlkc59logeDURZWEP9pA24OnsJZFN6MYFKIiKqU+tDwdsp9e+iaow9BocIXKrPySrEWyM92aFqUIvg1GEmAylUIyuKW/RofjUGJyvG2KLWI0SogtQcuPjCYugXqnofQUXwTAd0zRH8xnfhqdypyrbDxXqwuZRz3uS5cd+RfulLptmQYezZbrheFBKMzIHNQDppG3JFuCiNyyuDRkzMhEbYF5kceoVSte25Cb1GJuRW3GBOppElhkkQmbmSZa8eLKOIpyEZeJdgT75cIKL3ZW6DfseZuWXgz0GfulNRm6nGoW1A8xEJm52SqwZfsYxSKRE2ZbB332QaZ2woqJ5Sc0VlJ5du+Mq5J7jGWWvqEGlEhe1tWSNdvsm85ALTZRCaI0wXuWYVZrUU0BR5DYWTUcidHH0uqrmp2kIfQwJKfybk6y+oAG9w/S5XK84qJsDYc+xVQmcXHqThFgjOBIiObDE+BuH/g2Kv7eVq2wjkGMHAooWyZ9AGj+XO5oC+OJE6tbDRiOmgXJmbIAv1NgNCZ2rqHPcMYm6DhoKhkFCadSDFlR0dQ7NsfcclSkxXjWS+7Eov74r6V2+XjdjzJeuZcCamBqeTyQ0QRYMagotpC2lCBrp1uYYYZpoRpxziziHSSEGZzj5XY8NBILFbM+mJ2HHu1STGpppGmmifXP+U4QPInNl6zyxn4Q4reVNagFQSIFRit6ToZJaYRWaRozDyQN/Fd6OxulfUfT7oM72jI52uaXFnnL3hgNVNOTvDfSMuV00eB3IXDftMClrUBLUqX7L7jjSPrUNkPoz2uuzVOSJR9uHiMcqoAih1yMUPjosesAF9yUNDp/WvGcspnhPSBtBrUM2HIk7DAapM/xGeycDJx7yVtdR7REBDpJ40TaSP5xNc8ueY4NKZZDlZwtl8jouNGlEHCpSiCeWdLm1M3PFV5tvUsXJEsa1uu9Q1zZdeibHadpM6pj33oriwb27+bKWZ5GEYKoKPXRDZororQQTBkCRniNREr6QzwTDT/Q8aMEB7YRY3l3XOLH4yOe+NvecG+MZ261Nbl3erVEfb8wIGbWp2sryF5I/VtCEFPqJDUiGbyAUGxV6neO2cRlqdz2ZTazzJoORocXdJ1JqCVdIIyxXcrXKzlu58WXVkBNLLYU+QUCIUT00nFA+gb2CIgsjZ9+r2ycjeZyYbfiL5dbUqL90h9pfao/1knfc6KXCCzhkRWQ9GBEwFCpojqTqxvsI0KUozh8sEimab44sUNYTm5QVY0S0EAIrU9twQ9KM+B0egLzTogvfsMW26MiFZgietsZzcJHhqqqthzGYSTvkqRhizTRtYXurGGcLnu6MEts54IlzkS/epSV2d6p0R52n19sC89xflyQ26iI+7IPMfbNCu04rxeWEGu/g5LnUhR9AAD1LBT6fKRMbaHTpuct+kIhf5dhAHJrGnkELHfi5ppCEtopVMvhPRYMDr6CIh0/pKKCQl4AxcyCIeIHozSInHw363T5l8G5drkLhQv+fbrBgeTdDLO1p0TM4GXb714QcFsdpE6upXnGALyEpOzrHuwAEaJgHu1h6ZMozhQxzcoQVGQQNYbtFpK129Q7r+Adgto8lp8n1MJ68+d59fmoG8E048x9xCVTG171DMxjAgTkLwJtZQ1yAXLfM5BC49ixdXEXB640QtNTMnfpWTluaA9ThwrRQhS/Ytg0bloDnZyZy6pitormuUA0h4NK9M0F2jdRfr6ZLV+D7M0wmu9JM2NCmlG/qYFM55W656r9tHj+K6FqfcOg9/Ogs9Mh9RpvZsejIMd3VifdtlyJ6gFpgBz++6/B7db4d1YygyfheDlKLiDWkcDCLfQDegbFef0vrUh8EMt1ckoYpy2RTNZxO0RG3uhOGDzKnx6mqCF7CSodKubOs8iK5ubvH/0/buOpZkbXPerRC0B8I6H0z+9AkBcuTSkCGHAkTo/tXriXgzc++qmp6uGjrd33G6K3futd5DxBPT4IB2HdLZjOaEurBzogzUhbXfc+V0Cd9QKojjw0wbyq1rinXp61/21O+esm9MNx/MN6rfB05WbhwEswVQ5EQi0BCE/zpUVjZOWdgQiSk6ZpmpBPMwvLwifGmrNy32Yl46gto3uV3H8tUoJ0PKt4W1XUB7hMg+3yWnDeNZG846awAjGxW6G1QtEqoJ5YKM9GWj9YaeVcuVX6bHvX06bxEiP0yKfioGH9sWssnyfks7RTmaVbFpZXa+hEyHSvnHmjhnMV05hcMRDlW9nWwJTO+Lxmy85IWGOdNW5hXZtVRme3tVYHy6eB4MvXBoSVzEf8W0XhmMRMygNKXaZF5/BYusF5bLY8KZx49zn6ZafBSqG4OQHdZs9BY+z4mVfCq1cLgvLqw7GytOGQt843RtK1/e6CnRxrxRvdJeXFPpodVbM950V6NjThHdQx0QAVsl35XJkaITSleZy5heNE1nUNenRjvlWI1gDIAGPbE11CtbZAjtkpglP55z6bdt8nu8yMkX7h4bZagMtTkLYwFmdLwWy/vJ1mHIs8UpKzm85OBfqGYHp7DgUqkZ4nJdhYbJ1lC3hI62lXvOrL4zqRrM/qLZL0SJJHzcsfsxSZoBeinFoSI530iiJjvU4aqdx1yuaK0nlfNRaDzuwj8sNJCVbWrLjeVx68UONXLCLqK8782vGTWocHA1oBYCfVu2+q5xKdoRCsrJc90PwmFHL7QF+G4BKdrn05IlqFOtWykgfQKLcWVQWbhB+FDXlGN7dG3GyEQB8JfmdqyqFOC5eLb1aapWhG/uT1P1NcP4Lv7tdHwFKKSMhtwWKwV5fzqXTL7ZM7WkcqNDOY/f4t+v2hHkMR3ZcWcB0lM40/E9bCZqYu941XZKgEQKGgL4GqJlkWB3ZJueiT2HsNSOBxykvw+6DyRNQsntO/36PNH21HR+VlK02xj506FQeg3fsxUHXXJm3ab4BeWgaimckFeQzXFUO397y3XuJaUKdPrkS0y1sA6bDklVuLOfurMTJV4JW5n1Q3L2MqMYzE7Ue5ydAQ/Re2m1+yQ3mr8gpJyc61ThW3qLKxAHJOemm/Zv13bke8/7NbClvdjKGCtPouozgQBVWjhQkZ22ZGFRPesNViITXcPYEck7MOM+rZKTdmeya5to5i4NRt43LK4+AqBGt9Fsyr/OPnqASh8MlociewhnGMX85g5FaiZvACtBZ4VbJTc/5gQXdXPfobw4BVydTwnRGhE+9Lzxfp928RtAcnHsUKuGXGh0v7kb1rYqYDA3GtCnzn9encWet10d2YaDT7eog81pRQ43Be5lW5I4izPnb5MzhIlHq3d0kcicilSW+0mw71FCqAGkpRfbsS84rozYBQ0YPSK6RwjNbgLrPA85WpJzfjQJOs//9X7I4w44/JNB3OPW26J7XQ0JV+BA5tlY+58GQWr14hii1M0TyXYqryzZJOi7T6CS0diNbISCPE6NM0SpcNrqT8RYmxJB66cEmSWJLUuvKR+D2LIN8aNGg0qIS/LKUrrViywCtSPL/YDAIWurmrRWrS97kmzlbC6feST/4wcxRL08Do6CtSxvw6AWQ/oBZaSBjq3LkrMCj6jRLZx7a1hLydz+JX998BUdQGgtHkJtOVB4jG6v+pYelhq4Cm6IjqWLXyYHMI9543EQwvm8odqIcItosVuGbRg1R7QWMr8su08SQOlAPH6df78e9ZWTo7Wqz4083rHJPwrh05oPcaqnn/QMGx7ZWg5gENrl9BIaq02Ugigy2/QgXSegeGbjdX9t9suIST5j9ME/fLAZuMq9zBGTOVDEUa/9Rvp6VXXlfGpahWahMdhsfNKV/8QbweRDmVzU8wfKxs58+WRc1MhsIYK2CsdX08eEi28M5ISuWvwoczhCZWlbtOzg79t+uYbGvbJ7E9KqUn6JKNgFLP9EqqxhZ2Y23ri1bpKLcBec+ML9dYJmO6rPxqd+mUm2wE6SwzGqFzRNcdVbXd0ZzZ+Wj9EVr/D5/kRHff5S0lSfPi8iWpqyfZdo1GW+HxU/SSzTsvohNRwu5TaXvRJEJl/1mX3xbIZhimDIORA0bFz5L6sK1Keks1lcPklbmpyIY5lkr8BVpfLJr7Px6yiJVrpDUfgGW2whBNqMA4T/Te3e8u4e6kOBGYrpahvxW9ayj5H+YNN+iud2z5XPsz4ytL8UMnq/xLN/D5f6Sf2sdO2xzYjt7IQEbmyUyWdUJ78WohwMZqP/kwFRQ6nUSIo2Fp9LtFbvPToD+Ilj7LyIDI5KMkC4lQg3ZYuSeZNz8YoJHez5DCTEWlVpwwj4YjLECnJe7zHk69PxRUYL7M5Temuw/CjixsNw9k05EZ/4PbWYOxABrNAWwuXFln5xi0yGYTO5610sM1QA5O1YRz2VVxxtj7isYnZLxaGT5YpCWrS281YvgUbPEWbGie9AvmpoXOX06mC1ywgYQ0g2EjFaQkMo3HfPK3r25qQWjo35DGAfYko2wrzyv0RhWHpHbqbk5PJTGwLdIjEkqyuAVtU3TdK1Tz/WKEuVzUDUaKqvz1kxqKvfsOVZbz7qYoXSZyy9pmcUi1M6YfarHB4TXUDdQQ6PiLiE4KVHUF0RL4erLrMmz6yxc/Hy5AwdabN+/XfnQQfu4hTJQ86G8RLtNC/x4Z/LZscWYOrSxi2UWxQVk8V1poaT+UjG0Q2nYxKPWZr/4i76Tz36Kt+6GJ16V9XDtexiQvm1nUl929bXD5AAu9xR6wWo5GDooRCOTctd2bV2DuOJgFHZh4p/y2q5s2s3/qUCv2iMfp145/nuJ7MzWXmRXq3rUb/9IR98WdaS++0YyTzbirG6KTCIKbvjO5ZGFxRzWWbyL0ZEHUphJ9Co88XroqpsS7mdWUjdPehzDuKD//0ROTO2ys3kjCpJC1/2wpCtKGND7Hdh4JSOlU0DTLy0x23L1cvfg1oFvn2NMBzNih6SlvKvabVWfyo72TyYWkYZt5E+bQaTSwBzRgD2jXR/TbVSU4Zuz84bfSXcs2PpNRwNiKkuyVZWU9JucqcOerFwNLpc6cHC4QKdqjW6r1En/e1Qfe+b3JlXZC0i+M6gJq5UOOZyvV68sjPiFIToLKyPSeXtLc7fL+IWKK2abtpTYWzREGIM+VIBsifIklNLu2KtSkce00twYU8lV9+iOlMNP1mQWhZnsgIEtOdrTP8GWPYtbWi+RTGlxIw/e2U90aZretx0QVDiyX82piM88w5hbw98cqYJObfGPGdxb4+dyFlYMo+7T+JyOxi+pwPnfd7b7oXOfKgivij0dlWnp3yfOURa7D8lSO6v19vHI0OdhvT75To+IvK0t4CfMn9vxX10mhHBAeqyTgML1FNXgqonEb5JhbEiBFQeI9GaRIXWZrwGbFz6U9leQTvVPh5HxtLUYpVP0t++O67PeSoY5d+Na1EalH+pmrGjLcGXq72oOSHXTpPuW0kt559ycI6yRoDjwhD/SGqBHTIugAgL3fn2y3mAgZFNb3Of9tHX+19/MI0oLd5SMOYb5JXk9GNZP6mkO2UUD9SS4onW5Ul9mf6+7Q9d82QKfqnmE8OfmiIq+cp1SrF2yhZr2UujlZwy3JF1T0Y9E+JCY8iTdKpyq1WgevlCF8rjINOVoKcMjakxJhTq2tej02gCRJb2DGN4hiP/odlm3YpNjXVmNuJ8tJDAJhvtzwkvOWyybUvxgYWtQx9frkWBumRkElvpbxdSKHJNkyrrGhMeZMwdnmbDuV9hG1fMk/o4C+7NIogC08vM+JqbKhxL2Erhbh7dl9I4DkgAlFDtl5RikIlTbOct/Tkovvb8f2z9L366GyRkUVT6Mliic9M2IguOjPoBDCy8PSNLWgq58NNnG+hdqYokMmmM0cW20XVUIdxsJQzWyDmaFmt38fBlt9NTZY0hOGGTIx2tXUY+WNgijWHArZyOJGtYanys79qK/voBwpeO/Mpepnx0HY/F0oExhrz7m7vRSue4IuSJ2yxp28NETdr1Jpg2XzLIUqeoZ2P+t0f1KX8RvpYUGU7cg41tRaOQrWhtz0u6GbSr5JUDWpQBMLyC4hX85vtiQEqrma3Q3TWG7sM2vEpLiQ3kgLnoXaizpVQZL37Hbg1hb+95hT8IedvbFdnkMZ8WB+XaTnY0ZU5SZTxrm7lGdMZY86zuVdGk/KH+NoZQC5f4fixk+Ed13J23uTiPmlCxNHIbdndCGqGco84BmehD5ArJBGsl5R+hOs7pLhiUbqL4+k573DhFlKBOD3d0Gb/+1XnMzx3/6QQw8sqld6UB5Ft3/MOh2uJIlb/UMMhklHxmdzbE4UBEVfgRZG7CpIkuEkkWt91MnwyKlXrsNF6duXhFlYC+AdosAZyyHWkVv7tSeGqzHrbNMPdTrBU6tawcUwhaoq5ew4cjD5Ge4nymXKHoyPmAZC+NtCcxQ47I7mC02PH9W5jCp1l6IwLeNJ2LJfvY1uKI8VNROC389nN7QZbFSHlNAPiMVT/u5G7dc6mFNLDZ7q/ksTVu20fTM6eDNqiXrlkxvUNHWSATryOkrwivBLKRqzNOPCHmXjxtdOd8nhdI/crUqs/CoqbfC6/+4dvMl1BR252Sq0not2wKzUFhEYh8arVwxmtMBWzpbF/VGGJ5r3H7E3pgBStL8CpnKUPRwsq5oMcoWi0K+ccbnZO+QmdfwvBZGF7+Fou6G9L4jMBEck25oR9LD87l9eSa2kEmJMu/02PsCGL6lxMhSwuhDiiflC+1TrqSHvPVP9ytw/m3aDFoHcgXUObjvIIfUXel2L1q3rQv9ca8fznPbz+o3V2xKz2/m0jLD7adm+XfJg5oYzvYhEfM6C9UNBWR/fuNUktKogIQmnQeIPXHqpLnZ+N1RX+PeUtN0ggnfzeoSNG8TcT1Hbk2Eggjrq18BmXbAlaZmk15qPkKb2Y3nZNXXiXNTRfj9S5T6QHDHvyvIGPzyuvuEqRYa2VP6fv87FumpTVetduLm60BXBGIWLJiQQkGZguFnixBF8FnEs/DolHvVn2lwkqoc55ntV9JokrxojNV8KBr8w4ueYzuG07uSsH5i6Hdo90eUkU7KNGmsWpa9HGzGuKQRYboDkuv3elSR398hD8zX5uMDDJbGO8PKsFviKzOx3AKhEeoHheJkUGh/clEY2VExauYwja6aU3yba4LbsKMdb7NKDkvr/d5p1tOrBTwyqeQR0RjRdzekMuGyk0QtypsAwo49SWidvcV6w3gbpbGSzLBt0topiU3zVmbUC5qLjGvGFnqtO0yLb2DVvI3u2XwbZ0XV07zRrBKAda2REJneTZWgO1oTjrTvSqOQbGf5rOaYbWwnWMGGMK1ZBOOTz+Or0jhcXbJDIPb1PUNQf8RT+VxozGK1vozEHkajSCwynyezfw2Um3OyT+45JgrnXphXpw8yQRlByuPVnl9aev/jYCYRsjWRnbDMuQump3FIStuwkrB6e5h1O3uYVGk5vHVg1WIyMq2lV86td7C9Ty9tNc/dCrRbdza4Km2g1uor5DI4ttvw0qNxnGil7djTMyhy0ZFS9OPiNxqtXFUVHM8FvavwKv8Uo6ljwEKf0rVtIRqnZdXKXcdtV9C3Sqc+6ZsMkizGO2oRPgMmbBrKV7LJ0LtySJzrHvGM/O91Ow8UCnXxoi8WM7VOo0I63zTq2TtYttTOk2W+hkEkHLPhdEkufSoGBnMawJxPj6BHpH2pNPCzfkA5eVIQs8fK7I/V8DLZDds3B+8xiIRbl7jDI5XzKvanCS7qJcmE4vBl7j4uP34GtuE22KoRjWtskGP2niPdPNqCp/rKF799WWTXVZ87xWjMBz/qfibQVt93GK0w5V2JeMBEQ8ZTRvjdwm+0+nY1lVFMBH2Em6uD8ilPz0adHVs5i6LuejCNLywr9rpVcyzGdgXJ4fxRA/RutNpev0khSmerFZq6lD0ZD3wzY8MrHEfzJXNT5ZbpnkoPNj9DnlrUetfboPBuaLV9gCUkTUSOa3w2YlyLKM+4psG8PPXT3AebH5sjbfOhWPpfPfW/S3N6rf32kvdkKhOCuWpYgIX0rvNFr3DBd00rykF93mbuti/jHoUNLZg0/dVp/aYC8+G3Mez7CWeaLhjVo9YtxbcML2fnE0GZoIPyMoQo/TdwxCrI1nNCN7/kuQAscyvP/M85WcMU1XlWz8cvT9RZO8c4XjrvJeibyjPp4veqmesUPoZiUhMI2xPZulQ+pdxmmJZXe6idCuyy8MdM4YDxy5YulLZFlOlJr8XSp6VHaVyPeNWPMKTeortPWwbbm5s1egOimx2uMrzueAigem8HugAyIU9M7qrdBhXkOY3V/RFeZ4x0VmcFyX4zqNZNH2E0mw/r+yl2mM2W23Bpc//uNFwGDqDw9O08U8Vs34nk8PsOWJf3FnpNDHfSDRuuJMqYDBnXmxbySusu6kcD1y3qcUmUxNTBQyjRclIAjIOV/2Q8nGsdiXQYwQTAu8pS+uPFuOfv8mfD91PwywWeqggzi5N0hte3IbTPE/5pRRr/I8mFo3sgKYAD86CRqNV2au7VSMnrOo+ihSRRmE7NHNHuFtomAstRG43DOjITxj1FgTKeVsdN5UoJjcVrfJRDxz1GmLYX+/Vec7r0cpl4T3OifN5K/ej5zywWy+UNbPaVlzpYxOEgo1YqQsklQOgz6AyFzFVmbe39FWWQqK3KOs1Ip3peZcwSiiRbmfBUhYO7WKdgaFRihJCz8yaNvMh5uy09pnjwFjArIBw1zgratOw2mEKKIZ3egQwdU3QzjbnoYPABfZ//kBkuVljbtwpmxNxkempJYRbUxjGFygxSRBeYmdTpTMQ1699iG3jhndnLGq9Umv4wfvyhZaHW/AGVaJxiXkOPIH9LO/nOvu5DXBxMu8dbOlWvtdHFchSE8bvNPENhP8KkQmjdqaUEQl0LHpc+39h/WivoWLlJ2v8E5mlPf6E051riNS6Q6W3lkhkCKoWNqBO61++5Yop6PRR6X0pOlX7JS/wJ7XL4oEXBkJTlEfuvkwVXHeQSpuVgSKvyEiwObzqCP6ujAR4cM/iQ+0zH8riK9dRWrbstyHLAiTWB3VcxNaM9BZS8XQ61x8/6zGeMktGBWLAnoUdm6SkGhm5mTzOaUdsHrKplhyet/VCda3BXmZARvjXewY0ELfqfc+oZfsINL32/sm8FZUYZVufpejUE5jOF63NCExnwKPtXcEhX9DTl2ZU92Y5OnnkBVRCgUl4xkC7X9mlnElT8uzPzuf8XYsd99/igFiUywsfwERTMYfnFLVHup0IClzukz3kNS3bKmylJU6visA9I6aC4nnyml6mfsEqJCnu7WbFLr4MDavkQtmSlz/q88nQSE4hK+DrdF7oysk92OrjdT6LW6yuPGamm54HnUvwjrk5mRZUr39R9OSPLPRvBh53Kpx4nZmbzGIPUNqm61dkobX5DvSIPgYWBZpXLpJAfbk9iqZkyvBfo8FDP3VB0GWTWTNuQYhWBUJGQeBWqks4GRAGp3ES04ySomYbZ7JuOpwFgiChEAHQw5xRUNg9X8fzh8lyPB0fUx9fDo0/af/as3BW2DEhfRfK+NicaagXYsjFT7oIh1jZTsVT+iP1t4bs/Rl3juGsXX4yTWwU5zhJRNn5tVQb7UayHL7UcNREm6JMpy1CEL8WKWraHRKiPPGN+mrpmmYUZ/TgtAtsqwPc6yVE6F6CjI/7pv/4Q3n2pCTYLG8mC55Bl9343C3IvYj5LB6ypGOK6bls3aCppuqL+SZjG/qyw5afNRYikAKMh0YPKdtc4xCQaqVsJ+rObnFa3lZRbv7Mxi4goZvplHJQ75BUFhLakGKTWHoUNUe9CaLs1317nuy+cmFRK1PFlRfdRL9hNX/wCj/3eBWjV1EUEyyPlQK+xJd0UZsterS5PRdKpFqdfgOWRiZT5otDouuQWLHSD+fzVhyIRpzrJk80fthOud5Jw5NjvDZvuq6KY2lIv8LhLEczrukj9Jv2+7lqO30qXBxXy79O4pbSo72eGhJNwWriEaMe/pE3dCgu/JZMpAh4LCaMJRJLD/WKU3DSNo3p+21jDJozDI0Mi0p1xOO4s0q565pSSrFIDm1Q5dnjrivcoQP7zOJlHwxRpnhjFDSdMf7Sg+4RW6E6AyFCS546KwFysN/rD4yGzmfs+w3I8TzP2gXz2ZBRjNwt9odj4puVhVLReeU2atzFJklb1MVYewE4WEBnFvfVYvwz+Sp0bGJqZr8YFeVt1I8z6JUAB0priDWfbEeV8irvUGUu7/WkxRrCIABSEeBKYUGZkjrjRlAZf+7iYYXF4YEjYhGFMl1Bhz2dR9yumSfvzzmSj+/sE2XKn2oyFUfol3ihyf9VsBUMF5PiVSnlmqkLU7dXSM/COduLjRVfPFzPimnyBOZfmmmuOCtYvqkkHop7Cxxem27GLexk+927vziFEkfOuSxeNFebYn+JmcdPcNx8uiyOrYob99cpdJ5tv1xemB6y8kmf+OjY4pX/8k1hyhJDBYnTLqZ6NF7OTfE/Y55TVnQZWaKEdv5TGy2/xqkMTdJhI+0V3Fw0W01iMkzjFSlEhb9WKQJqMaJaxO1Uo3eT3qA6a2IKEb3dcV4xH2qrecoJgObxT50FmXYipZ4HPJ/atSXt2vn915/7rNjSH8oxPxvBtWewSqyXzgyux9mo17HGKJLpbOXkLMWn3LFkMll0emh6HV6YgjJjho/etU/nhilFJFFwDQZFCXGFQq+2YLCbEj1RIKZbmT9XcIy5Rq60x4lTt0liPJ9ze3FLIKT9euznYa/LhnC63uqBZ2Xd/zLx/IE9dOxn4gejrQOegJ0yOYTPVgr52WSyPLj4dL/XZcmp1pmDyW5bwXi/vOWT+msqrZcB0cS/P2vwulElpuDQdIELaAp7toyilltGoX2M8s6ONwKrh101PTw0zQ1LnpbOI85sJBCeNcnpL3HMtHwt+Fa5OW1urd/1bN8EqqDC2xRHm0ZzQe1YqCacR8gts6pLuqJYG44WhdtoqTRgrpxSer2lJyhyKOzOyjPM04Q4symYw03lTHL/DlAvg0G+4oEH6suhj7tG//JMg7vYLIq0iRA/bIvHaIcAHDmnk67P4REpQfj2T3DSOURO3/lBvVK/C1PJ9fk2C5GAcWKx75zFlKNWA7dPW1XB1lRupiKjBXcS4az5tee7ctqGsADcMBoKSZ5V2D6pjS89NolU7k50pByrGFAqp0xFNlSRfxT00Fd/pEmsEKoZGVYHWaPZbJV5lG1JJl+TB10e6F1WflWcj/IHIUG/mV0MfMHXsVFAdVcawcVE/yiImiUA4po3LUOzNT1NGb3IvPNnrG7icAZSrwG+ddAEKURZQJHB/KNTJwsKYPxS1G6K0pHUUXDSjDl6MX8eOQx5g1kLbU9hHlJEAso6lHkXzgVB5+PXuT4tz81NdasvpNK/4Rv/7lVmM7QRgW2mloMiwkE02Z6wwjska01HMrmh56Xiymm4/Wif8Y15mgoDKSuqZUEGhcdsBmNW+B6FhdXSHylc/2a92Gix0ccX5dqQaDNa9BsMmhWneWk1cS2doQYHOQlplIC4RNuvPzeCS8Wbt8g4vQQ/5i+TS38ztSDRcUMIXd3e+saArwihjxUgzeAc5YdmEwOG7AkaV7T6mVSohTXssoDp08thX8rOGhzTepTGN70qs6z5gYq9LqxWVzoD9dpxq3bOBPJgJRXKYhkB95Ud5Zzb1vKDFjg9SH4S8XKT4e6sCt5HyPkHy6dpPeNLZBvfts0yfdH1DvpBCWGaUtkAM5fppchibquZ4uRW6W9MYyU7yqTDQTNlQ1NGBVWdWjjRgDp8qwFSrNB3HFKCYn6XYegdQ39GoJnbbQGZJV70ZvxWYqJUZlAoFIRNvXNe/dOVXOlMpNloObL6y+wtQmK/r3xrzyJuJ6d2D+YqLUjEa/mu1sVyXmQFKcK9LhI5cIB/kpuw7o2H5Be1xhBIajcu0YYErML2qgzWKu1K4Uwow+7GwjiuCfqkDd8OjD8KzjwNY5L43KkUR5Zx8iDYB0ibocPiTi6VVBwKExfp6/7pOwTYpYiPZe62TPmFSnZcDGI6h7GdF5h7rCKK1ZQJIerqX62p974z2oZ0nNn9iNOZEGx31DV9uWNfqN0qA+NF9ylaTeLC0z0xe2TyaXu3HH1H73wgNgIXoYfF/pH6ZfXg2e7H8PgWafV3iH/5homUM3cj0VqC4yBuXApoV9ehwwxzpmARhqnRXnRlzMWg7bPZZlYyTbmnFrXes82arGq7RkKbbU8ekYSnkI5rIN+tWHJfwtNvdI+VtZjULpk1AmoRhkmKmNUwGWfmHr8ebaQDyXbnoI/ze37n3rX/8m0cwglBP7xQJY50MyBUEum0E4pmcMO0AIszQHDia/m7YDzlFVYHkG5q3ZJtxW0sRCqdc2X+UbMX/o2ioaNUEd2qsfZP+47H69eKqdnmdU5sgSX7NVfD00OVs8eFtDolWsmPCNhz0vyVfKV8Foz3bZUFisrN33nzk3pmD8drhVpTBA4pMJcAatz4gyOyC/p+JrFkPKS3aKBJ05YU/ioFwEXuaH6vpXhbO6hVlH5dUWZ8l5o24ThwWzc2ZTLBKBzXFTx9nXfEWOGuyyV0QxTfOV3R0UflcJ70MxtoiNo/XsGCP6TUvBUSUnnThegc7rp+ikH7ifJU+qg8DCYtwwQpXTBHQ/FaGBunq202KAojdFl/XNmkaQUwl1q5iYDKysV26OUvVS2Rg95C810eoqx80/2F1pX8cA8H5GUOJbGDtQ25EoIw3jWDMg8X8ima/aMM2L+nR48U42MlTfGronnyVIMBpwPXHCC5NP6RCo5KrG7jlDQ70wBvU2utFjbmKBcmX+JJ4aKycI2IclUzWY0ecg7QGaqlpgmgPLGidZPWh5qJswI6LTF+k1O5PRu75WHQyr+xjP2ZbEgkhwf/TjcgFYZFFFpETEM/K4bNsrwxXT1emqSD+iNzcDD7H9MUUyE/FhrlTpuXamhwkwu4I3Rt1nIOtIgbRWcX71Wv9w5eJrVu6cbq7sswRsBiFsXOee9S1DLbPJKaX5fFedD9EUORh7M0xwtp8KfHxq5PuNWCMNg8qChYnRab00a8qEQRiflmRakptJe2lYplYmy43uZuHWpmareHLBOy0rqtlmMY7y8Z7eTASoqp1ka/3Jlj+qMb63NniLSgjRWPqoby21pQ6xmoXsEqxx6HOwMsdyvjMUpemmuuF7HhxX39rmFX89h/27BrDy7yzge+p35iv22XB7dEzMLjlxQhnfrlfHx4WfULht2LEndMM9Yqyb97nuB6SNxuuWZ+e1N/MInPUkBsVgCbgbBlyLydi9psqdNlMjGa186FOkJglaaM44L4/6/8St6+Un/SQ0+xr1i86qSJRmOXr1Evn2xntNOT++ekmQUyFAVty7WwdWpc0xPcYYU1eWHan6uutAMioAJRevTxMLUrl4bLzeiq8/tzO/pTeFWqXy03f+YsJwzi6JJVwJ3DTyRjsiFI78J9KN95jWpVjRYo1nRRWDNREX8lxd0w8Wg7Bk0ypJfXrwBv/9ka1ZukjaaJacP4JBWsfnvagB5ms+lR7MFmnHC9pxU/WBeztbts6phcO+SPBqOmVvPiTmTYeXFenbjtjqoS+HWxsfDFJo4TVgW1eRKstGS7X2f12asz9hou0cTwfTPFLLyuSVEz1c2xo8H4p+Ui3LJurVPsSV5M53YFzqTL0ghs7lya/1aErnZFQuNWG/gXeokBFHcxW5fNpvUA1mqotc2LkbG/NDdQ7Q33/GrdT9VaY58N3OMDn6j3GtmkbXntmpK/6Ij1h9p/AnR6tptn3KkcBjvRtg1iykOzynQsjaf+wNTA9fbr8zoPuT9la8m17q/f6yeYhG+XB0e9xiBkN9OVBG6tl58cHJCCnDvVZt1OSinqW4+J4isHAml+V2iSlCktQoEuzd8g+SDhbp5IpiYT9wk0QMkHmU901sgvF7UmkPwqnVsLJXE1dqS6UQO67kq4k2d2SrBfZ0msis7o7CAL/uKNmJ/smH/aTUjFMxhjd6QGlY+7sCfKwldlGfPJ9hmglFZUAX/bTgT2dkeQlGlJLFAqQpfCWrmoPcCgdloIaqcBo061k6JBDjRHyeRnNCfJ8Pk2IS8QF54MoMEEgpZ9RVYO6aj7TNqvCInxdqO1z/x33080T5S1pdsWtqTNXtZB725bd+tGATfOva4B97I4JG/zc4En10/A8ChMTmPMzH3xa6nmH0uebxE8reyF15MmpmCtOVpKph6F+WVh4uecZ75LFhjLbIMSiSul4Txn7K7HXzH0n7e4pScl7N4UPbw0/YcHxZIp7e4jYJRPAVol5OI0nMUnoBPMuNadFd6sc92EYOKoSW8UbQSAU7AwkNF7hgCw2uOo9OPOM1Z3uJp9ZJWOr3ZHES8cpJq2FUTc2lmIgpHpZla+d8o7hXJDTCKRNQQb3KcIvlI61ttGrn4MRPnugdyffXGzTHCR6HMm/yyTF9LnyR7O2SZiFwiuLfUNP20mw6S+cTEjFiltT3Ympf7YNgYXwNoWurHO75TEU+N2LZO02ldhXG4Fphb8dYZAa5idmbI5HxmQAypkRnlLp8yZs/htjtqiX7m5+NPSRwrxtwlhjBE2AqiN5G/nGz66sOEuvmaTPkLeC5mY27JdqGuAS0m/2TK+U4jnbeBomDkKj1o14crhMC0Rbc5mo+AMdkoSB1fBg911IQqoQN8x5V1KkRpdOEmGtxy5O0SXZR/vjXyb5BO3iEJhNgyBiZXpvjdG9cfmg/JUo/A3Mo+4+8BuksKKZVMjjXtDVGC4tjgzWvskAfpKquohhii2IDiHcd/yV6Eqag6/eSg0JYUVVFrK7lziRV8Gq4uosLKnUcayMHMVRM+4V8wpmX6bOYa1VZGMghQla055EBdPSGbz7OHbLcniNthc2LfG6jo09Coy3j4hMox35jT46mRcb4doYBDRePgVY3PlqZV5NyHKNtBuro9InZFAi0aicULJ296YOjWtSpk+1u3gLKnWpDVIO4Y7w5st6QbPlIrVjafWQxZzIbVb68+Q4sfIsn82Sftu37efikz0lxsDxaaLXZL3FSMiTpcVFWriazmoMMSfbCNavhd840w+0h1FvEOeyf9YL28XGUesfh0OeLDt4GUQ2ThqKiVEnc4G2xwRawWfP4aYlsgySRvkaOniEGOwVSsPiIs7z/pJFswB5H885whvrN/kicm5c5F1t6Wwm8jrzWHpg0JlCD/9YlQjzfyvM/t4izjyWnJg7b6mZwoSLIQHzh40fhSznl5yeEz08pf5pujQZlhUxMGqgRdBdTeKP6Ol/HMtq+FJzxSpCkLNoQITvoITB1i6JtSaV7anBX1pIHxc4s+93U+ZCse521IQ8qjiTgc4wrM7rZxvGtiyxa/VKblyNBW0I5lbrGgm/HJOT5yygxTHC7e9awjZWJr0bdlawirdVFCsR0FBdKaClIrybjCYLF7n3cIWiJxUkSIFHUARTYHtaqaeJOSGc0tokHalS6RY22Vlztc7azvdBONv3YIS52wK1yUwHlzRVe3saLhLz4yHUdAkD3Tyo2my0af9bmc2k16L5jiL+zRMYCznmmqC0dmSLslZQTfkh5BQt2aa5gp1NjBmIg9uPnhHHTVGm64uNxvG05xyj2PDhjYnIh7vhP7tiWtsESthDnfRU+bVaA/OTfQnf+j5YFK2KXMXq87FcG3yjZ10vLM59KgiepdFryQHUypkNG9NEz8tMUp6lBXUgeOaY2TTuvvlg9KgJOwQix3HUKZjva/HI7rCqN7wS9dlhummLenL3LYtxBVmXW3xbjvNWfFHmAQNtiM7NAC5Hm37I8vHywnB2OaxcuaI6Jy8x3+i1AW+io1Gq2aDuIvSzLLvkaFF456fiFzXuoeYQshvCVsZDNVtmHpHI9v4Qnh3KokGVUctxglmWNza0U1W0FklDsV66fciurBH7SnYK+wGJMsU7Q9ccev9oq6cws2lxcjv+rXvAzQ3j26za3RNnJ0BtrjelvjQjH+l1GnyKHEOC11Zm3eN6ROb42AaPZp9jj2FUVc8pmjvlOeRcUElRlRHPMdOo4lJ3U3Cq93KjcbKSD6Iyp9SuUgru6gyDZknkPE0PFIAnekUpyy5My0COwaumrnlqpn8yPkD5fyPha5T7y4X2yCNShmVRU2Bgp+ZlHUlGA1ekhmca8UVE10kLO4HaSBlWlE1nCI/rTjUUv1chxXUpbjXAH7HcI7upSbnuKkoGyRQiUe9ibbMVFvab2X5wopdHUScWeUKzObgT3/9486zjUriFTE2PxIzv9tKM4zdsvBQvk4CvHpx9taUeXwxBJgxNYbOUbIFH2zw5Wccn02QZxjvBL2K6koD6ZruqMsM1mqCF8psNfLFhI7k245N5+j9lhUoA+qgKNEaAlXptEPqsyRkO2kXCOtF1EQG3/czLOVtSB9FxPqakPfPRseD2KRFu7Foq+VsVFq2WGqaFzSFaUznei7NE4W+P7a2NWJd9kGwnSNQlEp7FLODJAIs0/z4TkVsNTyZwheXfzJVPZEJ1Rm9fXpGck2dJZAYIaUSWAE5h0bJ5yDjreDq0V50eL7Z3p/xxxCw/APC2H7oUZZk2qLMVgNBJq4YBasoEapV16GJuIFO+yQ/CvzENf5m7kY67kbStqSrEtythAWPRWPnf69e0gGuuKtbMasig85KHCeNd35jpuklDpLm7k45z6tZ/sr9Yhg6W73hcrjta/Km3/fntLxvXXeDlkfLprU8zjwUCo64KcYo72lndyw8T8Hc5rQBLmmRLUQwf7/tpigMvMpGUajTEE6iRzWxbIe5nPmNOVTjDzj1BZOJgYeoyfAhI5H+QsztF3qkrE4DB+OI3HIYeecbKCc0SsHxpBEebSpuMNza7bbN/FT2s9AabAihe3pUcbZ7qHg24hq5ahbah4UKbOyw86OGaphb7GfExvYWyZgYZw6E33uEh05vFEsAqwQjJyFLoPmQFhfGRmPGwgStfNdGC6NPk29D7zoNaB22+a7i0iKzV9zqn08FDpK7jfrMAdOwfu3nu9w/Y+7+2VPuuGhE4JbJcKWIKyjeTIhn16bTwguH6XX3nerKzP3PiLvrcioFcbfWe+C2gTkqyWnp8JezC71U03Oq9wIkjVg1sQPLXCJaMmWOuAs+SGgqYhuOKAAXHD5YdIRLGO2htTh/v7/s9C6fyIu/PXYzdOvNR3MoCtzfezgNc4PeXRgTikwFwEjmjrQIfBOFSVgeb7bG9klKY+23qq30MNhwpl4ty4i9gL0gdEO9GDUmQcAkinRyUy50F50Em02A/L5AkZEnpuwKkd8KGWL1tCLjin6e+DxkpSkv0c+39vVXu/fDdTU6KrnDljIVcVkMfqxOf2U2bHHIZFXHlQPhxQX2te2D9/RCmPbqo6eTdXpaEe7ApppDIJewnlcmqRXnpbK1TtvHH5/4jI+3RnRC5MMZ9Uoueo8bDNBLplRLhGJoh03NcWO74UkvNiSZvqa+L/u+7RFrjxToh0esRlIxpoDF91BmLkNOizFuDVnZuRkB42U2cvODLXoRN9rSLe2uSiruYXnG+tTR6ndCX13mxYhi07nkCxEp2+g08bQhZRiKYhnOfHGWBjZqTQpL8dGzKb4nVengac+n1KVpjnGKx2uBvX/WZJ9p53ymvGoZNQGFTGa7RTh49BMVY4igEhPXWMeTV5nOnJGoRA4v6vkB4MvjThLXhtYV3VChpfO7RBLeiMicZgFjpb6p1Nm1eJghqYAiiUc1Nkg428tDJntkolvdlCKFKm9PdzBbu9XIrZntLad4/msb7JzK657k5OnSpmyegOJJp4rP4sBxyyyrdb+VTYeFEE12HMJBlmcbk35o8pWYQtOS/y6s0FC2F+b8gZywM7vs3YO40UIQIn4vZYO2jA3NU2Wr7lKDiUnhL1y0zCmRQc9uqlCYyo+aOGQO4bRFxs2xEF3Q9Nfg4vyF5PjvZ56HE7c01CiOz938NGt7LdKRPlb0AgccEviQs+iQXy4CgXEs9M8ixKSwzSKMYXsUZ9MSLlrDPd4P7pKCv4l4q2vv3K1OmCsmysWJC4nSZUIXUTB4Ull3IqxPNamwqID9Vxmb7lwbbaGWnGP1q7yVb7JBUEze48+KE/0w/DggJhXnpFXRhn+gSNG4V5DX2sItSxUtA+97sDkr1YXGsyJ6GQKd7lDNN6eFjHxr55seKI+yM1FOFO1dVAomIAlr08SaVzmWF/WfKr92+W5AMefs6HgSF3rjK3eedX5JhbZLoa+nuSl96fL/LQ3LbcqVEAKnwJKXTWCxzCFYiheroTncNXvMhH4L527qnwUAiOIhOAXdyFJ+Bc90VlMURnKgpERci0m+cDhFdrVx44nEIkzlxrOIiK0clmOcVgikFBBUorQ8Iosoq5T53CyPlvvW1e83i3/6Bjf2sSThIXxwkNUd43z2ZfZ/sOuRh7EybigQQoUFEUaof9ZzV+kwKNwWzhrDjymHV3hxO+dx235dC9KeJt+N+m9OgSIiL4mbE610zc6rKFywBftIockpkHJc6NFd5R6DvCk113nU9TndmN3Bg2eW/ojezj/igkwgMDfTVHiFRINdhUpZkfLTXWyJxJ1ISdrKc5+OAnDLXesrtqkyLZoXbZqbcwh3URyuoMG+1gXK3m0lyHnTcSDys+XlOrpQ1FkmRySJWdQpLrdyJ7IceWi2n2lpr1o5LrwvWdIFeIY027sC/yd+f29JJBEgyWozodjcJxtjwNKKP/bNHQ9oYlbX9U5vgxV4Fd9G+5N/PzEqToq/gQhzTCcDyEEml2npTlLvyTDCLLY1R0KjBUygATqF3oJeNlk5VEkzFLap1HMKvYb5sR0tUcVwVUScPi3QecrjUcfds43+CeDmDy3p+aHZusehHcV9K7aMt265ZV5BQeF/UzhhM9nOCIercwDfkhZ68kR7AHEcfEVGNTRdTvMtLVE1vsGE9unATCXvVrqMvCyvKd3kkCL+P5VaJWQo0QjOR9jxQPQkJOTYFvFxYpznOx+GMS/7Wn1Jji7/kio8nrW0fQrnwqUA05ggXblb/jROHn1zng72sI6HlNAsvSVufnxzSoJSCP0JG8QCTVuJtM1WqhL+Ue/2/8raRnP1sttd+bLwXD/BOKOLuZ+23WQd+K/fH4mk89pE/eGKbz6a6D1ta1QQnpSsCWu+7PgOIARq0kWtlLmWIv7oq9zUjdfObknylu7OTnNq+RqmVLKqFqhKnFrcI4GQhZeb5Jhoj265pjPkmUkUlBGZ1zpjPc3VadwbZf5B7INnp72RZ3elF7aYkovP/v5RpM3+mZLlWwHG3dbbV1zszJFDyCOaQl4xP1LEfJ0OtFVoxHE+CwnZy2dDfIU1CbQ5bun3gJcjEmmTdpXlqiy8a91gm8UoX7FnUwnHI2ZGSFcqgLyaPYNbodMrLH1s4S3QV5K0ysiUC488vwTM29twLDP/IAT2N3SxFE7IzW3GFK4IBrsRyG2rv0++GAPL1WOlNEw2lVFGS9X1yVJ1zHA80kEOwL1DeToY+jVAvcim9dHxjRI8Jwbw9kLNSDXq5wtg5zb56ZlpZSdAs2Uzj6dT/Yg9P4NlfHB6tuUBRqcqPO9uS8/jovXfCrP+IWlzG7F5dHBs2zc16hHc4Ucv2oyI5jr52WiyFuC0rcJJCRZnAwG6ufS3VYnEnaz8FIOeOT4G996kcKuiZO1g0ZIn1iVRwPLXQt8/ZjBFFLTEPWndC/dI6TbyJcbHJBSScEMHupYCnDIxIS0CnJRPmCTQEqasvpds39yUbLb+m/3S0uklHbwK38g6n/xEGSFRV43PGKgWY5qiKv5MhjEEvOLEX9Nec9HmO/+/Xl0GLmrtLNtI9R9ZVAeCLfJaT0DuFGnnZFKUEsnbxXmlZxMBr+e8Cks06dQkFzjyo/OEL5jbqUD+AhirzJ1fvz0m99nHxR/NK16SCseT9j9p8Jao/kK8sWNLzULsOjy6rWyKGoi3lkIZ0XQwvwSEDK7NQZrIWOYR1RyBqGLSN28IREW/HzojzUpKU63epW49emRjk/ZDo05lds10Dzkd5p2ChlNMciIURet7VW/rBazQrRfo4zNy3k+akGNU3wBs0dYbqUB5O1GYDI7nLjLKcr5wGUbuIzwRn0E0jrZfH/ReAddsnlOMEXumaoNZUg+XvOO6VAEFVcCQTK4F4ZEXpFLtOPhT1qzhiLKNjCHnG65Rsxw6jt5MJZRFaz7nQtMPecpB+S9hQjY11Wazsyn9F+fYTCFI1YHBy7P5CaSRXSwYanaO6FIvgn38lZ+X/B4P6WQ1ySgODuk4UTofmSsYeRaqFVt6awdfGzEyNI1QbniKLW+haMuM9DIjoAxjTxPBXOwc4SA5Q2xuYrFMI4wM+n9psfF70v/nfTb/WeE8aDYNXFAIJ2/JHJ6ENc23Mu8Ws8TKumeP0MnNeN6YMuYnwuRUwp/NMMlIwu7opuMtLUHdpHrOzeOiNgzIaaCz1nDsmx0LfCOKEglZuhe+P1dad4EGAnpc64MaLtYFLua4U/dztLnDzpcetsmfCgRg+W0KCRurJeRiRLyU8dM941UWW76QZLSuWbtoVp56wB/eX3Z4S4YHgAA5u2T2ALMGJ0NhbyxSF018LabxNsTMFba7+RV8XBX3eyUStlJfHsKqaLy8s1x5pwdi2oeqmY/t1x9wHrCnm2fVzjF4czZ/J+v8zeCY7YZ96wilF89gDbvGDomB9A0LwWmDpd+a1ZmjYg7X+mVc94wVNeyPwe11ScA1Ps7Z2SsX3T89hm2DYdvetiibSNatrN8zGkVqhfOUOX6VBHm+IMICLLAApK+c3hwr6hU5hma2eSrf1vuz/c65sIWOwgyyoseqSrBC+q+gAi3FagsOD2VZZuybsxj6JMaWTyWdoZC9UhSsRGZnJOZ8KrGZk5dXAwoJ2LazM3eNnqI6CEgbuMpf4lLiZT6drWhY3s8zfkNooYhCniyM/92erXR2mFt+7T3mVar9oV2BZIzNMbfZIlm4AkXs2tO1akvfkglpU1IMszJVGfcv4z92ffgi650fLQGt04KmORbuOOTwkVo59I16bw2slr9PK/IRrXdy4EplEp+WTU34SPn3FsLhQU6natj3eDjDKz912FGRPC60XO7G+ZuVcOcnj0pYZnJlXjIr7zyGNpwwpsGiJexk2MqlpXS6LHSPIoiZyc0L66/1c0MttHtohiINTuS8AWaoMjZO2cyLhqKq0mcone1MHlZozgNvLCqeIo+d+9jsH8xJS1Kx/JEnn1+Qg6Pm3E/ubm7JR8QLlTB/60l/JhZa/yvwV2xVaYDpHy0Mhk9FC4iwSOQ65o0z7A8cPIT8HpaS4UEjNHYnL+lB0iIVA8anSFrlAmadf5s5FObzWU7PL0/68IetxrfBTP0TAeC/8It+sHWRkmYcye/YsHzRweb1s8MEqxcY7KaDXYiw+xfDwq5f5jVF5W18SdXtcvUfNdOrqb/9AJ2wn1Hny6LX41niUFpsmRe32uRfn3a5hGEuczpUR8Km4YWMQnjShRec3SrlAwJBVz2ZYV7ZE4k9/haYgdp3pMiSaPaQbQZnohUtJBFTgQxQmqSCGSswO0whC2zowkQ5D+cNpqBX7/NjnhPsPOh9zSXzm4z7aUnI6Ztk/kXr75BXbFfiJTjnYMQoEPFYKw50LvTDx5KpHMqzNNzEQ322H6pMEvpDxS3tSVFGsKSv3fTjtswImDS+nYnjZjbXV7BQmVyWZSDp4kgvouHSmVXEENI6n9AGZZ6fmpiil5kaKsweeWxE3i21YuudHR9b5O9rXtN428LdY50hmgLcpolbTNyUKl6BIKXsGJVBnijOlPHX2lvY635EpfCvEwZoxaMseuPebwmbqltl3q1lDoL9oaLrKkiTGX8j/aslu/X6DlIF4wbnNlT7nuYOrWA2VeGUYz0i2UQjzT55j8bqKT/5XhdxZp17hYQKyepiebsYoi7e8UWcuPg3czl7KVGm1m39bs5/U445tUZj9XonszVaB6m5S7mTLytCtaYBMKeD4uZT966jg6xo+G0UbnhJ1wpVepo24GXyoWxEYGHHsIlL9Wjke7oH7f1tM/eRz/8Db80EmLeZRyaatbaMWeuYlxr+m4rIqvJa1+pzr+Hd6mJ8dun8s07lp4qq3aE012c0kP2NZrR54/kWidAQoQjgmLAtCi/bGJ53DR8Z41RG0ImmV8LVDVlssTHsUt1mOfmxn0O0GMLzJ46M9sjhdgLCuYLexWr1bdLwrd3cBFCy+NqvZvPoGUWLVbDsMuo58t9ZEhVmhSXZ+Tbb3xDPtyWsqYdimKlsn46y0Kg9AR7MjNqHJPiyJmAWLpzSBX3PpvftI3K3QQxp9ptx9WeNVzle2PDT8Hk1Pa4E43YedX9ZNN8C1/YCw/pd0fv7c2Osp5iY/WdmFrFg6G0gFYOI3cJgrWHw381mmUYzneurVvvl4LAJTwKEfnNs8kUp5VXv3KTXDm5KOs8B1aTD0tBlhqGMIqdDiWp8KRt6WafrZWN224wSIztMrjBnxzh2xuw9jedrLQ3xOTP/QUn8++fbgcDW5e7tYDX5QzaUvglFYRIAu5hS/CoWlpLKeWUG+T3FhOtPIycU2ziLW+qB/vHSAko51QVEpkEW9HGPGw10RjrTQx4/8By5pNEsD/L5qmRBTDLLdpGB8akpV3eXay/HrbeezITpcKX5ss+vNzPhezs5qqqNg2OjsdnN8aMLdqkGuFq0l+2FepW6Bil3Jh+BQQFTh4/T30o5NxSbtwL/IZkgL12vvgME0KztdpYOYXVrzICH//g6Iuox7P5leCxZNFDfprNnVkUmQieHDSoZh2yPnkKifd7gLeqjXOIfaos/fYcnL9WeXg/p0lsjUoqxwE5+yJmthxo71OpaSzYvG2v70j5DUeFgMU6InW0h9eJzW4u9ZDeQ7JCdxlKcNmKVzixHEUTyezScHpk5cKV8l2etM5xYybB+RXJpjnZMSWzkfv0ffj3bnJ4TyiMvUDbNuRHi4a7fctx+q1bbO7DmHJVrRlLmPo96ZmObpsYj3cQf0XWLgDSTjcqXD3k/6reaH2PgYeP1LYSXdpfTorEAXZwZtYYolu6u40fvI1ALFNAidpoBwh4jBYJQLST/RE5xJVm1fB5yfRHCH1TrX440frhJl/uR7xZwU9Tm23tH/5eFqMihylZSomot8dyTw0ALaMtBpXS03BRcYjtHzscEvOgwoWKH9CRzokbGvCOAhl/dgZj4IBUQCjeEoMqfbkjR6rL2XYuMSbVeW8g1+OeUasPBhs6W0Mrl/XDQ8OthoPfcHqLLrZH7fqH115+aZ+aSCP8qLFpAmZhaCcs7pwM/Jps5RbUVSMdLrnukkIU92ERCWj7CpfWQw5IuJMbakemItXRU4x9lxEtQR8qKPf62qTJxOCfGmQ1RVWHJXPCDCQSQq5OBnJEgDVjRxMbI2eOvwA7Wr4C2dlcWo762fOlbLZ/Ep1tc4GpgoDTRonQpDkJla8H01lS2KrJDWxAF3c6viMcOmdhBUoho+dnupMFdbjxhnSEmprnXsVx3hOHh81o1Ita03GD4aaBVJgH6jNzPGaPSIhEUdArmI6El967n8ZBVabii314iGx8G/2+7GvMnrsbj1WW1sLt3zU2favWFU+kNHTMHgy10EiCvXvLOZzLNaWr9uUOGEjGkbUfINlVkp4NsxOa0aohQoRXJSI8kT6zFzo2qNWZ1j3/+dtkY74oFQWaw3Iz1L7KS6us70VX1/IQfrxEo+vG6oUvf2NCd9Ng0H892ywfNRG6nsOsWi6tLNSfleJFVQ+1YpFWJUEb+ZAy38TE2tvaFIZDEPSmS5b3oZE/ZmxNG1VbMeXMJW3LaaENMVEFnVLRUVTKJZWStgroHkm3t8Sduxo3Lf+1wpsuk2yPgikln0+vcXuLDSqBi8/fobblKl4EfcE83ISePiM3wYvc7yaadiCEmbYl3zJKgVidH1S8ZpmrJtVfuKC+tjdt3+p32c4myIildl1KiPWxJs8e2Pxw3XWMOAVu2BW+i5Bl8EwMs8WIPEPdxnqRynnJ5POUT08HoXiLxfwv2z3X+ak3CCbZgmszp/VlhJVwVnoCBUUGT5/3TtkLyiI9DZdYaXYBTFAvOn+lmrKgllzKwEq+9ZHbmJC7aEOLraiD9pYEZ3Lqaby9A0+INZRb5i3Ohs0VI4yasU0wBvJXD44hR+lsakAdxp/782Iz8zdH8m/2zxva8wZuv6ppGHivt/GD01KFsFh3dIaXyjLZhwI8w8Z8a7qpxeb0+SmW6ktoiGZqh3gUBGfl+j8uMfMES6lcYZAIvy6tb8epmJsuFekOBxWN65z8Vq4un4ZjVOaZ/nSrnKc/nu5xSaH6YD13Mx/l998yvv4qBK3zyTqvgC7qQKCzmDHPZnjSVk4Tj89xZqNn6ilu/fcZ6lLBKhzOjDglg9X+XBkgze9kfVJbLn5oeovrVb8iTV1IMLpq+BAJVkM5XBFMQq6sJMMCQlFEBBfORoJ/nG4OLU7n9+iGJU1jP7Uj5F7K3y/xyOVJ48jqUB6qzxuylSOSkgpVbvlCM9v73VVzbt/W5dccMyiV1HdAZX4KCBzW9zy1EVgrk4+9SUYNVmJQGwmA6Olo6upIFHGYif91UFiKBlOr6ovDCHyMT7/J+PGtH4dXyv2SovJhUaN/kiAXCNibF1UyO9Rpo9Sfmlg0CsnGJK6c9HSg29JizWH1LHsz+B1kveAkxxVOGudKzMy66nDwzFIlU6lUUP6mTFLuZPboQASfLWMeznCnUFcwIttBufcmFwGdfFcZ9VJi9Xn7zYxPiS60Q48fTHj9s/TSLvF/kM/rsXrKeQ0VuQMYAi/GkMhK6ckbRA1VGbUX4UNYdw5GENwokwzqe9RG3ILAkJ5C/MTo2xPTZAUQfntfteuOzFp9How+VqrzkG58lLWMX9A8LyMTTNKjmNnqW9IgqPE125Dc1XmpZ7hwqH9Sm8SVM7zcjufL6hDcIocIwYzFAEn1+ocpy8cEz7yTzLkyQk43z36z7ymMy16PhYxM6KF6vcbMim4pyjh9D55nvNN41QoUMg7CvGJ2mmOoBu+4gbgtDciXJZirWTCliA9nZEJ8nXJ5heEkAMmQ0N/VY0NgfUkDk0e3y6GZ7QBbok0XxP6VYJVBhYHvrKKsbvIRCA5wF8z5fS8tTnk4E+Wn4ZxSlkMwwgbBZGdnPblMrb1XJ6C6nVo+Y950KyzJQFIpK7GDNpho5B52BtvNTpRng8F+yM1F0bKLmz3C51sdzPikhRQCQ/qg0xjc9Hy+Qpids5Vfr6l8xsqzqo1Qw4smEt7FurUjnnZHCirVwKKapdJaXU6M2o1UmJ8Kd74hDYZQQaohuszzZHJwU6XEXtiu3SXSy8mLknSFsLGBLCtx3rRoKf8kMncFCeqr4A6A/1XO9HDZH0UTYmX7LH8E2//G9VnBz3G2e3GK0u2iqF97vlc3Ry3jzjgqSg260gPwMkwu+nhwJxR0B6Km+MymqvPvpVgmcgk1mmyiaJfVW5HEl8ng0Q0GbBkIXSw9Jt1xNTGUh3J6eBa0IeCbOkF+f/nnC49qsorBVM/guE/jJ882G/Zu6SfG8kWEcB6SAkYzgF5NK49JRWU+as1lNjZ4ogbX6q6/Fc+OY2JIZqXhmO6Uwi06XucbNDdmSK/fbINlnlM2q2yVapsm+QuEWbUymhJaKYEouT3FxtiUoGc84D4zvry/DecTzkYd+Zr2CYLWHaOsfIMd+S6iYrFa9p6aeS7Blf70ci75qoSWa2ylDHZC6wHpdyZnMClL7arVqVO+4S+TVb71xUmLIvHlBWpOM5MbnatBnC9TNtOSmzwiKg3zd8G7WZgiM3DQElqk5Ob+cCFua9l9XxHnI6wrZ1LFMZPdLlGm7E9/+0JagY1jKXGYTc8fjY/ukSIXNjmNcU8zlCysvq3py+Spz/uo/FG/Td8yPg0NfNEWmyU7zIQvI95b6meCkkZHUIIPzoovOj1BOiLaz71HEkTimI04HiL2S6J6B50va29bSer+M7ds3ld0vTPqTLU9PsYCgzOIg4bpDMgmMQptLD3LFzyaWRZC8JVH6J+grTTwJdx7DmTkCp5s6zfo0M1gTKHUzwRYD2VHJXKgLb5LSBRboidKsfszMkTLdSi4OiSYS63xQCoZdrPmOoyYRvHcecUS9KemmiJXeWbG1j17dbydvzhGZCslp78o0kBigKmRsB6kunIRNeP0cSqkiU5CU1uu1dJPydhBSoZC3REhIje66LzOQN8qAxPByMJmvzfzXgk+1jGCPKL0P4coaVr/du//zoR+fvGYWB5Us8suEeHEwvcei0CN/jFP4qPsfgN5/J3Xz9I/YGjNZWFPAK9Z7g5N4QBcTciLz5c6av22nKUkoV5DZdn0N53xLOma7l9EbyaVbSAHxVcYEKO1biNg5LDYfs6bJOd+w795CkpGM+daSJNd77XgW6Zg0MzGUmfhehagKmQjF7bCYenval47Ch+CVM+R7AB9/OOuc2cz0lU02Hs1cAyO+eL20rm4KjWXyJXtGYlE0cLb09tWQKM1Hz8czbSu0W1cGWbo7vHwJEVkhWRagUkFDv23nc9LiY0WQOR7+8yFR1mHa0x6dCeccCjc9E9zzfPszd/MRLb8+ueX+SR/92Uwo4vA0gsnJINaavF7fF8xWOA1UyT7yYP71T8gUD50hihir2EIsIYVhqiEZYqBRcfd5+I7RQ0hoNciiFuOkO/wnwcyI0aTWRd5doAqce23MgNArrToH2+akufU2ns+1OA3kuHwfIoD24wWqrHQvTZ2k3nBiBLg61QTDhA3xpFWnexX6BMVG0B39tR2t/bY/LRC7V73zxmYJGz+dglFwir2D7KQP2/my9IAtGUbReQnETZ1MNpdwsMK2zTircTZdLfTmheiCZiI17Dbzn4e9HvrCbAJvU2j1XRL/ONdtIQ1ayywOBfNoKa1BozDNZblR0rur9QjqKsSsvHWfZTNRiwxqkdEMPB7D7bGpVt3g/gZwtoCkST285cMUjKVirIezMTmflNnZMVQUMjS78vG44awpzD36jMLk9YwnWkyP34+IN0Bp+8ERvARqo+51OhMTktUMlR6smxrT+l9v85wGEw8uKVkZpMP5Kl/6msdfkBpUgZcpN/eItYLvYXpCmBsrALcGtqbtuA6YdHSsl43mqGHPbMw+KrbNjIxwi0lSskBG4oXoaZ/4497TI2TzPIC/srlP7UXI8o1V0yTQejVv7JJ4S/P0a5m5fGcCkbrNJJNzcbDzHd2qYkU25S9bjdbu+aU8pJsbbe6IYsm+UVO7J5el3w7oTSGnbZ9mlkMwTQYUGZGYOCCaUxLsoKid/ILnLhzJxxKIpL6Xh53sNFm4yhhcvPtIf+DJ0zB4Lrs06rRQPVfJ0ElwxHWY9p/58iolR8G0XuCGlmZQ9slgTTbZz3JjhtMKrKW4VOJ+C+SD/0QQFCJFliBvRMsvxHY80vMMCRXHnLdHZHUzKTmJeL0/WUCGevz6rb2D777xxvbx1KxA4dqshjd75AXBfFF+edhe/CqPHIF26CHbfJ3qvC6fsSltfh07sifCCK2pjaOv2m3jlyl6b0/cHMbLer4zMO0QJawTUMYHYFL3JGiZvJ0LZZazQNBRnzv0PN32xJzD0j2IEvgY95U2fsymOdP3+UGCBcJ2Y4DebB8W1/CsFqgqq7wrTkZ1HCPXpOa0CcF8qysm08bJqn9yKEyZE7ate4rB0sJfq/46HzGxXOaVjA9xTxOTBysuAMBOBMgZJroqHGVaZLq+gg9n61oMun9Gpcei+jzxKzOBALeia+7USM99/08zHgc9/Ubbv+XIlPyb+2fx0yxaOY/ZOJiX0kblRZUwp6vg/PQw7vlWIKtx24+VUtGYjXlk3TeIQiotRUsrpULjtM0t2FkgJd7vDHaz0o4sIqer9HGosc68g+peYm9mmA1bGRfdeMoqmhBifIk/EMS+O5TID0vk5huzQaku9IKL+nai1+t4TRtNgXJvpcXJWBc0IHidRwRCTNoJoaJ3v7MIGy/vpgfvM0Zl2ndPC+sUUyOUf0JmsFHLbM0nERMmPE5NpgUN2Ir5ynk5mKmPC9k/ilyyZ7JyHvK8ttCnkNg6lk+j/okC+U9P54ZAcg+/qpPd0RlIUaFOYjOn0FaUSpOedWLEH9NHpIZcK391OHcq7CJBvZh3+/Y4iTA4ldT08bVdt+VGU2DZbO4gel0Ow+T+gqxfNJCz6RUtkwD0816wlnY8yWk2+j0WVty1fquvxXD9SZCNwuIvjdvp5HqAQDZ8oGFi0MR72JP7KaWolWyu0YAd9clJMTgqj4RoBFyp+tmWHgbTblNpktCZN3ikkGnCr1a+5pXtuNmFjnlLVxazH3O5afMq261EOqGY21rsw4k+QknJg/plTj/tEp6ev7JFqO8cgD8evgcVOkPN7Egc5Ipp2AY85KazGwDya3JAdIUNXLcDeMqXgTXrmTnPu6v9/S73G6xD2KnyvMd5+chtmJWM0Mo2LknuWmEAL3zoE2HuRjWjbNLKHZwV5PEXg1Mu7O5W7xzCIz0ia8Jzo9/XC/JDquN/aPx/WR2t8lFxtVG8pekcN2We9OJw94Qrq2saCxURZscXWbvhoVn9FruOHCJButnGwk+FSuMjb3zMDbee3c/TXEfNqI39Ht53FtZOJlYLBoBKXmHzJRvmmWsg5dHqAW47Tzk/+UDHOvmXvph3T/dN0O6zgMvpo8htU9pvKO32PElpKJkQPYkZhAgAJxP0gS23Maqdqt36vmAWVckpgzIuU4YgB5KFujMW2u1GH8uSk7KFdaMbQ7/QFYqYNZcjsQYfdN++P6vwO2AL2zJ/rNJ+V1mfsD84oGtLRB95eYjcumzp/u16oftv/U2/Kd/2086LPmEzCdiMc7cwZ8vClU4cpBru88jIqD9zE97Bmr68/MrtBNnlJgP0HYTjEutTHqA4/kWXohanWpOWWwIuXJaIyKNGWlZ2SqScQZtaeUASEj2oQ3Y80XUMZqQmHPdIXlXQX0zu9msF9yOaYxGK61K4sf2QraloWrEcZtAx6klnVfnyS7qXCclc2o62+Unah/IQEheg07sfqXmJJ6XcEKWm/DpNz3e43iFXiRJuo2DbPMGOT6EQhzgYy1UhShtzVo7vorQ2LsDBGrr1m9R0zAO/CpDzmN0CtnfewkvkR/4RdlCQxY31dSIo1uSxRw6CqlTL6KetLQWKTBnByufGIXXpo3FhwHoe3fGEqjRyimlRUIy7nKbaUHaqC9UMPYIJgUB70bwd8VlmBPHGOJjP/DC1ICVrMdqb1rde4mnAcWqM0a/R0Ln8RBrK6jdf6K/tj5WxLy32YENwM9B5m399izZ/ma2Fo0aZG7WZsCHFAW4zBbeZjiCrqhAz/6G80tFsvSZBQ7MFmgVVnAO9kxNrqpyl3UlxnWC7hjq5EV58ViYzAtwGYMlmFXJ9UGEHgemJq80ZQeqqd6R/4A25gtvOGXyMDzL5npv1A9bpu8eG7D9X51cJvcorhhj8JOuxrZ4sOWfyLrlFvkqdzgkcMEuZgeV5PemBbadIH4sXtREolpbhOjNZK5tqkE2bz+qs4ArNlGlLKqAF5SUvJKMF+6RKzrlv6nRf4cUytI57HI+R3ZtnYxrJbRrXG9It7VF5y/z4ftkhS8jDflo4obkIB1FMslUnjX3oNWYN8RMa1KZMc9SHlSKqNL/P8y1qc6DYyogKNy94H97aTnLNZ6TSSmBY+IFv1gUXr6DebVuE3Ohb5rgp0+Uil6InKtWRp205mCkr+xGX6wKd1yO6TeOMYopIkRE1pkYt/SyScDarNcuyZeGCXBwWZDXMIpUADimhWG4LJOpW+lYpT2f6xCuy2Pw3vCITcffeIWjh1e5IK0wmFWoILUFDuXsJB6XsT8OCtjqtAlDuZ8/hEqH78vKRhTTfOeR1ND1izhIK0md6CpEzwtgpfsjFB0g/67kXvfDrIY22dDPgWQyD5CLV/V85Bwp709L8kBOIsNFNkPjEkaMDARlLV0oQpsnnrmUjDxwM1mQtm48YUxUaFWuZEN2dgM+1YxcofcXyX6+CKRq8z4vOsUrnvezlo1I5xeJ50PlxI27ZJHd/T0+v31dlTaQeV4JbZvK5mWZ0tn2J2IqNPVKyQE3QlfWoJOeEVkf4ULJl9uu+epGTV/R5XcLv6fVUqcFiaTQatOdm6om4yQalSYXCi95ArDb+ydeYI+tkFl2kxwgJoc2gTDSv5TaInOI5Yty8TFXNcUDKj7H+z43VYzyTbpBnbvBJm/p2csBJyyo5XAPbplteUWl5Gy98lnfaX/W355x05F7CfDKiByQBsbo7ew3rjoPE3vg8h/LLsOZVjomChH7MuwPv2IMa/umCyjsr+4ZbWTk8hWNtLk8NMnuio+Q6V+EV5KbZkRzV+dTpTyp6+unZMddjXvd46GI/NO7Exp0o3XeJ9NEZs+Pk6lcnZymid7xIDifj0Mn1eou2BPautyajlLvVloBLg631yC1MUnjSBSr52r0N5aawiHK+iW5ZkGvtaTaHKO6qizKGiaOwP+6n2R5JN3xg51w+rLA/S9v8zQAa+cOmitp81TbiITEmN0P4nawkaOB0MuacoskTIvDNUHOtr3pw5eRJ/LbaLdqSbkBEKDEZlHWm3M20HOk+RPONDUtO94ZF8cm3XgbFQK82Z20Oc21qZwpR3BlvC+Zy4tR7hLodexSEy7/YyKz3zJv8g6c8+HsZ+hTEgMSM4+CmGd47cTNsT6csQouxYONOdm01/Y2Loc14pkQbSKN0Gdxtbc8Pq5OmG+1WLldhzWQSTuEomc4+TS0EYRoW8E9oycsU7WAhBR5ns9VzpxJBOTDvjiVdGeofLsNEgPofDkhP8Fb+ZGqXaMbPoKPapjDZvjnWTs1w9uQxOzctf6457KzJOyOQe4FHBTfS7aBuwHHEditi/Y/AmDD6qexVKpWKMzabgQyzB5Ja1RyecR/TAu5pOqCSaDhDzxUfL/K6CrtzGybJO+8w7/pDWsBpf5S9kjHk6G2tqIhEESrZxLY6PUz0zOtsT4i5I0eIZ9zGZ6Gx+BU2zfTWFEMbJl2q4EM21fASybDeVdxg6Nx75IQECSfLjMqmpDzwIY3yZzDdyt1OWaQzqtaVSneOcSI2+7wJvzXks/z2UGn89BEParMtsiWTgQ27Q8l6i0geedh1O4nEVKvHOauGIb9IdzbLJ8uqvgMs25hUV5/Ji422bCKeZ1ycUPbnjXFWQ8HZuBka92VF1FtZU9ZutXhGvpdQXjVuu6Tk46OLqesyNBBve+HLIlFvgmOoBgXUTy69f7rU/m//z+uEXzRzHxLYwRfSp8mGTjYkKaVuzTdY1I02IxHlLAS0forPtIeVXJtO+ZCLwxAHg9iRPJUqCl6hgxcJLmO97YxAOz7BRgrI2QcCEy0cxQW39OlC0d0W0m02mC8lL0gFTjfSWqyuANb3I864gseyDOxVWd5sVp6Wp+8NkF4WV6dyucca6GlbDQXBZWtCIySA5mTbMBWWwrh0ZhusK/qIam76g2DWcfeUh1dS9hSdSZojzW7ew1XnFTnMEIOXHkmV03HIk6NaWYWVNnDtmEAPIpA5eksxL2co80gSaGbPlRXsOThWe7zTQ3k3dj79cPVahfDSg6DNdumqEdh+OLlYoAiJ2ZOdt/pKF4WLfJnHoqpaEC2Z8Jqgys/iLXvYrwNk0AD27eCsRMlQoFRXYo8r+96uYpe5c9Xc+Yw58eNs1mYn4aZyeVSF0GnfIq5W5I1NhqDKtPBv8Rqv9tPtyRxPAQymgL1NAU+UbolXLif7nRuZPBWZlGF3ylATGwjS7zkEX1wjvTkmzglv01M+lcMjB222x1h13fi9yalRABlmzg4947LvGdHs4TfeVjj3HcAcedjxulgaLkKR/qrHyHeedRTJ7E+qYEQKAK/vRtTvzeWwmMEqO5ExfKsX8/DFt1HpHqMYQ681VWGgI6j5ag4lVmag4KXnBXwo51iWXCHT7Vq5UtwN5RJIdiSbitCdjYGdQJ2YYhs2h7pNJhqUGa3e2bKVF3HyWAvinMmc+YRcisdxtoliXpxTROPPiHaT1TcrTfacbw+KS/5pv3ce8yZ+rDOOa8VY8BUQyKZmItnofD1mjWgmF3rnxjhSUn56TTQej7mvoNyr8UomMHt4n01gsFmS9UvHA9uTVyYJy3SRtIA/udHMtRFrkmFetUr4jDhcJs4zFDMwh2NjyalzbofzmNdVx+lltp2kPmMK9w9BDEsqzi9oORpAD92KA/LWIGmPaZ4USi3S4Wr5xN8Qh3N56hIf0KcxbodqSbdPVep8OafF9pQ6X81N1y6LrYpEYIndytbdrIhU4CetREfI969l51qqifGM40yN1lU19ykNAWlk5bOJ/k/TcAaKl0lDMIXj3b7wJLUy7TU7Ry/LgsIb9FUg2aMF5PToGilLSoEboXGYthZ0w3KTy6QE6M0Vusk47AMLi49MVZQR6WdqbKV/SvGFLoZdJTJ95DwS6J+FlYD8+TzknR5xhVPv83EzvQsUvxHzvXEab7RBW7gyDF+Lr+IUlyZ5YJ45FnqzPl4iIqSY3vh9xi2TqsveBupjZV9thscOWCiRATkdhiji6VRgTPGjrZR1hel+YY13pZt26nZhiLIyzKA8i8KHVpzn3nvwPPsZwl1ZhdRuXmr/+iPugWf5fZ38myoOF81uXkjl/NDkV+ZB6F8q29ZEF/jrrlsIcycDCUlo69aT7p8tpFqPVAbtXrp5nesRWuaCrt1zONlLOu3KXjfHbzD1F51oSttx3ZP4Hdr0rTgVIXwcqDh1TpMu5UCFeHHquIgrbOcArtr61Tdgyw/76k785zV/q0S/DcUUyqTbjHCsrAfNJ54xEZeocmqC2LSN+pAIyT9oF+tyrWhudHh4MBq0HGflCEuPmlZ/pII3hEo+XyW2ep2t0wZueB5YY4KRH8MVbuSs7SqqYJaZjD5lKCapvkdw4TS0DL7TeFmsnsVP6Oe+jZNs5W1mz+Wx0VbuYp91YeFYerCEiiFubfp4bUi1BJpXZ+oULO2x2/TBM6tD4NIKRA4X0Ux2H3dQI6evVy1d/ZKXi+8kwDdlpWPsScAwOo6yUnoRr1Bm4CU5sAe9y5Tylg4GIkOEGU7iMJoFoe2llMu3D/ibB8eZZawZlQRz7Q3lYjOh2dnpyJVKegFzOc4REViYNDXmSir4v6gwbEAbt0LODp5kgOFgF2W0SJwNqwX4ib1vZ7fnuXGNfpt7NPcbMZnZYyl/dnN+iFmGkvns0RkH6hdUoZFrODCincvhL1YXL+VFu3m/f9KZPKb3TeiVtyquIdNoaGEmjhKRkBsLqEZzXVNMwVIQRpKMz5+c0YyOSr1xAVtRqMKT9ZjKS0pOed2TwWiamOx2ZxKpQ1nYtPuKuRx6yAoj8yIfjha5voyoMx1YZjSV2XOe9pzXOuL4zrFRFXCG7fqdz/Bd2QDP7lV2O5B/cvEslgzyQQxOuE77VomNKhx3hUVHnjbp1aJUzJfN3xD3nmZn0Q+W6X5wzPsuNF+Zik6ZahcEVaYTaYoKI8LFlKrVEJk3NrDI4QtbtRsPtzk4qPQkIynrPj50Ie7HgE4ObBGA28eM7z/zCD8pAml/hPKlCPflRt9SEDCWnxgPRjcuLlPtr2VaWPrEGjjYI476UMtVqwaUPy0jq3ZUipgTLadLV6uK4oGkzQj5G2Xh4QyxI7OkD6lfZSVToeucvTfHter8xbvcqpOdz5TuV+E8UnrsWI830JqjPv+39lmi77cFBAp7Ub7vGlHh8TdVJa3mWJqJisax4F8Tz0ZKCIQB+RN6w+iuODIy3CxsjuxrLfJlIXKIH92gPrVmq9moMeUeNm8NWhZFvqgeSchwp0x8y+ZZ1yC4esin0Gri/GwcmeeSPk85X4M6ME3ngW6ExPWHkUXan24+64WQ1mBl+f0Q5C7+Kot5zJQfaRrh6aQB0Cl9f3UDznpvV0u9weFz3q536Zy1M5X5OrcY7/dYZVFo7NBFthUuTAZ4s0VvilBJVrWpAOpzQmNZ5rYO/tN5slcQiVQZmwswz4/pGOVT3v1vttZshrYISTRei3J2ofJZaOUXO99JOJly+iY8ismWewwXckdteS72T8x/aGcOpFrQayhIt6kh3cl9kjgvnnce4W7FKNGXJxKCu9QWp7fOq+borQEsRYHJFBHn6JCn/GgU0cJAtf717M/TvRUYM95cfnvL2vrz9NRH9ycvGqSqDY57i89QjA/omrqwd6vD0nFjXqTsZxojL7q+la/PWP+MmQzs3HJ1rwgbYULZp93BBQdnii1fXfYCF+Uzs1YdOSLj8KoWdAsFjW0ht+eK99x8s5wfcKAZndZkRWtyrCbjyo6bTOFMxDgrsAd8tvxhZsMLe/08k9v/Rztysl3oTkUKn7JSKmKTUXjjRlYOIl3f13OhaV1Bodqd4kSqK2a5N+gtO+o4tThZ4dvK0OEmW1S+p3NmzlynPVRr3E98ag1IuGjWcoG6IsM1y9xqsrGeLf35lwu6wLgS46YGyumeK7+7hP94OHTcJEyCl77KlFSdA7k1U4L2DpUltvTCLVHQPUi0noe+hOmz0YV9D/lGRKZ1Z9nbvdqN6GzL+5CMxylpKaDZD+P4KpDpoLSleyvcYFlDK8SQdTm5HicKSgu5V/jgqOzZiow0n/rD7ogGyvCX1d5/+Ybl4Tmy59G+ChD5GhnnAJptIyfbyekCS9AXxC89GyY79MIqmqS8EkiujlqC/Ko0jf7ADfBreYjzRcOe1Tb6ScM5KVAmpa/KxZEsklM7qEawUNiVHMx7yF+FquXaZm9e6c2u/YQsj8jnUx64R0W5zveuWlKtP3uXx3LiiIZuCSvDVEM3/fdWeqRKf9EvqwDxfMkzdVYWbeiKq395l+e8dctZzj5JMpojzzoNQm/GNGw1HThlFwex4nGk+VZ8fWpexBWefEbemZmG5KwtBPr28yAx8A9ZXrLV62qlR7rlLegMBSEpH5qO9ne8ht/KwtvT53AWfcs6jIXb4Qw2qURXNWxL67kqEG+ytFYKqVxlKS9v4cpde//+0HSiXk4jyJIMgm2Gz4bDrRz9NaPn3s1dl325Kzp03w5Y5Z1JbduLZRqFLt5oAfIabKlih7nRX4ycr5UIE0+J4d6EtAJs/cYr9U/YAreD5+gvgGgtNhaLecuviq6QXFTk46k3ejYvTyLqNsWsf9LjKeCi7IA3kKHuQVtg+bSf0mbK7NRyZ2+pfpNVPo87z3Pi6LGecwd6jtpPUi5zea6I1HzBG4o1+COXx4mxdPWt+o5P/pl7B3XCIyec/Em5LCXmstOEAZzTXZKdNZ3TpSkISy8PLaCkwC/unWvdMmmmJ4XgRIAyWRBN2VYZBw6lITfPO+WKLz0gyXR+PTtw7Wilu4UvnRKkSJTPIKMrhOsR4LDIay/59vC000xnz5i7jSWZy/D4wq9WpD6uw29G6XDUGXDPPEHQgcXecvFdXNCXFmtoR0Upea75GN7Zs5yvaEYrICRcqspjuPCSu32IFOhG3ssoNZJndqKgOZMyB4wLJ2Vni+BGnDe4ciFnIAmKkZZ3/HT20iy300znC61T26PqGBAWXqzwP0LIKWL7ToZSf92gckmNPHxl+tufLGiTC2JNX+9K0vsK66CUF04KWaMEd5B6efbHJkqK+x1+7O1AhrkDW80wvqEeaujFK1+2Qq6W5Z4aoIygeeFwGCxORljR0Eyd2e551K6bYRhNNSbzJXmyPMqN76UBd1WbL6NlDsPN0beoXifmyTFsMJArrBZbSO0dbvIuHmfiqW9frsTCZqQvmynFEh+a1sDv7nyhLIWTyoiL1UnVKDSkTWwydTKeqPzvz2hZ8+Dql7jwzz/QyXGj1RKDuM0gbu0AqWU4MCPPhynNAJg+Xh51++xR//6k/s//7b//z+tx/6df/+Z+yf/T//7f/9///j/4T/6P//t//H//8//6n/8ZRXN9/0CmUe0Za+CZ9fdw6jCBmBFnUfFRFAAPWWWiq+z1KhBd2bMR+0vIQ7NMlGFbXw4P3i3S0ki1vKC5U3NQxnjS424m/q3cc9Cq7x9qxYF3pOfIs6RNyXTCJhRUy6AbRcodha2l/l9cSu1jKtqf5sFIz/XhCWubkgiEGWAb+3Z210yeAxUmaI31aUcOu76c2qmkrkzz87xTHnZ6BLuXO9h9KHGnB5myRZoAkyNtqcYO/hyn1pW401Sa88wz/XnF2ZPJ0lQswnw0mEyXrpxKJs+OUTy/r49T/m+rF/myuk1EQrzIxFtcF0va2eH581ELIc3u6MI1k6xgnPKUJP7Yll5H/RNd90Qlcs2Y1qUzqA7gkWenYZ5YO5jmzUhhAY3V7AwlZuyQfSyf5a1G8vi0MSKJWXtU+vMIDM6xiMlKkILjEBzFypi1RSPYis94cINLvTAmfzgdJWbvVpJvEqKUAd62d1NeyiVn+GkRpyDbxDou1YgybOLK7reju0IiSGyo5ghUTHZPs2GgtGEW3iBveRSbTzL7KKEmBPOYYV+2cDwol2euPFxTS/OwtK3Ml6vn3Eaahh15lVqZSALVO9yljymiFj7k+r/jtv+WudoZQ2+lgCrkgbyMzej5iLsZQk5sVipONIcYw8XBas5D/gwa6nDVan3zfqS8q7STYjHvW0In4N1asV1ZFsZtXm7n/khxzbsgRlplSbVRcmT8O2SM1xET6PNGMZeig/z1/zoP+cXl2oVtx5f8zoj5LolnsVyTkXixhvMECUrWwjy5iPRYtHQLEf5kveKUSmk1hlCVH01UowWOJ9+I0Hxpx5ngvY31F0+1UpV07a+kpCFGo5SYIlVT6Bw4CKRKYKpaPSjHksZuyzDFCYccgAmvcX+qm7MFoW/nxPzXYv2EhVlsoSZ+u9FN2soKwOoWZ2cQLdRmPFrxB0Q7ap+X1X2HU020a4bPuZs3d+la5HlPjJTPcboMCBc9PuEv6UgCBgJmXQKV/q+A4i3ONhOYBDhscT7Jujw951/JVn56lxKD6HKpyPV7f19X4Yb44WM+fjXltgtZ2OVWZACdgufLm3T32f8YJCxBZ7XAoxaf4oakTs+cFysRKZQVeC94atVBC0JVi/9OG5KZ2Z+u75xm3Jrw6xybcU6Ic+vpkXJWJGjC50Rj1VouWCVomAM0E/HoqQXtYbX8s4X2+e8ML3ugHTLqLsTKqce0uTkuS6z1zpx0YzRHcNur9plf5BjdIe1k83Wl4AAc7RjLOsrwzjf8xkjBUayC2bLRnmy0l0S4zE03n9Ydjaj4YGTLcnV5xjGcaWSkLU6q8xfXaeHCbbKwspf1/P4ojimbT7dSvy2GYcPxqI8Z8XdF+WkTi/e6FYc7telszt1te8yYINRoTQfSv2lhCrNSpeFuueDhEBR5LdYNYJ1SYiDR74zt5wwAKzORqlAo1cHk0tVqJUYjrUYWTNEd8g6ziaYerFsCnoFT+8z77wBQVlcH+5f8++PE2G4M859O/DkdNzfNYvW3KNAnlvxzam6vAStlqWFkjHULiuVMRbd03832iSyjzpsdUC5QF5QNc67lsqTcMBK0BJxEivEZT03GVW6wQpFSslvrku9tq9ZZZcmawRhnKK8GVcb5lmjgH4GUDKHvreB4n26Ub1DykVFtbVT4gC/0stLbO2Pmypi5difICXah73kThgJl7FcZMPkeHpXHudHHTUDc+87xrDnsC1LCdE9CZ7oliTpPygpZBieAAA7CZmRebOV2bqGLKpzxU1qcNTiuh3GFUCq171ehoi76nArxcMePYx4Ep70w4xPfVEZBUBQ0noKFjX58MiOdxZicSf7CxkKdvrT/yRs8nz01Z4NJGOnBTFw2bw/168mqrkI5V9AxJArjOsxocLYw4/LG6WJhNNqumpxCcciQikM75LHzJVmkyo3aHmOjsz+SMLG9sxva9yHjm6HMRkJmWPCmKl6R4w4MWxvwwZs+8BQvAA4bgdcIGP4X77JIfo04ulTCDxF+y6LUqBboEaQAg7z4G6W/HyPofg9L5QNVRT0lzZWzS9BFKpAzdFWkShuKYo4yuZ9n3B/qAcNtR33Sr/OPQUaaCN4rFIqKVYIXtf3e9mWgcONab1L0cDdWbRqYFB9Qwtnb1/YZ8kWb6g38veC77NdudtgIuC9idrKMKONelUjrLP1ouitGxEo/UcXpwt1duKILF0Phn1nYuCgYKBNvfok1thAJZyRUny7LJavUwdU/juT+2xj335QV0oZHupFe5CMVkV1vOMpXe9CEiKJjYR0ugoqgArV/1X1UvugTmqhYPEPCN0QvE8NU2TcSqjBTbivGaZuaOvKtknJ6qLgz9fWQAxCOu+priaAUmrjBf55AADgq7L/YM/z6dp0nPB8cUKs9Lfb0E442r/4AOD76W6I4Zq0JPlbC+z7cr8rnWCX6zOEy6C6QFuPCUxS8cl8mzcDEmHBliS8MFcoSz8uk246h2NtsHl6DW9w4VSvF8zUp3ry0RWQWKKuNol2ksC6nGhi/sSLemk17zoI2yXmr2m09YH53pMn+jOPwbRzoCnz+FlGHDWDj4J2akhFiVobt0qqOC4ObIkYGXRan+Gdd4DmbYSxrMSVosEaaVf5V/QErPCSY41qzi6XhW9v4wRXPNbjW5GLt6CsWg7mK6WjSKS6UnJneA3j3Sf9CSMltzamiZWBEfwq6mv5/5s4lR46k2c5zAdpJQ3Dztw+vFqDx1QK0Au0fUNl3zCM8sopNViUvoAnZ+B/NYmSkuz3O+U4MLtKDSWLtLjT+5DH/7//zf195XDIA9i0RZ4K52A8tztDJCDkOjxo5hjNv1jSY8rBBSPq+nkEQg6XuhV2dbb/aqDHd08NweQlCBxZNUTPCMee2w6NSTDq81a8bNle2egZdUWnBiMnAJHzeoVO5bSG+Mr7axt46cLVXexD0rYQm/3VY/xMlwVFrcD6++oQN7bhXdJzFi9HhYvE/EQHNFqS/aSEU6IJWIimy+px4uvcBA5X1Wy1j+cYQDCDkIjRm5vlKbK5lT5kpcbqGl9jWet5JYGhpuuxcdqOP9TJk2vKFU74pH2Ts6MArmdUPjx0GOouGF/Fer4cm9IeBSNpjP1RIc0XKtT8MusIBaCskyRbLillj5SZxdvpVQdcQXzaEHI1BavBpefmvEeZoW58sQV5FD6Pg8k0RHqCkjGJtstleWrgSIF85qUvfwZU98la6aAO8zpkla1eRUZkb+wMuj+VTTOJ8cvpaa7yT48XY8FtztT/4xf6/+MWf4aMwVi2BiPmFh/FzZVF7AejY/tqLUrvtCAPRVJNfmlJ4pds+0nklfBciFf5MzwXTkkKgbby1iucRuD4TDkpJHjLvseyWAUfjingxy0Zi9ACMtnKzGvIIEUYGKGUrVtE173rYonbTOIhtk17VfmTOmW8i8WCfyQ/W36ZOtsN6dkQSHMbKuiKSQEesxDwVH2vUrD00GW3f7vKXJw1pg8HMPdcJTTKamkEhZ9pY6fnTj2SWqEUe4nrLDIRTbcxIEkCDNG53fOf5S7k1xz2C6xBgFus/5R5pzilwURWqncd94zG6dqZ+JPRXydxbEcEQIRcTzMWoJiKYmQOELrEFX3wAZR443n1CubYWiKbKfhkZcwYCy2Mmv06robDouum2d2fxotcLGI9nPrbVW5co8bQIiIJg974d72iRtBBQnBTK8qLsdl/+g/D7+KePZ7wDKodsq7rWXM/8hdb2x4cHb839Kk+euD/HFRGWi9jKuvaStEYEc+OWbjgMlqi1CPmqdg5POnC+re8TxkCoWTSgsLsh7DSEnae20NROdCwl79jnvCt07cAo1SL7kUnoQFmRRchnup3bhp5xCIpXizRsaFTfTgTzM1fx6Vkt35wdz/Ii+qQuq0zdpF6p6GwTClsdtCYwLYbVzAYeehdHKdd0qFnKLduaUfz2FZntBWufmKguS2f24fWD3kYK4dx2gDgyQu0FKuOQymijYpuvjJRCK6fYNMm5+G9zOZRBOd5qiT1bqG39+eYjvaTMUCKOM1Xq8zLvO+GVUi2j3Z4l/GEKTo+oMga5DTFrOsLhFHQzGOAvfS9/mfA3OCkav9Z+M1RDtZxvnaeGbKJiiD+rwZpRqyXGQkpzKHXj2HFWG8OLcPkmcaBIqnTPt7hmUNr9+OG78PHH+uN9VGkhFLfyaj/7j7cyj1Ik0+xF0xzbRcLLMiBMjBRxhbKG5RK9bOauN26rpQOPkKnH2H4QBRZh8JtY0kok8rQVQ3kN4qeyG+rdxhnqNmMoNJhIzXWfDYvRm+YXSeF+NNELxk7ikrN8FxbeRymZzjU1H//kz/ky+hERulTLuWT+06WXvnlQDHHZxR/ZUnCpac916dikpqpGX7hUBsrGKoKOGTZQeqnghEWmIut4c4ODT3sWgCcelmtRQIaudptPR4/0uYL0qNBoXolzVdhFi3zszDWZcewEBXPSOfEvZohPMYKXR+VEa1d0O5eBHxQVh0G96S4/dFG+yNyebnZKssUifTFOiyky39beg14jllNS4Hjb8lWGkob79TlzkzZ13qq3rtAMnJo9Hee0hLU1tMsRpyjbY+G8grxcwfRVBTDvtXVbgUgMNDBRkBmZU8zlNg64QVSdsrG5VGgHgurAoG8W7LjeInyztxOlxhmpyIJ41XjEbiZBx6A3UjGnFWF3Idky8+hzjpAbnxiJBGuvRwZqZQ0gZNoeSshiBje147CdS4kAseIxqzVoiAmI56o3NarzUBPvs9IdlIZUEO0a/VLm0RY0Ll0SwyldHvJQR1L5k55XQJrPjgLx4l+xkwZsP1mLnM4/6B+LWlTV22KmqYw55eP0EpyKiBBmwCj5iXhcNuP0g7CXQgR3mNJwBHelDUgyV5ggbblbhMghj6srtIWJsb1Sgzu1QxGmjw96if4LNCBdeX9qPVaELtZ16ZsqA3rH9Ne6l0+eXNnbOgEv4hZZPeHsq/9s7vbVvII58rP7q7FWTWAGDNtwVRHNZs+7N1I9u4owhFzaHhd6bfvss5zjkF5I5HkdJvJN8v5JWdfZlkTmFxTVaGtS4PqE1ykjMq4aY+zKdaotek2blj2D9HqZH/CHaWgPH5iFX08PDuVSWCjFwHWI1PJbUedvAYlPJKJARnNHtCKC0ESurwhJTswc1gyoXviIFVevKcRzIjeoAgaL0mG3n74zoYwhcqHmI5E9uhT+k8buOXIc2OhcuSWJUzrT8FdyvBQqpnBRv/rotq6hh6+qhBXghjdGIm559gn+zrVsyjwK4HVODzNgeZesM2pQ/LxP4RVdlAcLVPqcIaSdFr1bo4KtKTIHMuavQi3iUi92n8/A4YuqOmvkkQ86hb4iCE+cDK2+JoFsncmwsf8fPOUs9jLjJM2KG5A0zTyTrK/qBcuGurN6FyZfYW7ifYnv4PtHKQV2oKUynCUEn+1cR80fbbG/0h0afcRk1S4yhhbL2sUpfb2I0z4DeZwlXVejpV7F+q+SCAQnUgSD9qmS63fBQ8rWK236b9Nekb20awgH/7xjYMaKGJgIqVHAu9Rniv/AEu1fBLEzaLgRLApGKX0nD3nLXrzY885KLp7jtKa+/joo+w+1s5QEA0lT59m2FTys0KPRu5Ja6BO9QNP+kbyz5iCE9rYJZEw1ygg1W+MbPtOdaDttzyREuVfWnTIqdbwKSiuCmMnbNwFNega2z+CkmeVzp/VnYoj5k0AVrsFeH0K4Oz+jfaZv/bgTHGhXj5kGCoFie+OkVR/OgIFuSMHXjSiexgaisnkuM47njs1r+oucb3yfV+E7jK5p7afcP41A6z0CVaUuDV0Tl4v9kqHnFWhiSbKlBKRyx2xIntFL8DMyh1aGRvfxmRQ+k1TupKPSpUL0p90Oqs4ZS76+MwP97XhujXM814MovhgtLk6C2cP4IURLoj1sNeRRWWY/8EDG4G296DvZyg2poPHtDN7eoUkGW/Ag8JRgF2nEP8t9MouRNCCiDDtyu9YtzyiczB2j8JDnzEK1GOHa2kbFceLejbj9TrkyychJv7003v/5z//6zx8Om0s95RjSQ8pzrmEGjrmKLKiMMDIKVeIHngIflFldYt7osyV/pZ4r1XmvVBU/kNO9rS5pg42oIdsMLPHHDxCIHaT/Api7WW/iokGeMDXCUNpLENkRX2jgybGSWO+VSyaX0dFiIfZNVb8hzP5CN6H7moRyV5Ex3gO4N6H8b8sw1XODx2jER8l+ZrYDeVp0dMNCbFSFE1ciLgIVDWweT3qk2wFv9XDAE1RnzD9MgEvR0PrOLzD2WOy3wlPCyLtR/AX9kwa7UtHXFC+FXu+JRyvTfyQGSlV7KAKdoR37K70z6SCterPrk1FEPa8zu/SGNLz/Ci4+g7qqEk8RXr4xlGryIsKgwnWX1E4UjhSIL0LSmHRf4aw97QOFYfvA6DHAFl9BrWV/xTpdUlBx+eQjOFD0V1YpISDgBpRirBKbrazLzBuReziJpR1Z+l54G75D6Wb+N7TRD1QCA53CYkK7OM8GZE2lxXVUiN02NUqJWYIQKTmHWeYikW/1X+6o1MzZzZQT6UzTwDq2qvYSdqoj3/PnnkJbuxSzAZmxwQjrQsMoZY5Xtq2gj5pFQol/ZJKH+8wVrAneYsnDx1ly+Iuu6X5k1/1L5sN3X+U7wmRhn1scc4sv3MKvO7mvZ76TEhuVaGG4mRFYZYXNrJABylxyZ8RUi0nsUI+gKR5PemAy6StWrSIKSBudUniyIpYVontFmVopruOgYNNVmSMWyCSFyqiUKLe1gtdRrZy05MN/16B+3LX+sM90tBuBPf8eW9XdbOMMzp6UGlVCZrarjWehIzKD0qpzGyBa9LIai3mH6P/lCxKmk39xjS06X/TJPrCwOZExTQFLFa2LjU1F43OtojjkfQ3U28ve10a946vOKBEj82q3L0UYhBmJpsY3ZoXnyBcqO/qoSkOw6FD81V7nRfj27nUyeDiEG+y2l2iJdYdsyGG+QvXjlw/ollo2Tda2NA3R0QotwX06eyF9RZXb/VJLCLpGiPx7CehOZl6k27ZxWCSYVmnE6xwpw6JKSCSJGV6lT6bCMLy0VkJeJPGnDhTd18Yj97XKDujhrbYcM9L8xGD/AarktyqZBx3Nh6TaYlElhAGCNdyoschbvNimgrVtdXbTcgiv3XwppBVBo6GSrXvcnzk0Kkeyoa9PcpUIOAnir9St2AD5e61fhTMadU+pe2TYTcW2AlicrLvL3rEZja/xvzGiO/0z8N77SujRaa3WsOcnRj+9qejK7Ar/tqIrSakPJwZrK8Rm6j7YXvSOlCZMUjXEbttnzDgbXYIxNkmXxfsGb9wiHM6rev1yR4lxPIxH4+fGnRS/f4YlfmtM9F0KCefE63T0453UFanE8rGp9cYOQ7AJd2SLY1oJKfgFmxlPf6S8QJ9s3JmN2VMdsRyUKmONSPmMKB75LXqkm1QGTVrvtLLzhi0Uir3elNBJEIdQBzq1i6B1aDmWJqOYJLIXIHPbLLX8zrH8zqdDbb45hXZ/bKmfkHRN+tpNjBLJvs7N/daePwVNXfZR454Kh4S9MBwSpsLFsWFpz0SJEe3IxTpTtAbrosmuV4IHfQm9gi9eggM6uQOn1rED67Y47gjJCxPbhcpkyGsJ073qCKEjb94uLu8PH/kxXSpyLzo/lx8/VuqLjHXYWXEM1xpOqQHwVH4l313kDXpji2jzdpvPqD7aP/Tsj2n/vFCUvHl9RXMjPKivZ1g7xg5LHiIJ1alBKodEvNls1UoOi3xam+03gr0qXOUgw2dBz1gg54eyZB3lwU9bcRc4i2TnnEzCN3S0+Lr/VXGb35iOMgpmRPoXz2chyFmz6CjVdNKP3H5FmaNMINQVMAH6fkxCx7E+r2O9XWd7uQ74vH9wW9dRzy/Ef/iRsFNMmnI1RMJQFG55RLCWb6c93LWbliRAuBed6OKenTIfMh8Ql1KA34J3RKGQhhDC1MApuAkS15jP9zQh1chrO3VqpLwLVVJ4Tzv5UkJeVsb7Vg+xJ3/wnHsHxe6klBgl6QSW6zqLSgmh2Vd/a+czuZ9L7uWmFtD38P6Q61m1xQ1YOXV3HdHSX9u5dgZcMgYP9txDDBuuu86mp9EpF9RvWfQosf2Yn3nZ+Ws484zw6pAY9ZvLknGKLPkgO74++BjynTXGx1MbU1qPxuNUZZy4ygrttaQYIfXytQOLEhvKhiVqI0AYzPh9Gy968BVeAjVYKQ9tnNsS+xly5Jzp5zCRVKLl3EpSIotnIELqhLk76yVF8uRqYduoMgcjXcrEMhiNLjKOR3et+b0gc+JADbhEnVCCDnHVbCdNWYxA1wgbXOPf2DBV1xGFsrR7E13M0jtP7ZFtez1xLGamMlJ+Ap5iwKSs6I83xR/zOKAj/6YBfcOGBhTsriI8x49bWYlpPtJHGap9oAhk2XbA8Ngx4NppyhGDs7x9hYIyUZfnfdWtvidtwkG0CLcVKHEhOVo09AVSRiublGGRTF7o/ZKidtkfFuaBa2zGCevzaLRVQCBdM1OhSsh7X1sUww0n105dpyRm9b+U9VdXCASW0IwlvOoNbZSSqiX4yYxBm66q+kfdS6WMuo7cJjWRyKgUf1MJZSynq3o2BC+1bOAen0RGshPZqjARDMWdAXSxHGj8DXyJlEp/q7lNqNxE0/HHrsiHHQ7jlb2Uih9frCdv/K0t4OwnVYDNx8JbOhEXTkDYM2/hS4ndXOMCrMxpNDowDQ30UHN+mRNpNlS3VhyPWmeb1/m+Xx4q1d+aFq0RWMrGsVpX6EQluaktTowCwqqAk4jUAuWz8pSN4fOF3MlX5LDDpwF/jpSOZzxENRNO7Sastt+2gb+xoUHHfLZ4SohBxLZIol7oqVaNcjnZHmdw9Q0QBLk/n+4XFMTcbxfE5J/7RWE2QBqql+mo2wpts7U9LtrwjLWzKATbbz1YfpVp6YQcOBSnxshDwYyDEcZkQlfRKnb6Dz1qO9FbB+Blvc6I3jGivWhm/9Yv9B/kLarwrVf1O76ofu+hRr9K4LJrXo031rPm7deMI/9qlNH8GbZDQzRVsc362Fbbm8l+ogI+EghAB/prStSc0w9buNxbjZ1nQw1ea6gvjXbUDQvKmxv2omOeW/nGVzqWLC1MDxLfVw4Iy1tSi/yntYieLNw3nXRsRXWJ12+M56uoUOL51LhyC59HhHTh8hLsIMyUJcb2bkUbO0jDK06W8/rt8Ez294sJYXOOkQQyjJFvg0kVtn3EHrTvVX3i5l7YZLT6WSi0YYk9kcCbH1BRa80cmoBLH1cUY0kZMcZeWFfILRZBG3nc6UWiccgImBRCjoy8iC4gNShg4K6otg57Mt9XoWAYUPInL/W8aOJ+IIQwrqavJC/vFG7zTCRQOIyxNR3ABLzbGxFhpiih0FVyqTQFHSPMvkP+LNJujz0qioBVN39Efsu9fvL3Xt8apsSRl6Er7nIZKtqPufHoe1KPeOMSLDR5/MadDdGp2YT7Nckw+kZubTuPLX/at0JArj8Z/pxqdozb/Bh6tyEh42rxHiwmZ0qZW3CFFvfQZC45EWqPjcsoLZIWMsi+EEYwRO+feNctHVklDIV62YiMsVsR23AzlN+NZyMbT6ULrHyyFcmISAaVE6NqNMciuHJoK4FQcv3cIxMtTZl8EDcGgstVcsMuqtlAhqE62a/dBxvDvl8nf3PKrMjVT7mW3SKqddDDCBauYJKqzgstcHwOU2IT/5v7Z/o582Rynk/2/crvUZSaMgmU/14p7KZkt2kTYjYGuPdbdmuMnrN+iBRwuYzawAexEv+1W3AbufBQF2NM2xHfUos3Pg87IFL+5ufPPL+vWSXf03s9TppJcSe2uyJJTFHrFwwOs2VBjByKzRJwt0R0cv+0fh0h369tZwGWiFoUlXhR3NUSccgNFFAc5CWSHySei8NbGnbpkuhmGreKSxeVH4kEN7zEzHS1gYjtID2m0dD4Derl3pXH4e96uCa8SnjlMZd/g9n+PlItf6GLmQfhdhF2YpwJuW5AdYlol8qIocy9tIDnjOzkC3biEkWjB1dtQF3rlEgeXrV2mmuOerqsTePhKqgS/7K+qTUKlaXUVvYrxk5lsU1J/EiaeqzrQ0DyY/Lq4pf2B5/8YZcDUDCVE+GjqsN6lfckz3482LcjwSA2KDy2halVKeZDMcv0CxUfSeErW2YECIh1KGZl7p8axhWpBZVfXSKKaKEz0egKNOY73WvENYZIZoRSumqruhGVc96rK3kZE5LsiXmzglyUAbrmW3dUODkmXMKRLjnj4llvEp0b3Lo0z/4jHZenbs9vR/p8DRC2i8nDibao9SblWHCZWwQRdxxRvrjTrAZh0xTKvf4Sn18tDNydNqeRQNHY0jQiM1uOQNbCHblYGFYtNlgbZqapjcVVPsLsCrLKzKvcWFzpGWfqJz9DRpxzymFLMHE9C9Pnk/Bhhp2j06Ka0P+lZ+zzbnrK27NTteaVQNyJD6gQO2MKTiKnqqJwa8zaRrq3V4lFXBKUM0kJ+HSoUAjmEaHlgx4x2iCsch0dWU+RMtjEiKHLzogX0xVdDkIsykQujspctHDNlqsf1+vdsbyNnUMsTyGMmFAmZQ7sMzuw7oQ7/1T/WhG+ZOS/1TLMQAq4RWe4bUDfpA7UXmRatHJZM4XJNFBI5Ja/iBkdfCMmUnJrYT2WyK5BLRGtuCHv1aOtjJEqi71KE3O91YYkaipQm29Wq1urCPDHNRtYwLvtfnJGOluyjStg9+ykAH/OZ5Tg6mFA/gyTeecpl1PdP7gOF/W38PqGdXPVm0be2C8NmuRJNJVx9xhhd3wd58uM2sbRUKIGXViBqnBS6u2VTCWhmayLWGEN5a3k2LlupgxxTYVeplCpF9Q5l6+lXqRFhZkwuDIuSGNqINsFTC9/0PPwqGShx3M9a+/SrjjM/8KgGZcerK/kuyt4XmPEA6wUcjXvtHcwtYUuPJsOc7R4ZXxB3R9XBDenWchN4RHegRwa3yruxPyPqZDsQuxIvxtxdwgclddYSyiGg2eH1iyXmPKkGq1B6MX6DkPhV+HXi1ff2Y5uSPk6WtA8AKO3/f7dfeOjXBmsamqoxTKPvqRNssMW19T/zcA7GB3epFCRCtw3gs+0x4E6QxqEsDAzqe4z0o5VD9YrM7qHv9b6DmWDmlt7PHzBMScEBGPpIJ+CbdJ3JkgyLMxqExRsikWaZlsqT2LPRz7xxM4h+RQaPYIZ+G242ji3ByABJDTvcl7o9UM30HZiUZu7jdOeGk/iTmjmMB/pZX/Os2yibvXg1/QWOKyOGnuV7e9XazPDiK5dohY4I22PkGA9SOUz36+raVTkQWNs0tZNujTuSdOajv3y0DQ236nR9dHe27+jwb7TTMo59sIJLIxjXTvdAuLhwlcYgCNHJdEoCQs0Pu8y2tYIuVGyv4wIK3wqZakoeqbkzZtgAdGprTtlRAdOGRFuMnoKC9HCntfnxrOIo1s3+RVv8uCqkYxsUSGq/jYmWJ3lweT+HCJWdX/UUQb6HPE6OdarTeu9dEdsCAuN+eLHXD22MbNsFj9O92GhM5op8qEKDticwznrY1vtpfNLgpI4P/IqFw2qyr4u0SEFyLkHP8nW9icPFrtAEao+1xx3hNkuVEYo9XzkjVms2FZQYwCtKk4oUce8srprCeHS2LEdLgDiqPlHOqhzMHgUKO8tduWZWkzlJze3fFWd1lapSoVEk9wiU6P37Y2S8CAoKfPr3kbpTOpnFPg6gqCXeKxjRqxBWbFETtDsytpz1bHJNzNIvWHyVnLPioNDD3SWIEhMuSwMMkojYv6fLKiW34+AwUYehz7d5X1xPtsZ7fg7qMRvAzSFD82S/q/gyE8Oh8j3QcYxmUwPeuYBp3Yw1+mKhRpfFNoXUomToPLPVu/YtVYj9rXz72709U3+fnVP5Fq3EZ9L2vdv65tzQPtTyWdIqlJWiKCsqQnw/4Btjthr7pzj6Pj4lP0RP2LXnEMiuoFn+H5el73R0pQvJqt19zdkty90hUG0Aw4dXh7ROnIQ5bQ/HRo+sGwsl5d2WYjaB8fmKLFeWIKc91uLUxCGtBQg+kaacUOPqzVd0KFHDAwKGx0BuZO26TnMlEXA6u2NVE/gY0Iiaa+UQYdkjiPCA1JKCojVx+/lRehk36crTfRwKuCGhKRsVv3UHLEcrIw5CtV0aRHY0wG+NIEQXaa5TdifO8fMDrJKpNB3tDHr9La2M1dpVLTjeexxHhrJkB6seFgyZhnT3FD198hUWvpJ/IOVJs99GbAPKPf0Sns/+fHV8SdrJxolXBVzPQX/9Uc+5S+hBmy1Fi/PrLGrVZE15B/RBE1Td9PE9x+ed2hA2r+IUq8djKzHkj5niQjWnoVTfUfaaImAiMFFNiyq8lwD7T1nlDXG5NfwZViNubT2X77t838BJmeqTsxy1KhCtX281f6k87EcO2Kkv7AEfDsnpaLpb1jdnKTFuzT5Ok2+xlMqrxWZKeGbnQGZ0nK1PrmMjzCl0m//oCTWVSZYkeuYKWn8IXyNJJI6ZkMKyFgkkcNdFUALb28Bmxkt2Jd1fzCLJrzPWIRyHUe0xH7OBc/K2DEpfT22AfMRQfPFeOlbCv8s+PG1eCkbY47yfmophYNXHVghMCasN5i2bcQ17gMKr0vthcbPyTFogzsneIcq31mYRGKxwm1wIlb4M7HeEpyL51Voxb0mZzBt9EVRr82tDdTLzouT+XJkvpJGaW1Kr+VbZxTk/jX0yqLUhwV8SSWy3ja2fHFUKC56MaobTKR7iVemqAcY0QNo05RX1FAFMb0CBloPZVyJ/OgXAZkibCI6jyVLmhtaZaHOnntUWHlxC16CwtK5KCmUOUjWgwLKaS1yhzp22cqG3E88bOdcn3yOFPnoy1S9ObL/oxXwB717EqyFJfTT3mA+gD7vbROVbb7Quk4K0YGApaeQ3Sz2LLWGcb1YkEoWTpy0dtxZilHvJVA6Vi4NL2dHCaKrUOLSRlJxJSJFcpzV42yoHLAFa2JJoQXUUNSnznBEcoqlrJJHtTRcooyWmFiAEkBUK9WdGKnJIpNm7KAUiSB1cKxHdpX1++b72cGRSJE/mmzyDxYEMCPgvgh7myJiWALFmrcpGQClupIMO7d8UV0UBhfGI3UrQIkxiaBURkU85wbFM7WuNPyBdd3zuXVMpyNvgvBepdFo25K1bWHEUvnwZbfyMVCPX61G6pYPkDijx+PgMJ8F/mMRZlvfdNn3HAaLCRPGqIMbMDXL4Ye/2Yki5WNcHUL+1b0LGNLTfb3KUkQYLUli+DnnnS8vQ6hiXjP/bWq3y74xxlh4whU82FswUPKMUadiHAv5df7q1qFAMEaeVamNvm0R5pBcVw/vGOUibTdEvFpjda2xXp/rD3fhnffgM9e8MdhAZpoIlsjEbw9+zddSgLdxMaBQszKJ7erlk5ws04JYvnkc4po3/jkrxHjjEwa2jgEgacDRiCymDWmb/R6fFuXVc0n7EbfJ6OLhlRYXbFXZxpUYPpwS0jJa6x2V4tc3yNN/GNO017i7N2Sm/nxb+6/Qmd7eKq+hi/8TjDCtyl98VF/JSV80pe0hLD18sy+W2fsXb51rOuSPVTbBao/IiPdbZ0tdy7F97iYm9Iuq2KdB7Om68oFXZH8KttAYZwlRkGHW+5wF/MYDbNIpODpK5s40r9cIlFE7Z22HC+egSjuTjtK88p9XVlw1xVKgIyqQdV4UJNmEFEBcmQG2drtcMwOriYHexXk4QwzZ34D8PKqdeFGTzL+sT2jt96YU0AoX46zF9Hwxc4hWhJ/fGxKLr3Bbd8RRyREVrL/R4IvmUoDnVGgwcL+IMbXFciRAuZof5zjmF/rKqUpRac4oeRsKg8RYwkaAy6+SuYIdHegglROWJCbRQEL3rydhbm5T+BKGn8E7aEaqxyLwlE+F5tM2/66rYvUvQrH/hnE+76OA2cWvheb1VwfFy2nxB0dGeTHd+2MsR9hXlWFCeuRXXtpPjdppnKk9mCcXNfxk3ztpyYYwcfoCr0B3GrtiX4+VsEJbCq5UfiE85yCFTro5cfeXIs6RD1jZLk0Fk9N3N75FF2u/9DvaTuTyxgwtzggNr0E7KBjF5mb0KGGNCZ6xPDc8BFjAuy6xWh+i6PDEV5EWr+Yi/0Q7+tx55PxF0cDEcqDMbT0Irp1dWmO6XbVRQyQUQdgpIuw8eETv39E0a6eUNLRLO7xuhorRaDB6iizL8HACHm743ypwxsrytNLmVNxShaVqDPyErZVmWoB4rGGZ2AVj2mxMsIxKWoNgJz/74uNK+FnSCmA7zo8olDczXJcWL2nPc8WlzXVDWzbqt9d7WVHG3hhjc2w1Qq/bLxMOZo5KW1vnjghLKLouXAwJUd1C9qXgy3VwplLfYg2+C6qDi2hGPeJjrAg/x9p/6K0Fdel7FXXNXk7zzSEPftRxkIaXPJnegR9ajHLxQt83GifFLcv3eNWKwmqr4WRh0LGzjy/BGV+6BZFeFHrW0kMg3esWzYgZp6t/xHRD4xmTLlbaFF8O+tSes4tPVO5mF5BRzTKYkJGYw5i6BgavPObY8f2n7pzI88LB8AKlz62FvYfuoto9z4eCQK4hkJvwQhNDzMEYSMRJZQSXtnM5oGxkFA5WpOV/IpwRM1yc7Gz38ayUql62eXBruZRVVcu2FSOQqGhd6owc18nSNKeN/UdEVpRWSFuZVyg9+rqRUjEN8rclr+0VrOuZlyS7qz1cr2NzHX668Nf+/hAJzW2eIExHXkLliw426r6xKDufkrqrUsln5UoqnO+5Ir3wUUvWYuVnyqBS7pFbmrFdCW++MpN2snPCrd/heQ22Sc22DYuyw8X7HMhegykLsAeztzGMkJG+o7fwN4rKX8fxjk1SGHyJtEtfzR4HxttIOg9EKY9AFEoNI7nDuP0WC9FW4hyuot3kAEEYbBtjB6a5ljvaPwe4li0cR2d75Vt2cNGdTZOIUjK8ZkjPyl8RiFUTVPmANDiWL0K+gdQi5aCgP8wIYLKsG4bks256l6Fi9hX1CDLr2MlJ7mVhwfYP4ec+Ez90cvYmBJfh4DFiKzheSSOWvW2A8BSqs6BwbfylFeGw2iYxszYzykJNEL84QhR0V3nsVu68y8xB0hgnJHlk2YxOFnkDLW0fe53HLiD6vLw3BUxVcw5tZEa4aCsin1eP1XRM5NWUXFlAvstr+eDgGj2wEjw+5a7Vn2/+G3/5u9bQiLGwYu91t14i5Ci2Q/cQnOQ4KEW2LwH/+5c0JWm9JBbQJI8TQymh9bCjaMIm80sSlDaF3T5COrSDEb0k75xhX90Ro+R+A2XQuBBbwzeva3C+cD18HCP+iO+oeGr5+K280nfKOzQpe/F0q24modjIA3PDH4o3eUMa0RcVXnipYfWZfEHloPflyXNwPJCCXm7CogDoGvTVTgnea1i+rW51y85t1O5lbVS6qPGVXe1lm59K/Zl39IyHd3D2ZOZ/mdxco/42cGOG981fag6Pdrh8boTMuZmu5Stp1ndGx1STky9+7EuZQk6C5SY9wwAiEFgZHMGDOcKoMXOszB3613T4XsIAq3JceZhLL7lkFLL1KGKQwnnINdFCZnqPlPOxfp23myIoQmJzkBrpBHAkTlyHFIc0h6i0NkHGH3G/ZMw3CskFIfWWCpX0Zlj80jL31q9Q4Q1WIEk44eQP1mTx2y9bJZmoEh5aoBkEREcOpiiudwJ06DZgkQ6upIHm7Ronm93u5NgQpFj4tRVT+aqzWqzygqywbl5dDybulIyL26KLnl+2h4pdnmFKNOoak3ggxdMeZ852Ua6SGxOeA473BPpDMvUXzdDAfCKHrMsB2I+MGcSozjZZ276m0E9p+mik/OQRdavv0wOlyUAqOErASCc6T2WPdpYvisHLTFEGO6jEFbwo7/Jeu0gnVzn0I6INnYtP5ZApK1y+7Yi2DEJEzCTlwGbGS4a3B2+EP+x5MJ1vikw+lnsz6mn74YstN80xY5bnYkN65gjprFQuU393WDAFnFaTZJJigy5tfBr7h+d1RPxHwZMp4J/CRxNEqpWDztMAdlWGrpV1lmtfxj3ZUL7uwp+plF1FhGnh2rAExAXSdwGKqCNknRisN3o4+1t9Bf1whkR8o6bWz53IW6NPhdhGdYd1dzGBXUwsJqv+scLrMNFurXQ7fVLaaaR5S3hcap1ffCdV7pN6RxycICqVkYLLNK7dLLetrOU9ysvGTVrZ8lbmFiHCY2FQsMVcZFYZqCqCt9Ij9HWBNPQvLWNGv439QduJVCsBOXHz419Mi/ZL346ggzp2igTaodlDjJ9GYCgVoVER6Ut6khGm5JiXM0JuL1mDiW+EDFltBHCwQ4S6dtcCyiSe8KgReqqAsotBZXL5oJLLdQdnIossLYq/oQAGtYh1S/IjRIXn7PMABoUff7I/53wIla2EkftRdzT7Syk/g7JYGXR1BPRiCneqSY+fC7NcNNo/H+uHOIX2r7BpKry21yK/M400JicLF1BHczWQsdSxOw3MV9s8SRRS/kdBBhLErmuixJKPccDwIS0jMA2TCreHP9xy9ShPTOgj8e53Y/7fCOLAnRznMgg1HRmF8LuxcfwRY1yihjMArQMH2aIlVxCNn9EvERLchoNdRyTNrIjQTJf+AKBBByPdQd91VTmI2Tr9YyOLqsKyqihYKsEdFY29Do5qm2DHIZK5CI27Wdosokmi3nBNGpzL0dux/esyA/b+eI9ze9t3afZCP+lI4xqzJY8Foz6VjLgpqHnumYPMOm0HbxFOaUwVsiaRn9wNalH62GZubGQh3iq71JB2iT9orY3eQO5dt1sojgl2rYo2b/WeAiyALJXh7kJk63AWC8eivpjD9pYlxfHc95vtxB9aYBcipuesVHKtbwo8ubYXf6fFyHJyuUzq5Nl3KAdAHy85GAtNZTMwS5AMNr/MNB4dd8+3yuUU24u1qGKj25YTrQivr+tOq8gSGCmfmgO7ILCfm0Pc0I9F+wi9oGxxhfNxJfIFfexdIPIhUXz6NjT4mxwTuxjYXdvVPRwtPzRDYQa57z2TmTVjoxQckJp2KSGxxQgnmwDIfnBAA9HJh9XMXkRanaqk8vQiclTbPwrTJmAJ5XCjEh9cbmXumZGY8iOMrPXy7rH3c/tk2t63jTCZ6OQS+a6C6/ssgf4WDCRrnI8/2R/xPM5lU6idiURtT13GDyj7R7+9DiXRgiK7OPsWqUmLdnwxNli0vUrT1AE9Rsg2i8h+2pQi+vwatF8RDeRyAy/ljlLbrlO8rmDTdKyYXR80a+eO26kzlOg5tleNYm9Iqq+xOJ+c+M8ZMYHYzg0zj6UNnlbMgZf6/rxvIdETTHVKBuxn0a93dUHIyEN8OFfoi6uFAq4yEyvwDKMg3dHMk79Bw3eG+ch9B08JQpTIbGkGG/1OWdxHKGLi5KBNUZr8YFVScE0OhkSGBTueGnrpRvMx8j0FbVCCOrVJL1ujzOltjKmNltIs7kS1KdM7lHG5R7wOwRmg345mcLYfig+r9G4a0/XIdu1EdehY9noZKtFk6T9WCG0XIoHGhL6syFp90Rht/3UkHOGPLJojtdshlccR+sOhXUVen7dPSvY/4xWucO+M9igLBMHh3BiNr416yD2c17rkOslwvkbxnwDwgbSdw567q5yD+mX/Y/zFzmRyO3+dV6XIH2rPMSPsqM09ZaiRXJsAPTS+kOzffLIkeUvq1xjJGBrFEuuC2QHMiYwORs+SMTV6yMZXpVHjVBhstUb92EFMyDRUxwbv5xhkLfWASPFn3sOkvPmBZWPh+bqyb/PnXQ7Z8n0bPtDaXzFivnVOM5SbtAHhIKHRHnwFhzaFyhWskUTcr+wYyv+IQhohFRhoje0FflSk97RtNqPcHTn+XVkTpRppNMFf4+kPC+7SlLpTXAgM3Snf4gej9KgoOHzvqp+YmDKeOg9alG1QuRDqBw+5PqYaPZrtUxu+3s/KtDOgQ75gYQT4IoexUkDwEXCYpfkouxRx7LCPewMnacyD93wdxuICKjAo9ZAyN77QbcSoZOCNzCvoM87mkZdVKAE61M4ZkXjDExOlwXlR56ZrsCPIjBzF47Ea4Y1KX0hFs2n/nviDvmIyaUayTmXrr5aS/ANj1I7dHvjYnTjMinOqm9Cr3OL11QsmUaF0WqXENiuPf0lfk5VV2pgmVUy/VTFdqRyoJoZUCzz2ofERTafwGVV7YMSLC3W6Ee6Y6QUnOhn1IhkP59rcYc4qTbUY/bIv1Ghu9IukbReLrn+ilv/kWD5gDeVYCK4RqOEB/q+KcESrEsBnCTiYAJe8AV48olwiStVf8Zf+r+KNUiJvDslXt60qGIGpE+tfncmSeQfC0Vx7vn3ZHQ4ZaKcvtLFxmGSCFfRIYqZdEp+C1IaURkQ2KE2a76qu6DWOixjNzS/f4XcdlPXJ6/tb4RwNq7PXd5nwmfnEh+d/pFzRoCfziplERKY8Z6KQyEkGcUdFjjDSo3diIMQSIW/mMdwwdsB4kSEYjXmdu+Q8Lvmq/ZC5OS5xu5U3hpxfISudg4YOdCEgWWgmFq7wxc28cCws8hsmE99BDvNAlFKH5K7H/TbZjzQs1VkhxTQms9wk/mSB+xvUbffNxk3a5g1/6XMbA/ctN+r2rLFYb9AtGnLQxneq8vkV/v0ZE6ZiAVy/yum7HsplzZLNm8xjHNff5l/UduYUsw2SZnHRJi3oCEGf05yZaa+oATKRtRWpPso4mwxn2tlnD5qBUUPDqxXg5NlXIIvzGCS1HknVXdh/wV+QJChkKGKMe9hXhbIKGT83Yc1BHymwGgo8OxF8Q8rOJwOinHWglxUzveRhilDkF/TfzODuJ9kFAO3CPDlRX04gLVMvXQtF1sybG8DIvFIIFP4KWWQS6cLtjuDWG62c4mm71QYL0pHy9hG+9y6KKHW54kcTTzgJY5nunYmPOyqfNG16HMYtyIOtRiCpEb5kyP+M8Ujky/sbIEjotMMW3HUkuxPxiJF/09w3+MJ/Ujg3ViZphGSg83WvZDgVFDEZM3kYy1sQiH12LEnmQy/aEVx10tI6i42OB6FjwdPErvUo1Hq6GaCFuXFRivmK/l4vaaFMD9v7ClBl0jZgBcslk56ZUzgzJjPPSQm9kJ0OOu7kZcbcYcXzRVE3f+ek/N5bzSrjUJITQ/NxrswVrXYG3CON6FCDPPZXmO4x0Fsjvpg+H3s+blXkVwZxyncFvdY9EFLXnrBlL744hbPCxP5DACVju5h0EYFKF2qcFVNDfFlbOTeELa0lgmcF0DHEuRGx1H0WOstDvhieHlZk+VVP/mObxHl+/CohOtu2+2gFm277uvJiKuSzIgOsViQymVi7LkjRRopEjHVH0igWE7pkxyHa2df2EnKYqUqaIyQmS8YYA/iDozOYdVWm9BHGnSOkxhBZC72oHNhKum6TloPTbnVpp/xx18Ot9i9LV3tDwNjHeTuyflgt0s4rOWFLaiw8C4FUmfeYTj9uYkfvAjkmvi96L3QSCubt8oKMoFl2Se2keqZoXvR7k8jAzvY6Y1NTTpk+U/GTcr+ZRqNsrDDKj8yMKosPv0J8pw33WJIsKox2isJ1xbz2R67dfIhy3yb1l+fUaEDq91rv6lgUjiI1NB2LkW9uPDHx3CuzsbZ2LCKH5GP83OeehWy/am83+SzjT9Eh3jWpG/sM4ca8jBm17de6oEvHctEwDkfiLhr1isSr0J0XRojGvtZMU7vuUzvfpyuA4gp57Y8N7DEN9VXnWybWMq5v+V/9ZdFVjMupQHRKvSyt7XKvjWc4ym1Nu21oL4mvX8W+tq/CXv0JjlM3d58KLyrb/3iniGv9IHsuDroFkmHZ1mPQVxfsER0xeWbulmVYr9unMgP/0SzSoj7x+ZjTXGrQTkWX2laDsq66HNNLaSotpCIdglbnTWvM/Bon/uWukuOyXSRWOBEa+jvxbAtUjW+HwQVEz+o6CH/Um7Rqn1IOLqta/UtqDM/y9j9Z40YBsCfbOA24SjBScolU8CaOy7zs1f/29jbePjczUKDJNzJ5LpV1dMq36bfPmxAnv5liC6vOetmAWYlM5sOJmVlnJSK3qlcqQFbRcGFB0Uuu9tzf6sEXiae8juU1Tryk3870gvZDnOfi67nfZPVeDLBGCsC91G21bQv11gBJ9C2JpmDNff5KZSs0g5S1MYhrwdToFpzmEI6viMq9YquaKHLKklBZkbagvARIxwdBksi0EODLrpwEvMb40LdtzXUK9OUkxo9ll0VNyDN++5SF+UZmq76qJmEa5T1SLH5S6X9RAqcLhJrzH7nSuLlKi8ZgIBCq+/5uer+Ai/FHMkkaDNaLhkhax+ntq1Mqmv0ezq0W4vtDHCTwUEQKqHvhIIhb4NadlQ+D8H0WrC+mbN9A45+vqjuE1ScbrnVflVMnTl7JmUNZ4R+yUnmZKI8a5VUCMWkjBuaKuWhPKcDgxIx8mY1ur+jpvKPYPKKJ/yrDGg9KhbaAeUeyMYfTN6PNOO81rRDmOSF7UfSwIuvAZ5nt0Z5CAfM/sip93B7+jB/puGX9jy1WHidJeTdz//FN1J5gvmsFeKiw8DBaOC8FS1A/mra0nISCAXbOtwGVwdGHKLOfYRpXv0ypFtmASm7mIWZK3Dx26ACUssoUpGgrDXWlaD9EMx7Yzq2kS0qgQinUQeIYx7RiTYpyMZgUXzeE5AQcJBKBrxvsOyS0cNtqyQ/NfU2/N0X9di09LbwiE23IRxtR1s7s0uKZ4XvHvtx5j+WSEsmmIfgtpn3/v6ylB16+PDYOfxsbTL1a2hmB0uXyr7p2H4X1U9XQUoM2RpfGgqmgSBDsuxPj4IYUxFtwI3jkTCX0KlfWHxy411ZJcXa6z+YjELC0nwL3KMaeoYt6r1lTrBzmBmNWnBVFNdDUZP8/TwC/BR9drv92n5WY7YoO1dfmoe5tf9mhiw3P9BW32OpNZFdArtHZFWQrDUjdIH2jwcnItr2t2Ci9Na4bWy36LO+nWeTYZU7jfuS0ilGmUIJ1vMjjfb4IX/OnHQrdgo80gY0465B94yTwYaqaZbA1lGJLx+sxlCCrJfWjmt8Ra4OXeZDRMiA7BrP6OqURufS8GUNI/2NCxJq2A3bpCK0uumerO4J0RC3RJTzpsT8tVNWaAdkIP6VMfkUmEl574Hs7gnhy7UUQj9TkD6zvD97oWWJT2hCueFC5XLvgdAfGDQdGtlhnhL4VS2gFopNxqFEC3aacx2Gh46XqyLhqtd03VDpgkXp9cqYeogbusCvPyjbUVjFi9O8RbJ7DPT84orNuC9Z1hRBk1+d5QqMYEnJF+S8ovtctfiuP/V1+vfMqd95PV6U16xg7U47YMC9+5MVLOUlnmfslXGCLO+qySqi4kUdbiQ5MTK1W3QyW8GRqtsZ4vpZ77aRXec5DtcW0rUgYjJazMox3ax9tYx0BR1IajNB0DWlLYvVh/c7IrW0PMhVtxFrgckJVfNg879g6IS60FIRq+buvk6Pu1fSPpz26+SNJmxdKKLLJ4esFFXN5bdgjEg6agO4dNV+TLIQupITrhZ624H0yVI0t257vLDQp+oOELaDqa2yb6to82rqnNjnc1Ys/dMEEH2s7rYVZhPWQc1REi8y0jjXccFx7QGfGke8UCo8RmFcGsR8Wzvh06Hp+vNe3Kvln08s5lbr5ynnpkVY3iVXpGi5ynlTEN4XKIeP4y5v36oYOTXVeqzotPwtLYZ/tS4HGUPQKmpIpUhEkfez5rxS29CAF8Vth2lt6oF0K36QuiyrGrF53WF6PEWu6aLRjC4l4y7t2IeaP2q5JMTdJkTX4KJt7+RFH+SVW+7wLRUitpLpOqo2PG36miGkYWnukcNKFsL0FPrOUAIdVmfvSvNqTNrYUS+h8cQxX7KD6gdTJjClVPgiKkcDoLCbuht89s/ao9TabdYRwFe97QggnQ1xaO01qhf9kkuHhK1XKHN+0+qPOR1Sx87bUo7TPKPCfojLMuHQObcDYroZ9kBh1nQm93iLo1nMqcqR8S/eXt4F/eOn6OnxTfq7kbgo96pcJG3Nk73FlTgqKMTd1eQRreDAQTnCT0txAEsT0FRBiQdcccXUUf4XtZOYzyRal3tjyOCMWzl+N5I+6HnCdLqpyf8CVbbypUsbwDtPecVwwDhb5YpOV/5TAkOavA9ZtPKUy9hJk7DEYXuEuunlrn8Ncd1Su3DqNs0Qm1ZRDVddQe3tJLCI1+TlZ77Qs7jBIqu4+Nm8VcWeGsm99h+dOoMAYPm3KU8f3ivwkjNtAnOPsaMdSr4tE6/LFT4ONn6/0FLJ5L6npvMWh9TNDCbc86tZiSZyIDNAyuDJx1NXemkZMOSbih+ye1nLJG1j3Uc0BIYtJKA7RZYTRIQU7J/GRzrEBZ3zUZUfFZhK7iiDE7JuW0qLIRxMldyjBg90ptG58XioA2/LH/LC7szvV7/3zg/6fb/AQDycJIwVnopZtayDCekILG5vWW9dWQGxId0uRdsUjzBJRnQlp4p/mqDrCwjDCCKV2u6vFtp2NSw3eqLsjoWTE5xCGM2qSVjfJqIfpvqkoIjx0EdpScVsXlugBS0FPvcEvM42Dkzo1rq/r4dhZ9Sek8G/mo0lvciRJcVxL5amIkKzQOC5Jl0fNmOMolqsz42dyun4VBCNBi1HcDRrvCmKuzW3H3poM1c0SzKa+70PdhCmI7Ath0xwBFM96wJoryZWpVxw4qduFxfx0M2vDqA882B2ti6tyXioYBYgpEsbP+SNt/ncQjd97htfpnUL1ObkfnaLBImuyA5qIAAdWkJEjID7PIG4poSGyb/zW/8pviXVYa+zFWkoUVmV3TUT6S3eU7aGJDBEpxqW53JLnKmMxjeWkpayXaI6rPHMrReAz616JTWTORk1eOFqipfFrlISFT2ForV0hud9rzhsv47WtdtUcG47F+TbxIUxqjUkJMOGYTpwiY8UJI51a/aWMuacnaifHVm/2G28tX0XCSSIJRmegJzuW/J2ZvUnRhGu7w5vgSzRfjUu4UohXtPyBteXjCb4qSHziSlxgNHe2NtdjU7nXHpnybAe/b037ivAnoRytw1S2tvjQOkP7DslKaADYXmoUXfdS+jc7QO/80A9X7GyVPi/2gag0yopGv3ELNgqLCe6s06pkCGw6LpQS2mvsUjMjARuRZqXAOUX4VSJgHCOOcHei7XX1risRP/5Ef875CoM5hQEHmnnUN6mgY51qcdzXC9Xl5Bb3kpgvrBQOkq9FXCi6yql4ikyZ6kcdxd54KfZSuTnBFUvavMzCPMs2I4+xKHVGQUlS1ox7rNFpEIfYr+tOipkYhBMql4F1XppEvzR4hY3hwk1nnFH+Of3GH3S5cp7T5RTOpwe+1nd7xVW+4K/K2MqlOOmgp2i1cBr6JuJr8Wci3cBnLoTe+0nr1drjWcfGJh/MDLWMGOA7LYxtGWQkxyvNb0fQycgpmlSjecn5/iQaK5mpkEWyn9WYj7lD8bAeB6wAfYNZ/Fp42O1QEFiOqi+Pz4Lbn9ssi9pxGF0F7+pkzuSvND1A+BIEuamBGnfjER2wKQvLL7SXBI09PS2c4mXskzkFuVwYV7WCPv6gmq7kTFft+2QA3+SXpvdatJe2F1kULhkbRYTClwiGbco06RFZySvOWpRpWMWfPa94ZzYBOcysPmM4VRr9R+F+L2fHF5MmpSla2U15De+ucfFoCbo2xDcyb3IkhvjR4vfkF7GrrQThpK/tWpGfTVN+u9vGwDiUO1OjKcSEYWm1uHmvxHgtE6vQdJR+i2XigI+26LcMNlCzJxnNTUH+vHd17cfH0PEx8heSRPsvLK0tK9/m+XFkpOVsnQeJ3IPtUqM5qAyZCxiRrNSeFFN6WDGlyI33bNzV6axbOaexiGqP2TcfpvFdsK085f03NIxV2EUWvA1rTxP4gb3rRDPX6WsWLolSt8gHgoVxLMbJoloFE7SfMtya1/aASnpoZT7U7fydqNYhwv/1yieWNQETnQxKMgd63z0lt1MDBli0oEZFajyTdmDajxFrFQsXDYKesaFEsHarnUMXk3fIF88vQv9W6JtEB1SQz2RtYNeFwjlfcKLEsxcNi++D5ejeg4kVZuOBMmHaOjnPet3d0Pcp4flvBIgOuCwTl1lns1HlFybRKwxrKQJCQOOsi/psv6sCK4vvaAtJgK84TKrSyNmDBdyBFWXG8p6pBbPeQyaSxidrxCmaNB3oaCKqWT+Wy659niOr1sqbAighjofJoID3xczM6RB/ZBXauT2WYO8mcwzxl656ZCC4bUqNZ1dVNRLpFMuUwL2FNttAL5tSd5TrhU6ov/Clctk5L4wHO0bACHXuIBwwXNQZ09qIvAWyU9jKqj2v0j6hdW7U3o3VUIYmpTCqxOypMRHpoBKyduQOF0W8799N/78rN3vmG4rrt2RYi3N/Hfe9Q4TvOZKm5grdQcBwEcB8lHuyU05GzgsjZcZXNvqGFNWNhc+/UijoDlRec6cyiWBQi2TLjoeh02JcVIJgigreyhk+OFnkG5hrw+ErqyLdjdhfjBWzsXgMOqvfvxxJnDZcvkR7zZyvjhHwsCnaa31h/vkpysSSJD83y4QQxkrskeItUw4WSYw3ePUUMyK4Qk6xR5oUWF5gPJfnA2HNwGA8GG+HVzDFEkwcuklNnVjdprIhltC7K+idyoSuMLYojJ9LjWwv+W/tlDOhTOlaGDL3FQciWTgMrpVuzv6s2wGJ3zqQrET2z4qx//kOUdsBlgrA7ZHvrEZGlFalPkn72UtYqCvnRMVILeOTLz64cYZjzV4HqxI/y4i5+t7IKINS0RI6UyGQd0ntaNVDoo++qYo7iAG6sEVweW/fiMUUAdBqbFVoi+eltsWDsjCqY/BERaJWJo8H4XnKJT/mGUBl7S423hyFcGwqzWdSwA2ahs7foikuR4WS/lveEKUJeCsQkoTyq0lIh3qy5satlj0D4aF1llYdzFGnA194ABdzaDHyJgPbwcPMLA8zLVVjN65UDmXR9SsURTRDPgcVnGJArIs45WuvPE+LxMVOew0bTl/SvP4w4DIf3LT7PvQINYsRVBJ2UvtsYZYpmwwpckFvsySDNFmqH9bwjhxHtpXO41M2R8MmGTJRBvstRbBB4yNJNOFz3NPqwkBKWshME571MTCKmooZh5Qw+qbX8/2xHkujXPc4hIbLhPaaO0i7B2UxfYYtSgz5n3/6qB9KPV6Fhc5xUfquHMzhtGIT2KjoqszRYu3Tt1uRYiUT14rhvX6BZ01SmKZbtK5xaO27+xRWkGD0KIJFFB7hyzSakTkjfKxYQDSjW6XwyzqwNPKAkuEoyx4XYvM3YVWllis09uNL8fF0j9zspViJ8SlWwnbNbO9PTlcLBtLkLz1BOE0mxNLWaRNVGX1EnCgdsmHSo+wyuanqV1MQ4YrlBu8rpnihGOPxNOw7lWVxZSJaLXR2lUO4lI2R3hutyo2wjpc3r4Af57S7vayzmAlU5VRnHkgX8PHz+qO2Rxd4q9PzQ3Fqb7HhBQQ4WIuZyBTdh6hAFjKyjApyMoeTh0xr66LQDF4pqQzB7Y2Xlrv0G360MAApJkUW2IkFdnAPKDixpO3BpFCJO1CQVt2ENejSZUZWcWVjVhhxFDQlhUFVQTAbowXGW9bCFFvYdFUe9pmlzTs0Jdg79y3p9/fgb4O1h2Z5KKmXFgJEd/ucCc3QlOiL13GQazCwrA+urki8o8Wtsjk8X2nWIx0RZ2/RqmR0TQvXa9fwT9ieckPAYqGuFY1yliiiNWop4xYBd9a/iS9I2kQTo2CW9IozXB4hQohZB3g2/CwXq7UCK1Cv7cLKT4MN+7mg6RGPKzDEwJyZNU6q/jlEilQLeHbBelZSpJ+Nub+qTFnDX3L0g+OA0/V6ZICum06gIIvK5kqwSsubRQBytNAdheBDKvQNsZwWbu6SIuugUpkkfrwC26apT5SRHqhJ1uHthV2pl6JJOFrvV863+Sa1/lxITav0tZ1bixgq1aX4AOKNFmK8xfB4CopG1dBlcsdOXIqcPEfL0unji+j7im9E4dTxeWepUIW/G3c+0LB90sxQmkk8EoHGM1LGGsdeKFVpYlqOoYqP/npghUy0A4Z74erWBTj8cd/x2oaRwcu7etQcI28P/RtgJKrUxXp/sSGaSLcmWIjJC67geEd80aEPNuSuXu9hhxdJP2vKv+cTj4ctma+k2bW9ejlbuaVlU8aPcjzydtO4AzMxtie8RBR4xldUUKhUpMDKx1TOnc9G0JHhika7Jyq0nnM/BtVTkvUsy/JZ3n0Bq/vem81kJ5wYklVTSiy04QFQYyKiRA3hOmPP2nbsEh2waMRjhCv1rqiDK0P/e8uq1Swyoc59O2UH8j3O+wbzvVkIQLTzzmxiFGuR2Qi0ftP3M+qmRCWycoSjZuYswYin3TS+GHIILFgFs4wL+MyYwacd+RkZHxPS/BcmpJZQDSz+tkvdNJOFyck5RjCKtNGe/E0U8eeXFycHUx1VerTh+bW2tnAWNQDxrW0sXdpQDcqwyuizgJYtjEq9qmbEsXiwy273ViALMMUVgJCuOu1chcbSdscdeFC1gOcuzGJyAkiS1MFZ5qFBXWpc1qcdzDtbxXxSzGkQFgPRqagT5b3jUml50/fB/q4Zqy0GN8z9qaey3Bm7IdeoNQ5ndF+RkM2sM2JJt2dZxL+e7tww7RMFvJ0UcboL89GfZ83uUB0nIV3ZrXij3bRPhF7IkL/g7eIH5gGvw+xpvirDLMBla697lZ9r1/M42XUobIy08oUVw2Sc287gOmKPNPFqq5Ke+LDzjLlY1RbglCOsTTbhDRsApmKtiOZWWVeN+7e1HTjIKjFTPUscJZjousqPGkmw/fAl5hRdbOZq8a5x24SMO1Z6IaKUIW/MK5CbTHNlhtUzPXO+nUoz15FKs9CRLnzwi+3mQiEacl+4IUO7JwYSLYcVU6CWRPvbv+RuNFRleWwVqoWIvWrCjWisUnBX5NSq9iZHS9bEkEcv5XyVBoUWPoZ6Ixy1Ff1kUWIDtWNGqZCVykkalFEwMSX1QY1PO6odajyTztfsYa3NP1SJTRBrmovGlF+ud5qYaCjQAl30rUEQrAsXeT0aJVtVfPlXE/8Zmt6J4M7STqRh091LTP+nDBktQo7l8OoW1USQc/mTuzK6S+xYIgYcg5P2rPQDaqf4kSkc8Bb4z85MySVN/mDLoVwaWly59+/RDtr35aYPjAFvx4VpdU4grp1FkTDW3pO28KpVFoMFe5ZsrFkuyiT9hLWv6FMcEppkpxrfgM5OqbMLbCOCBQXw7muzelpAYfN1Lmt/xfY6tqzaXPHNy1yR8vRnyHsaKgnGoKBdz1Bg7/XxOvlDrkcAzS3DO4+K/OaBPLDv3Aeyz0FnIJmbMh54XYUTlmRcJos5N7+JTEADfWK8cPWlZt4MwEUlLGLxVG+YIvM0Uu8Y2odmD5lopY4vfHcipZdkt0LnmIV+pxbKijXGZhBxET22tXLehKkFTRhAbRZanBKXebkrvzEMLqk9yK3vlRfKxl7kYS9MN4vxbPgB0A4NTpPODL3JAtgDdB9JRj2mZsbLsguMQ6ae74TMqhisug2zIEB6C6B5L9t3vrZZWTmSOYJxKtv18BMhcCz8bwrGuiueVGuAwRqg7zegsQOizMbor21KPdEyZspjqy+J85c77oc+IklFrpsv05UsVI8Fxa7rpHc8QSUjTL1CyhGPkUW7hIthtM8vCNiBmvMSPAqs0tJuR/ScSxwhVYeHSGkS5dd7DSNqoJqjLlxd3UkpLVx7Ufrwus8RvLSw25bYz8t+4Zb4j/+TP+p1PWqqEZ74sbTKPyH4PBFqhSiJRe1mdH2KZ50bRtB4Aaq2PgqfFymt/y6lOzwTyp5iRHFZgwarkkFdnJSni81wssOa6W5IMpusPPYCh5LoiupQpOFA47oskp8M/Y60BFMbb3ft61z2ia7mdDvRWKdFVMqNvXp9rLvfYriOISHxy9zIX2WKpIX5PspnJTvmCJGWEWWAr4tLyoKbYfkFmnsNLuY9K7oalOsUUdrukrSDEU6eO8UGqVfDgdrYPjUACnWG2aUgClNFrVylTkm/1DTbrqJbIMx7uQ9zD+uezc6dFaczfouPU+Pus99/3uXL5z0JmzCc4xVSfMNj67PofLs1xQStol7yvwkB2NSiMN9jjQ6/Ju3t7mDSPijkBufvQB4Qrgu2gx3XYCTYNAwcDDgbBU1j4VO5JCvmDw2NagniSrsWvNqg1KDM5h0qnSl1PPbAvRXtnPZHmKOFqunV8Pln5IOTwD+ZGRlrV4+3EHQfKMmkO5ko9H38CVXCxHS2yJgomNxfZqAPa4XCWyf3m0R08iln/EejhakgZLwyTLQjVqJGa9J5k7saFL7gVW81B9HirV6wbGwH35kpu81/EKA6aPYoW6CJzlbPKYa4B75Req5f3w4lxUl2KGUmxjj0MpZuBFCBVbNEpunhpKo1lOidu8aE3vLZTG0vZlrmnqMd7EUOjtJ2HV0iQNrYHcq8PPEj9rYT7hkjqc93bPW6s+AiO7PviYdIIqzxMwP0zAuekXAbwUWWo1PVi9yuLoVOWxiw019RfgoO/GJAJ7P9GhGmtOCjtLUzaQR/qIEAGpCYm8UBWbROGREiDC+xfvFuyx40ae20h1IGW5EPjkCJpXdYXAlWtIZEvZWIm6nIqa/BUlWQo/ziVByNBipmGroolffjaCU4ZG4h0I3ow+mPV8Wf9nZ7+ttc9W7X+er1/AuL7wnsOsbP9COrhgugYsQaDDTy3pWGydLiPEb15a/1c211PGcLsbOfGHOfvEhwZeicnLmLaO6ydkxHizOh1EP+vALNGbG6LQYYshdpId4uY9EWNypFHMoDA0iuBnY08tXurF0pwHLMNfLTwGxvGpiJ+jok0HbjllKNY3vMILBFJhcz4LoZKZk2L1yUkLOHVt/bceGXIYaNtMKJJAHJkOAUnXlH09Doni8XbW67P2ROH5qDxes7wnMh2MSsdySn6M9eSFPXZY02S0BTYF3z17zDdmdbZwt+URrXZ6X5G8/5wahZLFM6oyWBrgajOheWyvuqTLQR5IeizFHG/TIxu/jTP7unU5yNTFGqz5F6UMu2dGovy/NsdOYK822c4Y2pUuXK8BA4IWo4qyfPf7B1GGPnHLdwMbe+jxKdzxSw1vc2S1M5f6evWOP84Ied8Wz9/ZvRUdv5dQ2Lv3oxo1x0fTPvspe/f6LDSOyZ/R0SwqHFtNFbvk9BS2IJDe1fLZJugoQg1OBWcWSqOCW1ef46j8lH/4wGJ/WbcRGKZ7/GHjQpSVPdOFLNPDdVe21gDVmcxjVpXMxLet2dbeznOpf1p9HSXyhDpqIYruFSRtzY0ZEm1u5zRfnbewzkJ/Vm5QhtyNyqClPfukFNrOPZilu/2+8mTbV06GXLZiy8W9rqKkqwlMASthRJSzKKRWdZ9wPvIeKwdGwJFdbed9ijKKVsbnaSdNp+8L6dh775rvLQ5nnqwX76Vn+5IkzRHyrVURqZvlkbFdNU4T2wqbfBXzap7USo7f/SlcOqk+y2rnBU5BWOt8K/q5AvUjAwXqlrZcXnmHtQ+ExZ53NPWRicGJJGo34yXnHjMjH2ngZPeclq76UPFlN+oo8Px590PS7FO4B+febGfxuimTRfueI9uAq7sCn4vzMtXaActbmgpptskg2gotd9GPtCAr1eYuftoXFWmFogR3l4UTpbzGIjBHwE3enqrSuzpGzbVEF/UziRImoepF9mFhNwIgvOQSHJ0XtdoXW7Z5YOXw72dgih/SO5hnd+IB6imfS2iqN/Dvk4Ohlch5mUNj9jR1AKBlWIFixNdneupYIsqClNyl5UMzSWpR0gbs1QS5Da+gp7RicXITH3aDJhsNbRnzcZdY0UnJzKp1Xrrq7HvbbS5Lyiyej4fBNLis74Whklk7NbV2I/oydSGFdS/woM+47KX1qOSXvYSww65h5IdDq4xsZjseUwiXwgY+d6x2KvkKSTD/PQg9Vxj6K7XndGGy3t01kjUmXf8b+pJEBVsMWF8riwKSglAGJLPkJAVo2pbYXZNghRzXAtct4uoYqokS3D0i7WOZUfP54/5/HQREs2o8n27aYtvyfE/rYpL4/UiYJ2l62WEtsmqR7ao8b2cEVZUKiYstbKwI8QIL+6NzcrU1lWikoX80PwNo1DjFa/X6OkHFCrqTR2WmX/HKATVYZ88TmQe1jYTxQoOiWFGyC4EgORNNLzJt+KHyZETyTOkXkJwU7wUvs6deLHGsf1OY1pEO8hzvxMe0qfIrKycY52/nKD9dLSN7PLSmYvmxZO0nHNTqihOqubzkkkF6Nt/HlMYxtCD421R6SkF84p8a2S3dFLmZMry0i69qhDaAMKamNDt6s6vIcF7yHPeT1WLQHYtPnVQuvnY6aqVMT9oFvZWQk52PLak2orWsp+T0oQFRP3fOIb6WOPNI5k2H0vanPVaVDWFb9WAmKjrnxJOLOhEjLglj3HGmNPmJlI+zq23dlLi5nzUAxsvkGPg4NNKF74UrQKQopNcRk+nvMddewSMVoaYrzHPSn1qDF7z13Y2unh1HqCOeRE5z0tusNMbqlXfehI+wqTX1ESj8Sx9WAPPpEHULsVyxa7X9uhx9teqAM7MfUvfQ/1eqBnkm1bANeGxAaxwGHAK9ttJKtrOqDAXUVXBtDKH7FjcGWsmD5bGnZJ7Z6RV+XrjuWHR/RU9vIlm9HElCuxszwsPGFtRpKFUFNeloKLKNcgHSxGNq7yXi/53QqlmWnzwLFZdkwVnfDcmFhzQlxh0Y7okI35snr3DVEB6VFmNCwSQSQmXu58BE7hp8guvQ37haGICAs4GwQf8vizzhda6Zzj2euTzt+1vD11B0ajMpRJuCJabKEdcgUp1CotWJWibdugXC2Snf3uB4BprFqavMlnF64Cph6Imr6HHiNY9fWIIexjg6O3GG8x1xLGWgEiUjuPsgdN+7xOc9vGayAlEp4mdrKe3EchxZL94/zxx1zOxGNTsFjDwX+hwti/hOvtZyCDKhvH19V0WlGCTNSdo+5IkBKpuAo6yhR+qC9y7F3GM/NYuY5aVy3bCiUliXDoNswsrW/tFy+2MUxt1B59BNj6cuknPe5JZ3nFBGw6kJKXOpfk1HHOzbJYWpSyYQFLpfSOlxZv2psfndYOEXm5D+3n9d2aZ33HQDrLXkCrouDjyrOaOchXSoCusqWNuKyabfVuiW35kXE6aV7GzjgVxwlX1yAV9kJtdj4JJdFX22kVkvRslHjCt3wF8xaYtUXFxuSlxlJgPGVDu218ZibnCtfl0i8evTJHO2WkucZsur5m875zTk9sCM+ZKf/RZL0y8CGEfI72pqX43nZxWBk5CGJkoQXKQeU9xI22zw3M8h23X+9hihsCr40dGGYxupJwcbFHm2ilG4YWAWpFhk3gPiutS+HO6AxEkm2xLqNvq6HxkJk2tvcSKHiRt+Omqx0vtY/A77X4elvr38/hx/F2Y1lRBkMlFaAq9JsAF5/uMW9XImynW6zIyAr0L2sR8V3v9xrRWak3Pl0zaxPThkvTWqRZ9xl0ILOd16IUohSGW6W6aSFmlCWzHCw80Wq4OlPdeTsqqGe470UBEnA6cy+OgyMRGIn85KG8LUKwLVS7HIdgNCuT00rZVxSRgyGuchYsXsgqHhJ/m4LpdOxQlKJUttNxKLEuMt3Z96Od4QBqcyukFXPBJCkch/txCi24lP04brSp/4pJJqiOK4ygYm5G0imOuHirWdqmFj8qYk1/2HvFlXajyIDQu6KrCpnxuL+bvuCjlI/TbFHUTqqPKftBCjVvxVbYcFU4Y5ejfYDgGjW0vmnHm/+K1qGUaMTmA6Nyt7ArdwtvjGYr0kabkpA1WKIIbOm2GE5+zS22zI0KuYlliLhcnHrLyr9x8SuRAOIOKk6c4CEfeMx0Tf+fRJT2EEbbDwiPz/F/KS/mWckfqV0nffi0WP4phClRdRXbMl6hB2ecfT7AV7L5CZDot+Q/8kJshyzI5JCjDllp51zAUmkY1SpnRe1xQhmDAEFJOwd30k6x3ibIWfYGkbvX6L4NP4aVyG1hAvHx8/jTtoPWdidtnmbDt72Gpti640rEht+lR4DFMgmiLrzHYXnd2NzaY63UWfn3FBHw7UUrxhfmCtc0kdO5HwVkbwrPWvtlR4rf+NY2WBtXTK8SmrPsbQIxscBdmLRCos7iJbr3vBMCKoYEeFCGZtIQrOO48Iedj8WWs+O12LJ/H3t8R/moF5nZ4qIOu/JLDfGB83b5pvYe+eXyr7a1n60S3fb+kJXLQ1ojVrL+oL7CCjAUCcn+sEnZIFxQ3/5vJl2VeX9Fw1HFbQfb4XB8JYesuCAKxfIljsyUevJ/J9cwdSL1vAN3KQkako8P2B9xORctwjvWR4J9/1kI0VdYMNhci7nLoiucK9z2PqwfYWgdOQS3FX6ED9zHjjbgPOAgTs9p6T6ox8UtVrg0i6w2Q/mu8KYuNU3awAOanQo3uhISWjnM7xX4decpri8F8KC0sBZGlAh0D9ATIOJFO2S29XEx+rOOvqUiNXXu6T8kbByRT/mn12AXM5ore1oEl2WRfbj/EsOOJFxpx+ZBdaa9wMzRb9Qhw17vv7Tbt3Hb7W3t/lDLFJYgvcRJXVh6DaXtSeaUb+ZxL3sSQEBJJBiJ64s52tBUNcEivG8RcheTOuFlfmx8fFH90d6qf7sern5vn06LnzaF8hIvPuE1IqfMM7NUGSxuJv6+hfVAJLQKfy2vBKvEJzbpIQlb13GrvE2eWIOZG0btHrx56zdpd+kYYI4/WhwDsdWZQZ0vzFcMwWjX8cAIWqrpzhkWsUM1KIJszEJi1b2O29nHEtDosHAK/Fdp3j8PmTa6kUqiQit7FYhpvq5wS+aLfcgUxlb4QsbUd09NmP8V05PBpjHqlSA9V4zpAvxQooowUQVxHKe6af4S7jOau5Z+q+2E7rHv2hXw+/BnemGOBg2dJKUJs3T8F3LGZgq5UwhWZVupDxtWSW9zjasaid35Fbbf7tbUvJarZvSQnktdMRXXsXYBt+KwK5DkhvhPX1g2NZ4TdXThZpY/VhGGjX/3QAfWmUlmyJdFyg28BrXdjYfSj5WfLj3CUlxI3lhahc5IWMLAy7KWdP7zhmfTqOGuvF4vP7kF/rGNXPl0VnxPXjCQYhxTZ4o2ZxtzTC7qXt9dCV8AVHByeDSJ0WSMwNguPlTdyZiPwdEYkSYnpftlpx+q7ERdE6AgbfGdjmgGUtEFSi9dwkwYWc19K0v5eCoQ2bJC4T9a0OlshVVaIdTNApM+VSevdPBGq0b7LqR8zJ3fTaSXCfV+m/PcniBhNCzQLVMubEmx6r0FVSk1AXNpFPP5ZO6ASAJLICGSto145HoLlceQjwKvUGG70vWasznRH7QYdta1UQmcCvpS5RbgJGkIGodyqXeAZNJ4jpRil16Jh844dOcjg91YymPpoqDs0VHejoryhoGlP6R2RNAu6NHFbmZ3Q+a/0FhUegRlw6rN6jmCtgmGqJ/cKwJupHZbCwffDSXOCTLjA2gFs1zyc6YXTdGG0q5aCBwqs/+q5bv0GzIW8RkqmFpbxaCFiWIwdw7fDD+WfwH9UedPIg4ZEY9AkB8BBF/cWA8XJ7FZFYthldyOLGWlMQXbh1NMjLSJrcLwhCSh3Zs00s91SrpTOuXolKhRSThN8XA9kiuiQuthpmi0KavfpXNukc8YnCxq+aIsJD6gWKhN1rUN2i6Wjf14USf5jOTji+gP+hGkfAw18ifM6/cHRlwvMtIP2anRIlWVUDMWUlIOTHZuQ2mG+IAyVb8iod379Ixa0ZnRt8qIHbdM81IciSY41Z+wFyywgEYOp2BmVHUhj7Lmx+POF1u8mUnA537JMqgyVmQMiFlFha0llcuLBWdc9XiFp0Qb8yHa6HcQ+JvS/kgW7vVP0tL/9Jeuv6UHa1IIQB8XjAsfwCCv3RuFAnew0SP8YxIj0DlCPpj+hUDB7rqKCE9PV2562o28akhS35G7ExfKFdcOpdHQk/RlzndAxH9Iu0TsE7IumJaLAndSFo0eX1eJgHRzT8K+lAbollw/en8tBkX62Sj7Il6iMYuocYZLNO5CXuYYFStM1biJQXuFpBZlmjYjjEeKwuypd7IyopQMtBUwI9+534PAlTIviiusDaRGOy45sM8bdZkfknL/f/6dF5fKarJNHTUcgctCLF9SLMv8b+MXXnpO5P/9l0KhfXmwZwqXRUGxWNLWCq1tXW6RamWA0LSNbv3Wtkz8+glnV5vH/N0haI7upC1ll8DklZlmpNf3fyR/VwzTzkju6dIZifpVD0v3z1K/zZCkLDqlBRdhMeiSDGPSa0wseKGaQyw0sDWJqVXZSvVfZoltgLZ0WpKKl7SxGaxCGzO3CFdiQNqo4hr7iwZGs3Hrt7p9mfgGM3POQhlZ2IloJtSZAyUmliVvMaIrEgQfTiQVclg8XT5ROWjY8lKmfdvo4/8dUWDlC41t2nN6hBaTR/nxiJvWeSXqqsZCPtBeEnZBz/nKYczHoggyw94zWxgFB67Ky2E8CEMwqtHO55GEHd0o08YopIHTv5vuslH+K3YHne+cNghJ0kTuRrV7DZT/QgEAN+0KSF6ftOPXg347THbgRlgrzD0N3lHfaRsxdpTlQybeFMNayYb7dewBiO4yCI4XMEGyO31p5l2XcSB0ixdaUsTw2RMlOyQmt80t79Evm9S1Y6fU4N7IHGMG8NKQG1kLiXXlp3PBlBBTvNFMM0v77/9tXenI8+VIPgYWuYbk5btttILpFzrtxbRvgi1St9trCFBajRiCsscxsht4kJviaUb5Ek/QqeA6fImeIn5NybDqiAeuQN11IhyvclM0BnSHUJimOwc5H7FiCbuA8lVL2SsCDTIt4tq8hgECWAjicpysnxbrikMeD7DzmTxtR3XxzUg8iVGuzJk6QnR4gdrTuEMBR9/aFsBYypoqINcza4tfTTLHHsQr0wDXzWXlVsbm5Hg2jufEMZwVO4TocJXN/kOvUnsQ+SUKVbyj+ogJ/l15cuopaJEB8rixwO/RERHf0x9vPoTLVgNB4LjL03BZ31LiLyWKPMOmDSePxEQ9bSIuFqUY1Bd0KTW+0JnKaqlGoDewF99DbrfZUs1cR25R8x2vHhZB2jttoYyBvfjDU75YWYIkrpD7gXVXLBRXZPgGCpolmUT6pnuHV8RyzIFmD3bJSuUq3FjMgjBRYsIjRP0N16WCOo5HTRCyhOLCO1Rqi4xuK1KQ2EY0XJBa+DRKsClPWI+p/eNRl3WETrc76GD2UBAM3FFx/bFpk46lES/fUMk0DoCmJBtswJcYMevKG/tQUWI9h0emyzGp1/HQmikKkL8tUUprp01714K/Tb+VL4KtvncYQ0U5ba1NR7PwzmSU+gWhhEDGi34oN5a/NRpnm4EYXvAevuKjzbkJc1o+owZV4mBHMyQ7UEOQcp0MMsIbRdlA5Fj7/RyXOMMieaUYjBRa78u80zDsFNwlknmqjAY9JMIySZrrCpr2dbSDDf+RT/G473K8y+XHDmLGsMdIk7Qm3+GuwLFKyCKYnDbyjVuqH2FVijdKMslAz17PykJHgkZsgTxqW8Lc46Suug6VDkYxnNOW0Sr7BwdgrRF5qKV/xR5fV7y/l5m11Ng8GQM4w2UshpdxnDB59s/Tn3S/WmvAEBgty5lZapc86+dHtDANL5KWtXaQBMrWxWhBjOHBernN2FdUJlyCwyRaV9ebfMpEkVZZQWyRm3A86lZ22q4FhVxL0N73dQju/1LfG/LSXHbwJkaLK/q0SFrLZHOOoBKI++DnNDXyYnJUmCS35A872r7JVk+jttY/i/G/bPv+kKbRn6KIv/OLyUNsV97xZJrjxV5Dh8Hkxj8OfBKa4RCt0jfER9Occv2Sd/AKNF0Fvfn/w/z/wQgVczi3sPFjLH+C8zA0dG3uent2HPdQ7WePUOBrE8+eLkIsorLee4bkFtnm0EmoqgwukFnQslyfrXKakYffBXyHOSjli/BeUQBr5OQIyzVm80eFzAt1HdE2lR98XB+Mgjv9Qa5z7GuhN/a/9Iu+yn6+xR+UKjGJ4K81MXoPRCKyzsSgZ2362AjMR57hdhorTERFr8sjGzq+3FLSb7tTKAjTJlHOsNk0IdjZOnckxsqNH3U3FDN2nIWRUJqbal2CPmnHGGiNUHtNZRT430gMP3KQPABz2RW2gaFsKHHUz6XPk8vvaX6+my+Pi/RXfoYBO0OJYI1QlALdPm+8ch2BBFfAUUIGAJiO0e5eeAwOyqGgQXGo8uHLXEEskNNhYiAReTUpCAJVf3CiUYkWxhSNmm0evBJfk859BKctDedHzVxu/hlScSTdZjIKe7+3s6MhSfmCYu+V5r1Y8saGE6T8V34mk5bikB4y5KjMnYNgUkIkNzCWN9b6rvwDGCAQvP5q4dRmHfEyRMpch4vBUU2xyIrxkdYYqD46S+yG2yKAXkz0K1qhCvn4yh7sugLnlsfBqLhh5lQk1Xbzgv84o2jPOTQkjW7Q07zXDpnGtFMkdfGt1t8jlDPSEcJ5Ehs/8haotKC11xGBPzqMInKHTWq2TXJqyrJCGT5f4qVXvyE8UntmeSnypv6lkNX78QBZqaJIvAKkRw9Ia2yrqUkyHttsAYEJJGuOmTj9j/4MbJzKOnaAvFLpPYRmXbnSkWqwlJnZPk04/ka2Ejyyg360dllHxtek1x0YkHqKTWBli9qoPi0HotWoOLIutqesaNJT8wXvzIJ7205Marug0yEQmxz2A3JoWjfZT6+xvCVC5Kp9ybLc8urqGJmq6vRJdLH+2AdaVPyWZL8cvlbVEXP7SyCh1k/07LzzSe2HztYlsoswi6SRX1RcT6PlWJj8xScIk4kZepJkMCC6StFd4Ij8QomfUBYOcbKZMfnDJoPn0hpWC79aVzAKMs/GOLlh7W4wha+Fl5sENfbAedWoXwI7IasrX9CMYc4E00R2zaxXV2vu/pDH8VY7DUrn+fhKsvwzxXITGOp6l3vavDTUbhN46mRYO/kmT4bAA11rT0GOWezkinB7xQ+99iIP0KxVlhQ7qBqKqu8i8DMgND4EQ8w5MAe6OUfYYwnP+Tc0ojdbirZd8YXC9GS5XrebKtOuGm2lEdhujAqXYmApFG0ehWLR7tW/I59ggH9Dtzwf9LQemNzCPdjozGWUkpprrQg66XwFGvaUShF35y/lyNS53duXGbDk+2mPunGMbEoHkteI6aRoDZ4JJU7nPoiWvUagqTEht0Obb8j59HOsvkNTcsTU1yYF87ZvF1h1/sTXmUaj6ZIXzqdhyt7DlyhQYoG0WVgGIqEbTcPkehyQRBT8IH9ttdhvlBbAWcQQrDg/Jw4q+FXg/UinJvI0yR/FLLRcCBPtvy0MrQFK086brrvnG2oZ0kSSCBMwDe1wOzdlBYbEa4S1wM9IVhTKWP74Hn8843yuVG5tRv5bh4cZ3qeFNSPUn8wulm1K606N9y+zTJZSD/OXaHPnbxWhDI3bML+IuOYuN1JU2OsycOKxaOCYG0PqUHxCD6viwFBWFmadmiCWHiONBTHGX2BZtPniRYSZvlTMtAyshJnGwl5TEnU4NMW7EqTTFz3mC2/xp4yHuaKvdE+aDk2e5xVv57vttpHjfdNzdAfNyGJsJUh1v9iwRJ5jPu5AjuKEA02gh6ZtSz88aYjouhZeaO9r2XKPja4TfEOqcgW2l3Upfn1vS8ejWsglCpDqkJx9tE7+iMvRzjS9x6280rveGd4tJj5rxc1nONBkJWlUdMpPi7xdY34Gx6mNCJszKWuTxhd17unPcVZkuxMbK0LxoYfNI8zlyFFTstLcVmxsLRUlQEVPUNFulhmCfSv3znChBy0jKCYm+Z8OPiojPlZl+5DHMH2vkmPYP4A6y+1Q7QupePoLfFZoO2mFVbWvSBdY1KvZNrih6sftkaqbNSEb618pdDI+Nds68BE424XzZ4kSgHksy3SK6XsgnF2ava7w7uW0GxKkFfJlSRgw107fpmc37X6UvYaVxFV1IYrBY8IzbtdCxS6BlyRHz4CD70sQlWwRFYWi5GY48YQ6zNzkg8K0tQOqULcGBeuBfF+/Mq1ys00Uh50jo/abqT1WDPmveJnZtjp8xUHUqSQW4s6Ugk8ZQzA9PSCuxlBEn7/JEYV4jkyoLsAfQyhf3GAlWbmfmTMaOo+nZ/XaVn3jBf7utGN85tOFXAYuwswbFIcAyHgnlc7l7kroCzZipY+pDkHhOkUHPvZn4D8ZX3UVbRKN062YaA44fBqlYufjnfneqoQPrm0YDK7WQkmduS+D77AlY4LXJG5EickTTezgY+pa2PJhTS+n8+WIUI5VUnvYnnPXG67957fiV+04q5OFcn7hWFjUoJMhxhSEvEYOayZ+OGG3lLHDLyp/6X4djo6kv1FdxQm93e5Sc2nt2+s+oWkAfZOS7mGeSH9TypK8ceXw/gs3X2FqkFfEuJQcIz1jpsC8l/tC6RQKeMx+OR6x0umCxej3U8yocZ+9FYHX52fIg6zyDbBDwz6stleFl+2AI+bzRgb3V1r9PfSo4zZIVKbdhTSricMvcXxkhRoz7ugHUKCvWzAqOV0a25edw2+1qPUUbZwYQi3mRCYuIGtOgwiYNNXw9sV7148PwZ911Hq1XiE1+r1+OsN/WlInRgOHMUIYHqw+ldDjhrhj0Gx0HnNOO2CH8dDihNcVVO2LpiXjVZPLMq0AloR0AzxKxfJbcXZWvCw1B4wuoSoQwFzKmdmDQFgwUBQGdKHSZ+udGb5nGNJZKtEe6pq2IkXHEFB7I+GPuRy9Yddh7ouPU5vb3i35ejlIgAenTkG7JIkVephJiyyT74Q6ma5pPI7+YhFRkoWheGHyLLvTHSWpiRzYfu/MNQC5PbA8Z/8a6WLm/dafrS9WwXgiJ2ETo4RGsRIH9PFvyyvwgBWMmkicndFMRpOQBK/jBDlzJ7pqvy6j62cl6c+dmIxqPrFiDMdgm5uuzZs0ZmTWrbK1HzMy0xLIh9GCptA+SREqj9VmJDuOFNPYSKmBDzj7Ht8py44hWEPKXDHBXhw1hfA1PoDUNj0XfWjpMfUoXJ0FqU+z/bgR3ViLxy0rrIfTr9Ie+7Kr2P6KRvyzQ2TWCFIJQMyiJhwMRLZPcKpuYyjZlO2gYFhwoP4aY9v1IWrAj8rzqF7ISGveHMYRAd5qDlPdXhRIi43PpW4/YlMKvSYfVINWN594z6qFAxKiP6/bnluJ89DkA1meYSrGD+vTU09hWjvrGENmValdH66UkS5x/zcdmbIU3BlADD1avl9g32Ux3ekgYFoJjbfWdwqmTCucayaB0wurFU3W5XwV32ggtWvEtPV0a5hETUs1sjldsSt1I6ueyfKl1hsS3/u9SxTyWyZMu0CAWhRirDCSkC1H9lVQ7Tk15mET9GpDs2k7WYDtfpF/iIlRbDd38ELduCCMzBF9uaV9fIpzAeC9MA/OLMyzhfyuSOrm04b58qxFkRKzoMoGxySlcGSo1Qn8H0B+GVslZRz93t5aulN4s/B/8+bRlXRDW7vtLSH7AEP9oZ5YUR6ydnMZbvl5V0wpWJ7Hq3zBeH7+kMt5JE8oPA5D1hjv/9H27sqSJMmW3a/MBxRhpvYmL4YABYAAMyCHAAHIiIwIRgTfP8fWVnU3jxPZVRknm8ms7nurM4+Hh5k+9l4bcdYUhKv6xNNFtiSbbN85nYqxOciokOYV5HEtD2MWeL3XykCvF8iEhZaISI1CuA2HqK3sRaW6pspevPIHVWqYijKkYAnyY4PvqXHMm9Kt9S5nrzfINO3dba8rkneBEVSJGBAq/ZnMlP6iDmtYuLdmhJn9hGjR9N3VlaIghxyY3xn2Pbw3fO3tQqQdnaG+DoP0gc6Oo1PlSnXtQ31MhE3kte4LWiksU74rOIVH1Hpj4dWc9OJXnbVbTWrJhzYTHNNqYTPOvnLZJrd1he46EbdKMf3nojQ3oqOefUplHC0r9wBgImeJ8swLigO5Q4RhaGJKAV3YQ2chCdZrlubySN+RHNYxZ9yEgP+b1JTsxhqnWMXK71npCqgpsUOpsbGaPhepwAgS/ZNiERpOrUxASuexyr2tX0tX2T9xZa5qx8ucs2eWvjTgv0U7+r/+7//xArTcs4qHHp0KYOIP2xxtpkU+cVIAr4jLlyOdOaeyeOXprPWpetq2VvAbHc1UF7/DPLFDtqqBdrfkWAJyhtTi4ZmG6KBJvZGjG8weTyp1tiYcQi3qwhhSbxBPpGV9IUFaZMu9U5Ly6RF0HNmDSzC1757NT0MPBrqkJfMd17THpVRPd3RMQdt1n5wtk9VABb0haKI2VHV5OS3jznNDKwBpOdgP7UaHeuqjDhmuyNpiZyv4CTCgjlDewaJBLhgtlgNQD3xRkz2daIH+LpdpiFoqI68XAGtPbffDrofJ4k7HW690eK1o/36A+s4XywG3sHt4rSxQPuNj5SZqMJYZEBcpP8s/cmtWALqyookCI+x24QtT+KAKxtxCb1hSwDGYxmULbbkm1HSUxhjVkvu/GmroSvPhsC4eZYW4s++L/b9F7YlSLmzN++m2k6HtLCnlU5YfGuSFcz6G00p3noESZ0jRlldYiloUQGT1SJVi0qOAo18MpwfbQNnhV7sNWW7irLdXqI2wcgasXPtJLdcHbcqIVk9qyYz88bIUD+azMstL1b8X9mBvtIIdF3B/7VK5RjeyB3LLIyT4ly5QV72zjT9bEW6V32IA2phdbLYwMp7ZPYcmiWSJhKNdzGHB4KnWGmIBe0eAj6ds/fZiKezE5MKq3o8o+MRT7VewHoQJHa/j0wFKuqfwAoQlPFED1e4zPGu6ayT32toxPg0+AC6Sr499P+UzqWO65hG1e/5DtcXqJ+0o+OSJiZHhXimUy0VWLKDZCRWSQBBKep+sORrokmqu86dcC32pyRuAFSv3W7ghduWi5c4sDccVVSofkAQaTA0rQ4pKFVnZytcSmR2MG4x3vF9FR3OQol3sKd4Hd65IF5+ktmvpEYruyH0n7v/w4juTleb5tCeImD3kV7tNvzUVlgsBpHfPEh0zMqgYeyiNxH1DDHZuSLmkNQPj8MCePXgX3ZMV87mioHSoU1mTKRhf/un20FxzzVX0upVaw0N/h+OOPC+shKhV1Qc7m0yCey7xTuRAOa92CaxneoDSxm+g6P7mjE5OhFjJj5AJA3/Sqk6+jJMfelJvDPChgzXTSJ6IKRrD/IWFs/oRIrh547i2GsNnOBsdrWGPfl4iOx3OLp5mYrf4VYFtRZD0HN56WAqVvITCosFiyEz2GjGT+9hju8BVRBrsanZkotwj57O6aD80rQzPbv2zphUvP1CP4kiRLWVdfJHf96aMy6DCL1fe7KtfJV9JZXvk1rwYLq/AxBcdTP03r2AZfL03AcDlnfIPsz91mTkViHFWSCa4JEjZjn/98voqS1GumHPrNxRCJ/GizFbJWGTz7ijKmdrrXuvNyeK75lNUo0BLzUErhhDM8Hqa7kGmGMqMMxTueXlMSrpGtkMmrMiSloVIRDr3dlwv9I9TYPOx7fYZHUMzLypEbGZSIWhBUcSf0uUoS/MQ45Qx845qeOI4NB26M6voCpNgYD2ijTs4DUTtdXj31zl5Ww+JDF1hwYbv8UkEKokcZQKBLveVZurnTt8nanOh4B9sBC9Z474Lx37S7ZqDynut3+YbAFL+dzot9kzpHYufGmVJNY2gNFPDVdGtp+sALG6f/fwEOarpSOONqX9n+qdzewWUvK2HxrHlyEZPQeLgqzbZiguCWeVAINaiNicB7vZcaelKueqxOpQysHnq+CZm6aecDuKfDPcyx9Bp9cxy0+aHqZbl7ScsRu1Mn6tZGow5XBmdeE3FBh7ieWPqHBoDK29n7heuL7ypb1bgmV1K10aFV30ux0V3aJsdYv9uXrCCy9k/GX14QOllNWMiU5obzirJEkkx5+buf2su69jLUNafvhzEiJ7Fr6PBFLNufT3xO9WKxXPSby/rq/RBmOYY8u9eobBS4xlr74GmaTLHIKC1stOpWjkzyrlgDcx+03PQHyi1xoNM5fZkKc94Yako5id4M08d7OwgS4qhXfate2UFWDXEsDsHtjPQEF5GkT/KMq09HHVsaDPX7VK2UkO9u2dKV3x3eZEYHKUIhnGO7v/4KQlMyn4ewSxOM+rkk9QSz7V6AGuL5HGs4001h2Bs79vy1lzxVWgulWac4NMpGrbQfMjc3bjyxnJSkFW3UmWoPN1CmhFr7IIEzxgzV6a1Q6yI/abul0IT8h1jJf12Bd+2iVXM+9ulUQLs0zQjbefWu/xMHj3Gqcqj1F8MJyYX3ujRHi+PKrflrL6cI6CyenzwXvV7vFL6noGHXmhfijWWg+HPkGRGh/1YIYRczmXqxbMUCiRBOZQcxsKIxigqPNa4eUCfo1K4MivWXs1x94u8f7p9VA3C6NcV3F1lyxqKRTlcQvOHG0Ltq44uEb3M7hXBoC22Sa6cloRRsE9tRoVl5NgrDNR9N8e3/glGOawrk/Fo59eCHb+L2QH5IKOuqazBl0Jnk1+IFXNbRa9dq6++BxdiZgXRpAiEeaB5dWKRuahMpPBZSp3hcJ5Cs+06JFK7tb+6cM+vSRI/AaOkM0YCHe/CzD3RTTsLTFuT6u+29hti1KpILfuo2/tS6vRnS3SvVFpgZYbH9yrdZKFtbMyN0mWlCPFdYx3pJqAUdXd2tnmjD5/MWmv2lWVB2W7dj5l9RkvPaBiZPBO27/Fe3VPorw89Jh/ppc9Z77DlH+r9q9PgZVTeFLvuiGeDRryUwSs2f9+lx5a98PUTzGOI2d7V+r3X+9O9dCTolf9GZV2S+kcB08JZaW84nHHTk9uz2ogZCJeDJysNt21lBXuQKlZFUuEeXOSfp9D678WLyPtLc+n9lKOX3M906l3eYvH7XV77Xf797LvDXDgOY/L9TrfuURIeqSRmPa60wZ6whxCrw8JUcPA+tcUjGK/hxrSaWYUHKyzJCSYPUzsR+au6YD7ckRrl2YgAepqVOhz/1ps3rtdr3hh1NXhKxplu1U/wK4BGSH4dIQqP2+Hd6+ubEy90dyHHm10hYUD77Pip/L/RWQ3FKVLo69LLJKQ38RyGfTAIKbSeRgLYhi9TEPZ+I3YbH9hIkfpMSZ2FeAss9mDSic5Vhc6u7pHySFy0Pww062QJqrhgibKlf1zb/I/qL0W53EP0j5ZRU2kpmm5OY7lXKx/TA1P5JflggqfYUSl0CIsR/QxowZwep1Fn2KWIpx9cg1sGensK8SMP1lCD/NuBC/BCIigdvSv150pHl8vDfM2jKzG3SC+NTnFAYFjopyeu0kKxnakR5YYTQ1kdYWE37h0M7NfJ+xy7lqJdLF15PqOrfkv49d7Bkuq/YY7H4BR3C8gZ7IZQdg+AcA/aCbpeehzxhOtjBniQhfM11mvX9O4egKNqaNcvnL3jlA5Y8vstvQF/2T/aBJ6lmpFVN5avkRu3WkP9JvF8EX4RIHXBe2aMgHcTwg6+Ax/+BbM1uzCu1CMchvmxpsVDqUi45lWOSb6VQyJumhnzfhomwsziyjsN8GQ5KWJ9ArHcR8PehzG44zXlL00CmKv0qc7mpbGVmUh2+Xx0Gy39OCFwAJ5d6LMXwC4fUKj+xVQ6OStG96REbTD0xe+ECMg0RrxyugA8Z0QxI/+ENiPBVZNxu+YITJIHRXU2SsNWXKfR2E5JDGMWwRBKOdXULgdU3zyy4v5gdH7jxFQYIEDGWcQob9BaV1+HHYI1KzVEetis/sxdti92++MHAU0GwzU2I9xbMiNTQCNOoULl2tQmdCsf1NqKTI5paH9H8NJysMwUFyssBDDT9d4XXLsB3wN8PcmRTojMMYnoL6aqn7EWHzEQjVDtoS152byHwnhi71IF+l2eiDtoYzPy4KWrgEsgMQpo69pNHDs+QYozxJ5x6RBZGQkE1InT6QoTRJnZ2OBWxaTHxZQlX0l3fFqtB6WHmb74j7Yi34frz/VE8krFRjXva2uclocbMjz+oC6us994+HcIx1okvk1U2YPgv05UTpPuXUPz5iq0yl98cAj34xlf82FUz0PWnX5naCshPimisjhrt4mFbp43YVQAxvI/K8qbitYDsDSlwFRSijfFNnwy0VmPNCbDMmomc4oMUTN7g7gf8yOt4Gosyks83du77W/eZGpuNzRwQ80cXJwcJmxzV4F+okZ4lpinmaZ+8vLu0aTYZ+slzjL1uznexmts4b17SOggTCMrerSFU1iDByVCwNIolLwF/YQhqVFuYl6+kWlAcCtaLOPumwwt9/KMYTTzV3y13JzSg0e2M8duKA7rObbM8zotPmYsMp18OiuJaXZ0Bn+hof3ccABiG/6KVZHnVC6aY4bwovWX51wVLlyPBRQgVqc9VA/56nwW7g/sjraUEF95z4OAtYr6X11juXIWwYvaiuw/C40nR7XHaKf9K6eir64bB3N/3e3x24kHzPWnj3pVh+8onG4zjqjIF5fFZHc+JCwe7l1vmJVkQZocxlm5BkmW/tdoeNqwjrTLz4kaugD8w/Isz3wnLRYBQ80lWpWurMLIrMVl4Atgl0ZoArXKPSJsWmaaqbyDInJluehGu71XMbcznVdkOjO8/Hqpsvza689xHRbj26V1EPqgiTZqso2bEVtemF0K7FVhP8zqkzENdDMbhF8p45RJV13G2KkoLq6DpQj84fVu01/plB0103D/aojcCAFtYEBbdpd9o5AWOj1NDwsxkxxur1fZn3LlKRxijy6/Hvh+wuEhGVrWuUu4v6JC/0CxtgldShQoHtVl3F5DxRM+69+I3bh/MWSr1t0jPXOE7YhywY71Ok6TfGtcTV3U5XkbmVYQGma7MA1K+/yLW9j0/GTshFJKjbfvYVxwiqDhiDjpOmcTZ3+soJDh99DZkyg1OSEWZGHtLfuK1k7F6vRAyApIfafHbkMSIS4viGwGhG6UVAY5up7O6dK47yo7IW2rKpvha+0vO0hOMTdAVickd8meAVFzGERCYDu5k2/4Q/GKpzeHC3sUa9lmhojKJmy8qWhrb4u2H+Qr3qbJBRZhVbfy+bIZT4xe6tZ9zWuyuFfKClSYGXhXxpQ+XrTfNBvD3KKaWGUM7r7UfV3ScTk4J3M6v70iauwI2wqNWhPLHbDpZAzXWPuIGpwFSIRVZRoFj2PPJR/DXokaYbcLHtp+zJf+jbKtSvu9r4AHKfuHTrOJh2I5RXEI2SDVW3Y5puLYK6PzgobNU3szjApfXrPP1OAlted9t0ZIN6M6ztjbi+47psEKK6g0OdPuvMQkSzsqiSLBENbjSYJwlaGhhsCU/YszM6cLHzt1Rd62J0o5fO17u6Kh+xXdvCdnXcr6fTMeZYVO4//yQXXM924BB1oMceZ0mFFH0bBosra5uQaTkIooQSM0HZj7VMSG2q9Z1pEmPFaAdSL3Vk5qYRt6vndw+yWWxYaf3zEMgHgKynxDHWZs/Y0dv7EVsuJd5hqhFwPNk0ltmx5pQkjPhndszKZoiRHVDA5jKnk827NkKz/UF249Vin/Bio241+U92AyePitXkPIdiGXbxZ2/a4yfCswfNEWloe2kDml/7Kf4eWbJrXrpvT1P3feDlaM39nBBGFOdkNZbL3kuScV1ogSDWz4/VER6A0WXe929lPG0sxpwL3W9QrLOzMc3dVRsLTiWWEakmXciR2OiYfHq6fDsrfvWYkIEc0ZRZ1NT6RUoVLn7SerAhyxFDFxSfea8+tHja2Qz9GLbKeHrM3yTynueDGaXp4+/9T76hkWeFA3SYQOwodqtxgkX6T3EoSdSWYSuX37XUUBwE2pYVmNYbve83tY9lYvux/iPDTFXoN9n6P/NsPiN3WBbal4ebMb+vaem/JXtR1iQFZoHhIL98FuxiJQRGlEB3GygmEOMLbNmztZqSZGPtxjJVDZVLuebWkeUi5IcyMxcMD6XDlCIloIN5gQ6W4UJHvmu9arKdB+VG17ibDVVdPr4lKOIUV5benqbwdunMl0L/ExPXmg12LFubDgLF6vifbGFfU4tLQ9k3yksaAsw9eUJT9rti7wdbtZzKrZhL9WJoQiUNSjT/IhPP5OJGEBcKlrxOpyEbMiOmjxeg1egwwjfE5FMwq0jBkhRqZKyTlym/dI84ps3oukrrVyHw+sSLnXyj9kqi5ZFOR9hrLVkkMtEpjr3P3G1s5eo/CS/5FzD1JMzU5QbBy9+hpMWd+pHqZaClGFRJIbrtZ2ZQl7itx8BjxEj+NX4nD2KYQCgVod8YrHjyKPYOm4mOXT8e0RxcrH9l5oK/02vm07Pjau02Yu2tNFA7aQ+C6e8qS4HzOYNiBAJrLvTmPWYGxOgFsTAZD0S/UleCrNW1nV2o2pXVJWARtZ6xa2Nf6MROp71REB+6KJqS8ncL4Hb6M5Tr5AIjB05J5/gPIls7tiWy7UF/IsNXpXyO0WXm4jlwqPk6/Vr2HQf/7hpGIw5V4MYlbzqqNWN/KN5LlyhhbETz6UxZKZTqhmw5mwTJ/tqQLyWHcLWkCLRX1xZ3VKEVspTCBUgEoDXdU6T08fHGxpF4KBiVs1UWhIW2/CnUN9qtx9Cp/X4A2EKu0Hk+QpKNh+2qGob6Go3z62v+w8on/wQs9yxES4jJtN48LyLJXbBHjTp4sWGldO1zayI4KEYNqakkzehLyvQH6iLetUIL0GV1y8VNRSBQBRZaShJKDFoVukEdRos3L+BFTNswiKA5fXxTOb4WoAE1Dg8sm9x5pNuAt0KesEJp4ytqOpzj82TNanYXIJ+ZTigYsclzw/LqOAWsN7XkMsae3gQqJ3GsqAedFm8hZ6hhqzTV2FHU2ay64YHSt96vJICsI8kDxnOBhrxCnfnRfaKKo9QcXuZy3loFjGgzVOrx7dmhk776XJLjvWOUnO2XGIScd0nCCr//Bp93U0L2v5AnW/zIQVTrGxgFx3hndNi/fhzByt2TXP6DHP6D7JOJYjJXSaz6yNwtRgjkg/oTjzGbIc3fBAfJfK0qoWl66ZYmK1nWFMN0pQR7p7dGaK6HIhQbOvSCTJgJ8Dy/0ZjZv9zc7fzKnlt9WDR6vNYbhYGSy+1Cu5E+Trizla9If4W5roVS2mRRwelpyVI5LVrmyl5zlTTdBbDEo8eX87qJHGLaulX54R0j2deTEYFDVlxRykW4GBlzztnNIyTTSx6+ot7RY7YGOWWIfThHI0gTvWhPlKxQXHIOr1qm+DCT48pvmsr6bEH3TCrFBRvFIT6NDQu5SrU3PU5GZO7wzZqTwjlaIRb/JSUxonnqpBUk28vw6IowXf57NgzMK4QMqq5kBRmdvauFfUUpQnKo3KKHRSE9Ycu8cV5zND5c0vawrD3djXr1Pj64ucjgby5sTZKRrKP96pqjheeBJW8yjtTAzjbEETMTc7KuwiJ18C7d6AmKIUAOUlLdpMTx2sLJfCe1q9yfky44zhLB73AVPGt+lJ6d0iTkNBGsxIKwViYWpxpZlMkU0QfWq+kVrY+HhhppjjCfh1Z/PLgz4Z7k2Opi3DfUcP/ujAWDhbFkffYsuwoOJMZj6j+7G56Sj03xW3jKMczXN5RECur3Pl2POVGQ00upaevZleNHU9jvs7MKbEWyzRAIM+9zUNr++62mjzls9RzUBejDfXkg+PGjWdUUH7+F7X6tc3kUdsp68p+amc8ikQsEtY+B//YKH6QiSa40i6nOgjhsotfAlNwQCKdUKSU/SOsOG+cm86KffrbRDezvNqLujoxen4CiIfKTK6MdU0YGm+pK6UNMrr5rYyLlZDSGDNzU4Jue2SRgiRduamE7x9n4HMy31lmXUqd2XD58UTrofytUim5b3Ks9/+AHoorP/Cz7h4KycF1EQbMpL79uW9d8iBPEyaBwwxls2HRfOXr28aYS9QsI6aSfYbVxsywlNyJWfPcuOsC4WxGj3jkUspXGlBszDbAtFeDiZZtunpOcn42mEA+XroPNt7HrpdNLt8JeN5q67v7cj0FjB/brDpZ7ls/EkFD8iuuqaD1buOP24YpQgmCuXGvKFilZukVLzrTBaJxe0YRBfYGQ2xUlmRBQ8tv1E3VD7OgripSC3KaqYwhio8ysLs36laDKv3OYH/sTEs1C4yU1so4lnmPTmZ0p597JnG149/OUzLuIjWMN/bDcxp17P+ew3y//Zf/9///v/9p//zv/63/+f//3rQ/+l//W9fF+T/cIZkHBgpYq25nBodW9H3HNJH0cWHGEVpI8p00vP/xSCp51hY4zbt/HM7JMqyUI/ioPzO6qSh323LhWNVKFVGsM4sELuTa24yVyqS5VV3lTIqoeLgrvFjgoz43dsDs/46e8/19b1V/YMsvkSn9J2xzFGyNcqXO69tVUut7ssr7Iwk4kOjqJSF/c1PL6I4PVXq2l5c7N25RtVxTEj7bp+ZPjKptD+VpW7lzlR3XZN7ewe/Jg7QDBdRtWWmH5yRRrwvD3aAXboVWtSKbCCzstzMw68HfVrzbsDyWV70H66vB0eej5tRt06ULVN5zNnpWsLTG9pUR8xTJwtPTIaFgZd/O9LgyKgC0CpKG6nQUMwvH96gtCiM/tK8/RtToIEagQOMf0pyA5CxO6s6xLiNKwqMBoqoDnejc58O7dUSL/OelRZKuCvycr3E8Mz3kQMf0/jWQSU6PDaFjhvYwibWsntYzNVX8vCeTCc+coi8wGxOVHHSxj6GGgPVQRO9j/QZAwiVGLSOHHsVsSjNvwxTH7aCMI/GUfFJsl5lpX2xG+h8ptIipOq8HaUWGF/UKxzWTewgRpIe+RkQv6cayX+3d3Xzb5IAljMrOssk8dtECst8l9V9TXVcFt1s84hFpTYN0YoXISGvJV3nlPX7cOCGZNWyO2uKkFViDWK+Bpm089J3dzgtK4WE1jwUuyjnQtESnAGVCMscw86tfgZ8oWAbyg3IJzhGdpjJ15MdD2/6fTbnbx6c32lIfnNzOOwA9x2vegUqnrlA4cgtimyDdyMbu9ZDeNL0E6aLMfQtVSZ5sFSjEndDaeg+U7+9OomxkZfUCPGrQr5AKdoIdvjw0PhS73iTjv5MKMUxnPPqQr3kzNdJB5AowXffuI97Po1bpfgvPosfTKSHLJD34I4di9w7mw184RloFRUd1WYY9pDiluTvYkd5iDLPjV7HkaIQRr5RKQfjzNy3rtQN8cWVArZ7RqbIDfi6B/8xEaw11KfMTA2HtRQ1ncc+JLabIeXB3ZOVISKvSnJRXTYiXnnS65LJnCk+L+ka5XOj5MwHkuFw/VJoGzi5UTzQuZMT3ZJPG3qPsIviSXz7XtKWZv/jc7+yYlIarGt53qyEjHy4HVgpan1FvV086qszBl/UJKmFx+TC4s/gtgfFdnu3JFzkhDRVUMhLMgpej1PadcJ+1BFbB74dpwkrAzZccXavTzK/nqqvMl4IfrR1SxcgV/7o7hxr2PLyjG2dhR+t30IwRgvrdUyqgbS23/xzxtYzlC3GwV6nQ18ajNfG8tKxLs0V+knKYEbRC2XNLpRYwRRzxWhDFqZKZUliWe7mRrkPin1WgEzjpjQ7ghhzCdlBfyZsfBLH/Vy23AOQRdTCYsSx4J4vRBSy+XTUxbW7WL51v0VdSAiYRPdXfSJXrzpDoYxWb2+EtI2mqO0esFCWx43Uuy28U9GdA8y4PAJrsExvjP/FnanXVE9Yffwrwupk+RLNYe6lKGF0q+941vUx/i+efY689e7Vy/x74Oqv6df7f9bIk9+HF19rV4ia519n0Jty5GuhUUfICrtvtITr3jMHZEX5pTqR+DbLSrVuK5WxO2w1VI3NT2jtsKZyxQE+eYmd79yBDXaRLWOCT+W7l8Nbq00hy1HZTXYjxa6SxQ3LZu8dryy7DWLYZtK/yFIt33rHn+r2R5fm4c+KGrVfYsvIl5lNo+z8G6niZoUOWvYv3nNC7bxK5yshxf1Wkew9tegPzFvk1L7IjBJE5qf4sbmo8etBjsuRxoh8n7+KXCrf9t2fJu+M0/m3InW43djaTHmxUOI2c1ZTVYQTF5Ix+cvM6zO4m/ZSXYR2o7AXHN3D4QfXZ4dD0inkGqdOQ/Dd2CCqjvEcAuYaSjsqBGIUSPMFxEDBGnRBzJZFch6jcy/hqvsrBhvvxDBa7+w6DK1XwsPDodb/lqP6t5XcOMVfU/OO7gJoHZkNoIz8M1WhbhCOrbr1TiIqYt/mZeD9tkyZ7FublikExIu8vBTowyVnFM6Tjqkrmi7H6mTFNE/qpXrjt9rRiC/0MTNE7oas1Od4cinies8sODk39qMu6ejGmx41y5VL7bx+z+z+cgAPWo9DWJChC6DkEJCoE966ay/pg+hGqpaxw40f6hjLjDPRY8sDSTQUaYc2Y6DXGuiWhjnvqaxA4KNhESPHlTNQhyrAuiqFS/FaWc++MLKeyvkQwk6ZJSgL5CUazUlUFxq/rzuLR+dHRNLRnNya6DOEx7uT/PEUj5wRf5tjQaj6rQAEnsWDAtpyZrs0cqrfJsqIDQ6RcGN8h/LRZj+Uz8VXsI0RqAZ6GQOa0PCG3Uw8HKVJyZlhmLIHtXpmOLDGHf+XGNYOqnejbrMRIBg07Uj4eUk8YbSziC32sMLfcRpnQu5Pg/+S7JKXLKkHMw5x3GQEPLA5NMYMVZJDeltjsemUn6x77Tv5yZ3CDEY6Y+xe3X/RioOeGn7MVhyv1UDZjnGLINXqGa9vxRk+qZKlgtdzFqclY34fl4WicIdAbs4MUBy4k9RDLZ0c5bEndOpAWg+Vf/7Ior0FN3neKPG2Iut5eXpGBxhh1du2HqllgzquLJdO5OWEzF2i7R/52WWDwinliNAwJ4lf6FTNqSuPe9U7gG4o7JnicRAwXUdkL4bo31hzKbu86UFj4R60IKPcrkImT3uABo3O14TlBj7Buta2u9u3I+MHiBzFaRcx7Vv9c8r+vEvmPa3kTKeylidytmBhSCvbL63seFJ1+kXA6Jey/6LqMCAUUMcuoX8NG4tjdHiIXv4CZJ86decjlKv+nhfl+/02T1jDbjbYOzzg7DJRVm88JiQVn0tOv7szX0/gjPXZYQzy7AceDFn9BldfX74JHHCtp0jzaGB2z0Ed7MHRLJe0T6iycAVxb38w6F78kJA9hWmuMUf1zYNqNcZ/4dvYZ93XfclTHmcoSa6Rr7N7pm9txm8a0jD/HiABcbFI7huMhacY9EyAlFeTKBr6pXxHzoo7N3uX3J4Lk5IC30uCmfIsO5yy1kLxeVAhl9zTlfU2tWmZHlcspJsmakUzVWK7rbojbfLt13hefk+Db6Bubr85ctyyGDRe4oglgeN78U8f0/s/5b4Wv9dE/XA6/R8w/KhiU8KN4rpycjaQElm8ie0OrN2KH9yZOx8OXQA1Ftsm0dv2t45u2INF9mdLoLvoOrSA+QLr9AusQ4NxJZC8LkSOHVT9Q33xwlju3Ry+r7l8t7QXfhToMu2X7BzAkvyFWFoFZxKBIAlhf8rP08Gm65+7edzfiHlwnS7TXWSItBn5Ws0tnGndVutJrzb58qwaSZPyVg4PXZMGZjCd6MNnTwjYWf+JlAuJxxuMOh8BZ90ftRLfXylln9a9LOgWlqdJf9NlzzBfQnQI0D1HYJsKr+lZ7i17ZtiS3ow3qL8+ZNQzk0ll7RF+rXg+KtWGLLkhYqwzAESAS/UAJzu63TCIPShD6nDqo7GIEqVXXwykRBnzfYlccbKsZFvellV1Fi0deTpnrHh/s4T6zdMXlaqvTUUU4y/fGDDU6nbyypuTLDA/xePvihj8RWtgexOr0UVmY8rRCRrq1SGnmV5ijIiN6+5mLyE+NvkpiAwwJBdWXBVdx/1kxaJWWHjpQQpQ5KFrDfcfyD2i15eGXg1FOxUBt2vH/lQCsIcTxQCiIp7tLJQyVNOvn2RKOM8XVLz6snxhMyyEfc0p8MRa1Zd9UpYevIeXBI7JyG5wlzJOMPwi+pvdlYNHAKM+bGyS0gglOLCkC17fmWV2DjJBwjP3ngLlPTs8C00kte7XT8FD9q5tZrl2ih5yeVOk/W75MPshbFkI0zwmlcWCZ3mzU6uRhK68zNlvLbts7dzIW/j37XDQXs6D9tgcZaCaTabMGowy9tB7yiCXCNuidjCkpeJU1q97RSzoqKK1aMgnehoCi6woV0Hm0M84nyTj2qE8i8SX3XMyaP4LtfMxT5vtFtr/sIBQK8xnv2cQ2CYrGippcoq+pumO+t26OT4AsfRgD1Hbp28meQdECr7QfNBQwJImcaQFE2m+CDLeUB8iVD7T4uEUk/3rQBm7FFRR4/KdXp/V0Nd75WLe3Rj1737A+M9AUzWuuyvOBUuUFEQzP0q1+jNY/ZbitnN0WUFraSeamPFL+VNkOIDXYBIiclhPLm+/b1Do2BsNUVuHArzExqi7+nMwHNUGZcHBWGSHJ1JE9JK3GjegkN46udivFGACBoDeOPUv7K9CEVu/N3NrSaDF8bHvxIH04opzYTo8fNl/tMbjQ0DcFcpeEQllDuM6Iv8X3PSO4RQvm7OwpuBRmG9oEkwgCtV3dgbt4ApS5SGwt/K08FMb8pnFgVGUBMpIWMdvZ/Gae1DisN0Ubo3C2HNv4jiEk/zUFG6FRnN0pylpDDwd1TEE96kwBb4ebX/ytPZBvCeqb8qJDzpmxtxHdMiKsAW07Fr8D5Q3nbNBkLyC1sG6nxyLXnlqNfT9+Zp4ZUzPuppkdHCGXHNqesYHODFPDrmrMKPqu7LEKKNs1rMuJMT0fKffaBFrkHMW1ichvqqAddPrCwo9EnBGXHjjWDMPDXb2fvzR0F1rz0+3SeIJ3aMJKBZa5mTCl4TB1PdRXZ+WGzKCalGjawUAvPDG87niUPORQXL2fCTK5gjsJBXX5WAseworC4mRDa2hhgxbtTYjK4hrZMOQUmRrCJ3NV054pDtPROEKCq/OV8An73IEW2ijf9gZ7BsdLv/+QaFXeE+AQYUu5DcTc+1AeOpMBpYDhb26qygpoDIFRtU+E6jK48rrUgY3T/BcK8KEMP81aYSBeTeGXhUo3pVXoZR77VHyiMlEcceTMtezPFiCoZjfzKbITgap+H8ck7P/RUHAjMbjSrIQgcjb6K/f+zdMw+c7UfnQX4VAFa9ZIj1EyivN2bZ8kknaYHC4eXo4hITAasxfq2hA61kjS8CpRMmJKqgDlzQ2SK25f7IDi+z0lO7fEVwSkEkjEKox9W28Hi1HylxHwMJ8WC40y6G8Qvyy7w5hrMGiLqrm7EmTPG47RFf3BunwAdcfw7UYpC/K3FU9ZLISGVLQtJnSFgWBsmD6MtbIKrXZPsq5/U6dLHGlwjmBb3XGwY3sBfeQZX+ZO5zKJLOkLE+0Gx02Z9a4skZcHI+vMEKz6QHMop80vm+ZbnsvxQjtYnOu+VJnBI6wLQItqB6Wqor1ZGHkkn4KgFLS1wgz/6oOuKoaXEmY8BHjULZgDIHGIWlgj7ywQgaThxtap/KnOWanhR9a2ckYsjKCl2uPaQDJipogXnF5KIW7BtmzjZIi4ipiwZju82DrIy7r/ZAi/0YP8k3pw6zvWRbL6Mglsqj7J498cBLqLJW/rkzfzUzmFhMD4tBI8dHpZYTZ2ifXK2gPv0mvLhCXA6VyArhSkHOggZrVq+3ZN+vupxWxJU/w5LROuBdUW5bkUfAetMW69IKi7qsHBN/Xc4588HSpqvR7+05D/TzEotj3I3mwB91RTowGZ/IwZEmiGgAQr2BTBPlAx5hOIKtPWdWWvy3H18sEtTg5hhSC2vohGMhYJhvZZXW5nKKB2fREls4/X5zlGg8cIXnhDS4ok92V2h0JUyxMFyo8md9tQaDeadepjCpyPdmdSV6z5/WX/p3gqD3/fAQwayMtWbKw7JsEbB4jLvt0I4A5my8yrAhV/4uAuDvqt4Vvhxu0TY/GUb71UKCitBUUfZ0AQO1M99uOg6hONyAOytBBQ6OESwcL1tsxpyTVLdZRCvdFZcVskotzMnIKDD6zjKEDZnwbgpafxDYsk0/y8v3Rei+slg1U4lbbm8euLDZ1dbhbvWHBrj0yY/kpKKztxShV5QTh18xRI/B9QWKYOGpsebh155qVoKNNLww1KSzTW9SW4rHD5ZJ0V6r7vnzvYCysrXiVPWT5EwG2Xku/TP8yrnCtTWGD9p389+8S8E+Pmab51i3RyugsDL4O+/9avRHv4o7JkqZQXkU6apbeNREb7Y3fvYtvtiJYYHh4+GQS3VbUJ90XCqnfSIEO2Swpnp0CswhGglCsMu7KaEpNTGusljYiSFxaEAgrmaWx9zjmWYJaVo1zerekr1jvFJwfw1+KEhmjIxfIyCS3AJJhSH8yI56Fui8xSZMKTl7yPUMgVaVdeThnm2g85nJg5HBaKlJL1uFOr6/8Tkt3coMwwZ6Aa9E+IoNURrtzXsI6rATmloOQwVI9F28Qt1uJoDbMWpBIvp5xOzasU2P++ZhA57+Pivt7QrA8DIjfMtzar2NhkqQwlCSrCZpATdWXx5P3WKtiZjZ7Is+m6EXRwq5m8Pp3zpdOjkyPiD8ZdbIKbLwLmam+aALipCnn2sa9FWy6GhnXLf5CTWQBesbtYMjOC0taW/FU98ZqkB24N1ZND/nE4U9tAucjuj3/lFS5xq9usJ/9sgeL8o5sD53YDtX+ZbLTL4Pd7frlJc79Xab78QuPcBxmkPvYrQ99252b9TFh2VYQlrmqFwlgkwtvqrHmnxsztkoRXHgxS/bzbZ9gmIs0A6tPGcG9jaK7rvVersrRXUtAVZujVRv6VOVHKiMiAXVdKQbM3KwF8n2BOXRl/MoGYsWRArv7T4Gyxr2SmYewxx3+qIMZvt1Qe2jZJZy3V5fqT+qJOZ9B1W0GO7z7/kSigWQRRYt9Y6Bd79QZrbq2Z3CFK5jkmYmqifWFoBz3SVEoMSrltkb9sx8R1rgYPGdH2Mnmt3Kj4nRlNHv0SnpfRadQlY8U1ZzOC8nSExVcgfZTBBLHDDLz0Xefbct4M6b7sG1R3/uQfFMjTV66yYpnMBJTFSBRsDdlmPQsqTUcLcCUz1gdOGSd175zq3W0XB3vQmOZ22AeNpgFjbl3YxlS2TLWGrtB1iaFwfPq4SdDM12qw4M1ORIPqtDjd8oJ6RkyuWVSbcll2NibTDs22reY6JxwtPL3eJe/nSP1+1kT5yL3cuNyqc15/wIu7Uno8voHlxAjx4brNv0qLaO1yEbNvjxJQIgSXUZHnVApzSbPz4qzAJwxivnUUI6bECIL56PiRiO82lb4bcxDy9m9af+wTAx83hDa0A3T5CGXYzl1os36Kwn/B+JNQTf/PEZ8uP7FxzmexH1pqfLlpFkBGZdOc14RiHa5a9YzDBGzzYjbUnfky6UIoJzxcrDYsVZnFWX5ycnJqf2WPez9mqTWF/ShmGrTTfqLRZHcLns4QKvlCSKozDLaQqFHeLeex8IgFW5QJg1KgY7Ny9tCWcSAcPoFJ8ESR31h1VVa+FkpyTJffNH3Fxr5QeHb+GspRHVdOpgFuAV+VYb5nKESZHF1Etz7r4d9YyZzIFO3Qup4X9s/oTJ8h7q8Ewkwgr1HR/vpVcctC7Sc0bTub3FyGHpicrmqt6UohuifnQxuL5uT0UI6TxPYaNE8/ElkreF2UqMdrhz1xW6DY2a+3cXgyP7gXcWNbM9RrsOpPpW+o/cQeNEKyfjIPffXktRBoow5Di7fHnT9lT1/5fL1lvw7cbOvA9FUjqzZy9y0JXJ0/V3La0VsC74scclyg3pBMpE0O4/x/nrp7Mx9NorgEgN4HJ4bwawNjY0FHq7ClCms/53aCfjCAJJYdwLf4C8w2EppkD9YTHZMmSZOM/PpnG8VfdY8cRDX9/WY5zWq8Ez7pN++B+zk33mrHyng+Zy/sWld/DXndHacBEed+qLIMQ8KtcvKD/VMHub+y3ioiv/DUAtIpOzKAYWBd8fV+nXIwdT58rTlC6rMhCj3gCU2R6A1GvsCQHiqqNYZoOclKUx1QGNOmhbA0pT6s3Ncr7tglhZFv9mriiv9/mF9Utu1jXgOn1kWz+E7qhXEyMb/r5b2BlVBNzovZJbP4Hu72EGoKF/d2U7DJ5uTsMUBT6qnCH6hzhDnq3KfFSjb1xy/s6gqUoXL3rTuEBifVuBtk/ZopZh1VmdwT4Hbk/jAPOx7KHRWcetN6sM/VBC8HB9PIjDM2VU8Z6cz2Jy8OyIFZRFpuZGK+G1aMe3zbo/mZP54JMFc9n/l2zYUc6L3ZV5a09eCgf5KXicXPHd7O1Lu59nP+AAmFQI/LOShhQq5cnYkBAZzxdlBfrHSBTPP37niYiFeOHES11N3HHB6YSHmD6RzT43iqMejLponQ9rSyLdxf0mbKYjKMFdmZ/g7uTnAryGjy2+EGoIJbZrZ9Jj7RX8ip0ODtywX6lqOC63s96q5yqmwJ5NoJCscXdRUMeOl6+P2EzVVbBnxwRZjTQ2Spf43UtuJU2OZEjBxMmMCC1UfyTtQ5n4Svz7zwe17YlzgPS0EwAss9+J+FDNgkuAylZvBmqNTimjykYtmPIeYYKbbgrowmDVKyck3pyM87bz2swf6engmq0S5QgfPejfifcRpL1QoEsvttuRaTdehJNNwCoLiilymxsu/fZk87guU2MqvvZL2WXn9HpbfGCrtbQlv2uLWlF1SP3wdTv83sRI5EwcHSVMftjfQjRS6+cYzOVMoFBEjd8zaXYGIKv/MeQ91OZnSu3vgCYVS8EqgNNXXiM6kJtgj5Ro8IvaDnRZAQdxdUL8e7eDWAIHb/LqWeOLjesH1pf6Lqfr6gyF0+JQXANLFpntJcc3IbohoSOvt4Avkbzad9q+Od1KzQi/dZ7s/33692kW+6uk13oh6u4iZ2DwseL+MlJel3bF/U1EwFhM7hHqFHryguiloLK17E9Pwse+XEIFwZo2cLWzASDlqaJ3z7mNyEIJdZ3ANkv7cU57MJxb7hwlcZgjJAAOkIUyRM6ImV18tVQCypXIqEp9HbgVB4E/Bfvb8iMnWb4k43H3rfWETBwIDKyExWk7zKxrkczR33cgI2iXv6vSFWot4yOW8K7s9lGW5hWEVR5ByKXZvI19qTtfyr86X5d+70Mp/4+J75sMb+O1UX3BfTFZ4Dhp9SEWYTvahY/qzyphApn7i9kL4M07wolH1iq2h1NE1NExU2JUKW8veRcko7aNcLNIjKBa9YsVsVNuJiPQ6oiXq3vOPERYtLMXGHWWMDq8Of+mtL0ftbTrK90f+bfed/52fhzA734QhVm6Myeze4ysHooUeJiFlk/ZQ/TL51Xve8aQBDsU8Um07RoqHowDTnsJ2X8K5SeXnbljqqc2WYGLeUuQaQCwsnIBlOG1jRMRhKU6KtxxCWeTEWTv8RjVJ3iCMXD6Oenwc8sbvL9EuWeNmHdeS5u+xuC/0AcVfbu0jJ+Rk/DMV4TVdqZgZLJmQzCHBVwJu6DrXL1C45uKoORwEow14Z0HTlh9yFZFHQqPeQElIqq0hdkfrq8GKR0bwLneaIOtx0NNXqv3JbA2liOWLCX8AmR6JpDsGi2fbfuHdPGry2rwm/5jRNRgPL9aiS1P/5iHPu6MHGzuROk6wL0PjXwb9Xare7qEOg59wYh8Z8/tc0PYoabDIEv71ulilgBIXrUmPoLOmEv886eOZHdYUp4x59nYbwYPo/mlIZbjQHeR6n/Y70GBLWgVp3S2AUg2++p1jKb67n+S/5x9epu9BBPtkZX7TaYEa+rHSnd5myP4zYLwunthuIDqi+r1f5NC299OTxnxLbPQmPyVWsFY9C93JXzXW29V5/sp5d2TRvIPBrAvQd+v8N8QNfySrdXp77lTlguEE4aYX8ICgzsJDHleLeRoMX+qV9DJ0/UR06lDY+36cN+JZEqaFQHLiWMrDcWaN1IfKKsmEvMebWQVm+JaYSW8kUaQh9JjolbTQHYo4oG8pQqJRMAoonZQcwZvbIMZ0MUTr7cjoyvVK/mYUYGvFHNdfdSxfUFmwjRfMEu5cTvM4QMYK1d6uOC/v0E9BoaufJC9wnIsHtlhTTaS2k6N5MHxoJeT6kr5pks/IW3HQ3W3Wz2jBdWMVRa0S7i8zUVbuwazOVLrYJZY8SmgLImmEertZEELhKbJDN2FH8eOpefT6BdvpLh/53uXsgcoZdyfNz55x5+Bpxw59dz7GSKf+ISLrY5NwCPMazRCFx2ihhuTHXeaZKVt60N1rvCQxaC6H2ZrPl0ctdFKTT6ce+dsHu7kJGsrgO0XoTedO7N1HW9Y88LgtrxOL8rpZB5vOPWTJVWt93v3EbDhlz+X2bPbGvbk/Gh522AO6XJ77PnSz55/SMM0Xle4fk9f0S09zLQelovlVSDHamUNA805F8zbu9U2OMcgYyuh8Su32sUFpQRl9ZUccPLSPCfBrnpZk8Pqbd0QhO5k8XPzxrwZyQt2aIPjFGNfArgofeXUF/YX/abFzzI5Ba1QYAv8l3tghAQh7ScXoLUVMNM/67kjFGoQOBwI29ydaDtzw8nSyjGhv7yLNA50QXPATUjbtE3tKh5BzOxr1pYvv67cHBf4DhvDvorMrN/otCkFps2VAimOlDK4M8Qy9sim9AQeySPzNgUXrmJM8kiX6imHdcOafHmOldRfzr5XQMglGWpys63FJFh6h4WDSroEU0euZB74YRTUmwg2rSy73BkEO9sZbnfhoTM4BKr3cD7nCU/74EoD8udSJ++XZnbOYWfzlFve+R4ZBEx/IDR2iiC6ygberAqVifejfoLdZL32LIprX9yqlk4zMaHQ6A5VS3aHfs6d7GK97YR7u1wJmAqUQrhocJYrDwgas8N+Y3gkmXhm9mk+8I/9uUX7k8TDNmVfV9qZZ//ic/mqSpPm5Vgoghgtjqywrc9/P+et7O+kVulpjtpPbdNJcSZCXQwbIKc31hSshdhrXodG4zBH1x3SekhI0u93Dqr6CpDTcB5Ap8wbXb6uxSwtp9RRyowR0OPmKST451R9S5dSiEc6QgiQHEN65VFlLdjxS9YFQqz9ww/AnHhq+s8aW1neRJm3d33J/+jhTNJWa8F8m4gEx5oe5vlIGzf5ytivze/LPrUYIL9PtgXZHMuDBsXS5CLpihYQrnuFAh79/zcr3V0SbZb6wjTqksaRXMEsRb0T0bJx32dMQcj65rUNTKJdM/oA1/LtDqPQ992OyihVSv5vbsbZcEUmSzBhmju5MKAiYA47g0tnrpgFZdaPXX9zHZYb7gi1CA91RcSrU4hqLJR85XUvGt6iM7q40vOQyF1MMsxhXMnFrNoLEJHPgX6K0xjWkycngsClMaYNkTinz9ZbxkaTXQ6b+tsH83WpHoIzTFTMx5w8NJtCBVjRSBYquomL3yHVEDk9WphfSMyTWj5u0K1BL9tMSNwLjQ4n+TNY65Dyj33YiYVXEREjailnEcOGkUZdlQcVoaDwzHUDvd8Sb1pd5esRbTh5ZguyrDR74k4d5n+vzHxjN/7W+ZFXfl+lVXoyhEiVh0QAKkFgi48P4zmn1WGk8Oq9758cc81dDP8lIMnpKVT46BGq786/kATMe/JRpFw9YVZ6ebDIp0lgwvzQs/27GAz8gdL9CKDNjKS5aBdMj8KJdp4KUPSN/fVXPmJWpjcOukc/t8OU1//TarOWYX68ZNTleRpm5Co+h8S1XBLRI+VOzCSYRQicqcnEUp6ykKzN2kIs3qqcEjXYHIwvwWChVWo4ihdG1P1glOTE3qPhJXLLGGsnbc5ZqHleo95pTTtAMFwowLlDM9PUW72MPx1G2c0JCLfEXSQD7DviGdv04cSK3owkaJKnootzEMfK9JhOLjppGuoQdUIVEbYwjaViB0+NNObgwGbQZ4Sm8Wp6EgN+tE9/YUKo0upYKpNrFgZWqKFAKCmFI7IzWtTWuPiBpLAmqYnXoyIa27iCDtn6GnwkNgRwxOejbI71MWO1bLfgHwI7T4rkyFJnZn+6KvJLsgEVMz/Lu/yP2oz+a4bXwVjoJaBh664lqVlpJLdQnW96kF1VEdVijE49GZvtbuxtJJLvP7F391ugOSSQlDw4MOFmGrZ1LhLGrnrJPoXZZgN7oLySI6xukIv3muTxFBAKa7EXWcBHCRH5wBXh3zsJOilSnRe78/zdVwOmXyxglagmyLbU78qvO07nPa36VFr7Jg95uCaDppKaYsxr2UKroktyFkYtCMpu8/ZnIXaI2t39rkSexsQ4dACHVXrFfkFVOyU6td5nxaS8DQObwmVtk8qp2rq5K2wGFmm5oCcZJ3OPEXJL0thDepWdaxUBfebc0x7Qv00Z2u5vJYsF/ZHNw5aCWHJjo5pVgrzcsuvYA8SovZXqtNwRmoKZLsiIh5eqcGB3SGM/7RFOYoja/Xvw/ZOpf1Gp3EdeRZHfc/AMG4e4zuHP68KJgKDA+BaFKaHxOP1/mFg30jqdc+DV1V79eRjAJiDWnkiywiwLAJqFYpAJBPmzQrirm8wqhvNLFFrbuzjgDyOIoDFV5cjJXX9UmVXO05mof1TSWekgrq87kXch/5yd8+kqPfmorGdRcOrPBbHrnDfI2jOHGLA805yCtSj4bCm72mJOHttIFZOzb78DudjcqRpU2T/kvV5+nITPrMAbQk9684dSXztWWn1iF8rsgmhN+RenpeQQxRLlyKP1M4Mev45uRU7lKOs6PLn78Hp9/61D+rZqFsQ5syK0nXoHTU+vRePSVDUxBTl2quwHaiJKL8VQGQdE1zT4R3opbSXfeo/rzupzK1Ysf42lFYBAFfwUP5ZY6ThdBFIWINAgZxgbXuGTMPDU56cqctwhzzuhlIvLQ7YL6RPpzf4CGpH53gPzEFzYollyvHYeqfuxFu7x0gNAijxVllRTTykjjVVqKQCXZ5jH37ugQOtiIzndkS+xqmKCZyDTltyNwblzGlU2nnq5CEa27xX3O0PkxCsjU25m5jJvsXIhGAi7U7P2Nkeh5163UjjLZ5HJy37q0aVvT/506/bkGsJ14PaWBS79AUdB4X8RgKcWF6LW6Ytt4Q13LaJIxBpboGeW7bi3UKjeQvrA3aFHYNM712jxwcCnhkXdX/Me1bn2a9vwqAKfsHoy0OyLAgo7VBTd2symc4rt1xEz/Os14WefgL7kKMClu5apN7I0o6hPtAqPLyZBTL3VbbrBXbMwSWqg605I5MT2fzzoUSvjet96UihMUscwkRWnISSmOtH9N24LkScc2AoBVwz2DLSSzns3MBHL1NOHFIaCjgKaMQbF2/Pvf9OCGdTXm+z8WXuh60vVMZ7itP3dTOnkamfUVap9ZklWIkZ3SpLLK9ag7bjZPOy9clN3FLup9xYU/lPGy5SnFrVxgThroznKsYRhpPMeG6MejBpi5VEQ17gXBLlObj6JWc5lxTY7qbLgWanaawu5mwHBu/Q27pF1NoZyVDT3X/JCS1cvx/7rXtZ+sJNG7LKaMi4HNBOcwKSDcUjNd3bgDCUnuqXwUYo5aWChUlSByKd8ec18Ras/0eeQ7DGuiz8nUzgs1yAJU0amdE2ROBS4si+Dv7grJbI6vd8aKiPn8f+blszssYdtohf8Yqhbrs6/bh8d8E23SdWSgfrBDtGfpMiD84sT41w3jECWSV2UhYl/m3MilGpBXe6BWnex/E/nTla6mk700uanacJBbVdj6eTgrVFqbGMYdQynKK4ggDNx2wYE3XR2jspQrh1dRnv3lfBo+grJ0MM1akMIjLlLMb8Ir9mydg16C2u1xku0x13KmPh4jj+/LxvRxx6g96O3v4PBQtvc29iZ/OGrGJ51E40uapL5hLrxn8BwbYsiXJ8l3IEAbMRjUBMBTYy3y3nB3ddJrGiIrD8TiU6h4mFzcgc/MA5GbN1Air0zOCqGDRImshERMibclmaRtTNWzhFecHe0ARt4G6nncgSt9EqT3Tl6W+DEnFKVBYzCqb5mGLPlcUU1/+R5UVw2Vlak97NczpobD4GKMLZ7owNJRgSNvV9jy23Ax8Ffm0lRwfeZOxHEnKv2i0OjJKUEmXxLIh1xECdrzQR3ImehJMIfbEr8NkFgRRObM9SydszZe8/TRKJ/lv/zU+Ti7w2U7eZdVxCWJaNEuGAZSS04yKPPmHu1eRkDG8kuRZG+xUsG42pDzuQdPCy3x/ZtPYSvBC1IezHyzS8V1X0dFsS+W/SXxHlApBVWXnvNvt8mOS0TV5tq75snKvJ7xQkWcPbHT7pzYeu2zflOhcDzh5OVknBt5Pv/DAmGxMAy4mAx1+WK4vOit53TOZMIwtle5iEw739Jq0vCFWX1wSg5WVBquDOLbBpO2oVzEK52McUkud0p1OeOTMYsow3MEcrGXULHQ/EwLDQpulJr9uyDoeqQc8Mhv23QL2zSv1PqW6PTrk+NfX4aqqpw1y3Ricv5Nsmkmf8Mp9g2t7uS7PGjwBur9Rk5NpZFTO8wJ/tgbyvMxVL9wMMtumnDcqfvOM4hv4R5raPWSBq0zEu+nbxsrR5Dgy0N44RDau6VKeyzqI3YbXa0g8S17Bvl11O2nHMktACSXyuf9qv05s9K3d3rQfhfqvAZLr2Mb2E04WclVk15z2FdRHiAzShmQRXpLb3PU261ErdLdWIDYAYBfod6SExROlMWb2GoEQkrey/zpMsFUhRbSOuq001lu0CErQlnlTClyWqtwU+XPG/11nsXAab2UHvMBz7ogkR97TNO3gRLGxsULoKyGxQHuKfYlEm+mi1MUOGrVrb17mr0/lMcgdbtgQBcPPqphXtTI4Sv0vaMBBi/wvF9g4/ZM5t1MXQHAJ5luELMzUmSULEel5iPRfinDUFH0iolUaBWMHGIEcsS66HkHA+exD//psONFezORUiaYhQ31c6GVmCNoQOwSink8vIbCysbddDyBs/J8HiGVEXQf4U+HktdpJLoFvBq92GDfLSZWYnHYLAYfkRsreIsBmbXh4FVjpGLshDL+UY/fRFyY+bS1nXOtdfbRk4apkTqyB8M0Pntk/egQ85+IE5jnQdKbtyq9OtNDUR+JAXyHHuNMZcQsYk53g1T8lyrX535xMKFyQg5km85V24tfXxJPajLaR+wbhpfLcjwWiiB1pPI6NhaICt1cyt0qkdLAnDUTUukRh8Xj+EyOgfNR0yhG7MjeGNBUfa+pxx/b2cJdmznCYBGHmzRxxSNb83SpLc7/PeE9cs1T/nVB7XoZBXkVHylljbeZWqXhaS1GB+UuaPD5Ul+6AS5icjJ6MG1VFIxtpvkhwlmY2+jc9VGBZaBehIHHXMqNR5E/4ge1O9NTO2M7y/jpLHovFg/6Hl5tZ+3JzFV9lZc4FW35zN9Yj6opnOoMNmxbj/01LjkXj4DoCEka3WEbzpTSalLKGHWEZ+p3X3fsSObDaHJI0xHKnp5q7NGrZ4k2zrSmXoZXuVT/MHxI/VXQdFd6RBCJ2LLeuMw3wXE/ODco75doaagJV3PU0zB3wgyggkrTq0qC5nG5lLlqvrvIoHgXVpRhnY4ZJHY0uIqpvhaGbd0J69ps2fKAInnSfcXCCs7nqt2Dk3O5uZLK/R7y1zKaXrz+CtXhhUK0T0H+9VLwmAMUnl/G0UflMX4KMlO7fa+wvr6Di/HEZGcxUQ9OhVsIP6jAMYKRbXgy4UA6nrzisGcMwbWzVR5dZmTameItKubaXDjWhudSi5LRaoyti0/xjKIvcWUs0PdTOwIe+8xOlSlsIaz52Nrhe3uhOFgojr+mWAVSoF5pL0Omrn2A2CPWc0/h/7kG9QWKM1mBHtlFM2D3vHcScvXkdoikb24KvYuUKZCJMl2z3pchO+CpRIBrnWpowqLpU/+SdRdqFI2mQCauBn4oYWHuUHnauDHJUppmPumF+CYXb/2MwtqyeyzbtR33oDNcXUYsPJV078eCfKmMXv2EJZd7dfvh2RzekRcrecfXlfB1iaDcmZJW0KiT5+Py8iv2RvNpUGSWnwE7ctMMbdqjiemH23/Me4hqvO2j+lq9DXfdZjQexlR8Dl8SV27F2jwquGEimUputFCOmSeD2hU/p5GNsJMmbkju8+RqPbDJ/0LJ+0m5QdG/0Mes5qnrQ+jZubcAE/1F5z3TTktWh4KrZzM7CeRlK/s9u+/SPZUeCUbcUIq09Iq5uoloVq9yPFUZnLsnGFWvMQfoekNwt+RuByea4M2K+bW0l+cqwSio8MnBMAyj7v5FKtORj+iMpgfdvmnxfoIf6ufxoRuRJnhxPU2EFAoYaoztanYz0MSZrK2o6WqX1GAXV+WlF2/d7QODqdzdi9PBrOIwIZ/wU234ZpEnW2EolOkgETF8ew5CS3YRisgx4my5ptu8/sgEFmQw+R7YpdSSPW/iSdvhLC8eF86C9DpBQjdWPn3Wpu7/FfVUCOyS+WigNjVoWwveZ2flRZhHZi5nXGU5ZJ5qLR4HSNe5zwEyx32A6Ioc0ZMPJvmdHrXj4rrUOeojjW+ISImFI77KUgAFbS4Pifakr+qTEvWRIpHmEW2NqpEdlcvTLoect05PSnxhmAXa8z9+ivZEMrvYNi0qkkkPMGGJDQ7NzjjMv/fVOZvGyy1b6zbYCjmT2hvOU1OAAIusxIN0zGePwTUlest+Hq9QeFT6j6qIKpGkuI5Li2zMGayVeSwL+JAzxoaszDeWHPw9sH+AVFICaB71WnCpiPkLgOiDWtt+Z+nyCuZzqnpciZ5thLZXZd4uFhj19+IznsqZapTVi11HyY6j6GrB+stuyzgxJnvDWoIZRwnXQVu6MUgIW6QaDT54BXxV+UsKOlFJgyjTEwYS8zzTHpwNV1cUKCKQhDSzIT8RmKjSSoKFbo1sP57yGXO0NJ3e6JHnG/2DXOb0RHoOjFy7HGKOP6dzsAZXROVK7LxCQ1sYse8opVhwvY2pVEZDk1SJvqWXeMrmSj1l3DbUeUPdSz6otTmyMbqrpvaUKwLRpL4e3JCVl1qNfCdwtfBdq4pXTc4J5/ZZSkPLkdiA5LQIlZCVE3O9zPNPxElBhkucGIUOtLE92dKi4cP7SS+3GSWcjwWKjSnFDCkthl1uthcxTdd0Gwlf51/oDDk7XvrLhz8VWMQf4BnuK+Yj/LUqV0ple3MRbRSmuMS/5C8k3GS3QDOa+hWGuMBWiHM3oJg04WMeIpqop8f3Kel//njQwax3wTdaWBc8XpwByJguk5M2PLMOV17ktPhREAzS8GaZ7Z/+LF4+j20ogJjo8Do+rIagRt1mMwe0m4VkRomrMn5CJlNOpq/BCXoqfKI2PQ7bWFoZtueEqEnFxWJKsIUeAyU7ih+9yNGAl0d04rfUjA9MAHsBdxUaCylaZ1uo16tnD50VemZI4MJtPtFRyHhSkE+39Et3lsBM5lxabRN79vCjqtpBpk060AUmciq5C4l6Wb4vayDQqtDO04V1ilmtnLuzeIqj0nKyXA64ltg0sNRB5eDYhCsqo8gntB9yTY+ojJ9LlNhFLF4N5WJM9tLjWNZpEVfNBweFFUoDfr6ujCJw9pixHpVcx1PUuwcFT1Z/nedn1ZmGjdKgDmejboZ49hNYqCIl9rV2MH5HdP/VsW2J+1e1WkLOqFJeov/d9POhovpjUPX1xeAhe3dSn3aL4yF3XuF/jFf+3//7d6rhE4PP3H2ih538cAPSQ8+e7T30g1J8GqETNQvHVPSE+wuDVjqkwurVGBsVDoyMvmMwp8tyCzI2ShwPnS2htft4EAQo5bsvLArbEhOYv1aFmdC575K2VeUOFe81THDZRx0SQUc6Bs320Fk8+iM88ac7K4XWxSTUmM9td32/3fhDJZZk94iyTK8J4AcxqTkLlTD00Jr35UzZztJA7Z5w+gnVc9UNh3Bxlvv8NV5n/YnZbhh+Vc5qvz1uEr7fmXGEdZswB8XllsyL9rGPU0MgP7IxcmRjdOgqPgstr7r/H2JqCn1eocObglthGG28xG06Dl0hbupsDRqEfzfVxXCYUkU9j+ZhkdSHhl+citp9TehRW5UCjmpBqoCanTg7ea6F55roDgxdiwJdJh6lxXh/wkvqHGRSohd0fxv7p5Ct7VKkHkJf9XVW8Yjb4StckvJ//fa9Bym/G035puPrXNRjOvG/CQ9Yfe+pYBfEMq7p+Y2ArtKdfKQZ5lQUqqZ5ej7UA7X4rtxCi6pD1jcIIt4lD3bNyEsybacSxJcOXBQaG3zBcltLKTJgxW1LVwCK3uJxHBRdK6pdVh6P2H4rmO+lzWtM1BZf40VZ6jGenRAJ8DuD6UxnTtZRO+9ObMQKhabDBCj18/hF+dzRDCmjYQr4RiVYKY7H8i6kQ0Z3ioc6EuJbpQKt1Fx3mmdxPnlhv34pBsxihIUERlA2vTT7nxoGEPAjX/9DPOEoizcHaP8V/pLi52n5/mDTepbG4lM+rz0Ei8ojmcXnOEasZg9Vd0EFaxyRyqXYX0om+lufuP+Lx5DIRTKSacgPNCOinA6jU7224YGps93uNs0BVwtG7PCllE/37UaTVhrpznS/8Z2QPCbNiDzrXuh5gy1qBCuqGRXyPpW7NHa6Ra+eev00y31obHmPLtCLDpVyA50ztqAGT9MIUS3glYWb1hp8n6p8R4uiqtuT+ngHnSGRG4xBRV83xnBKL0hIdbMCKdF/FfgnEkYrXCqPAMpGdFdrEd0FbaNS0uj5C35/0SllfWu6C3dHvfHy3vCtCDtLD/RV+3YD/hNp3WvsS0FuvSiIJ7b4gWW6k+TX2J5sRT397Mxh285uGNl65+m6h9FerT8X5VEuUA4OqfjlsSp2ONjqXc7J+1qQO2feYUV4ZkYT4hXMK7YzO8exQuAoVJZbKy/F6O7BUZzQxrALYFX+9a/ycO3gcNwsqz/YTytFxwma7D8X98hEojyFZYQw3akgmvJipX3gDfNUla4iY0MHXqIxIA5crsFSPG+jU/r16oFnauaMUWqjt56M4VKKMZG8seYDKrmOK4j9jpyhXc6JwbmBhC+DT94tSXW9n7LVSY8YyhnPEUAi54+qOHvkpcaa9VM57koRYW1UbgkwWHW/z+RmmixIJvfN4PQezPgHk67RfRY/pkf3FhMH8AQ75sOKzAGtyZ5QSpOPoWFOtnHb3ZSZWI7jQxm5QoKPFBHlvOI9R9w2Wy0PY9jygD2mk7Ge2DDSoKWLoRuJTAw0uGv4ZAiIz/dN6w/LOCn3p1rQ7uiA2v3CM2E2JBfkcPNEN3CLf1fHXc3ySK5tLKytSg3AHc3ykJUWN+LQsiXd22kx67sa5xHCQ8bdGfNJtnADgozez3KX8qjmVHUSl6ciDrSTDowRwlBGmXvgpVf6eJtb+4Rc9X/s/5svoxf95wIGugA/TyqMjs2g6QoXBIodnbP8ZgBsyZHYgoy9U3s+3WHOHy2IbZtiXWYEnyGqbuYBGxnQ4Jy3ebtfoPOwTIwRwZKXZaJE4F3xXm9Q2ndqCg3qx41gq9f4rTB+W/Mwotxncv4Z5eQ4khWRfghBRwSp4pVeUAYmP70yV+ryJ+EdWY6SbnmkcU/uTXnWccOH/rcQP7sSZnDPd3743txa5bWD7D+KnJPOTpnhfBtUqg/Ezp3ScpQjeA7g3aSyE/lV8ZSt+i7qon9Vvc3rWPbdtcX5LuefjjA62/Vgq6WbXC4FV2MfVjmCK/TVgsLZmtPKxB4ifrtcTOw8nsq5DqVRSbTGLsux9IjvBxrbiZdKdLH9K3KlAiKkND/vJf5IzYE8+wXGIVPQ8Fl8uwKDxACOvVihKdm/EEeqedx+ne1OwNg/TwwvcnnzQpcfRAMbM/uF5GWnAQPKnGgmRnKiYmeA01psgbL7mmq+oI27Z/CWtr7UGBEC3Bn+9eFyxd3sMe9txO81qujK0rN2JyI1vjeVlVPRmzpiejG8xmnmYkmrHrM6QPoobFWygEucODVWnjD/M4/5DlHFesK8qJ1AgvZ7t99LqTzWd1LgYrq9GMUv3OuTuN8J1sgr6csBMtz26OEuMig/d9aD0lCQ7zt92e6c9sE0dAnESHGn9YmcmJqmTD7rgtvNcB8naUY7ttj4a7hcBJln4RthAv6jT89Ip3N1eH1CSw462iKvQg2Jirn1bSSXPlxYs8E7iAS4Xgf1ckMSINNSb4HZoPOQ1EIAW3prvLPUYl52nBPPGrz54hmIpQeDgPe5yiokrVygRhXpOjVjRRFgLBYzGSydc2tdkzn+5lef4mwCpnEz3yyN3C8DvXgEjQfcDsHL/YCPV7l7y/cvw4BfnmxfYSEWzJk3Q1Hsi9xDYyouIfe4hNzC0nV/A/YOXs5L+97pXUUsa6YWEMC23IzZMAHLgNnM7W2FWYMCUferR41QStRq1cUpOUdAtSJNuExUFnPqbqkuZhjf6xZtFYoyViyCE/bPgk/sL3FK38R6fvDOUrcvcLirumGnIlpOmKZq+PKaUh6Xx/QoudRDUylP6e6EtGwvCbWCw9NEZ4WW8cinNOMp2F08tpZcV6GIN5FxFU9u7EEGvkwtpfNyHk9JXtTI/6pLeKGJtSqHq/D0Wu/uzCopwy3Q/VS+SzTL/bV9k/D0weNlFrFY5Cwe0SWjTbRz1qOiYFfntmmGiIXdSGZdJ9ru/s/flfeLcqRRPyiCIrPTG4gYBxunfO1hqasbpe+F3u9SsCRHHxbE/l6kFQ+xGTQuhnYlWxSOw51n+3uJRYa1gOgwrEwtXyWEzQfRcv1B5vYisu6qIQpnxWTv3wAKqE9V/bSSzzOVs+cpWONfOEg8P7a6BKhcizta8MqevvIVrtR8227K9aRwiTkDdo6VqhTf9wv4o2hJ1b1FyHO2/uVQqQtZiBpKtLTC7h9V1uQpewVRliL3mG3mV0Vn/uyMmPUZYr2qeyoXMQZDVkeW7ZvRD3e2CtXO+5u604Zz0rdvn8cvSZIhHdRqJSHgbNK9XbBy/sWKmFOv67VhynTYso5oKTrY3A3M241Xt3EwyNYiTa/mQJKJ2ThIO/16zghaaO0sXzmSO7n4uNvyG1Plx8LZeRCGj2AxKjXJLjo5CZKtiVCSrrhSAcO1LeJYzEzQpnw7cSwP/DgDn8fgInOsNrr9TmPYq3chXRQ1xm2SCQ3AfoNjqpdgEXCheZJKd1VN0uJv+jTKozplcdDoVXy45kt1hzElHvc4dW/JlbM7MueTTvp1dpyb6vFnNEUFWa7QlCy9kFRq6IYbD1iknY0yYYOszDb1Gy9cuoRjcFe9FGa++FjOFukjCorpPJ2J+0qEkU6PVxCZ7ApHEk5wApdpxDidG0rlLs4OBpKFDdBbZcZEWxPF3JboAdmELZDxeM+WcDt7iPD9WP4oVVl6mxuVjQZgkU3TGXZOaDBKACkMMpeCCpqHEBQUbEanakInDIe1Hi4diLdl3ZEIq9zcLuvBV+Qh9+rAl8GZLrqxLkUlMuUelyIzt6qAT2KyqwpIReepCDHnZ1e11ggLwbFgl1H8rF2o+PHYUNv32Kv/5TcK4oUQ5MDvN09iUoDvGJ7sXaOHKvgQjCF6vL8AGuCx5u/Z4FQIu35g9D7ND/jGMqRRu/lqaDrRzlHNGvv029eXqNBT9vCqgozAx09B7+oWTFzSKTLamUz7mavHj0nDUnjAiW7O0tHN3UHs84+Ubtsv30/XZNFpL08KVYUceFPrH3rTMgLGzsnpgX8iPLC13N/dJy6RPrmmO7tjtsA2CLqglRzVd2PN1VAmVsGHAhPl3pF+exh6CU0sC1Zj0GPskYzrNk8POZPZDOXx/j4CiP36F3nET5jAFCJ78iXOB/Tlc6tZQz2xeB8W2Bxdgq6KVRx08mmAPIzKmVelnwUsXD7dQn/yBo5xhVQBwO7NY2YVaWo6FAakUJ6voKuZiMe2AgAmhw5Ot8KqyTH7wXo2xSYzyndZLDfa3t9IFrunfFwAErxhW7BHgsE+HzWc34ul10zTT17jLPLxxcWgEynMe0x5joFzrnIock4XumCbTpWd0pmQN7cAL73MfrpiHs8juDnitss9jzZRWs2GBX3Lshic9nkvS6z46rAU5wjUEeK76elEovFkTgsxonKP0AiLlS4335A9mwLOyqEVcuxneaRpRpim/RtTO7KyCb4HuWl4zwBum5e7K2sb7+AMZXumBsr4GJpQ4Crr6rP4KLzkmUOk0Q5aCYmnJC2yLCyf1qfieJmKHaFyJDkAdkaENWXHYp+qmf2gNWwrBC+UfKYNyXQFl+9/meUXZvmNvtvq1XdnXGB/Zd8I5T8VmYfccOGgXSyeL6aiKQASpvnXezRVSCA42T4Q81W2rvs9ZZ4K384vyUDJ5S37ZFlOVjRl9Op8Qc3czRnlDZrjpk0BZzWw0gs2sWEinpeQDnlLJfrRPxjqR6+zs/susOjsUlVGv31NY5gVrsusXcoiLpuk314Iz+knEJhT6fKEwDAJnsVPAIWYDMxKCVZIo8HFc7v/cb8inoj3SoafQThxwpw2icOt3WV43H2j8Koyxoq501wlljEOGwR6446eKLYk7JVvpK/b51elJ8PLbBp9ilEy9AIjGqApJ6vX7Obdck6xWLXXNUn6pxCH1/n91M7xasDl6mu3Xi4pukPFMJv5xuBed1fjqym+2waQ9fzGa7bwmt3ZSPBEGn1D4yps2MAbB5P7zq4kXrBpDS2X9LZGM1NwwIuV3pmCFPmUj6TvRJk0R9BJzIOu8m69EWNUVSLzmCzfY6T+Zgz6a1/D28nGYisxZbJn7q5wS5EMKzWabiOjYpJ4ZwsutaZxf/4vDA1SWMmyMGmpm9IGNV0useRbrkGoFqPOSERfOEI6JdzKNwBDIeJy7C1a6sQpOwWly0Lbdl0V2zTPYUJj41diSUdzMnQljvQmx+qzyoN6bbGxFlRnKG9OaARGaD5lRKJ3rR/mih2mrPpNUNMBgWQ86+cl328O3y/f487Z0AEM9OTBJxrbrempa96HNCcjik2U2p2+0WpAAoRjkOmb55dRpWLGHhgFtEjdMVl8U77+RB5vPQTg92g5v/pR00/4AXasqBcjx0nbOmDzdsK5W3PJpM4voxtZf4En0ZqY5cVTmxXT+0ztZtRuAwNZalGL0z4X0hsuueZEZjFGILDNm+Vk7mJ3PIPGnazKPQklsTAhOiLz3cvFtaar3b3f0iBx8Px5zGGRNJ26Sb8dhV0pVyP4wSxDoUhHWlKFN5KJmkkItBL2PQ4OsZsqmJW1Iikn5gP7lVcgR3uhBqdj8lnnPUCS4zexqW7jFiQvbaSYiBZO24r+fheMsesrl+aDEZcX1kw7LC7gxABOgOzMox0KMxjaVA2xiiyo+TTbXedv/zOt9iS74ilqQaA5BSs0F1T2Frs+pXxNN4zI9aKI4N1JC+gy23daQHYLgySG7lDngBb2cB+VFUFncuGo3mmjIbIWRDPdAxpQNQ9SL6xLjQ/bOJqN7ZjkXFoLzuJbhztkTY+88ohP/Od9xR0quPxbIY6vj1m5qA9CogQXKDYXX7DJxnNi5ZpQjQft88iOY91fe6EnhmuHyova4sR3znrLChMQz4RCVwgjYxkotFpV/A+lnrJmuoBzaHlLD+1n4c5E0r8byEuoPn3AVSyoEWxbMoqMHDm9Se/yPLLoh3CU2/L1Zl3yz2sJypfFxGzCNJCzQPWue/WQcNvyIAID2zYQIqu+ZAbTf2mOlFmvFYcddmSbvjkU9FSDhemlbkuheGPBagzUrLj9R34RU+WVA20YEbqmpTm7kF3Oc+ABjkAExkpNmXZNp/CZiXkPOscJfvpJMVFP92lMPAuOpy52HNIIkRZ8TjMjdFKQBcQPOua6zt9njFpM4IRuX/zvTeB8thxb2aYvBA2iiHBPEyeIZvMKShvM5gvzC4nOlUFVVzjU0V4ZNGdj3n+RAwcfwtJL2+/oHpVsEUQg2ZtaupXPM8J+a9f3Yo5Ep7BQ8oniOWndJofsGB62U0bM6PGBaYybZ9B8dnmRsrqN10jR6aY9E8Ns3BedDNQzhbeHBIdKu1EJrXKyw4pNU7vjRWVOb3y3RrsN1LuqKB6DlYoi5P9aSufGwkmEzZbi+BFcfRY3DhDAprU+hxL1Q6oWjopFUenxf9qAML6d9FQDl/6IdA3FFEmzMy/1GXJCL47tWx66zl8DjpPaPWRuzZPQ+/TAtrnc/dGGBz+Il6hF30TLb/l25SyZ3ZQIaC4OMG4M46PISipDHClQ455F86X4+nx5wCejxdUss7yunX7QcrSzkqiEEOwHjapSnXKHNVO76xs60/qsU4Lj0Vg1obOVGue1lCga3fM5ZSXLt0BTN2fDLcXQ0R8v9ISDQX3mGZq4ZSiv5mHmnf3WJQsX0hC31eleCm8+h5t824p0niz0OPk7VutxwTWdEi2/ai4+fsrjKCSOsQRHcgIdsrDu9eZWO58sU9qVGGc2tdK6f1zj8nzM+BNSvTngLZLOPeVBkc4sExvTPlVvlVu4KpxIafMRallynNLctqV4kd6b56j4+awpMzVfRhjp8m/FShXf7gUPf4IsUyGxL/83S9QPjovpFcXejyg5VCXacJS1ArE3AbnCO87OFOs5KE7w69mp/8VCP3Cpt6BQgSdzRogUZ+ZlcBLRIUPI3xPKFig43JADOZzckKnc/JsswQs3YUOrO6nWxWBPNTT/3d3pmtXvCD5xDvc61yu1i4g/H8dFfxM1/MFcbTwph0kbKOLLTbvUHBmilMg6UFtyAY+kkbLmJSIU9nTNXlgACzdNEZ6djkPC+S7+gkyIDNYSjV1qEYiGTFNh5JXqsqKQc5I4NuGqlHmFAmJlKMMNk4OOWnaR0jyfjvpYWjzXtQSanf1e9HXj9UB+Wwv/i/00imONBxyzhgjNE91CPtgh7GZWOPskG25J701+zb+YxTMEpyb4djqE+TErQhGdoWhCiqKUakJgFe1AE7aaiZRq3rKNn//Cs8zHcXDTV+wfzCj/1XGL8HyWIL5ypUh/k+Q45lowNgLt0tPEXjc7lcmE35RjNz81hPNKbuW8bSifWvdEa8GAKswPxZl19b3mwZcmXQx6GdfbVm8j9OaxPxmuwVS+kTvQN5NrEjByDaDwLRGiY+3k53lswAlHzvYDXdvuKSQb3DtRGdDZmU0mCAPvZosvYUErLazUvFLyurO0d7jF/iZ+R/Z6XIXSD9X1WoB70R42/rSWPFxLyQQJMeZefQaeMLWoFbKHkmhhoUJ3yUuGeylHnHCePrjM2UeWGR/PVAIXARjWTn/jc64eDcUFDPpEaZWO2MlLyjYYodXiCaGdv664/IWbpnCXfP0wgxlKmodZE7RzevErZc/BdY9Y9pmFTSfJdv7FhlnGU72o1Cp/tDs82M1LWlDMW7YmWw0UBkNg1XSNobErwOxN7GZ08bU6FQTR0/RR8EVT3wuiTSj+K7sB6ia51d8Zob3PkKs5cJudZwzGd7LAHcPTEDqI1oaMKUvGRBGf2K33EbJTfY+xRj7naKgGS7slVyqEK24dRYzYEfBZWAtVyWKx5I5604PkWlrUB8pVla2/l5jNR6TtYqkspQdBlFsqgkdIl0RjTRRI9Z5OB95rQJH9U8PSsz1WoX8MKnOE5CBenPxQo/iGZ2qAOKM1Zc9jwnUOj7VqVXqbp8lRrZt8NPU23xlHSWUn2mX7oKyvKwC8rOT3hYvtUcSmfMS4y4y+coR/cb9adyrMbubM4ciJI0OIZI2CzAMoecrj6C/uuvcw362fmRJkGE0s4RIySLucKXhqMoSm3J3G34rGqNLYFEFN2BURJ/Lw9vfhGeXCaE6LtC121UoCViqLgdozjuOsHEMm0teRWpYnEiCCZRwJRkcTIF1xhcwnZKL7/t2PTJ84fTtIB1P1MI9tXNNJ3MZ33HT5cI+x39t1NmxFQx6UJ/va4wyYtOtDCD+tf8naqtkVV0XUILev5Jd48WDwzuHLkD4P3hh7tkbncDPi6NpS9RDVllwVO5BhKpV5oootqnd5twcagsJJYjPigYtntOiUqNQ/wDR3q+SOhHYOKrtUg73+EaV8Tty4V8u2TUsaOSVmBvBSOq9Epd0tQgrLd4y/PENszETdTIWKP4lMUVcMxmjJvOR1PzSECJeWhJFmgH9aJdCdPNrCB+IeXBrokpzumNMNlzbkL42WTRowzwMuvili9ydoqtdsgaZn6+kH8KHJLPYTK6O0lwcnfdKswZQu2KO0xBcaVlDoxO2fYJloaFg5P5S1sOG7+eUVbuWW9iSkPZ2pmQB87jinNR6oIxL2qCYLE6piBfZZvWGxDVderWFhlIENqkhRKI5x6DZPbdd6SBu57dGUZjfrEecjW7Lo+C3rjfA1fzalnHe8ArPVnUjW/GbqzdN6E9oIKfWkLG3MGhY23H7F/b7L3xPQI8eqtDWHqBT0QWLAZumfxIBGx7Io1Na6CYTKQ+vpmPumEEhECVz4UtUL2cYMZWkJ3pIwfk43Vkfc7VBNTc2AZ/6mTLMPX2GF6x0zSln4ITEtnEvGi2zDs+1c71v8wKgCsVIxpe5dV30RRkT5oMmvB3jK/3xBeBuj+Or7JEmq6pVFyz97tG+YLTNFY1l3VEjvPpMu1Pm2XEA1W1BhKUyycOlZZryFZqqfruf9aclhvmeDj87j09e46/yP4c6kHNbCaEv+OHMHhWmXnYUkjzJdXpyZxOYZvKMmx/ZrrdbKXQePchuZdGDo+9LoqyuCn4TgR8Ydfaqa30gklQHuNnloNMUrHvlUuFlt+SJPU7SRoz6jA9fqfN+HUxEW1usB06yit+0K5whi/5m6+KTPL4S4CoycPfwYI77SMnMOX9kob8k0126Oz8uKj/4GIaxUwZNlhllACAP9WPE6iJu8skskKsKHylzE86iLc6JbCmKpwmB6IKGaW9vNnJ1Qh680ZM926JX5WnT7DF3D3b2/A+3vRzF7o+f287f5Nc9zebXTXq5Rs9pfSUJmZPtkX9CruEgymVM6T4Zt1Zx5Wxxy/MoUUx5IYnSZlWSNG68iq0ooA01B7ay1tcModsc2KQ6moFcbTPqNB5tSGLM18wPBnFGpCeRw0W1mvWAVAx0grUeEskA47vIjFCrHeo6E88fZ1Xk/Kwg2HVGEmI8txeSWbmLD0drtFBhyxlGrSvlkOEvfm0o753LPLgzOy+HFDWlnoz1p7OQbXkX3n6JnaBTDrTiponIuJ0RVRZFd+UbqSLwmFYTgu7KFif2BLHB72JqHPhcReK1foCCOjaljY7ZXseWH7juBdu+TuWO7S5rvEw87RkjfYYJq7mWaA2NszgQ8Kr1Ow6+XMcUVzqm1viBWbKOWQihyrPLN5cK2QhgY9MGSbhO0gpa7uJzcc4UIlpzuYGDF3A9Br0zxkFTJUPFaVMlNB8Y6FhtFZXKZryXch33IsmeJYUd0QjdHmDZCdItC1SRrgk1pbHUz0vfcfIBLtOvrBF6ZnL4Mpdzo3IAi/GdzsFajMqwUHTezg0VgAuo4UXSN5mFoxtxexG4bngi+GLop6ybXGL+izL98jhKubW62r+euoJscOh9B9w7r0m+hHt/cfv0RFYm3Rtmng1Iu05/kKy6ZgnZicxpcO4PxjUxIwprkLobsueooR0Uno+7xdk820FbvPqWXiFugCOrNReGF71WRxmoFLJ01Y5NQVIrC4ZIlbaMb63ATSTP5DFnvBDHsPGkv5mo/9nT1DXX+N/P13vHb0DI+1fBQxSclxLTQvSoMhfdsWVAhlB7f/Dbfih427C8D5UtXLMmEoJIlslCLp2Esyd4h1KQZmEltmhHHqdV0uArunkL0Z6FlveDHneGgi7qv2PjidnQ9bG2s8HsUvdux4q8P1NjxzGdchJ+ZDlDYLMbag7nrYEvusaVsFiuT3sLc3os5Bp4uBYLXrHTiqgTU9TLKaHKHWYgByebu9IG+fSZZpw4H2egEqcJK11BvSFeFy90Z9MjgjCdoySNOyYWce/uxteHsWXwRVRHES+dhfj4/cld4vOx8CL5/FWN+dESrq+caFmdzcu/vCQYPfCgKlRHZVCC9Cp3hS3Qf0vIQmTe+NNzX+G2l2D2xcO8o6TqTyNY9pnoykSrcuLKgi2PRuA+bckB4oW3ezq+CNmWyEzOKTMkliva3bJq3Emj4sy7CG/mR4eNOWw8RZn4nGPzHKszF27lobad5x7BE3ec8SDJxI78ZzekxhgPExBzUnin9CxlmkWxKSW/lsHTMcKriv27mlpjMxkURlMb9pl10Zh3Q6DQmV25hz7VgWElMl9UUDb73f9Hxo9uS/YNlCY/+613goa5jm28q3Ky9bqDLx5Ohh7pK9fG22ldvDBYCdRkLJ0MupaqlHhMaJjdmvu4HStDfY8TagRFLkcK5IkSIYfKk2VPgaVesW/McgULHXxipOPOX/8aqB8eqERp84KuHGKU521h5NsNcs39RQUgqtHn6Zppe3fYtzv5T3IpIUjemrd0czdkcv9gkqluueSzVY6DzdNLfpvk8kRSPV7jbjTxvNDVKnpbF34hiMui6E9zHbpxhkjriA0fwFVSvl1qclVzu9Z3kl9WCICbz6vDafWbv8jjRFdHz9d3jAedTJejO/nPvP380RG5nBcGkcQH3WfwoU6tFvZ2IV5R7JxpkY8NUqztZ5ohVlD0xCv+ztnfZrWRZtiv7BdQ/1AckBH+Y+aMr/YS6ahZQTaEA/b3oY5pFxFrJ3GcnSXW4z737nEwyGMvdHnOOeaXVz5Uxm9dqWrogxACzJke3Bey4P9LwHB6eNLEbPFRBGdsZ7NtFyFpRbXSPNKzWw0Uj8XsIBJt0xOeBc8llCMihojHS1T/WV8XE79g2aFsbNN/iuBtc5GK0StkQNFwddBzDkbANxpgtVGSs9P0Jtc1m6uIr9q8SYYJHrAa2zJDchzmp4aIDLhGrbngjjTOnlTgTZPgcitNpEZFxce8o+GXpn5CNT0TJOedReaJNDodz5n8Abms6Hlr9g53jX7/GoHa96+5/s912yCqGf0NaYvkvesYcOOtLAwtmNHCa4Z4AUYu8jddXuD90Ffv2dezM6Q0zzQpoUFcuMrsRuZXmuuMTxoiS/CqV1Qyqu14juZpc3xf9avObUJiw3gyt95rOYnuE9FYF2dTxkqDev7OLpnwNubkyOXifm6wcfKTj4mbfVD047lNJXUt5n+1PbLE7toqiWusRodsazLHJjbbBeEh31JnhnHpOoMjRfljGtp6171QzN59g3b93x0yGH5sEkgV6wHuQpEYLOk1HBtxRq0biBAbjViKQchNScw7ZT5RW5KuHWbzGjq5TkLngNUzTxPnp1NOCyYoapmB5Gcm0hVs70TM9Rg2CpWiC1nbI2pBhrah1lwB41G6a2QXhdcXQ8hTo/EW/FEv58d5fZ0H/LN34P91pD4r8xAEXZ4FCX8G9L42KFZRrgSfoAp9Y6Nt8RlCp1FECAp5Fe39zF3AWTwTAE4/xZB43wXTcrq8Sc42JpC8YTIgJIrie6Z7T+ila04StHwlX2bc4RbKUVbOtLML97vMFUL8BwtNpMK8AehpDjPj7mdD2ra5tMY/dUFE2PvlASlDwTzTtQ4G2O8STsslqc2YrIIqV0bxrv1/fJNmia1fq3Mpvq4rmMW6UWIW3XaB5GG1yCJOZZcoJKilQhb3dV+juO1vpKMZnLG7nTiHzkAwbTs0aKdXcEEp1NqzH2WAqfe1l0VGzZOhflP4MhsLQDUxWspokR5TvQ252bUKpsmJuMvBsY2n1T+I8Lhediq0RN5VmbwPNnotdCVbGeFONKtpwwgVuNgPv3e8R5hwhZusMIBuz91gs0dE3hbBBSFGyEA0SOhYFyQlzkPE0XGe3HNN/poELTd9L2cBRt7l+JzsP99DbiOWnCZZkbI2h91qZf73C0Tr7Z5VvlA3tbuSGKl9GlWKdL2DIthLc30IjGIwnOcc1MWMmrEme0u7kovSS1CUtFVsEAA2EKuqGhODt2noxfdjlecdpfHayeJ6y1/9UNfzZCwrvbBOqvNkIL1LD58qFBCAIy7FKa7ldHFoxcweClflUQMF76MpgE3FAsaWMIwydakBPGKJ1pGvnvdVGA42r8ta93CRSbznTEW2C46m18Ik6e406owZmGcltoqAE0Rk6t10m09AeDxnyz87lt/a4f4lmrqDWW1GMga6h0VjIfTew0CNigASu4y/afy6k2uVcRQa/1yc0lIqpZnPibvQRzry81EgW0lLDwVkZ8kHrYTdq0hNjMRosA2vLFxhDaeN31tBstB567YqUo9pDSfxIVqoMfhvmWx5xf1jFq+Y8r8j4/cDq/pWe+C4pHGnqouFd8m8zjph4iUJ1XWMoochLRRg3BH+bUa5o5wNCQWO7UfunKVYPaJjW/VVCCsmKLWc/Cx2LNN0zkkBkqKl2hye4JTjPwn2i7VypV+18zjWRAo6Kk3/Pi0X9/vHD8phvgodsk5IM1lf70Vf3R3M+uT6shjZuqDUDxT97DIQXIpuJcupM5kdQ1bzF8KWX4JQ0Tdqf4Xfo2PojDWyMSGwaM0hhblGTDY5J32GpcyTcLga6PPgtoUsd25IyUtMzqrx5yQ4m+tyZAaSovEmojtyJpTd5PKEH6t/OmuwzQOYX6gl7MvnBwm/61kU3pSS2SeaOMyk3XJzGe6fUT2XuxKtyaqTX7iMUP3w8wlhL6eW8bC4eF5wh6YudGdPl7RKTWstnv2i6rKm7RT9kiDO1E13cwAW99ujRskfCa4mvUqcUxJnMeXZUxUaPrAO5voBoTk/51y4v5XNtuvgjXuOy29JfCvwuY3zPnCOJoZlkV4R/lfsJvW55Rasl+6usXFbWQNgN5TuL6cPK0iVU43JbivfZt+e+4OmUKKVR9Ko0mz0l+WJJ4ipoUvgjd6kc0xG0jW/p/KWn6A5yY//4FpOOCZVKRtv1m9H2q2t8RDtHqA03t3IwSPCzk0puLDclEQtHHbtgzUqQNTQFQNv6ZH4WqblMICaf+w7pq8xIWbMd9oJaMu5Sn3IL89nm8W4uWNnCmvLtREBD7bNbcOwr0Z6RkkC5o2jCEKN4LuKI+OmlPqxJd6+xX6NHa2bo/r2f41jrzskk0DcNtMJnNnNpxcYvjHET7ojw120ENWNztp1dPoWU6MQv6RJjh3yqWFIBPcZxTQ47ToQ+Q0pleDSs3+kHVkLX1Tzm/R2/bufP7FJVePDsPCm7MVaVBrYzcMcVsiO5GnhH4SG3hxxe/cZ8MTDXbwza8ZRsDtaznV+ho51CU+6Au0ekX8s8V3z4vQZjp8uTL5OoomxRxcdpMcXL5KMyeaUmL3SoBkvQPCTdVlhKo1Qudhdu4hXvkQFVChnOBaeV5I0iB68jpur7Oh18KLVMVaeaZmZpPbN9OCDuo/ez9I4vPOBWFF9/OTo2aKoZAB/t5XwFtEee0crGvvJTTo3DFW0tkipvyn7bZIgRr0DXCBrVSm6l9ITFz7CgNC5UP+d9nix/a/CJXbnxLI16T9lRnsjdcxiBKjaWdMIw11D3kN1OXyVjx548ZXsX+vCP/R2gj6yJG3nGoluf7LjGDEV/036RYaWa0MFpF5FUrslUed1vvkx+NX8zioWhSouNZkfOaRfIAIlr6NIYmzY+TI0Tq9GKNZCPDZDopbIcLJWFs4jvSlZ7J97ylzSGYgNS45y25OO15pH603l/SQDrj3gMJkTJzU5ocxRuPpBLpkn8A7PHXMY49SWKDnxcT9YsxgRtaFwmq6c2e9/zB19BI473dSYnk7Zu1oi58hKncJwLvLud5adcYY6PrrcIde1UfyEHlPbEIlp0YUbbuRM6ghR+RR+/IZ7veFxuU8/34x8/g+hYVAg6eDcf1mXxYfUVJErjw9eFx+FqapS2Nz2ralLV4kp789BpkCyEV8M/7hqsISnbDHal3Vk1I20wFXTO4d6CviqqmtwbIm80hmZKcOorwZaZ6uWp5llKrYd3S1rn4SR8/Ip5us/UchON6pSiP2Pzauu1q5gC1jFGO4n1IKSmvqudEeUU8TKpNeV5NjAXvBG/ymsgyqA9GQjxhgeWVcK9zrh+jxjXOxOzo0GGxlFWnrZsXDor2M7i45KxLs5fCSMK31alh6wCOQsxivhz7Jt0K1YHSTAf/5aHvJ6vsOSVBpTvnZZUvyav5Bk9ZKzAk2aNrIONZm7j7TntByP5j0e5qRbEc50oZkYJNYoGLu3dPN7v0HJnT2/cd9UfHPN2C4mdKVNXRTeTjilsLubUK0KsQRXcPY/2dDtezGLbGV7D6qldq8OArpn6jKeq5w46sG8xOiaf+a0aVyPbGtjbUtPaZWETbpAFtmd0wIhNzDkyz+H7VjJcXIlH1Lg4i85voyNrO4PLTJUxzlg1FgrLnjN4HUp5bDWax4m03ZAL6IMkabtm/9gF2AqdvxvstGhUhUuOgLWzKeq1POKz75LhuZ3/ljh4bgU25W7eeqYtMmFaiEmmLMOo6tzjru9saTYF0FiB7xECSguj5+iBM33zcraRs50ZzPeyMraDGsF7mBZiAGHBtTBmZ9r4BTUUvWD32I5uT0vJDl/o4BcikacwATOIB3HxYVTsGa4GmnVGd/EZtLn9yavxD3fcfCwzNh6MjY9vs5rfHLObcmyxmxWQavIoJIcwOdylLv2kThtUzgMt76BXu/hIk7lEL1k9MJx0CkFnSBqeco+PlPzlg4md4XJsJVetohZmsuukwxsKsIJ+MfAfyetV8JovqAE84fbEd6i/ODj73/ZFX51QLvadH2/jpuzZfMQWpbwG7hIKa+sbEkDG68YEVzuwKuSzmrb3BrnQPvR6+xK3ZzyoxJt4ERzreUwgGcd5i5LNYF5OBv4Cvvu4Y2h8ZOuBX6TNwLMuYDXu8fZi+Ahd8Om44+zNaLVZXyY8v22Uv0PJ7jmC4MO0sCYv3rrVI4lKqar6QC+FNVBJlZJABHovTdoD8vOQVOo+mzdJrSuTlZN5M/gxFGfnK3+qwxEzem5jvW0WSIulqhhpsPYrixpjWOKOBWNlIJLMxVODyit+rknmpB9/DU/Ynk84XuH+F5Xan1u4CGS6AF+YbAcU7o8HsFAeDC0YPTD5xtt6FpVUC5E4ZZ8v4rTGp5t2AMyXWm/VzK1FBW/MMI0ls5YRF39Omr2uVAc6ith3zpRAiHM8Qw6hrWeFM+zZ/OSKiLL4qAw/Phk8W3+kW95MifmdxvhA/lSJATY4WkmEcost8ZRoAa+OIR/psJwbk4AaKw95Aqz/0R/HV+drmXca65QPjgN0lIzGZvZiLEoss8NUShiNWkwqKXWlMpOeyj3Tm5FX1qloFsUrniuZ4xmXOUiVj08YD3U9ZJP3XLK9WC/+4kj4B7PLqYGdUMvdM01YOB/pO0ZEoBrDPhMLZSUF5QzNJJjqf9wkS0NdyGCpRIMuzFrKbnB4EdvS48mlemUSTHaZip3rdDZbJlNg+luM0pqs4R0ankV7HJrKc5Mdn4eO3DPXVApuHzzp/QAdTB0NZxz1vcKXAnHj2dnUBEshKmj03ZOimNjkSl0jZ5ni9c4L8lmM8PVMmeWEnoTFzxZ9gmVPYdkjK4vLET3SUa9aC0/XpSGJZB1L6xs3VyuR/CAZhqEpqlwDZ09At8ERLR7D+V9//GXnmbb6MNDeyof5WR7rF0FU66lgZzmwQQdvDKiLj99iCr24NZbsmkwTZgmrsWqrkpj7tt6KX6RQsweXcZW7exMZUPCP7jEDntgCBi/hldVTW5oJPADkWoUUSuZOGs/kgCmWZE3BWlh3hQ3Vw7wsgeBEa62Toj0F1neT8bua5/u2uGFRRwz8L27hh5uaJMjsOiJkRNuCZXnwcRexm20CFIFGrO+UwBWohEEn7UAenUHo6WnFCpRpl2qhinsO2WAp0FFbzRV1Qi8hiZMLX2bxOrM424m6VR6E3zSfAwh1GJZHaGlcdZnvJSbVVQn390Lt6ym4vYbvfutZIy1dI6QPElZHWllJsKUYHRaofPbehkT8KHfLG358KtWV8dq+MiCERZILbEcUgtjbc6eVloF5PFQtTqSkph5shDa2EQDWLb33DtRxq6HtgeZzftOUMHQjjIekYe0Z2GW8y1rUz/HbSfxF0u0jxETaVc66hYxrarSICTKqfXL++o48oVJi1TUV0oUXvM3XeeXC/q1P+aY9lgi2IFYvihmgDXf1atTAHcjB5H1Wxat9mxCBrkpN2Sp+B/QogLeLwIqwR3Lwk9MkViTRMUfGobzbnlFduumuU7l/oqv8q7uO89FUX65wTgpyaGLY9hvdEuHB4qSWmLvUpYbegHTaJ1opV6T7ZAQm9XW9A0Q7BadK40Ir0WgTNn/0UQ0zGY5i+2DbztJHn48j2Asm6PmLzyka/LTzf3YkcrdygN+3jt3xWLpdAvaX2Xr997E7v8fBmP0uolQqdlNzKKLOzr0F97zYOIop7PpZyvpTWxHeCY5sIWOcJ2hwpUxhZ0xbxxUebOHqaFpX1KwsVFZJXoJ8orHlD0YHbqzGd9V6bAG0divgroWSHenoPFebyoj59B9fx+36ETLzCWi2/QZJYge3CThbVF9DBm76iI+fXv5Unzeh1RQepUml/8YQTmalCM13dbAir7Jw0ymiSzMbt3tP30d+rrhzO36xrr68xi9ckIilvo3BWSwAGO61ljKYNNbL5Q3tZFMAfxREz9Txm8+83+wYX90gL+6Gc+auxF7jjltAFab0AkA8xw4KifzBbeXyqwbLcjWlKvQ3R2cyC1wpMuXGYQ8OY4MmI4ZaSeehl+jvvKZniANY77exSekzVvadA03LDcVJNU8KRwkzBrfZlpmMcrGJGNozBE01msUi7vF480X+K2PGU8SjiJ2hWoE6d1F3VtQIe2WcjWI1VwQ9rOz26w4t86HBa+I+nkOJKY8+cRsTm3hIM0Vh5KwJjTVraRdsghbMqMj7jqx2kbLdcpeJi7CxT6or8u70y+47sriIg4E2H0liI4h6VfFcvd8Rwu03iPuF4Sj/PkD4VcMzAhz1iJ5cIyBRcp1Jj9s0ZhmhTGx0Y5U6gr2L6qLPphG8ZQNEm+B3Z2KEQ2vvGJYZJ7xp41cj+Fr9nJXMMB9BDhYNSbJvFbtadQaanCGJsX4zYSA4GiTM6CMhXwX6rZ5wfxAXu46IAzB96KQu7G357kBCTXv5k5/ty1+YUCgDFDjq6T3uvWi7BscCptYMltH9v64vM2Xz+uLXF0sMrL607G/0hT+KQqw/p5Gx1BxoZ9onldjXkGn9GcPllkI/zv/FwkYUk8gbkAunBgtOgSCdi9qwlFR6t3dmDAONsm5w2hARWx4jarYq94tqDQKNJv6vwip54VwSuFkuxK7jaaajyKkyOCQ611lbkXYnZFpne9XRXBsNEGV+SKMyt+9celyf0PIf+Ie82P6d8vfjWPjkfd094sUXJu+ONKpxvynsSb63wbTrCG1ZibeWTnXFD3ZZzRAn1TcBu3BaoqJI/zsTFIpZYMiYMW9jliuxQVkZLR8ja1eF8118GEMB5zsjuCl4IrQPQbbkh7JVKrf9EIAQ3X/8xDzl8WjbXIev909WcN89GRRL8vMHwyIO4Hya8cTAucTyeq4TaQGZI0PwYUT051PEr1OkXmfHvI6Ifpnx9lWc6wsPcj6YBK7+18dPZeoIsL2pzDeqss0oaZcYk33UQYszT3BJl2Jr3vnscsxTJFX94C9xnjFSoFEZQBkum0TbmeopPxYNnIQrxvzCsGVGGFSLiMmY61xmlxFboK7q5SHUUpIOVxeMB17R02QzzBCrq/er0pUSNQcM/yqV788P1jR4RFAvK8XIjXjvybTgVolOqOd0defoibENIwjKeshHL2ObSqpL0WThsbT0mQNgNnDGmL2vh59thHBwYXHdgDLcMgmV9jhcjXmY7lTh7EhyOaLTeYf7DkmoLfY/mconYeQ1QP/EwPJfv8ql1Bpxq4+oQTJydNNbo10usrUCWG/slCNafQf4RqKucVYufPhme33EHW2DsSmWb6VcCfc12LVONXZmRMzHjJWqzRhG6gpd3GCzZ6KGVOxATK/cLf1itpikM2ov1GfoNAyMAf+7j2/zPOTM5PtkB3/nlHyDZAuXaI9IsFco3x6Rb7+YXM+dESOIOuqOeXkdQr4Lcnw0aKgJXke7k4bgusJOb8ZeSQIHR8YT2wtJiUc4DN2DDaOQbONT02l7I6geSFrH/dEtjobOBk6JCMbGAoHOMTMgfsdSK3tWY5xjsbE4U5+HVLL/ZhH6738TUbS07LvkI0wYiqh9bNmmogJSgt/47VcND4kFUS7cnH9aYhacKiqvBla0wYOccv5AC+094vWipVX0t1ToUMy64k1bFFlS7VVqhM6MwZWZbQmmSNOxWgjBxDvNAwTxA21SuFa/svjmy3tb3/qyrxa6iqe7sjon/a+XUCI4jm7Tz7tiWB3xpIKXcqWdf0uZG1XX21DX0YtMhJGCs4r/olCHhq148d6acnWufebgXTXUTpXyHnpx43/V8Jg25DZxFyDJqQSJ3sJIrFfnh+TAE9/z7I6il8gYvlFetu/10ZhZ+x6cZPbfMTANqVkTvbazMEZDohW6r4TJ9VjObk/QJxccn/fXXsJfmS9E2s4SRNUxAgd4bTubUEUUEQ3XjOtlZ/NpM6NgtBZin9PJ/ursVxVeJ95qHGMAjir84doj1M6hwEhDYn5NI0Vg+CXvzVsgyZd7tsAw5mHhgD4nTsXGBGZe2zXq1NgKAFFoPTJ+hdA8a+FX5kO+zMPvFD5n46aKrWBpnVJu9BRo0h0YNe7VjjXL3NkaCjIdtkVRUYxGXfpeXu+JTcAtX28PvvWacsr/WhJFkezQM+3wbeT7Q3C5ItbdtTQWv2TgwsKpeRpiVHqjxLy7QShp7MeXcp8Byp37Y17twENqpuzZ3RNDwuZWSFRnCuRc/G6RRDLY/e52YyAmF9zkgqs6RuZ9Uk+747mmpGY4AsT1kxpKUeuBB+rBx7w01Rl4eF5uzv5fjNg+vuaJMf7mRf6nfu3lgUs/yZW+wV9E8C9qnhgJc+DNHez1c3qzK2v0oC6l1HivjWmy54r/xTVG04qkQk+sNblnui1XJE5qY112aoU50+J40QiuBGvQmWc6mZ+u/RxYr03l3DguygrmeXTLm67O1hMn3jXu4TS7xj39k/n6vwcxOxL1OUKQvlrIzTWaVSqJDBKS6PeS6GP4BI1XrvJSV7QxUz6XPEEmx+qkSpg9pkZdeGB2GeahTXc+SA7qyZQpoM+KR2Kk+pJwD6qSmBl1VuOUWPK/jRDvYBgLB1GDIO45XTcdzPsRQHArIMZ34yUbslStLqyFgidm6nJBUC9rwtKwUcWigndPSlqMlO1VLZlbzY28v7EIMmTsC9vmor4YsgqJZ6YxurZuELUXzPDZ7vjxod+neBqqKfDEdragYt/Vko+WMX0VSBuBFv0Mu6boll9SO++A3/4tw5sUC/dgkr55csZPjskhgbJknpSd4lg0hSUk+Rz14x9qYkn6gg0uJ7ckU6x/BLsvrPldp678oBz08sFvbrSmkAERwrlpS70J4Y2Jw+bbEnjSKCIqi00rN9rLyh1zL8FvhnhifGt6tIHtu13Hl27nv31hYyGjsa61Rf2AGF9kyPOKSTi20JMwcZErVlV/YSNEcNwZHmg+5u+xvsw5fCXrKwXra6Y5Sy+W0gQQnTsWL6NLNAYWfcVmzZmRGJEStcaFFuHIvNtV4xHIMFuJo2fRxP2JEpPl3MePygNuD+LDnV70Y21HFVlUrzF2hsV9IBX1YHelu717BpgzYS04/5Xv7OT5NkWUvvcdK+CdW4Gsm2EvRZryG3qNUZrRaxhyoc6nvbOP7qKr4d/oJdp158iV08YEuu9JTuV3FsGuRSAYIs32FX+451Wn+RMNrhe4PoGI38nmm/AAFOEpT+FQnJOM6xaEgCHSmYofmARzZUAsw8eu2qx9CujatwS4cFI01QZ+J/W5XEOCSM77uN1+H0tr5oqNxXZsMPm1iiZYpX5jKcIUS/OTMBI2BdE05Uu4zl1/lAs3d+fxcBXj+VWRGUddVL8U/ptLa1HCT1S2njMJTasci8iUALEpRT1O4XpJZR4ng0KSN5LHxsiy0zcXcV0QsVVKO0PgMER0QeDQH+ZXoQbKuDNSW7kjZwx+VNEKWWKomekYRQy05jI1UWWkFyDjO7WMv0Y9451I27+/r9gS9EFeUriyzH5DMeoj4rZK3t9VNBhFAyB8eN25/S4DrpYZnXSJzozWUVga1a1hSOmsh4N+SZBoR/wQyhGa6oZfSWyzJgHSiliqjfutthhUUgi5QOsT2joV2UTvcLmPfT454doKnQPnOZkYCd75p8rs863bwlR5k40cteT5tXsg6BfzcC9hzRE8pO68j6suDwRJ5TWjKNElkcTA6Gese5GpGVvRoJmxgwYOfeWoISkxe2TO8IrvocpOP+iQ2beJLqi0rV3T3s+UOokafKks4ApHMg94PQfvl/Ptsd48Xd8XrBcuZJ82Q6yLm8d+aHLvT1ZhvkIzoxnKeT1Ey4pq94/a9VYzBw5l33l1awb09cCVKKBTAX0Vi4vLGIT5uAumQf3QlBjnN8wobryWZ4VnIpRHIRbF7hGkUGygSVPoRc/sTlmFZOv++Ef/TAz1lTGPEMpYGBdcxGkBlF3syJwdmVP2l5ESXMbkDddfjSDYuv9Enzw1gyIEqFNGDez3AtSh+LINPmO2NGHNCGDdM+fqivJtQetrqEh0wlpLlr1FNjkeajynDPWBUCGiFST+FCXRDF/RnfUF3Oe/6Sa/BO5b/dXOrXhJ4+1dNRiyowc8RAnddWV8i2t8jQyVhHjlM/irRH2gCmw0FlOJhgJFaTeEN3GsWMg5RuRrQ6QAZS3nK7ACRyYvZbXcr9JRdw7LUSKCr8kmIm5Ci7wAVWo+r9gWZyE3LjWUgNVS+p7W5Kn0/ak7bsxIMZWetLRAayrPh1qqaeHW/nIvf+Ev5KqqnDLCcg7dKP2dqL5XZBuFsgmpvzA6F1ddqZwtNehHvsrFxzaDLaF29QDDpAw4G3rONBW/V3rneWub3uHWXio0vyyxX4v4fdGb2UyCCT9tTHm4lhfhIsfv3FOMx6bBdgwN9e6cxlWkmMfcbPeAKk5q1zO7bOlbUWoAXs3BkGjgvLuE11WhThwl0/LFx1rkGp1itzWdtC0M35tFiLGJ9hIp65UunVkAr/c58HjKT6zRM0Q5nvH4jhhi40WYSqixCIJWAkUYJ3fqdESHVrWhbe0IG06HM3hkiJ/M2pXJSYE6GFyNHvQSTR5l13I0D4srTBllhTGOU6ls5UjxlxHQi0z+AIWxgwr94teq+EiEafTkyjvTdk5stZaSSmZaJ0/yVkDsH4HSnje37TumzBBKnqkh5a1AkaPnBE00LkY9g/mf0TVhXpD8bn6Wx1DCUDwYRQ6KzsGI27m5nEmE06idAq2nuQoExvHFgYPfYhAIXVJj8RkEfBbe11x0ct/VSymJsILLReZ97OJK9u2ZHen7T8wH/xaPwGDJHdKDB12yQI7bjB0G1IWICPNk5yltT3oDBclSo54zowjc99xfiAzDGdCgEUh1IiytNOqLyrcrDkc2fKlORsbhIM9tO9BVz6BOu4IMd1CMSk8gbYvAtwO4Of9xSli9iL5gTz/mp87CTycPX6PJncRVDBFLQ3xUN4sXbrJhHnwVFbV7TABZ0J5CTZJpMi4QlL5WDwKHUzefimFlmjcDiSCcct4bnbMJIcHvzEqojB24WqFPjhzhfRuFJq2GwJMaTuyc7UgtJJn6mXPKBVtLBpL1sa6zQdMl6fjsh+xtWhRs7E27RgDOJIjaAfY5nJKKHUrLemUnhRzchcKDnNxl3On19Upb12W2gjo7YbAvz5wLLPdKZjDSCTrxCp3/fmeZ1kHCdP77SidQGLYGo21GrdiVzcHMaWGwKGfcwFQPyRThDArO5uidz9T6s+D+lVKK/hYr+xUOAZq5eyR5VHAWk5gOLkBVpxLh1ZzK7D+VLpILC1ew+u/dm6bGA1/hwE1y5QmtmVyHHuMdWYbaZRaSA0vW+Mzb1ObHW/CSGsuIyl6oWuwwVbhJIkd70UhwmjmNZC5Z9HjrCyn1VqL5byKev1kEkcD5jHLqdMRF8CV1ptTw2x4hb56pw7JlQhLQoPYTn/xYAbXuO8rpMcIJK/dr32nL7FxeM6HfDMU2cwU9zdkCp94gebQSwde1Z7SFdsRi13MYXGfv0rOWHK1d6dOLey3TN2EZ3W1x/ZHF/PFiNX+BpCr0R8dg14ekRSMwASvEELAk7ExaKxHfAnTWXp+xmHzmKT3zmNVvtciwdY4TS2TUGZAHGxE23/DkB58TJXTluKi0fhV7YkUuWBGZVYW9MIWuDDmFIq60hAQEotM8w2KecI7UcWHpeKhva+LPWEb/nrSzkvWLcXuie1COemHSLvq68fGWD/bsaRQcz48hhl/88E000v1GqlYc1LAHtbplHsEI0L1oRrWG78BbuN4mF19IeFoSaTMAfPMxEy7KicHYO1PWuUAFmxF3/5z4XCVaHFcmZjOF6v5A9tX3wW/7Wub0Ge2s53LThJ+c57jY2sANqgfLSEGNu6GWRGY81001pdX1z5TAhTzTvlNGyQhBMWgDXU5wotTeIiV0NlSRHq6SosbmelBGrHVHCMxHm70UIYD+YivVnfe9llgF1KZEIIaFH8+chzwfJvl7LPlDVE92Xhut1kawN1fkEntGZjpUVcOdbiWAsIuZYOGQrGQf4O3t9kmH4SMCeAdopNFiZr8FB7fczqMQdmlL+cVYDx55Y5m6sVwov1B4HVmeq6gaM61uFMW1BbaGFhj9+gmBl379/Mo+njePdz0f77W+WC9Qua8fxbs9k9PlaWFRvFugCEaLaBVnNG4MSbqmVDO2thPziBIuT00WDfK4uBoLkrIpvXCELkA+2QE0Z2CViQFxi0Hw+YXSK14ng26HJmehQDy0ch1L3OR8aJY8e2A78sZWdh6VJVPF7lw5tY5+h2I4Y05XeVlf+HN98WN7IsW40Jku5g2THm9y6E1q+CEzJUOauPqZq1WuSBkFBfCjo1v7LQbZMgZZl18PfOTQ0ohDotIp95UGohqro9YTmM332Vky9R75nNoyVy7lSuGxaOOVKrLAUZjs6F1LQ0aCGDkrTd26GfeepbE40C/p3t84NepTiM3ycePSXZLfrBgFjxFWs2sMq0gBGSbln25QxY5Hq79ZkBUmYohDK++xIXPvl1IbnZ8jEbYZ8tRKq9GJeGolqVy0FCHqGbHEmArSYhjlijqoKYoh9CWyiJJjLaf3wR/HZjkjT0ntPl3RL5AX/0de6eVRKH+8NlM60h0vjGtRBA+x5Hj1D9uiT+fCqfV35WLxgTcljmlJkmrNxmCsCRinB7LvbLTICOCEPqJJf+Tx7ljZV0RC+8JjMsnL+drhRzA0bkAk2C5nIiditKEBxVj/pf9MWgM69OigaY7mjHvKRGrAvilZaPf8LCKIrDhQgHRbtHif7Y50i3Y2SKVG5mmEYeDXj11GzZwyT+YhZcclAZbcpbNQXgz3ikRS7Va4Kz7W2GjsGk+cUcUUwc/ooM+AXqiCTI1EudoE+Wz+HF7+mAl5QyxZ0EtcOi8LdNuZW0rVhx94jL9ca4wg4zdq2InKrJTk0jOsrzOcNeXSkfT4WntmdrONJjBamQsQa5XCrvQFIuBGkdAkXPPnD0RhyQ9Dr/3x1vBwx2Mz9+lWw8vXR8ObzcGGZrXB6awVob2FvE5xpGoul41Vd4CGPCI9jjxMDstPhX9iuS+8Ag3kTmdN0VamxErdQjyAY9M09gCmJGqsDEaDqYShviKPOhRHyLk0bdNW1PvNphikXuzsPY5+XtaSST2xnjCTocH7afN/aLhWC4V9kMI52TZVwqIOU5DC0CRxxtzQGBYMhLZHBIVjQ6Xatj8nlmm7TC1cJaksAVAznohRJUhYeVHo5sgFkLLlE9C+au5ZUpE8cEia3xQ629lzVmV5H/qaPFLYurT2XLe7kzAXdXcvcXv/eb72jxY5bZMVlTVwvSsdT6JwvS8FNWPjp1ISdFuRNlx3fGxFsxjJF3oqp3AfTkwagzHQIPJi9Iy8kNiHrjaS4SRa1amv+KHErnm/4VCLSWoTcp2dfQwkDuOBRznPsXaKPIXtkUV19gahNsnUSJVofxquffFwYEG4MRFtSvLFuGtR8seOAz9vQD8R5PaezHAAioLHL9HEPmNIUfu2GiHrwx9xIjXQylKoCUq7JR+aKe/hVhTgPXSWiDi6QkKTgLRo5ZXsZSvihatJCn56d/rHc+5aCKi42fY9vHxJi/yRsmGSYLhRRG2cvQu1+mKOOHcszbZmLYpZKqlo7CLqnufwmj7/KjmhTVa426ZZLohNJmqWI/PL9IDWM++CqjvSA6QRgZ505TVsMFJVXEYKO83ijDpYG8MoIVpqgG/yTocRo4fbXghHn3uUv7E1kjN289NuRgabVcERTtHQffzbVSK4d1iY2KzGz9xY1kg3fiUg+Cu5djIim8iAJuXIlY3eR+YTgu9w5N7OINJrPHrTTSdcLjqf4Wns0kZpRE29+FwVRkF63CL3wYIhBRkH9dhCQFtQ2DMs0stvQ59/Xzz8w+qoP6cSeLA2qs/gSaGTHJyvbrHrbVIy0alOIFljhZGoxmn32+xSOS7zJnYNRRqK046gdSOx8JZeAqbPAUkj3jCQgYQmd+JwOoFfij9tCDNiXj8iFPw86Py0yfBZqOyOB1DaP2nT9suIWMvlsX8oubdKc78xX20o5Ru20OLdGKxrrQfNwAh0cqQcc+QyV2xr2a1EiRjrsyZZ6ZBnkrRyIA+BWZlzLgpl8t2PGsNuutxSdMMV1ZuMudpui8aWesruob28e7VH2RwhZUdrqOjppQc8Ph2u+ddml59xawFaPVBSduPmJgp0Ubq0e5Djr85bdW4rF7s4D9cj3OXJYheSR8w5Bj8VNc98ZLwsTI7Ss1YAaKFCQXI1BU6wmy3XZmS26EoLk5Eab0RVlWK5jth3bMY/4zTPC6HEWY7KnZFZkdJP6TVur+6Mb3XJI/ccorDTapxLT3mFmPWchb68wG1EMJlzmbQeqSMzmF1UFO3tCSuKvt6J00sWGJQtFQFWxawwWLtulQsila8bptpLoq7lH6OFbzTsV4TvqqEPrjuER2emQgWuHHKwQbTJ4ibuFyJHsim/RuN5e7ZKDntRXS8MO5N9mbjGNkKIuzgkKl1tZ1tAk1S3YJw1JBL2WqhF3k0J1UnwUxm/OKMZQ0sdtUSJNG8VYQKiCbUxeJ46Z6fMcUx/jcph811NRkLFMqYhfcmYjOg1iKgaYoh/PFwr5dHHnbvhjCI+DsafqNNw/W5cKPESQ3zetJuLneeiPVWorovbsCMgU1PKxTTA0yz7bgBf67aB18fjNmhzQxZzGWFHcEAvyknP+ERjWWSKFycrpM/ojoVfLuN2bnTcDftKpaJq3xGsdWphJoGknVq5w1yUXKM6rf0GDv/S4yVt/GE+hLL88Vla1DO+Ygs5PEloSFI6dVoDQtiQ65xTj7XNwqZR3+q0eidOr5JUSsZJl1VW9qPuybqkR7cSfpC+IpL3IsUMDgLvsSC8VvxBGaRYrzLPSkw1c5Z5mZI76hke8jM7/ZYA+o885FWfagk+qAsh4yLlfGKoUiie90hWcHFdZJa7EoDYF8krd968lypCZdmsUfNFHjh8hyskTmjVcqW6sJFwpKuml66GLLVbziPSWB8XH5ftZPU/Vx6/oJRq0BoSGX4KtfMmKZ7erkjO12HPZ2GRX0ktq2w7HzJ3MNbTgwgV7A2BISevkMWoqqADqeMu1U7V8foOX+lwMnjyVcBw01FBfzdJ31u8vIIt1X2LKP0xBFZM7/SMc2KpKJBCnTGgLhTlQqp2HnKQLLSq7fEK62I+yxmesj/vOf8dq/qN93hIMqdFM1aRxehlcj4MPly2EwvLc+49ibsz/L9S1JxdPUKmVz3rZDU9wcONHXso2WlnC6W1W2QDTOz7A+2PQtP2yhly5XerNDPsj22EhbZRAMuXXpEvK1htjeCrbumpzhpbIwmifYre4ZRanmOiSSzRyssmo35DacnbuSlgF4OvyVBFYU3OwRd0DPnVRqzwrecKn3lAZSkxwrRRXo/igv6k9SC4DhCWUQezbHCehTNVN5baQV2ugb93JIBL7XDJOFQSIhsrkCgbWbdUclw0nQ+vZ2PYszLTG5m266qLPT4euAxFHk8H+OSUKP9CJvxPezg1crIgjmBsHKEil/2UJn0m+pu3zGa0WWGrYKg2pC5nabDfJhNx19GB7562AeYwzt3lWtrvEFb5ZQxAqRUT9xX5q84cYo67bVaA78Qmp0euWfDZWtOOYtXHl8+Lwabk42/nMT9zDW9O+0PTat9IfzqIT2RUBQ2DyJw1pelhg2+RWCGyYaETaKorpNmz8/4cccUrk+4CUPVY/g+txbDVh+LHYrscAb8l7fZK9GZCYfyCOgL2zu3cUA61nrgpmRkg8VxbN2ETe76zC5dMFygr4hosg+HQBP6RENG/HIZR/C3ckMp+KZXFIihZgwOZr2I0zFp4pHpOf44Yai91xNjB+XP2GnpnCw9y7oiW9R7vr6dTzrntjUhro6Uz9MLWA9Su+N6G+l7gNM0kZg0vV+wBRhjDqUkZGoq5iM2TlZxlMByV2j3v6Z8k731lYyRo0F0PV5heUILPJJNN52KruFjWrhbin4nv53yABUgS5amLKv+SODARNeh0CBh+RnpPi0iTwfBscEcOC2yo5JjL0o4vrDiXmTPNiSaQ88LkM+x5dMOmrhaZRpcLrDyWpqZVLi1dpsOdySAS5l8STL+v5spfcIKf84iuGjxL4k1fd4a3OzxVBtg7OtgVY6zIIVUn8qeE71dLbWcdJ/SoWOwRt8UQuDBZWhy4C0lPQ6DmDNek/qsrMRGcNQqraxbA4kGFU1nkL/Ha2x0K1al2ggW5JUnaeVT44xgeOobHC5/91H6ZU/S91f3k7dnYZxcSmiVKNW/AgBxtBAWq6m+sHSpE99oVfznjIEwjaH8t3AZS4rkf0bO8tVMIRm2OWHRM0QDZHwvBPCVl1nJbfAUF1LPo3ggB6sU+SSS+LPhnkSC625nrh/ULlOU5pFFTWR2fTX9+SIHyUf5uhhODyNMO5fps51aEZO0VAxtj+RE+V8W/zBgTWtfOMRxI7+CTyrne1+0/9BW+A1d1yMrVqW+9BT1YrIOlv1J8Sx63AQSd606CioxD6rgiLbwautO/1ZoWGdL4kKqdAZzS4qzOR9qsq+XwVwVK+w6cg1Z3y+BJzTY9uD0m6d7IfquFQkzdlWTZmryeNSlTzE8o+oMP66CaGwhOBqPaUePB7pECNewCBiGxz0hB8h4lREd2doVHaj1XWjrnWih8wqF83lqwYosF6Cnbzurk/FdN7i61HB/fWi7q6ot86nEUD/8X2Kk3GhLvwq458OIKmRI7ygA0YunVVkThrR7swspOZ0pP2f6Q0amt3qZgwLjmuF+dh+38yVeM5LQ8Fnoo/ZrynNSf4/jUJHLU4FTUErkcp0QrLQ0wENgpen1dle/RpJ19zMfPdJ5oy+SR/QKT2e97ufoDiimFn+LWWT32v7WFEKJSVGnly8/3gKT/R8mUtZiP2UhU1yVap/VtGvLSGjrLCa3UlFy4KbCnWl90f3rMfSeki4mlJpO1BYOFjSdM44qv9kiozvvMnBUNhSyfdqUdnqdqoTt5vLGzxM32RVzPy6hnw+aYFmDWOWK2ZWS2xUB83suG0W/Kabm02RYcfb8E2ceBh8dOauPJkRmxvpQggViUHVTeD04IV/lSAi1T632vRTqcBAWXXYd9RYTwtUzwdGwFPR22LRJJILwoVNI+frY4HJBFdB0ORwP+e6zkt6MONz/npszZvMYbb4GcXwu7+9zBHR8M3mamxIpD0nimYsiyIamvSsHJ9mPiFR10xgN8bnABscY7G0uXzMmY6rcYVUxaHRt3J+0z6eNJRqntFhuKhK7oOIXkKh210+CXckmFSfZFy2oZx3cURMyxf1GVnp7yuu36XbX9m0f+ejAfv3h9lsZnVMGwbdMorx0u0RPpyXJnUrENxlleY+mugdgagbzXLvqlBxktGcNQNibKsjsvSiQAhk8bPrnhHe0j4YEJOZD9ubAN2ZdZKd2ks90cq+EhamlsHeVfvd5o/OOGiZyard05Jfymi/7xmbD1SxvRKfbF1YGQB3MazRUV1uJF6hJVjSDN6BiN2RYQ6uC7I8F8p35N9huKsR8ezy/47irYWJjGW6sklBnTHpk23JLbo6hDdIoxRnYIkBbhZgVdsdh1paUxSdTmGnSU8xZF9NLmGT/r4jNy/nVe9/OjvVI7FEv7d0kF/+P/+3/+2//4///f//m/zmvakKWscb+4jSD7A/VaIdo+zjj2uxNB5YTrO9nzxZIIColnlO94T1sH8NrWPeWUJGja3War8X4ao+WrtAc1dyE43Bivy0h700QXoLknA43GdyDRIFBqPp5IZWi2NNj/+Ml50FEjd45pNSBdI7cfyPGszxxPASVYPWunc8pilCFu2by2SDHWzS/nIs4qgGWkvvT9JsOUe4NXuc2ETtSgNzt76MH0w1laDT4x4ng5ew5Rr2u59xxyzqmZU9qGiwJpQfeoNVPWpwqP0EwIh3GUV673eD2I71Nz+fkCqOq3z/lLD3g/t6SNBd4CjK3peZmJkcLFY3QfEbqArkE/IbeNCLlvKqA8iWMyVOM1VW/iO5XaEt4LUQqfpQkr32/gxNbqX6sQi/zLS0Nc2NltUSHrA8uoaRDlNXxq0TzPXXh+Uh7yfjgNjqbllwKCH1Xdf/GfrDbqU97W8CeVTP5diosXOZ93q4ucs2MJyW7hTMbP+RH5pS+V9WAYMvj3jr/uMi/umVjWGQk8KxG8hiDr6Nkk3sa7MEbicRDSXCXf7pnrt1BhQlaKjd+MdEEVdfJAVzoaZ55xnnhmJCqBw9L+TIFxrUR2CLi/Moab5XkJUm1uJj+DCt8tGBwa05uUvXjtziqImWMTDxcl/EVVeU8ymLzbp+oTIYiqfPImX5pNKd80uj8zTiFVEG5FyFEPEaxuPVEFRLFrGPq7WPSY0JUj1nueb1XG/T5EUVkSM02q6F4fQTKmzbT9loD0VzLu+/Lb85k7x2d/7ZBwD+66jx9n8FiMvXT3ALgOaR+Btv7TpHMEJc9KxFU7kgFnTeE1pIMNm1LjhBZAxfqNXFOGlPLJq/bkO9kUGaMoPuPAPDa0s9ZGl3fXwMTRHzKQazh2ebyZxm4vK5H2Dm/tX/WYMzjeFGaLI+J4RD0n6ahArIcgqHNEtBI83ArkVvhf5VeX/Qnkw3oylZjauWifYpqUgFAoptrKnXEye+Iua5zEMpJ3xtmrJ6tVPJodrGFlH4mVb2kURcN9DhK125vtDadyf5rrXDJuby9bU/6Vmu1/Roq+DTXnW1yiZxdCQEGhN5gJBza9REK0KmfoElgwTdiYtt/avWg5OAYq2syplamEWf1GPCuJwJQ7IAQmV59UAMbVN8CULQx/nWWTTHhbSeEza3g0gq0F76NYGAGrlAq0PRmXaBlMyXTzTvkcXyUk/NOVVy87+A9+qZp7soLaQPzObHnCUTjv+sl9i2TvfaX4tTTitPWaBfrHGNBxpX22t3hPPlQ8Sn/sRu/V3fp7Fs1nD4+R5f3CHpWtByDQQXkYfYRsQ42l+4ShIR2k+ONiG37+IAc/m2vVx7DeEfU4Za4j7tamw2WR5AHbilxPhVDWeXvIq/Ji8X8J4VF62qxFzaHUaZqd6LX0OLta0pWuek2NRuZOsh41j8Hbe/DDF49arfbvu+y4YIhvWgwoJiVlJHByqEnrKy+3fozKbLd26XWVbv8eiqa+jK1qJ/PEKEgGGgKZGEvNGTKHanCdiamxFkexjEiKSt09cQx5GnTuNPNwjlf+zMj7497bAnhQJ+zzzVYmm30+BkBNY/i2fgjlUfsU/vGaSoiXgofm4ztZumJZmM2Z2iCEk8a2v1KzdqBolYEb2td3qfZSJVYfcBqS6OQY0f657wxEwpM+GPdeW+jNZkRooAphr3MolxZE4r6jXmy4TXpL+IQxX2Awflk7jC6DFRhTtv7EOA+9xQdc9pvO6gvAwC1V812QeRhxF5/RyW3veMjPp3aG+vRs6kqqSYug3uuP3q/WAjo6SuR/bVGrmF90jgihK0zBfjvEElbSFrpC+tlZIF6K+DpzMXo5ZXZqCbHvVjg6FboCsmkUdBx2YTawK56yvLBw/WW0FgGVXxKyURGE7xYAgyRXi77hyrifPXekiOMnC5+pOktbR6p8HR/7LTyRDc+kHorXF8LJlNmZCvvKBV4IYQuD5OJ3qMysyWuT8o3G2CGuXio45aH4CN9dpUeUAoH/x9J0+IxEaJk+fjXnEWc4JbjhobJhzGfRW78usaqmpccMbNX5NpiKTVHTyJASbLnzIY1QCI9Moao8nkYcE3vcz3aieJAm8laXK5TZpSw5wpU2VfJMfQt6Nbso2Qjj7qwCj+r7Ql86IgqNVKtlKo+yIJnE8TFRvNE67ttzIX78eDzd9ujYLg7up1rifw15H8o14vVb3GS67iZrtaHtJfMnMXYas5864kBAD4g3ePQ/lQ/yF3UGOp1j1JRSQDLKZI9t2tljIlD+zBIfgd5M2ktZv4o0iZYr58F/RpcWLo70HUHqwFmLA7T3bCEIJSV/xzKVki7tOnJ/RCCxYBtsGqJAJu3Ihzk1P6B6nZMahMd0BdZe5CSaTNlUsp8IAtlzDsr6wZkx2F7Kfut0XM4f4TyY4HXwchmz0M626QqDcHo2tcB15gp85iRNkeCXQVEMXeJ61EieJZ8c45rjZCAlSp+7h5g/UpTVosnHPZ1c59A99hyayblCG1kZ5RTuDxNWa/9S8aPF8z8MGBgtDBVduOy3cBRakbBx6th3tZMeGpKXB0NU2b/SsTKb7DCS5A3vzKfFaBH2Q09XqxZJszWhlEB/tItCo31zBlEOexkA70cX7I/wqG/OJld5rdI+vtndIxyielx/i4HZ7BHqMFBVzBXUXyEH2Jz69dK8agQfywvJtXUWy88cWdpskCbjSlfe6o6AjzO0RP/XLAIUjTbvYldN2SlXDi1rhHEUAEq13eikxstSz9RsnOn71IGR4MBX+dp7KMSX2R0mVaKeMT/q4gM4ifEUkbILUz+DRTMUyIC0YbDKPcIs5W8cjfzb+EHcZyraCfVLVnSFJUZAOwslQ9gZe0yZ03fqBxgnbGY5qm4HI38TjEoGj5HQUdF7OWUUdqWhLxr8pWRxlWn0chniN4uYPvGPT3b7XzmUiYy/3+GO0rWjdB349BdqTL107XIEjHihFIeh1Bx5CJ0k05dc5onm5RoAV9bMe6ZDFFHcLOHzqBdPF96PE67i6CaNk0xx130HMWjxHZSVsUjp0JWsTurbDsu1ZD1cizKnIAMBcTW/QGt6kS9jUnucHRKw2RdX+oucuVu27YC0j3HRYgHatZGXoajFgMKlKgMUFuZ4dfxEbtaucUs6GqdHLOVAEVAhoC9+BXXEWz5WEG8ELpfntzMk1uXg3I1nzcEv0vg7Qj2jTPEWysytX/kO8UO1gOT2EjPVLeXz0YfEmP1K+GPZrPHPmcX+DHBiKESV57fpatcOtesJqqQsUrehrBMFzHYGEU3gzkC94Jjp6xMIZsScsIleI3LSYhrBqEYBKnFoMDQ9fw2huZ1So1laGlH/ddi7irvqyOEvg4ftzBe3GPacv1HL5lNwC1dPvp8xXfNbC3TRcvnHY0Fn9mN34NYS4MZP5B24+K7vB85aZ9P3qsttPWwAdYtHXP1PEkIfeQ7rjwCYIvizz3Dm9n5P3QYV3pihZb6U8A3LR2XhUVYgXTqXQqe56y3qPKWQr5JCbrCcNfa/58jZ6ptUdny8cfnM2c1NNvq1vbXSP4QP1HHJsvn0Z52aDMX2Es++ymJFXndTJrASkf4TSNCw/oukbSXGN5Vp+pjpo+PEbez3L++iIAHC6U8dTfREAl9UrjlJT+xs8D1MdU24NWcwfX77XMzo+cEfkhWgRjoTvTAxDlV2p5V6NyL0r5rucFHFrEI4IDZBW0HcIAsWNrDJ9lxOGNsBMVCMmeQMoWMi2OmdjeD3zddmRAMFg4Kt8OVXEphNdnNTbh23YIONrExs6WXHTmuNIjska8P9FNlYjMQbOEhkP7poZL4s8HT0iHMcNF/ypx6k0fmNmaYpIFFw70lAB7KCSe2mRHDnorAZ8adak8W4rQXBXLN2ua7eR0Hl4SzvLaU8klWzl3I5HDiqjUm90kGthqBHGQd1ZBRgDeRpmHb9ZrpUVNyOUoIAmiPckCj2LB2FXzvH0ccH6DzdK93LUgpbk4D+2wbpS901k+7HUH6z8oAUdgxsFD56BY8oWxToEXy/PqLXrT2R7vJjtTd/+SWs6ndXorVdo4QzSjgls1YW2ooNVdK2s9zuJVhLwjMEKVOUqqSErYthQ8PahN2HSCgE/9bbXFcWzFIAZTIS1tGqbqT297E8ku5/2C390323/nRPfW85N2IFouiyB2mQLZSvTBlmQ2eUJsiz+icbuvP9SULerg3dvZzr13Z7Xl/oh1DFXyFI/lIFP/ac9g2J2sRxuNE/bXrbBUtAOScD96qGExpyCUstHmqA1nwLY4aFo2rN+DwCVm6PaXydNtcZA9mKYb4r1bkl5guwfwC+cK/fi3qqL0NwqU1RFURw5ehHfeYON36LTPZ8J6fIkSO0rOOZr1otLAcvV1j9ui0f2Wrosmeg7BTTs3sMhhfewmmZJyPEEY8m8gxomgQo4kn3Nw6YPvKdNZH2Tt0zjNkDn62YBGUHi7xwmgsu2BCvIa62FT3dIPLakcor19F5AYYosGKLqDAvj0XnJoHjF3OXEeK0zOl5oUvMH5FXTqqV4L4Tdb+Yai0L5NGQ26AFiF28X7HeoSFY+D/3n5yK2jocfOWMiXCHia0raygWVxsiAcDYb7rypYRHYRayoE0MtpxCX3Yh9nmSi454AziVQHiwghMMRWRshu8ELUwg5ToabgvSOQ5cCyNfz22GNCZflKEdOXB5zHomgDUpc7f2MgjCOrC+ikZqSplUIkG8lfCM17iSy9skgv97aLOgt3bGXnmysx4rIM+S9ZjKPIbGYeSYMWuYzDy83zbm7dGaN2QSEUk5eQ080iuqsu65u86is5pgWscUeR5yJiGBlvhU7v53tMA3vy3fzFZTzm2q3LRVYvrVUfttCv9F4a+uaOJrK4JMzmQFdsWX2lsZZnYvlAt/bLti21M13IAyOsXBorItTHYK+40la460O5wCpdwEsIKAWXvtej3tEY1atytHpoHnPHXZUWx81N084fYYp91A/R8zgdYWLvHBd2fsHTvdcAf61xgjNn76OrLMOu/BCtNqVfjGp/Hsm2yCxVGh89tKxuIqwauGHNU8wYojpkZ9J7gC5EKFQyxaRKXlIp0woyarKFQRWXum+wzreS80IlFkAQfv9EdQAZ8k0zKuv+AkYl3/7bGDJoqbG2TzGi62tqtnvgCjW3FilmXkiV5kixC4WkNiB7mtq6x63nVsk9WzlZlYpRkBV8qfOqwflhWOgsxpGo2/ORyNmkpSbHcR66Q9SVGPwtIk7dmcx9UDpbQitYfctCoqp4lkZx8H39MQesdwfO6M+fepXguEzMRvrVQ+o0YT8uUS8xemdkqhUxR6S4zdFnHvxERLW/Zb/Ce+cBfpi0GvMeEp6EgUbmU8LtntDWfL4tyJVDkEDjHWRbgnnxaojiNrIYUFyxkfPyRVlA+iZs2Ra8/TwQU0aT5j2a8G+PH++lceJzfr5hULDZps3goNt3Avj5aQObm2pfkQGkPEp9AAY3dpb64MG/HOD3h+Zz3E+SMia+HhGnWFc8A7yqw27mBFV+Czpuv8stdK8SoVV0OpHikbLTmbNXLvKYwD27zITsQdrittP8ihtwZi/d5SfMnAReu+WffOET7jwU/jAgm0e5HYWmaSNUlijluKikED9E9c4al9KmzaNjXe4te0yZUoJD64BNsUA9sjprYxN28CyzCDq0zxK6S3ihTxyncIFbIJE5JhiaB4V4LHidVYt50oU0uG/dasvUNQvsJu5nqYM3Bxw9LgZzk8nZGNFVyMHijZiaPhPDy9qMhN62exBM4prcusMcw1xplLPQLMQdkIJ7PyuWMtHzj3Ht1XF7yd3+tQd3B+u31klPWZPOiXTTpFD3xFpjwUvQDnsOe5tmcXce00588klah2urV9EkcRNieQtfMMKgoIQQ6d9MeuETT53CDoz+vADMze4D2yGvYdapN4upQEYRxCqmQ9gsAGT3fsB2QKhUkptwCi8NRFaG5+p+50ZWFwHoydDL0euVFyBWw8TzgvWBqvlwDr60jw7wh3AtqzceAs1gnBAmVf7TwJ8wiyMOiy4ypltSoTH10rePvEAKBkzwXIQwrUhfDXtEIrsG2RQW275+iGJKrgrRDdSp3Y5G9f9S7KOjPBlXVJZWa/tAxWFVaTaFIIp90XfmPZgxx8ayXHD3EVyxSxIpeXAy3qCT+jaVh8EgdUEJMPC7lCE+0Yb4pyNBXrpMXay3E7JZ7a0Y4ZAwUlWjubn4XHu/SEd/V79t4ZKHe0KeGZTWC+AgQD2qzzmctsKXhZyDzLsCgZAAIqgRL19Egf5yCP2B8pta/C9feckm+TepbmDPpaQ4z2cRMtJBAyprrftp3GRlae+qWQ3ba1/amaHL5b7M/OQUSZGtVHEx2Jgm/maNioSjv/NqLOeLu7ugGgQF1bCMQNbQWnKdxLSgkDr6DkBIHGxVTbqXTgpD5cpo+Cmke9nyfwtcNsP3MCr9d32UuoJydTwcH0z+nPDP+pArUaKd5R+s5U15IcND4xfcfqgaT7itq0lUAsDToJnyEtWczCyrhBaYP0h8Ee2MU4R61ePdOB2Q+HqQadXEU5Uek5ag/7UGTVTgRSv7hdz6T/POGdhLrXNK7xmwuj/UWxK5DMg766Ufoxijyjej6Okpw79iuDx9lxYYduuYqtR4h1HZ90D0ooaTxSUatai9WRAztyIQZLhMkJXSmHrEgQG4F116XX8lGnU2siOtzaQNAo7nyJK6PMypb4GkTiN9HASbLUzCIgP5WyTMHux6/5fXOA4EcPxQ6pUUffr4E6B9ycwT2bquUlYURFIIV46em25gZar5HANxfCbn2UTFqnXZlhn3G1vbJfMMqtqP9ci2OtJLVdqomMtsjk6bLGjvt0bsoq6KnDuEyxDCYNwQ7iM06I7Y+4+3jIB730AHD8GYf0D0Uv69Mlrgu3kLeg5gUPX7o4pHuKHWtBUwAsx4b7zxrKGZImpa439RGA6JzCOoIG+Mgr3muTZrk5QNVzdzytk1+gRLFlBfoeIowGOAhOdJprF33OC6Vg8p/O5IeN4cdRxPMczxP3utzqj5y4NcWauZ3cvLQD/GpX6atmGK7kXiF1brQI1eTBOeexeKZ0bOMtZHKOWKsPvL3Dwo4/4JMMS5OQSkDolUcNorQXFs6u3D4EZXvnIBLCYGd6pnHkxe9RPM0moH23GOOhg0ABT1d99AAfz9fL3aspAeuXpMQ/YhhS0RvqBTSd22LHNnC0OCVxw2i8MFIOPqMTEYfiOwcw5p0Z4S+JRoN1wGBNNFjYxhEsGI9QS0xZnHwj8Z9DRKYUDebjpvEOWnSjrDFm6H1FDoTc83LMiypvzBtEld8eOaMbgWBgbhfP1x5mlj/2bF9ETY2p+dLlKiQGpqxIM5ozXtyxc53NB7p5ok3nTZMlyBH0g9urRnIi1mvX9LwE86RxyY2d1DQ+xubBIZByrHGoDjQf5eHZnryoCvlRWomSJ8YO/E5rkUIhDIRx8G5laZRbL9n1kJ+OIdfA4WwQ312wX1b7opW9wu7PpeaRtjOxCxyVgYfJTXYoXWqbVqOPBHl3of4Gpuk39HWft1akQ8s3WkW5u0tNlCLVxYUFLVQLjXrbgCgqBmHzVdl2ynbYFMSTBrPq8Y+EhirT0yOFgHUxrizRhe3//r/+NxAl11ZEKAYA'
raw=pd.read_csv(io.BytesIO(gzip.decompress(base64.b64decode(DATA_B64_GZIP))))
print(f"Loaded real ORN cohort: {raw.shape[0]:,} patients × {raw.shape[1]} columns")
print("Missing cells:", int(raw.isna().sum().sum()), "| duplicate IDs:", int(raw["Study ID"].duplicated().sum()))
display(raw.head())

Loaded real ORN cohort: 1,129 patients × 61 columns
Missing cells: 0 | duplicate IDs: 0

   Study ID  Gender  Age  Overall survival  ...   D97%  D98%  D99%  D99.5%
0         2    Male   58                 0  ...   7.52  7.02  6.53    6.30
1         4    Male   58                 1  ...   5.93  5.23  3.72    2.59
2         8    Male   82                 1  ...  10.62  9.80  8.18    6.42
3         9    Male   70                 1  ...   5.57  4.60  3.67    3.03
4        15  Female   66                 0  ...   0.98  0.88  0.81    0.78

[5 rows x 61 columns]

## 1. Phase 1 — cohort audit and exploratory analysis

In [2]:
target='ORN status'
y=raw[target].astype(int)
grade_counts=raw['ORN Grade (Tsai)'].value_counts().sort_index()
audit=pd.DataFrame({'dtype':raw.dtypes.astype(str),'missing_n':raw.isna().sum(),'unique_n':raw.nunique()})
display(audit)
print(f"ORN incidence: {y.sum()}/{len(y)} = {y.mean():.1%}")
print("Grade counts:", grade_counts.to_dict())
fig=make_subplots(rows=1,cols=3,specs=[[{'type':'domain'},{'type':'xy'},{'type':'xy'}]],
                  subplot_titles=['ORN outcome','Tsai grade','Age by outcome'])
fig.add_trace(go.Pie(labels=['No ORN','ORN'],values=[(y==0).sum(),(y==1).sum()],hole=.45),1,1)
fig.add_trace(go.Bar(x=grade_counts.index.astype(str),y=grade_counts.values,text=grade_counts.values,textposition='auto'),1,2)
for k,label in [(0,'No ORN'),(1,'ORN')]:
    fig.add_trace(go.Histogram(x=raw.loc[y==k,'Age'],name=label,opacity=.65),1,3)
fig.update_layout(height=420,barmode='overlay',title='Real ORN cohort overview'); fig.show()
site=raw.groupby('Tumor site group')['ORN status'].agg(['count','sum','mean']).reset_index()
site['prevalence_pct']=100*site['mean']
display(site.sort_values('prevalence_pct',ascending=False))
px.bar(site,x='Tumor site group',y='prevalence_pct',hover_data=['count','sum'],
       title='Observed ORN prevalence by tumour site').update_layout(xaxis_tickangle=-25).show()

                         dtype  missing_n  unique_n
Study ID                 int64          0      1129
Gender                  object          0         2
Age                      int64          0        62
Overall survival         int64          0         2
Overall survival time  float64          0       466
...                        ...        ...       ...
D95%                   float64          0       885
D97%                   float64          0       844
D98%                   float64          0       838
D99%                   float64          0       804
D99.5%                 float64          0       782

[61 rows x 3 columns]

ORN incidence: 198/1129 = 17.5%
Grade counts: {0: 931, 1: 36, 2: 39, 3: 54, 4: 69}

                               Tumor site group  ...  prevalence_pct
1                         Major Salivary Glands  ...      100.000000
3                                   Oral Cavity  ...       25.000000
4                                    Oropharynx  ...       18.648649
5                                         Other  ...       16.666667
2  Nasopharynx, Nasal Cavity, Paranasal Sinuses  ...        8.695652
0                            Larynx/Hypopharynx  ...        4.294479

[6 rows x 5 columns]

## 2. Dose-volume statistics and effect sizes

In [3]:
D_COLS=sorted([c for c in raw.columns if c.startswith('D') and c.endswith('%')],key=lambda c:float(c[1:-1]))
V_COLS=sorted([c for c in raw.columns if c.startswith('V') and c.endswith('Gy')],key=lambda c:float(c[1:-2]))
D_VOL=np.array([float(c[1:-1]) for c in D_COLS])
fig=go.Figure()
for k,label in [(0,'No ORN'),(1,'ORN')]:
    sub=raw.loc[y==k,D_COLS]
    fig.add_trace(go.Scatter(x=D_VOL,y=sub.mean().values,mode='lines',name=label))
fig.update_layout(title='Mean dose-at-volume curves (real cohort)',xaxis_title='Mandible volume (%)',yaxis_title='Dose (Gy)')
fig.show()
num=[c for c in ['Age','Smoking Pack-Years','D30%','D50%','D70%','V30Gy','V50Gy','V60Gy'] if c in raw.columns]
rows=[]
for c in num:
    a=raw.loc[y==0,c].dropna(); b=raw.loc[y==1,c].dropna()
    u,p=stats.mannwhitneyu(a,b)
    rows.append({'feature':c,'median_no_ORN':a.median(),'median_ORN':b.median(),
                 'median_difference':b.median()-a.median(),'MW_p':p,'AUC_univariate':roc_auc_score(y,raw[c]) if raw[c].notna().all() else np.nan})
stats_table=pd.DataFrame(rows).sort_values('MW_p')
display(stats_table)
if 'D30%' in raw:
    print(f"D30% medians: no ORN {raw.loc[y==0,'D30%'].median():.2f} Gy; ORN {raw.loc[y==1,'D30%'].median():.2f} Gy.")

              feature  median_no_ORN  ...          MW_p  AUC_univariate
2                D30%          47.77  ...  1.320315e-24        0.731431
6               V50Gy          26.81  ...  7.556243e-22        0.717088
7               V60Gy          11.83  ...  2.227861e-21        0.714495
3                D50%          37.29  ...  2.787572e-19        0.702894
5               V30Gy          68.14  ...  1.115177e-14        0.674606
4                D70%          29.31  ...  3.618674e-14        0.671188
0                 Age          60.00  ...  4.622300e-01        0.483389
1  Smoking Pack-Years           7.00  ...  8.030763e-01        0.494532

[8 rows x 6 columns]

D30% medians: no ORN 47.77 Gy; ORN 57.48 Gy.

## 3. Phase 2 — DVH functional feature representation

In [4]:
dvh=raw[D_COLS].astype(float).values
dvh_scaler=StandardScaler()
dvh_z=dvh_scaler.fit_transform(dvh)
pca=PCA(n_components=min(10,dvh_z.shape[1]),random_state=SEED)
pcs=pca.fit_transform(dvh_z)
fig=make_subplots(rows=1,cols=2,subplot_titles=['Variance explained','First three DVH loadings'])
fig.add_trace(go.Bar(x=[f'PC{i+1}' for i in range(len(pca.explained_variance_ratio_))],
                     y=pca.explained_variance_ratio_*100,name='Individual'),1,1)
fig.add_trace(go.Scatter(x=[f'PC{i+1}' for i in range(len(pca.explained_variance_ratio_))],
                         y=np.cumsum(pca.explained_variance_ratio_)*100,mode='lines+markers',name='Cumulative'),1,1)
for i in range(min(3,len(pca.components_))):
    fig.add_trace(go.Scatter(x=D_VOL,y=pca.components_[i],name=f'PC{i+1} loading'),1,2)
fig.update_layout(height=430,title='DVH PCA (exploratory, real data)'); fig.show()
n95=int(np.searchsorted(np.cumsum(pca.explained_variance_ratio_),.95)+1)
print(f"{n95} components explain at least 95% of standardized D-curve variance.")
sil={}
for k in range(2,8):
    km=KMeans(n_clusters=k,n_init=10,random_state=SEED).fit(pcs[:,:min(6,pcs.shape[1])])
    from sklearn.metrics import silhouette_score
    sil[k]=silhouette_score(pcs[:,:min(6,pcs.shape[1])],km.labels_)
best_k=max(sil,key=sil.get)
km=KMeans(n_clusters=best_k,n_init=20,random_state=SEED).fit(pcs[:,:min(6,pcs.shape[1])])
cluster=pd.DataFrame({'cluster':km.labels_,'ORN':y,'D30':raw['D30%'] if 'D30%' in raw else raw[D_COLS[0]]})
ct=cluster.groupby('cluster').agg(n=('ORN','size'),ORN_cases=('ORN','sum'),ORN_rate=('ORN','mean'),mean_D30=('D30','mean')).reset_index()
display(ct)
px.bar(ct,x='cluster',y='ORN_rate',hover_data=['n','ORN_cases','mean_D30'],title='ORN rate by unsupervised DVH cluster').show()

3 components explain at least 95% of standardized D-curve variance.

   cluster     n  ORN_cases  ORN_rate   mean_D30
0        0  1019        195  0.191364  51.230128
1        1   110          3  0.027273  14.471545

## 4. Phase 3 — real-data ML baselines

In [5]:
exclude=[c for c in ['Study ID','ORN status','ORN Grade (Tsai)','Time to event','Overall survival','Overall survival time'] if c in raw.columns]
X=raw.drop(columns=exclude).copy()
X=pd.get_dummies(X,drop_first=False,dummy_na=True)
X=X.replace([np.inf,-np.inf],np.nan)
X=X.fillna(X.median(numeric_only=True)).fillna(0)
from sklearn.model_selection import train_test_split
Xtr,Xte,ytr,yte=train_test_split(X,y,test_size=.2,random_state=SEED,stratify=y)
models={
 'Logistic regression':make_pipeline(StandardScaler(),LogisticRegression(max_iter=3000,C=.1)),
 'Random forest':RandomForestClassifier(n_estimators=300,min_samples_leaf=4,max_features='sqrt',class_weight='balanced',n_jobs=-1,random_state=SEED),
 'Extra Trees':ExtraTreesClassifier(n_estimators=300,min_samples_leaf=4,max_features='sqrt',class_weight='balanced',n_jobs=-1,random_state=SEED),
 'HistGradientBoosting':HistGradientBoostingClassifier(max_iter=200,learning_rate=.05,l2_regularization=2,random_state=SEED)
}
preds={}; rows=[]
for name,m in models.items():
    m.fit(Xtr,ytr); prob=m.predict_proba(Xte)[:,1]; pred=(prob>=.5).astype(int); preds[name]=prob
    rows.append({'Model':name,'ROC-AUC':roc_auc_score(yte,prob),'Average precision':average_precision_score(yte,prob),
                 'Brier':brier_score_loss(yte,prob),'F1@0.5':f1_score(yte,pred,zero_division=0),
                 'Recall@0.5':recall_score(yte,pred,zero_division=0),'Precision@0.5':precision_score(yte,pred,zero_division=0)})
results=pd.DataFrame(rows).sort_values('ROC-AUC',ascending=False)
display(results)
fig=go.Figure()
for name,p in preds.items():
    fpr,tpr,_=roc_curve(yte,p); fig.add_trace(go.Scatter(x=fpr,y=tpr,mode='lines',name=f'{name} AUC={roc_auc_score(yte,p):.3f}'))
fig.add_trace(go.Scatter(x=[0,1],y=[0,1],mode='lines',line=dict(dash='dash'),name='Chance'))
fig.update_layout(title='ROC curves (real ORN outcomes)',xaxis_title='False positive rate',yaxis_title='True positive rate');fig.show()
fig=go.Figure()
for name,p in preds.items():
    pr,rc,_=precision_recall_curve(yte,p);fig.add_trace(go.Scatter(x=rc,y=pr,mode='lines',name=f'{name} AP={average_precision_score(yte,p):.3f}'))
fig.add_hline(y=yte.mean(),line_dash='dash',annotation_text='Test prevalence')
fig.update_layout(title='Precision–recall curves',xaxis_title='Recall',yaxis_title='Precision');fig.show()
best=results.iloc[0]['Model']; print("Best ROC-AUC model:",best)
print(f"Holdout set n={len(yte)}; ORN prevalence={yte.mean():.1%}; best ROC-AUC={results.iloc[0]['ROC-AUC']:.3f}.")

                  Model   ROC-AUC  ...  Recall@0.5  Precision@0.5
0   Logistic regression  0.680914  ...       0.025       0.111111
2           Extra Trees  0.673387  ...       0.375       0.312500
1         Random forest  0.652151  ...       0.200       0.296296
3  HistGradientBoosting  0.634677  ...       0.075       0.200000

[4 rows x 7 columns]

Best ROC-AUC model: Logistic regression
Holdout set n=226; ORN prevalence=17.7%; best ROC-AUC=0.681.

## 7. Findings generated from data

In [9]:
bestrow=results.iloc[0]
print("DATA-DERIVED FINDINGS")
print(f"• The MD Anderson table has {len(raw):,} patients and {int(y.sum()):,} ORN events ({y.mean():.1%}).")
print(f"• The best model on this single holdout split was {bestrow['Model']} (ROC-AUC {bestrow['ROC-AUC']:.3f}; AP {bestrow['Average precision']:.3f}).")
if 'D30%' in raw:
    print(f"• Median D30% was {raw.loc[y==0,'D30%'].median():.2f} Gy without ORN and {raw.loc[y==1,'D30%'].median():.2f} Gy with ORN.")
print("• The real CT archive is an independent cohort without confirmed ORN labels: image-derived metrics are not used to claim ORN prediction.")
print("• No clinical ORN CNN/LSTM/TFT result is reported because no real longitudinal CT sequences are paired with ORN outcomes.")

DATA-DERIVED FINDINGS
• The MD Anderson table has 1,129 patients and 198 ORN events (17.5%).
• The best model on this single holdout split was Logistic regression (ROC-AUC 0.681; AP 0.278).
• Median D30% was 47.77 Gy without ORN and 57.48 Gy with ORN.
• The real CT archive is an independent cohort without confirmed ORN labels: image-derived metrics are not used to claim ORN prediction.
• No clinical ORN CNN/LSTM/TFT result is reported because no real longitudinal CT sequences are paired with ORN outcomes.